### ISSUE TITLE
kprove: should error given unbound RHS variable

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#1046]
If a variable appears only on the right hand side of a specification, this is silently interpreted as an existentially quantified variable. 
This is potentially dangerous behavior, as a typo in the spec writing can lead to a proof becoming trivial, resulting in a false certainty in the verification process.
For rewrite rules, variables appearing on the RHS of a rule throws an error, unless explicitly prefixed by a `?` https://github.com/kframework/kore/blob/master/docs/2019-12-16-Question-Mark-Variables-With-Ensures.md. 

It would be reasonable to expect `kprove` to have the same behavior, and throw an error if a variable appears only on the RHS (unless prefixed with a `?`). 

Cf. the conversation [here](https://riot.im/app/#/room/!MfVXcmpKuyudZHcqil:matrix.org/$1579293981718150SvIjN:matrix.org)

**Comment by asymmetric** [comment]
Seems like this has been [addressed](https://github.com/kframework/k/pull/1058#issuecomment-579163219) in recent versions with a warning, so I think this can be closed?

**Comment by ehildenb** [comment]
I have confirmed with the following example (`test.k`):

```
module TEST
    imports INT

    configuration <k> $PGM:Pgm </k>

    syntax Pgm ::= "a" | "b"
endmodule

module TEST-SPEC
    imports TEST

    claim <k> a => V:Pgm </k>
endmodule 
```

And the following commands:

```
% kprove --spec-module TEST-SPEC test.k 
[Error] Compiler: Found variable V on right hand side of rule, not bound on
left hand side. Did you mean "?V"?
        Source(/home/dev/src/k/test.k)
        Location(14,20,14,21)
        14 |        claim <k> a => V:Pgm </k>
           .                       ^
[Warning] Compiler: Variable 'V' defined but not used. Prefix variable name
with underscore if this is intentional.
        Source(/home/dev/src/k/test.k)
        Location(14,20,14,21)
        14 |        claim <k> a => V:Pgm </k>
           .                       ^
[Error] Compiler: Had 1 structural errors.
```

That we are indeed letting the user know that the variable is not bound correctly.
