### ISSUE TITLE
Investigate performance of `kompile`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1057]
The MKR-MCD semantics at https;//github.com/makerdao/mkr-mcd-spec takes a weirdly long time to `kompile` it seems. It is a rather large definition, with lots of configuration composition, but it still seems to take too long.

Maybe profiling it would reveal some interesting hot-spots, or maybe not. If nothing interesting stands out, feel free to close this.

```
git clone 'https://github.com/makerdao/mkr-mcd-spec'
cd mkr-mcd-spec
git submodule update --init --recursive
make deps K_BUILD_TYPE=Release
make build -j8              # step that takes a seemingly long time
```

**Comment by dwightguth** [comment]
There have been several significant improvements to parsing performance recently. Please reopen if this is still an issue.
