### ISSUE TITLE
Float arithmetic

### ISSUE THREAD

**Issue by ritwika314** [runtimeverification/k#106]
Hi, is there a reason I get a (parse) error on any float arithmetic i try to do:

 rule I1:Float + I2:Float => I1 +Float I2

[Error] Critical: Rewrite is not allowed to be an immediate child of #cells   
Use parentheses: (x)=>(y) to set the proper scope of the operations.
	Source(./test.k)
	Location(19,10,19,43)

**Comment by dwightguth** [comment]
This is generally a result of a parsing error somewhere in your grammar. I need to see the entire minimalized definition in order to diagnose the issue.

**Comment by ritwika314** [comment]
I wrote this minimal module, same error for this

module TEST-SYNTAX 
syntax Program ::= Float "+" Float 
endmodule


module TEST
  imports TEST-SYNTAX
configuration 
<T>
<k>$PGM:Program </k>
</T>
rule F1:Float + F2:Float => F1 +Float F2 
endmodule

When i change the floats to integers, works fine .

**Comment by ehildenb** [comment]
Do you get the same error when you wrap `$PGM:Program` in a `<k>` cell for the configuration?

**Comment by ritwika314** [comment]
It didnt render here for some reason, but it is wrapped in a k cell.

**Comment by dwightguth** [comment]
My guess is the problem is that you have not imported the FLOAT module.

**Comment by ritwika314** [comment]
worked, thanks!
