### ISSUE TITLE
Declaration of `multiplicity="*" type="Map"` should check key-like access

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1079]
This definition `kompile`s just fine, but should throw an error because of the rule which accesses the `<mem>` cell without mentioning the `<env-id>` cell. It's almost certainly not what the user intends.

```
module MEM-CELL-ACCESS
    imports INT
    imports MAP

    configuration <k> $PGM:Pgm </k>
                  <envs>
                    <env multiplicity="*" type="Map">
                      <env-id> 0 </env-id>
                      <mem> .Map </mem>
                    </env>
                  </envs>


    syntax Pgm ::= foo ( Int )

    rule <k> foo(3) => . ... </k>
         <mem> .Map => 3 |-> 4 </mem>
endmodule
```

**Comment by dwightguth** [comment]
So, there are definitely some cases where this /is/ what the user intended, for example if you have a thread cell that contains both a thread-id and a k cell. We could maybe raise a warning, but that would make some definitions very verbose when kompiled.

**Comment by gleguern** [comment]
Hi,
Personally, I may write such a rule if I want the mem cell of an env (any env) to be updated without additional constraint about which one.

**Comment by ehildenb** [comment]
Closing this as undesired fix (the current behavior is good).
