### ISSUE TITLE
Deterministic functions

### ISSUE THREAD

**Issue by asymmetric** [runtimeverification/k#1109]
It took me a while to realize that a case of non-determinism was due to two `function` rules being defined, and that there was a `--deterministic-functions` flag, whose documentation is hidden behind the `-X` flag.

Two points:

1. should the flag be turned on by default?
2. should it be made more visible? 

I heard that the argument for not doing 1. is backwards-compatibility. I'd argue that this is a problem of release management that shouldn't hold back a useful feature.

But in any case, is the flag still experimental, or can it be promoted to first-class option? :)

**Comment by ehildenb** [comment]
This option is only available on the Java backend, which we no longer support, so I'll close.

The haskell backend will not apply functions which it cannot show are deterministic at runtime (if more than one function axiom applies, it doesn't apply any of them).
