### ISSUE TITLE
[Error] Internal: Uncaught exception thrown of type MatchError (Some(BAG.Bag) (of class scala.Some))

### ISSUE THREAD

**Issue by gleguern** [runtimeverification/k#1131]
Hi,

I use the latest release of K (Git revision: a7c2937). When trying to use "multiplicity" I get the error mentionned in title.

When kompiling the following K source:
```
module CONFIGURATIONMATCHERROR-SYNTAX
endmodule

module CONFIGURATIONMATCHERROR
  imports DOMAINS
  
  configuration
    <T>
      <interface>
        <port multiplicity="*">
          <id> .K </id>
        </port>
      </interface>
      <k> .:K </k>
    </T>
    
endmodule
```
I get the following stack trace :
> scala.MatchError: Some(BAG.Bag) (of class scala.Some)
> 	at org.kframework.backend.llvm.matching.pattern.SortCategory$.apply(SortCategory.scala:25)
> 	at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:92)
> 	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> 	at scala.collection.immutable.List.foreach(List.scala:389)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> 	at scala.collection.immutable.List.map(List.scala:295)
> 	at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
> 	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$7(Generator.scala:77)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> 	at scala.collection.immutable.List.foreach(List.scala:389)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> 	at scala.collection.immutable.List.map(List.scala:295)
> 	at org.kframework.backend.llvm.matching.Generator$.genPattern$1(Generator.scala:77)
> 	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genPatterns$10(Generator.scala:99)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> 	at scala.collection.immutable.List.foreach(List.scala:389)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> 	at scala.collection.immutable.List.map(List.scala:295)
> 	at org.kframework.backend.llvm.matching.Generator$.genPatterns(Generator.scala:99)
> 	at org.kframework.backend.llvm.matching.Generator$.$anonfun$genClauseMatrix$11(Generator.scala:134)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> 	at scala.collection.Iterator.foreach(Iterator.scala:929)
> 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
> 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
> 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at org.kframework.backend.llvm.matching.Generator$.genClauseMatrix(Generator.scala:134)
> 	at org.kframework.backend.llvm.matching.Generator$.mkDecisionTree(Generator.scala:140)
> 	at org.kframework.backend.llvm.matching.Matching$.$anonfun$writeDecisionTreeToFile$4(Matching.scala:38)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> 	at scala.collection.Iterator.foreach(Iterator.scala:929)
> 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
> 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
> 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at org.kframework.backend.llvm.matching.Matching$.writeDecisionTreeToFile(Matching.scala:31)
> 	at org.kframework.backend.llvm.matching.Matching.writeDecisionTreeToFile(Matching.scala)
> 	at org.kframework.backend.llvm.LLVMBackend.accept(LLVMBackend.java:48)
> 	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:74)
> 	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
> 	at org.kframework.main.Main.runApplication(Main.java:118)
> 	at org.kframework.main.Main.runApplication(Main.java:108)
> 	at org.kframework.main.Main.main(Main.java:56)
> [Error] Internal: Uncaught exception thrown of type MatchError (Some(BAG.Bag)
> (of class scala.Some))

Any idea how to fix this ?

Thanks,
Gurvan

**Comment by dwightguth** [comment]
Due to longstanding convention in K, cell collections by default are multisets (bags). However, `--backend java` is the only backend which has implemented multisets yet. Thus you are getting an exception. I am writing a PR to make the error message more informative, since this is something that trips up a lot of new users. But for now, I would recommend that you add either `type="Set"` or `type="Map"` to the cell declaration. If you really need the collection to not be idempotent, you can introduce a unique ID cell to the cell that the collection contains and provide it with a fresh id each time a cell is created with the !X:Int syntax.

**Comment by gleguern** [comment]
Thanks. It solved my problem.
Is the attribute 'type' documented somewhere ?
