### ISSUE TITLE
kprove: no `int_max` in Z3

### ISSUE THREAD

**Issue by ReedOei** [runtimeverification/k#1133]
I tried to run `kprove` on the following:
```
module LEFTPAD-SPEC
    imports LAMBDA

    rule
        (leftpad (< N:Int , < C:String , Str:String > >)) 
        =>
        ?NewStr:String
    requires lengthString(C) ==Int 1
    ensures lengthString(?NewStr) ==Int maxInt(N, lengthString(Str))
endmodule
```

`LAMBDA` is the tutorial langauge with a couple of minor extensions (strings, pairs). I put it on pastebin [here](https://pastebin.com/z5rJz5GG), but I don't think it's actually relevant to the error. 

K gives me the following error:
```
[Error] Critical: Z3 crashed on input query:
(declare-fun andInt (Int Int) Int)
(declare-fun shlInt (Int Int) Int)
(declare-fun shrInt (Int Int) Int)
(declare-fun xorInt (Int Int) Int)
(declare-fun orInt (Int Int) Int)
(declare-fun notInt (Int) Int)
(declare-fun |N_131| () Int)
(declare-fun |_257| () Int)
(declare-fun |_258| () Int)
(assert (and
  (and
	(= (<= |N_131| _257) true)
	(= _258 1))
  (not (and
	(= _257 (int_max |N_131| _257))))
))
result:
(error "line 17 column 30: unknown function/constant int_max")
```

I assume this is because of the definition of `maxInt` in `domains.k`. I resolved my problem by using the `#if_#then_#else_#fi`, not sure if there's a better way.

Also, there's another issue with `lengthString` not having an SMT translation at all, not sure if that's a limitation or just something that just never got defined.

**Comment by denis-bogdanas** [comment]
Add option `--smt-prelude evm.smt2` where `evm.smt2` is this: https://github.com/runtimeverification/verified-smart-contracts/blob/master/resources/evm.smt2

By the way you are running Java backend, not Haskell.

**Comment by dwightguth** [comment]
It's true you can add an smt prelude (although I would recommend the one in include/z3/basic.smt2 in the k repo instead), but we will also have a better fix than that shortly that will make such a command line flag not required.
