### ISSUE TITLE
[K Tutorial] Static type semantics of SIMPLE

### ISSUE THREAD

**Issue by zhengyao-lin** [runtimeverification/k#1162]
Not sure if this is a legit issue since I'm still studying K. In the following line
https://github.com/kframework/k/blob/master/k-distribution/tutorial/2_languages/1_simple/2_typed/1_static/simple-typed-static.k#L566

```
rule try block catch(int X:Id) {S} => {int X; S}  [structural]
```

this rule only applies for the case when the block is non-empty (`{S}`), so I think the empty block will not be correctly typed in this case.

**Comment by dwightguth** [comment]
Good eye! I haven't tested yet, but it does look to me like you are correct. Thanks for the report, I will test to confirm and then update the definition.
