### ISSUE TITLE
User substitution hook in java backend applies to variables

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#1165]
The user substitution hook seems to apply in the java backend even when the term to be substituted into and the variable to be substituted are not concrete. In this case, it applies incorrectly and disappears without correctly substituting in all cases when those variables are made concrete later on via unification.

The fix would be to check that `term.isConcrete() && variable.isConcrete()` in BuiltinSubstitutionOperations.java and if that returns false, then return null. But I tested this and it seems to cause other problems for 5_types in the K tutorial. I don't have the time to dig further, however.

**Comment by ehildenb** [comment]
Closing this as we are not investigating the java backend anymore.
