### ISSUE TITLE
Kompile option for just including all imports

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/k#1169]
Could kompile have an option similar to gcc -E that would just perform all imports and printed the result? It would make minimalizing counterexamples for bug reports easier.

**Comment by ehildenb** [comment]
@dwightguth please also make sure this respects the `--emit-json` flag. Having the pre-kompile-pipeline version of the JSON semantics is something that would be pretty useful for the `pyk` library.

It would also be helpful if it happened _after_ unique ids are given to all the rules, but I don't know if it's possible. That would make the pyk library definition minimizer (still in my tree) more useful. But if that's not possible I think there are other ways to achieve it.

**Comment by dwightguth** [comment]
I mean, unique ids are given during compilation because some rules don't even exist until then. Conversely, what @h0nzZik is discussing would take place before outer parsing has finished. So what you suggest isn't really possible.
