### ISSUE TITLE
kframework.org links to defunct googlecode.com

### ISSUE THREAD

**Issue by mikesamuel** [runtimeverification/k#1172]
Apologies if this is the wrong project for doc bugs

On http://www.kframework.org/index.php/Projects many of the links go to googlecode.com which was [sunset](https://opensource.googleblog.com/2015/03/farewell-to-google-code.html) and presumably most of those have migrated to Github.

For example:

> Here is a list of projects involving K.  Send us a message if you want your project listed here. Feel free to contact us or the authors if you are interested in any particular project below.
>
> * ''''\'[**http://k-framework.googlecode.com** K Tool\]'''''
: \[\[Traian Florin Serbanuta]], \[\[Andrei Arusoae]], \[\[Chucky Ellison]], \[\[David Lazar]], \[\[Dorel Lucanu]], \[\[Radu Mereuta]], \[\[Grigore Rosu]]
: Collection of K utilities (interpreters, visualizers, state-space searchers, model checkers)

That should probably instead link to https://github.com/kframework/k

I'm happy to do cleanup but would need to be in the wiki group *Users*.

----

There is a larger problem with link rot on the wiki.  I pointed a crappy SEO link checker that checks the first 2000 URLs found and the googlecode.com links are but 5 of 107 problems found:

Status | URL | Source link text
-- | -- | --
404 Not Found | https://iohk.recruiterbox.com/jobs/c76507e4cc58451aba891c4ff1eb3869 | IOHK
404 Not Found | http://k-framework.googlecode.com/ | K Tool
404 Not Found | http://matching-logic.googlecode.com/ | MatchC
404 Not Found | http://c-semantics.googlecode.com/ | C Semantics
404 Not Found | http://esolang-semantics.googlecode.com/ | Esolang Semantics
404 Not Found | http://freenode.net/irc_servers.shtml | freenode
-1 Not found: The server name or address could not be resolved | http://lists.cs.uiuc.edu/mailman/listinfo/fsl-gsoc | mailing list
500 Internal Server Error | http://www.syntax-definition.org/ | SDF
404 Not Found | https://fmse.info.uaic.ro/getpagefile/10/contrib2k.pdf | Contributions to the K framework
404 Not Found | https://fmse.info.uaic.ro/projects/25/ | Formal model-based language engineering in K [302 from http://fmse.info.uaic.ro/projects/25/]
410 Gone | https://dfilaretti.wordpress.com/ | Daniele Filaretti [301 from http://dfilaretti.wordpress.com/]
404 Not Found | http://synasc.ro/synasc2013/ | SYNASC'13
404 Not Found | http://www.cse.psu.edu/popl/12/ | POPL'12
404 Not Found | https://fmse.info.uaic.ro/publications/getfile/96/pdf/ | PDF
404 Not Found | https://fmse.info.uaic.ro/publications/getfile/74/pdf/ | PDF
-1 Not found: The server name or address could not be resolved | http://synasc10.info.uvt.ro/ | SYNACS'10
404 Not Found | http://www.springerlink.com/content/978-3-642-17795-8/ | LNCS
-1 Not found: The server name or address could not be resolved | http://ecoop07.swt.cs.tu-berlin.de/phd/ | ECOOP'07 Doctoral Symposium
404 Not Found | http://4c.ucc.ie/ijcar/index.html | IJCAR'04
404 Not Found | https://www.darpa.mil/Our_Work/I2O/Programs/High-Assurance_Cyber_Military_Systems_(HACMS).aspx | DARPA HACMS [301 from http://www.darpa.mil/Our_Work/I2O/Programs/High-Assurance_Cyber_Military_Systems_(HACMS).aspx]
404 Not Found | https://www.google-melange.com/gsoc/org/google/gsoc2012/fsl | Google Summer of Code [302 from http://www.google-melange.com/gsoc/org/google/gsoc2012/fsl]
404 Not Found | http://fsl.cs.illinois.edu/index.php/A_K-Based_Formal_Framework_for_Domain-Specific_Modelling_Languages | A K-Based Formal Framework for Domain-Specific Modelling Languages [301 from http://fsl.cs.uiuc.edu/index.php/A_K-Based_Formal_Framework_for_Domain-Specific_Modelling_Languages]
404 Not Found | https://fmse.info.uaic.ro/publications/getfile/84/pdf/ | PDF [302 from http://fmse.info.uaic.ro/publications/getfile/84/pdf/]
404 Not Found | https://fmse.info.uaic.ro/fileman/getpubpubfile/53/ | Slides (PDF) [302 from http://fmse.info.uaic.ro/fileman/getpubpubfile/53/]
404 Not Found | http://fsl.cs.illinois.edu/index.php/K_Semantics_for_OCL_—_a_Proposal_for_a_Formal_Definition_for_OCL | K Semantics for OCL — a Proposal for a Formal Definition for OCL [301 from http://fsl.cs.uiuc.edu/index.php/K_Semantics_for_OCL_—_a_Proposal_for_a_Formal_Definition_for_OCL]
404 Not Found | https://fmse.info.uaic.ro/fileman/getpubpubfile/52/ | Slides (PDF) [302 from http://fmse.info.uaic.ro/fileman/getpubpubfile/52/]
404 Not Found | http://fsl.cs.illinois.edu/index.php/Path_Directed_Symbolic_Execution_in_the_K_Framework | Path Directed Symbolic Execution in the K Framework [301 from http://fsl.cs.uiuc.edu/index.php/Path_Directed_Symbolic_Execution_in_the_K_Framework]
404 Not Found | http://fsl.cs.illinois.edu/index.php/Irina_Asavoae | Irina Asavoae [301 from http://fsl.cs.uiuc.edu/index.php/Irina_Asavoae]
404 Not Found | http://fsl.cs.illinois.edu/index.php/Mihail_Asavoae | Mihail Asavoae [301 from http://fsl.cs.uiuc.edu/index.php/Mihail_Asavoae]
404 Not Found | https://fmse.info.uaic.ro/publications/getfile/100/pdf/ | PDF [302 from http://fmse.info.uaic.ro/publications/getfile/100/pdf/]
404 Not Found | http://fsl.cs.illinois.edu/index.php/Collecting_Semantics_under_Predicate_Abstraction_in_the_K_Framework | Collecting Semantics under Predicate Abstraction in the K Framework [301 from http://fsl.cs.uiuc.edu/index.php/Collecting_Semantics_under_Predicate_Abstraction_in_the_K_Framework]
404 Not Found | https://fmse.info.uaic.ro/events/SSLF12 | Summer School on Language Frameworks
-1 Timeout | http://thor.info.uaic.ro/~stefan.ciobaca | Stefan Ciobaca
404 Not Found | https://fmse.info.uaic.ro/getpagefile/10/k4dsml.pdf | K Semantics for Domain Specic Modeling Languages
401 Unauthorized | http://splashcon.org/2012/cfp/378 | OOPSLA'12
-1 Timeout | http://wrla2012.lcc.uma.es/ | WRLA'12
404 Not Found | http://www.cse.psu.edu/popl/12 | POPL'12
404 Not Found | http://k-framework.googlecode.com/svn/tags/v2.5/ | K 2.5
404 Not Found | http://www.kframework.org/index.php/K_Framework:Privacy_policy | Privacy policy
404 Not Found | http://www.kframework.org/index.php/K_Framework:About | About K Framework
404 Not Found | http://www.kframework.org/index.php/K_Framework:General_disclaimer | Disclaimers
404 Not Found | http://www.kframework.org/index.php/User:Grosu | Grosu
404 Not Found | http://www.kframework.org/index.php/User_talk:Grosu | Talk
404 Not Found | http://www.kframework.org/index.php/User:82.165.25.77 | 82.165.25.77
404 Not Found | http://www.kframework.org/index.php/User_talk:82.165.25.77 | Talk for this IP address
404 Not Found | http://www.kframework.org/index.php/Lesson_3,_FUN_polymorphic_type_inferencer | Lesson 3, FUN polymorphic type inferencer
404 Not Found | http://www.kframework.org/index.php/Talk:Main_Page | Discussion [302 from http://www.kframework.org/index.php?title=Talk:Main_Page&action=edit&redlink=1]
404 Not Found | http://www.kframework.org/index.php/K_Framework:Users | Users
404 Not Found | http://www.kframework.org/index.php/Andrei_Arusoae | Andrei Arusoae
404 Not Found | http://www.kframework.org/index.php/Michael_Katelman | Michael Katelman
404 Not Found | http://www.kframework.org/index.php/Michael_Ilseman | Michael Ilseman
404 Not Found | http://www.kframework.org/index.php/Dwight_Guth | Dwight Guth
404 Not Found | http://www.kframework.org/index.php/Rewriting_Logic_Semantics_of_Beta | Beta Semantics
404 Not Found | http://www.kframework.org/index.php/Rewriting_Logic_Semantics_of_Java | Java 1.4 and JVM Semantics
404 Not Found | http://www.kframework.org/index.php/Azadeh_Farzan | Azadeh Farzan
404 Not Found | http://www.kframework.org/index.php/KOOL | KOOL Semantics
404 Not Found | http://www.kframework.org/index.php/Special:KOOLOnline_Online_Interface | Special:KOOLOnline Online Interface
404 Not Found | http://www.kframework.org/index.php/C_Policy_Framework | C Policy Framework
404 Not Found | http://www.kframework.org/index.php/K_Prototype | K-Maude 1.0
404 Not Found | http://www.kframework.org/index.php/The_K_Primer_(version_2.5) | The K Primer (version 2.5)
404 Not Found | http://www.kframework.org/index.php/An_Overview_of_the_K_Semantic_Framework | An Overview of the K Semantic Framework
404 Not Found | http://www.kframework.org/index.php/GSoC2013 | GSoC2013
404 Not Found | http://www.kframework.org/index.php/K_Compiler | K Compiler
404 Not Found | http://www.kframework.org/index.php/On_Compiling_Rewriting_Logic_Language_Definitions_into_Competitive_Interpreters | On Compiling Rewriting Logic Language Definitions into Competitive Interpreters
404 Not Found | http://www.kframework.org/index.php/User:Xiaohong | Xiaohong
404 Not Found | http://www.kframework.org/index.php/User_talk:Xiaohong | Talk
404 Not Found | http://www.kframework.org/index.php/User:Tserban2 | Tserban2
404 Not Found | http://www.kframework.org/index.php/User_talk:Tserban2 | Talk
404 Not Found | http://www.kframework.org/index.php/User:Dwight | Dwight
404 Not Found | http://www.kframework.org/index.php/User_talk:Dwight | Talk
404 Not Found | http://www.kframework.org/index.php/User:Phil | Phil
404 Not Found | http://www.kframework.org/index.php/User_talk:Phil | Talk
404 Not Found | http://www.kframework.org/index.php/Gheorghe_Grigoras | Gheorghe Grigoras
404 Not Found | http://www.kframework.org/index.php/Michael_Adams | Michael Adams
404 Not Found | http://www.kframework.org/index.php/Ömer_Sinan_Ağacan | Ömer Sinan Ağacan
404 Not Found | http://www.kframework.org/index.php/An_Executable_Formal_Semantics_of_C_with_Applications | An Executable Formal Semantics of C with Applications
404 Not Found | http://www.kframework.org/index.php/Making_Maude_Definitions_more_Interactive | Making Maude Definitions more Interactive
404 Not Found | http://www.kframework.org/index.php/File:2011-09-30-CK-MVD.pdf | <No Text>
404 Not Found | http://www.kframework.org/index.php/K_and_Matching_Logic | K and Matching Logic
404 Not Found | http://www.kframework.org/index.php/File:2011-09-30-KML-MVD.zip | <No Text>
404 Not Found | http://www.kframework.org/index.php/File:2011-09-30-KML-MVD.pdf | <No Text>
404 Not Found | http://www.kframework.org/index.php/Chris_Hathhorn | Chris Hathhorn
404 Not Found | http://www.kframework.org/index.php/Denis_Bogdanas | Denis Bogdanas
404 Not Found | http://www.kframework.org/index.php/Sandeep_Dasgupta | Sandeep Dasgupta
404 Not Found | http://www.kframework.org/index.php/Theodoros_Kasampalis | Theodoros Kasampalis
404 Not Found | http://www.kframework.org/index.php/Vikram_S._Adve | Vikram S. Adve
404 Not Found | http://www.kframework.org/index.php/Xiaohong_Chen | Xiaohong Chen
404 Not Found | http://www.kframework.org/index.php/Yi_Zhang | Yi Zhang
404 Not Found | http://www.kframework.org/index.php/Manasvi_Saxena | Manasvi Saxena
404 Not Found | http://www.kframework.org/index.php/Philip_Daian | Philip Daian
404 Not Found | http://www.kframework.org/index.php/Brandon_Moore | Brandon Moore
404 Not Found | http://www.kframework.org/index.php/Traian_Serbanuta | Traian Serbanuta
404 Not Found | http://www.kframework.org/index.php/Virgil_Serbanuta | Virgil Serbanuta
404 Not Found | http://www.kframework.org/index.php/Daniele_Filaretti | Daniele Filaretti
404 Not Found | http://www.kframework.org/index.php/Ralph_Johnson | Ralph Johnson
404 Not Found | http://www.kframework.org/index.php/Ali_Kheradmand | Ali Kheradmand
404 Not Found | http://www.kframework.org/index.php/Everett_Hildenbrandt | Everett Hildenbrandt
404 Not Found | http://www.kframework.org/index.php/Xiaoran_Zhu | Xiaoran Zhu
404 Not Found | http://www.kframework.org/index.php/Nishant_Rodrigues | Nishant Rodrigues
404 Not Found | http://www.kframework.org/index.php/Shijiao_Yuwen | Shijiao Yuwen
404 Not Found | http://www.kframework.org/index.php/Yilong_Li | Yilong Li
404 Not Found | http://www.kframework.org/index.php/Stefan_Ciobaca | Stefan Ciobaca
404 Not Found | http://www.kframework.org/index.php/Codruta_Girlea | Codruta Girlea
404 Not Found | http://www.kframework.org/index.php/Wolfram_Schulte | Wolfram Schulte
404 Not Found | http://www.kframework.org/index.php/Talk:K_Project_Needs_Professional_Developers | Discussion [302 from http://www.kframework.org/index.php?title=Talk:K_Project_Needs_Professional_Developers&action=edit&redlink=1]
404 Not Found | http://www.kframework.org/index.php/Talk:K_Overview | Discussion [302 from http://www.kframework.org/index.php?title=Talk:K_Overview&action=edit&redlink=1]
404 Not Found | http://www.kframework.org/index.php/Talk:Editor_Support | Discussion [302 from http://www.kframework.org/index.php?title=Talk:Editor_Support&action=edit&redlink=1]

**Comment by ehildenb** [comment]
The website https://kframework.org has undergone a large overhaul, and this should no longer be an issue.
