### ISSUE TITLE
openjdk version confusion in checkJava

### ISSUE THREAD

**Issue by livnev** [runtimeverification/k#118]
When I try to `make` I get a complaint that I don't have a `java` of the required version:

```
~/src/k/latest/evm-semantics(dapphub/stable) » make build-java
== kompile: .build/java/driver-kompiled/timestamp
/home/lev/src/k/latest/evm-semantics/.build/k/k-distribution/target/release/k/bin/kompile --debug --main-module ETHEREUM-SIMULATION --backend java \
				--syntax-module ETHEREUM-SIMULATION .build/java/driver.k --directory .build/java -I .build/java
Error: K requires Java 1.8 to run but the detected version is 10.0.1.
Please either add Java 1.8 bin directory to the PATH or set the JAVA_HOME
environment variable accordingly.
Makefile:131: recipe for target '.build/java/driver-kompiled/timestamp' failed
make: *** [.build/java/driver-kompiled/timestamp] Error 2
```
Indeed, the version reported by `$ java -version` is:
```
~ » java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Debian-4)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Debian-4, mixed mode)
```
So this appears to be some confusion in the Java version number convention. By the way, I am using `openjdk-10-jre 10.0.1+10-4` provided by debian testing. I can only assume that anyone else using debian would have the same problem. The problem is resolved by adjusting `MIN_VERSION` in `k-distribution/src/main/scripts/lib/checkJava`, after that everything builds as expected.

@ehildenb

**Comment by ehildenb** [comment]
@dwightguth, from the best I can tell Debian may be doing some sort of change in how the versioning numbers are reported. Have you ever seen this issue before or does it look like something else?


I also thought that @livnev and I had seen some evidence before that it wasn't because of `openjdk-10-jre`. Though to confirm, @livnev can you try `openjdk-8-jre`? https://wiki.debian.org/Java

Instead we thought it was something with how Debian was mangling the version number.

**Comment by livnev** [comment]
@ehildenb Indeed, it seems like debian has changed the numbering convention for these `java` packages for 10 and 11:
```
~ » sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for jaotc
update-alternatives: error: no alternatives for jdeprscan
update-alternatives: error: no alternatives for jhsdb
update-alternatives: error: no alternatives for jimage
update-alternatives: error: no alternatives for jlink
update-alternatives: error: no alternatives for jmod
update-alternatives: error: no alternatives for jshell
------------------------------------------------------------
~ » java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
and the `checkJava` version check works as expected.

Similarly to 10, version 11 also ditches the initial `1.`: after switching to `java-10.0-openjdk-amd64`:
```~ » java -version                                                                                                                                                                 lev@dellian
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment (build 11+17-Debian-2)
OpenJDK 64-Bit Server VM (build 11+17-Debian-2, mixed mode, sharing)
```
I see there is a [lot](https://stackoverflow.com/questions/2411288/java-versioning-and-terminology-1-6-vs-6-0-openjdk-vs-sun) of controversy about Java version numbering, I guess only from version 10 `openjdk` is ditching the `1.` prefix.
