### ISSUE TITLE
Non-exhaustive pattern-match detector not working over subsorts

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1221]
On this branch `non-exhaustive-match-warn`: https://github.com/kframework/k/compare/non-exhaustive-match-warn

A test is added:

```
syntax A ::= B | C
syntax B ::= "b"
syntax C ::= D | E
syntax D ::= "d"
syntax E ::= "e"

syntax Int ::= applyA ( A ) [function, functional]

rule applyA(_:B) => 0
rule applyA(_:D) => 1
rule applyA(_:E) => 2
```

Where the non-exhaustive match checker reports that a non-exhaustive match over `applyA(_:C)` is detected. But this case is actually exhausted by the cases for `_:D` and `_:E`.

This issue initially came from the KWasm semantics where I'm trying to make more functions `functional` to reduce the size of side-conditions.

**Comment by dwightguth** [comment]
This looks like a bad interaction between the usefulness computation we do and the injection triangle equality. It should be fixable if I can figure out the right solution. I'll have to think about it some.
