### ISSUE TITLE
Update Tutorial to Use Supported Backends

### ISSUE THREAD

**Issue by SethPoulsen** [runtimeverification/k#1271]
I've just completed lots of the K tutorial. 

One of the major frustrations was running into random crashes, and not having support for cool new features (e.g. the REPL that the Haskell backend has) because the tutorial uses the old Java and OCAML backends.

It would be really helpful if it was updated to use the new LLVM & Haskell backends instead.

**Comment by dwightguth** [comment]
The K tutorial no longer uses the OCAML backend (it uses the llvm backend). I agree w/r/t the Haskell backend, but I just wanted to point that out.

**Comment by SethPoulsen** [comment]
Ah, you are right. I think one of the times the java backend was crashing, I switched to OCAML just to see if I could get better error information.

**Comment by ehildenb** [comment]
Related: https://github.com/runtimeverification/k/issues/1419

**Comment by radumereuta** [comment]
The k-tutorial is fine, but the pl-tutorial needs to be updated when we remove the java backend.

**Comment by ehildenb** [comment]
Subsumed: https://github.com/runtimeverification/k/issues/3168
