### ISSUE TITLE
LLVM backend skips a rule

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/k#1277]
When running C execution semantics, the LLVM backend seems to skip the evaluation of a side-condition of one function rule ([this rule](https://github.com/kframework/c-semantics/blob/master/semantics/c/language/common/typing/effective.k#L205-L210)) and probably proceeds to evaluate the `[owise]` rule.
The problem disappears in an older version of K (51686b228).
Function arguments:
[variables.txt](https://github.com/kframework/k/files/4611258/variables.txt)
Old (working) version:
[LblsetVariantAtOffset'LParUndsCommUndsCommUndsRParUnds'C-TYPING-EFFECTIVE'Unds'EffectiveType'Unds'EffectiveType'Unds'CId'Unds'Int.yaml-old.txt](https://github.com/kframework/k/files/4611353/LblsetVariantAtOffset.LParUndsCommUndsCommUndsRParUnds.C-TYPING-EFFECTIVE.Unds.EffectiveType.Unds.EffectiveType.Unds.CId.Unds.Int.yaml-old.txt)
[LblsetVariantAtOffset'LParUndsCommUndsCommUndsRParUnds'C-TYPING-EFFECTIVE'Unds'Type'Unds'Type'Unds'CId'Unds'Int.yaml-old.txt](https://github.com/kframework/k/files/4611354/LblsetVariantAtOffset.LParUndsCommUndsCommUndsRParUnds.C-TYPING-EFFECTIVE.Unds.Type.Unds.Type.Unds.CId.Unds.Int.yaml-old.txt)
Newer (broken) version:
[LblsetVariantAtOffset'LParUndsCommUndsCommUndsRParUnds'C-TYPING-EFFECTIVE'Unds'EffectiveType'Unds'EffectiveType'Unds'CId'Unds'Int.yaml-new.txt](https://github.com/kframework/k/files/4611355/LblsetVariantAtOffset.LParUndsCommUndsCommUndsRParUnds.C-TYPING-EFFECTIVE.Unds.EffectiveType.Unds.EffectiveType.Unds.CId.Unds.Int.yaml-new.txt)
[LblsetVariantAtOffset'LParUndsCommUndsCommUndsRParUnds'C-TYPING-EFFECTIVE'Unds'Type'Unds'Type'Unds'CId'Unds'Int.yaml-new.txt](https://github.com/kframework/k/files/4611356/LblsetVariantAtOffset.LParUndsCommUndsCommUndsRParUnds.C-TYPING-EFFECTIVE.Unds.Type.Unds.Type.Unds.CId.Unds.Int.yaml-new.txt)

**Comment by ehildenb** [comment]
@h0nzZik is this still a problem?

**Comment by dwightguth** [comment]
This is definitely not relevant. The semantics linked in the issue has not been in active use for months. It's possible there's a bug here, but it's not worth trying to track it down.
