### ISSUE TITLE
Transient error with kdep

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#1285]
The frequency with which this error occurs has gone down dramatically, but we still sometimes see the following show up in the build log and trigger a failure:

```
.depend:1: warning: NUL character seen; rest of line ignored
.depend:2: *** missing separator.  Stop.
```

This seems to happen seemingly at random due to a particular confluence of thread timing on the machine during parallel execution of Make, and it leads to transient failures that make the build fail and thus slow down the development process by periodically forcing you to retrigger the build. We need to try to come up with a permanent solution to this problem because it becomes quite tedious for  an hour-plus build like a full CI build of K to fail due to something so trivial and time-wasting. However, I expect this to be difficult to debug because it has thus far proven impossible to deterministically trigger the error, and it doesn't happen very often.

**Comment by ehildenb** [comment]
@dwightguth do we still see this error with `kdep`?

**Comment by dwightguth** [comment]
I have not seen this error in quite some time; I'm assuming it got fixed at some point.
