### ISSUE TITLE
Expose `--repl` option to Frontend

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1289]
The haskell backend repl is one of the main ways to debug Haskell backend proofs.

Currently though, we need to override the `--haskell-backend-command` when calling `kprove ...`, which make involve setting up paths manually and such.

The `--repl` is a common enough option now that it should be exposed directly to the frontend so that we can just do either `kprove --repl ...` or `kprove --debugger ...` (to imitate `krun --debugger ...`).

**Comment by dwightguth** [comment]
Use --debugger.

**Comment by ehildenb** [comment]
Also add option `--repl-script` to the frontend too (for passing through to backend).

**Comment by ehildenb** [comment]
Have a look at `./kevm` runner script for how we are using this.

**Comment by ehildenb** [comment]
@dwightguth says: specifically, what should happen if you specify both --haskell-backend-command and --debugger? or should we remove  the --haskell-backend-command flag entirely? note that right now what it does is split on whitespace which is guaranteed to bork everything up if you mention a directory containing spaces

**Comment by ehildenb** [comment]
Hmmmmm, --haskell-backend-command can be useful for trying out new features, but I think in all cases you should be able to just use kast to convert to kore and then directly invoke the haskell backend on whatever your input is. So I would vote in favor of doing away with `--haskell-backend-command`.

Any features which we want control over from the high-level command-line should be exposed as wrapped options to the frontend too.

The only use I know of `--haskell-backend-command` is for invoking the REPL and specifying `--repl-script`. @ttuegel have you seen any other common uses?

**Comment by dwightguth** [comment]
I'm going to err on the side of Tom's proposed fix since this is the haskell backend part of the codebase and he is the code owner.

**Comment by ehildenb** [comment]
For clarity, @ttuegel says: I think it should be an error to specify both flags. I don't really want to remove --haskell-backend-command because it might break scripts people have.
