### ISSUE TITLE
Substitution error in LLVM backend and discrepancies between backends

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#1299]
Part of my syntax includes:
```
syntax Process ::= KVar Def
syntax Def ::= "(" KVar ")" "." Process  [binder]
```
which seems to be causing an error:
```
[Error] Critical: LLVM Backend crashed during rewriting.
```
On the Java backend, no error is reported. On the Haskell backend, a `no hook` error is reported (I'm guessing `SUBSTITUTION` isn't available in the Haskell backend).

When changing the syntax to:
```
syntax Process ::= KVar "(" KVar ")" "." Process  [binder]
```
The error goes away. However, then the `KVar` at the front becomes part of the `binder`, which is not what I intend. (I also posted a question about the documentation of `[binder]`: https://stackoverflow.com/questions/61946642/how-to-use-binder-in-k)

Since it appears the Java backend won't be receiving any more updates, I've been updating my files to use the newer backends. However, the Haskell backend tends to complain about things I've already written (which I think is `SUBSTITUTION`). Will the Haskell backend include `SUBSTITUTION` any time soon? is there an alternative (without having to define my own substitution function, which becomes non-trivial when extending syntax across multiple modules)?

=============
Incidentally, after the error goes away, the Java backend and the LLVM backend start doing different things. The LLVM backend replaces some of my bound KVars with `a0`, `b1`, `c2`, whereas the Java backend just adds `a`,`b` and `c` directly.

e.g. one of the cells is as follows in the LLVM:
```
  <methods>
    f |-> a0 , b1 , c2 -> a0 < c2 > . b ( x ) . x < a0 > . end | a ( y ) . b1 < c2 > . c ( y ) . end + c3 ( z ) . end
  </methods>
```
whereas the Java backend is:
```
  <methods>
    f |-> a , b , c -> a < c > . b ( x ) . x < a > . end | a ( y ) . b < c > . c ( y ) . end + c ( z ) . end
  </methods>
```
My understanding is that the Java backend is to be deprecated. However, which is the correct behaviour here? Should it be substituting out bound terms on parsing? Or should it be doing that during evaluation?

The Java backend is also evaluating rules involving `Set` differently to the LLVM backend. Using the LLVM backend, rules containing the following:
```
       <processes>
         ... 
         SetItem( new X . P ) => SetItem( P[!A:KVar/X] ) 
         ... 
       </processes>
```
Appear to be working. However, in the Java backend, the rule has to be rewritten to:
```
       <processes>
         (SetItem( new X . P ) S:Set) => (SetItem( P[!A:KVar/X] ) S)
       </processes>
```
Which of these syntax is supposed to be more "correct" for Sets in K? Are they equally fine? Is the Java backend just not updated with features of the LLVM and Haskell backend?

**Comment by ehildenb** [comment]
We need a complete example to be able to reproduce this. Please re-open with a self-contained definition if this is still a problem.
