### ISSUE TITLE
Feature Request for binder generalisation

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#1300]
As in the question: https://stackoverflow.com/q/61946642/3002076

If the `binder` attribute could specify which non-terminals to use as bound variables and which non-terminal to bind the variables in.

e.g. something like `syntax P ::= A B C [binder(2)]` to say `B` contains bound variables in `C`. Or maybe `[binder(N,M)]` where `N` is the token number for variables and `M` the target term.

**Comment by dwightguth** [comment]
Closing as stale. Please open a new issue if you still need this.
