### ISSUE TITLE
Allow specifying build output directory explicitly

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1302]
Currently, all the K commands take `--directory` argument, which specifies where the main definition file `main.k` is located and then builds `main-kompiled` directory there.

This can be somewhat annoying, because we may have multiple ways of building the same semantics, and so need multiple subdirectories where we make copies of all the definition files. The implicit name `main-kompiled` is also annoying, because our `Makefile` then has to explicitly mention the word `main-` in the recipes for building the backend files.

It would be nicer if we could instead say exactly what we want the `kompiled` directory to be called, and if `krun` and `kprove` could take exactly that directory as output. For example:

```
kompile --build-directory .build/defn/web3 -I src/web3 --main-module WEB3 --syntax-module WEB3 src/web3/web3.k
krun --build-directory .build/defn/web3
```

Where the `interpreter` that is generated by `kompile` would now live at `.build/defn/web3/interpreter`.

**Comment by nishantjr** [comment]
Would `--definition` be a better name for this flag?

**Comment by ehildenb** [comment]
I think something more along the lines of `--kompiled-directory` may make more sense. I think actually there is a variable in the Java code called `kompiledDirectory` that is calculated using `--directory` and the logic of looking for the `*-kompiled` directory, so maybe we can just add a flag `--kompiled-directory` which directly sets that variable and skips the logic of looking for `*-kompiled`. Then it doesn't need to be named `*-kompiled` either, we can just name it `build` or whatever.

**Comment by dwightguth** [comment]
I'm not opposed to this in theory, but I would prefer to avoid having two different confusingly similar ways of specifying the output/compiled directory, and I'm not sure how to make this change in a backwards compatible fashion. So I'm a little unsure what action I can reasonably take here. That being said, as I understand this issue got created as a result of trying to fix the dependency issues in the kevm/firefly makefile that are causing it to rebuild definition.kore when you delete the binary generated by cmake, which it seems to me ought to be possible without any changes to K at all. So I'd like you to please clarify exactly what your actual need is and what the steps are that reproduce the actual problem, rather than simply describing the solution you have in mind for it.

**Comment by ehildenb** [comment]
Well, actually the build dependency issue was fixed when I switched to the native markdown sources build by duplicating logic in the Makefile about which was the `*_main_file` (eg here: https://github.com/kframework/evm-semantics/blob/master/Makefile#L216 both Haskell and LLVM builds use `driver` as their main file, but we can't use the same variable name). So now instead of having `MAIN_DEFN_FILE`, we have separate variables `*_main_file` for each build.

The problem was that we needed to mention `definition.kore` as the build dependency (so `make` would be able to tell if it was up to date or not), but `definition.kore` lives at `$(MAIN_DEFN_FILE)-kompiled/definition.kore`, so it's dependent on `definition.kore`. _But_, the web3 build for example needs a _different_ `MAIN_DEFN_FILE`, but there wasn't a reliable way to get it to calculate the correct path to `definition.kore` with the updated `MAIN_DEFN_FILE` using target-specific variables. So it would always look at the wrong path for `definition.kore` (eg. it would look at `.build/defn/web3/driver-kompiled/definition.kore` when trying to do `build-web3`, when it should be looking at `.build/defn/web3/web3-kompiled/definition.kore`).

Anyway, during the switch to native markdown sources, I just gave each build their own `*_main_file` variable, so there is no longer a worry about how target-dependent variables are calculated.

But this also could have been avoided by being able to specify the name of the `*-kompiled` directory directly (independent of the name of the main definition file).

Another example of the annoyance could be seen with the Java vs Specs build on KEVM: https://github.com/kframework/evm-semantics/blob/master/Makefile#L176

Both builds get the same tangle tags, and so see identical definitions except that main module used is different. Before using native markdown, we had to tangle entirely separate definitions for them. Now we just create an empty directory `.build/defn/specs` and another one `.build/defn/java`, and tell the kompiler to put the `*-kompiled` directory in those sub-directories. So we can unambiguously get a handle on which definition we want by specifying it's parent directory, but it seems rather silly that we need the wrapper parent directories to specify them.

It would feel more natural to be able to point directly to the `*-kompiled` directory when invoking `krun` or `kprove`, without having to make wrapper directories for them.

Anyway, since we switched to native MD source support, the rebuildability issue went away, and this just became a minor annoyance rather than a build problem.

**Comment by tothtamas28** [comment]
This improvement would make it easier to handle multi-definition projects both manually and with scripts. From a UX perspective, directly pointing to the kompiled directory feels more intuitive. The constraint on `--directory` (i.e. that is should contain exactly one folder with name matching `*-kompiled`) seems unnecessarily restrictive.

**Comment by radumereuta** [comment]
Add a new option. The new flag should override the old behavior.
The old flag could issue a warning to deprecate it.
Suggestion: `--output, -o`

**Comment by tothtamas28** [comment]
>  Suggestion: --output, -o

I guess eventually this new convention will propagate to other K tools as well. There, you will have a flag like `--kompiled-dir` or similar. Maybe this more explicit name could be used for `kompile` as well so that the concept has the same name for all the tools (as in the case of `--directory`).

**Comment by radumereuta** [comment]
-o, --output-kdir
--input-kdir

**Comment by nishantjr** [comment]
I think I like `--kompiled-dir` best. Its obvious what it does (I think `kdir` is less obvious), and no tool had both input and output directories.

**Comment by radumereuta** [comment]
If we want to implement something like incremental kompilation then we need separate options.
I remember starting to work on something like that and got stuck right away because the options were too intertwined.

**Comment by nishantjr** [comment]
So for incremental compilation, we'd need to specify both `--input-kdir` and `--output-kdir`, then delete the original one once we're done? @radumereuta ?

**Comment by radumereuta** [comment]
Not delete it, but create a new one.
We had this requirement in one of the definitions we ship as a package and therefore is read only.
In any case, I think it's a good idea to have them separate.

**Comment by ehildenb** [comment]
I like `--directoryx`, and eventually deprecate the old one.

**Comment by dwightguth** [comment]
Let's not reinvent the wheel here. The flag to specify the output path of a compiler should be -o for output. That's just common convention for compilers.

**Comment by nishantjr** [comment]
I like `-o`.

**Comment by radumereuta** [comment]
Names:
kompile: `-o` `--ouput-definition`
input: `--definition`
If you don't pass these flags, the old behavior stands.
Error if you supply both.
