### ISSUE TITLE
Input of non primitive types does not work anymore

### ISSUE THREAD

**Issue by gleguern** [runtimeverification/k#1312]
Hi,

I have some troubles to handle inputs. I need to "load" adhoc data type values from a file. I am unsuccessful when trying to input adhoc data types and unable to use start up variables.

I use the following version of K (worked similarly with a previous version)
     RV-K version 1.0-SNAPSHOT
     Git revision: 396a314
     Git branch: UNKNOWN
     Build date: Wed May 27 18:38:26 CEST 2020

I built a MWE provided in attachment: [inputOutputMWE.zip](https://github.com/kframework/k/files/4702242/inputOutputMWE.zip)

When using stdin and Int values, it works even though K also outputs the following, seemingly on the error stream: "project:Int ( #EOF )".

When using stdin and DType values (alias for Int), K is unable to parse the integer and gets
stuck with the following <inputs> cell:
```
  <inputs>
    ListItem ( #parseInput ( "DType" , " \n\t\r" ) )
    ListItem ( #buffer ( "24\n" ) )
    ListItem ( "on" )
    ListItem ( #istream ( 0 ) )
  </inputs>
```

When using IN variable and Int values, K does not output anything except the following, seemingly on the error stream: "project:List ( 24  12  5  13  67  99  .IntList )".

When using IN variable and DType, K does not output anything except the following, seemingly on the error stream: "project:List ( 24  12  5  13  67  99  .DTypeList )".

Inputing Strings on stdin reads the string token by token, instead of the whole "-quoted string at once.

Complete tests can be executed by executing runBis.sh from [inputOutputMWE.zip](https://github.com/kframework/k/files/4702275/inputOutputMWE.zip)

How can I sequentially input adhoc data type values from a file ?

Thanks,

=============================================================================

```
module INPUTOUTPUT-SYNTAX
  imports DOMAINS-SYNTAX

  syntax IntList ::= List{Int, " \n\t\r"}
  syntax StringList ::= List{String, " \n\t\r"}
  syntax DataList ::= List{Data," \n\t\r"}
  syntax DTypeList ::= List{DType," \n\t\r"}

  syntax IdList ::= List{Id, ","}
  syntax Data ::= ".Data" | "[" Id "(" String ")" "is" Int "and" "knows" IdList "]"
  
  syntax DType ::= Int
  
  syntax Program ::= "forward" | "drop" | "duplicate"
endmodule

module INPUTOUTPUT
  imports DOMAINS
  imports INPUTOUTPUT-SYNTAX

  configuration
    <T>
      <inputs stream="stdin"> .List </inputs>
      // <inputs> $IN:List </inputs>
      <data> . </data>
      <k> $PGM </k>
      <outputs stream="stdout"> .List </outputs>
    </T>

  rule  
    <inputs> ListItem(Input:DType) => .List ... </inputs>
    <data> . => Input </data>

  rule  
    <data> Data:DType => . </data>
    <k> forward </k>
    <outputs> ... .List => ( ListItem(Data) ListItem("\n") ) </outputs>

  [...]
endmodule
```

**Comment by dwightguth** [comment]
Closing as stale. Please open a new issue if you still need this.
