### ISSUE TITLE
Endless compilation

### ISSUE THREAD

**Issue by vasil-sd** [runtimeverification/k#1315]
I've just found a strange behavior of K frontend (git tag  v5.0.0-3bfd4f8).

When attempting to kompile next code, compilation lasts forever.

----------
```
module CALC-SYNTAX
  imports INT-SYNTAX
  imports LIST

  syntax Exp ::= Int
               | "(" Exp ")" [bracket]
               | Exp "*" Exp [left, strict]
               > Exp "+" Exp [left, strict]
               | Exp "-" Exp [left, strict]

  syntax ExpList ::= List{Exp, ";"} [strict]
  syntax Exp ::= ExpList
               | eval(Exp)  [strict]

  syntax KResult ::= Int | ExpList

endmodule

module CALC
  imports CALC-SYNTAX
  imports INT

  rule L::Int + R::Int => L +Int R
  rule L::Int - R::Int => L -Int R
  rule L::Int * R::Int => L *Int R

  rule eval(E::Exp) => E
  rule eval(E::Exp; Es::ExpList) => eval(E); eval(Es)
  rule eval(.ExpList) => .ExpList

  configuration <k> eval($PGM:ExpList) </k>
endmodule
```

**Comment by dwightguth** [comment]
I'm not sure why compilation isn't terminating, but it looks like you have a bug in your configuration declaration. You probably mean to say something like: `configuration <k> eval($PGM:ExpList) </k>`

**Comment by vasil-sd** [comment]
Yes, this is obviously wrong code, because of my fault with markdown. :)
I'll fix the `<k> ... </k>` in my comment.

I've occasionally found this frontend bug, when explained to my son some ideas of computation.

**Comment by dwightguth** [comment]
The bug arises from the fact that you have both of the following productions:

```
syntax ExpList ::= List{Exp,";"}
syntax Exp ::= ExpList
```

The syntax of user-defined lists in K is that a single element can be used wherever a list is expected. However, you have declared that a list can appear wherever a single element is expected, which leads to infinite recursion when parsing. Normally, K would reject a definition with such a circularity in its grammar with an error, however, this was not happening here due to a bug involving detection in the presence of user-defined lists.

I suggest you modify the grammar of your definition so that it is not infinitely recursive.

**Comment by vasil-sd** [comment]
Yes. I've noted this circularity, but expected an error from kompile. And was slightly surprised by infinite loop in the front-end :)

**Comment by vasil-sd** [comment]
I've thought that List{Sort, "..."} is just a syntactic sugar that is desugared before any processing of K-definitions.

**Comment by dwightguth** [comment]
@vasil-sd that's not quite true; while it is true that it is desugared prior to compilation and execution, it still has certain special meaning to the parser.

**Comment by vasil-sd** [comment]
Is there any details about parsing pipeline of K-tools?

I've already several times got issues with lexing/parsing...

And last time I've found serious bug with lists, when empty production was inserted in kast from different list. Something like that:
```
syntax S1
syntax S2

syntax L1 ::= List{S1, ","}
syntax L2 ::= List{S2, "-=>"} // <- note different delim

syntax S3 ::= id:Id (L1)
```
And parser for some program statement like `Proc1(Arg1, Arg2)` (Arg1, Arg2 forms L1) gives next result (I've looked in kast) `Proc1(Arg1, Arg2, .L2)`.
So I've needed to rewrite statements into `Proc1(Arg1, Arg2, .L1)`.

At current moment I've not stripped this bug down into small reproduction case yet (semantics is about 5k lines in total and it is hard to isolate this bug into small case).

**Comment by dwightguth** [comment]
I can't speak to why that might happen without a complete example. You might find that `kompile -E` followed by manually removing all the rules from the resulting file except the one you think is parsing wrong, as well as all the syntax declarations and modules not used in the parse of that rule, would probably get the definition down to a reasonable size.
