### ISSUE TITLE
Access to source location information in semantics

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1358]
Source location is a nice to have information for printing error messages, and possibly for defining a semantics for whitespace sensitive languages. My immediate use case is so that I can generate output closer to Boogies, and can check my semantics against their test suite.

We'd like to be able to access the source information in rules. This means that
the source information would need to be represented as a term.

We cannot mark up every single term with source information as that would
increase the size of the kore term unnecessarily.

### One possible interface

Have a special sort `#SourceLocation` with the following constructor.
This constructor is not used in the grammar for program parsing.

```k                                                                                                                    
syntax #SourceLocation ::= #SourceLocation( file: String, line: Int, column: Int)
```

Consider the production:

```k
syntax Foo ::= #SourceLocation "foo" "(" ")"
```

When parsing a program `#SourceLocation` is parsed as an empty token, but is
populated with the source location information for that location.
We may also have multiple occurances if we want the begin and end information
for a particular token.

```k                                                                                                                    
syntax Foo ::= #SourceLocation "foo" "(" ")" #SourceLocation
```

Note that the meaning of 

```k                                                                                                                    
syntax Foo ::= "foo" "(" #SourceLocation ")"
```

is not obvious. Does it correspond to the position of the open or the close paren?

**Comment by ehildenb** [comment]
This needs some design work, it's not clear what the best way to do this is. The proposed solution doesn't look quite right, maybe something using attributes would be better. @nishantjr can you come up with a simple self-contained "wishlist" example?

**Comment by radumereuta** [comment]
I had to come up with something like this before. I wanted a way to store the location information from the parser, and the simplest and non-invasive way was to create a new parametric production which stored the location information and you could insert it everywhere:
```
syntax {S} S ::= info(S, source:String, startLine:Int, startColumn:Int, endLine:Int, endColumn:Int)
symbol info{S}(S, String{}, Int{}, Int{}, Int{}, Int{}) : S []
```
When pretty-printing kore terms in kast, I would add one of these on top of every term: https://github.com/radumereuta/k-light/blob/evenLighter/src/test/k/unparametric_examples/positive_numbers/input.kore.info
What I don't like about this solution is that it makes the code unreadable, way too large. So I added options to kast to pretty print with our without the info nodes. This way we can transfer location information from kast to krun via text.
The info nodes can be only textual and internally the location information can be stored inside every node, similar to the KIL/KORE classes, so the backend shouldn't be affected that much.
When matching in rules, you could use it only in places that you are interested in (LHS or RHS), and the rest of the nodes just preserve their location whether they come from the program or the definition.
If I remember correctly, Grigore was involved in coming up with this solution.
