### ISSUE TITLE
Sort error messages by source location

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1370]
When fixing errors/warnings, they are displayed unsorted. If there are multiple errors and we start with one in the middle, the line numbers become wrong for the other messages, forcing us to recompile to get the correct line numbers.

**Comment by dwightguth** [comment]
Technically they /are/ sorted, but they are sorted lexicographically rather than based on the source location. Sorting them based first on location and then on error text is something I have wanted to do, I just haven't gotten around to it. But it shouldn't take too long, I don't think.
