### ISSUE TITLE
Multiple `prec` attributes by 100

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1379]
`#UpperId` and `#LowerId` have `prec(2)` while `KLabel` and `#KVariable` have `prec(1)`. That does not leave much room for other priorities. Even if `KLabel`, `#KVariable` aren't a problem, since we can't have negative precedences, only `prec(0)` and `prec(1)` are available to users. Perhaps we should multiply these by 100?

To make it backward compatible we could introduce a new `precedence` attribute with `prec(N)` synonymous with `precedence(N * 100)`.

**Comment by dwightguth** [comment]
The prec attribute is more of a special purpose hack to get around certain restrictions in the current scanner than a general purpose mechanism. While what you describe sounds nice in theory, I suspect actually trying to put it into practice would break the very delicate balance that exists between scanner and parser in K currently. I'm willing to be persuaded that I'm wrong and something like this is actually necessary, but you're going to need to provide an example of something where it's necessary first.

**Comment by ehildenb** [comment]
I'm not sure why we need to multiply by 100, would just shifting by 20 work? So 21 and 22? That way they are still close to each other? Or if @nishantjr provides an example of where you would want precedence between the two, we could do `20` and `40` or something.

But if those are the only two places where precedence are used, my gut says it shouldn't break anything to monotonically shift all the ones that show up in kast.k and domains.k.

**Comment by ehildenb** [comment]
@nishantjr can you either:

-   Close this because it's not needed.
-   Provide an example where it is needed.
-   Respond to our questions.

**Comment by nishantjr** [comment]
I don't have  a particular use for this, and wrote it up as a comment when I was writing the documentation for the attribute.
