### ISSUE TITLE
Context does not allow the introduction of a new sort

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1382]
This
```
module CONTEXT

syntax A ::= "a"
syntax B ::= b(A)
syntax C ::= c(A)

context b(HOLE => c(HOLE))

endmodule
```
fails with
```
$ kompile context.k
[Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected token 'c'.
        Source(/home/virgil/runtime-verification/rv-c-semantics/./context.k)
        Location(7,19,7,20)
```

**Comment by ehildenb** [comment]
The symbol `#KRewrite` (`_=>_`) is used for different things in rule and contexts.

In rules, it's required that each side of the rewrite has the same sort. In Contexts, it's not required.

```
<k> b(SOMETHING) </k>
<k> c(SOMETHING) ~> freezer_b() </k>
<k> c(EVALUATED_RESULT) ~> freezer_b() </k> #And isKResult(EVALUATED_RESULT)
<k> b(EVALUATED_RESULT) </k>
```

Another example:

```
context <k> foo(b(HOLE), _) ...</k> <state> .Map </state>

<k> foo(b(SOMETHING), ARG2) ... </k> <state> .Map </state>
<k> c(SOMETHING) ~> freezer_foo_b(ARG2) ... </k> <state> .Map </state>
<k> c(SOME_RESULT) ~> freezer_foo_b(ARG2) ... </k> <state> .Map </state> #And isKResult(SOME_RESULT)
<k> foo(b(SOME_RESULT), ARG2)
```

We agree this is confusing syntax, so we should make a decisions about changing it.

-   Backwards compatible: 1
-   No backwards compatible:
-   Support both indefinitely (with deprecated message): 1111
-   Support both for a while (with deprecated flag): 111

We will support both indefinitely, with a deprecated message.

Ideas we came up with for this:

```
syntax SyntaxProduction ::= "context" KItem "for" KItem
context c(HOLE) for b(HOLE)
```

```
syntax SyntaxProduction ::= "context" KItem "<~" KItem
context c(HOLE) <~ b(HOLE)
```

**Comment by ehildenb** [comment]
@dwightguth please investigate in teh C semantics some of the more gnarly contexts and let us know what you think next week.

**Comment by ehildenb** [comment]
I have confirmed that the original error persists.

**Comment by dwightguth** [comment]
Closing as stale. If you still feel you would benefit from this, feel free to reopen.
