### ISSUE TITLE
Error "Found multiple modules" when kompiling with --coverage

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1388]
The following set of modules are empty, and `kompile` fine usually.
When kompiling with the `--coverage` flag, the process fails, reporting that there are several modules named `WASM-TEXT`.

To reproduce:

Extract archive, `cd` into `coverage-error` and execute:

```
$ kompile --backend llvm --md-selector "k" --coverage --debug -ccopt -g test.md      \
    --directory .build/defn/llvm -I $(pwd)  \ # Change -I flag as needed
    --main-module WASM-TEST     \
    --syntax-module WASM-TEST-SYNTAX
```
Output:
```
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 structural errors.
        at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:134)
        at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:76)
        at org.kframework.kompile.Kompile.structuralChecks(Kompile.java:351)
        at org.kframework.kompile.Kompile.checkDefinition(Kompile.java:298)
        at org.kframework.kompile.Kompile.run(Kompile.java:133)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Compiler: Found multiple modules with name: WASM-TEST
```

Without the `--coverage` file, the process succeeds.
[coverage-error.tar.gz](https://github.com/kframework/k/files/4852106/coverage-error.tar.gz)

EDIT:

Here are the source files:

# `data.md`
<pre>
```k
require "domains.k"
```

`WASM-DATA` module

```k
module WASM-DATA
    imports INT
    imports BOOL
    imports STRING
    imports LIST
    imports MAP
    imports FLOAT
    imports BYTES
```

```k
endmodule
```
</pre>
# `numeric.md`

<pre>
```k
require "data.md"

module WASM-NUMERIC
    imports WASM-DATA
```

```k
endmodule
```

</pre>

# `test.md`

<pre>
```k
require "wasm-text.md"
```

```k
module WASM-TEST-SYNTAX
    imports WASM-TEST
    imports WASM-TEXT-SYNTAX
endmodule

module WASM-TEST
    imports WASM-TEXT
```

```k
endmodule
```
</pre>

# `wasm.md`

<pre>
```k
require "data.md"
require "numeric.md"

module WASM
    imports WASM-DATA
    imports WASM-NUMERIC
```

```k
endmodule
```
</pre>
# `wasm-text.md`

<pre>

```k
require "wasm.md"
require "data.md"

module WASM-TEXT-SYNTAX
    imports WASM-TEXT
    imports WASM-SYNTAX
endmodule

module WASM-SYNTAX
    imports WASM-TOKEN-SYNTAX
    imports WASM-DATA
endmodule
```

Wasm Tokens
-----------

```k
module WASM-TOKEN-SYNTAX
```

```k
endmodule
```

Wasm Textual Format
-------------------

```k
module WASM-TEXT
    imports WASM
```

```k
endmodule
```

</pre>

**Comment by hjorthjort** [comment]
Changing to `--main-module WASM --syntax-module WASM` leads to the same issue, _but_ just passing `--main-module WASM` and removing the `--syntax-module` removes this issues (and reveals another issue, which I'm in the process of reporting).

**Comment by dwightguth** [comment]
Please inline the k file into the issue rather than putting it in a .tar.gz or .zip file. Adding archive attachments to the issue significantly increases the burden on the person fixing the issue.

**Comment by hjorthjort** [comment]
@dwightguth Thanks for letting me know, I assumed the opposite, that a tar-ball was easier than copy-paste. I'll inline the files in the future.

**Comment by dwightguth** [comment]
I will just proceed using the tarball for now, but the reason why I requested the file inlined was because I assumed that it should be a single file. Unless the error can only be reproduced with multiple files, you should take the time to minimize the example down into a single file before reporting. Even if it does require multiple files, you should use the minimum number required to actually reproduce the error.

**Comment by hjorthjort** [comment]
Alright, gotcha. The files are inlined above in the issue if that helps. I don't recall if the issue required several files to reproduce or not.
