### ISSUE TITLE
Nested binding with ambiguities in syntactic categories

### ISSUE THREAD

**Issue by dhsorens** [runtimeverification/k#139]
K is having problems with nested binding when there is more than one possible match for a particular syntactic category. In the following example, our binder is `sub ID with PROCESS in { BODY }`. `Nil` is the only process, and two processes can be written side-by-side as `Process | Process`.

If processes (`Proc`) and the body (`Body`) are members of multiple syntactic categories, given below as `MoreProc` and `MoreBody`, the substitution rule will return an assertion error on the program below.

```
sub x with Nil in {
        sub y with Nil in { x | y }
  }
```

```
require "substitution.k"

module BIND-SYNTAX
imports SUBSTITUTION
imports DOMAINS

syntax Proc ::=
	  "Nil"
	| Proc "|" Proc [left]

syntax Body ::=
	  Proc
	| "sub" Id "with" Proc "in" "{" Body "}" [binder(1 -> 3)]
	| Id
	| Body "|" Body [left]

syntax MoreProc ::=
	  Proc

syntax MoreBody ::=
	  MoreProc
	| "sub" Id "with" MoreProc "in" "{" MoreBody "}" [binder(1 -> 3)]
	| MoreBody "|" MoreBody [left]

syntax KVariable ::= Id

endmodule

module BIND
imports BIND-SYNTAX

rule sub X:Id with P:Proc in { B:Body } => B[ P / X ]

endmodule
```

The assertion error can be fixed minimally by removing the substitution, i.e. replacing `B[ P / X ]` in the rule by `B`, or by deleting `"sub" Id "with" MoreProc "in" "{" MoreBody "}" [binder(1 -> 3)]` from `MoreBody`.

This is on the latest version of K5.

**Comment by dwightguth** [comment]
Please refer to the attached PR which fixes your issue. Note that K no longer supports specifying the targets being bound and bound to in the binder attribute; ie, `binder(1 -> 3)` is equivalent to just `binder` which binds the first child within the last child, the same behavior I assume you wanted here. If you have other binders in your definition which do not bind the first child within the last child, I would suggest doing the following replacement:

`syntax Foo ::= someTerm(A, B) [binder(2 -> 1)]`

To

```
syntax Foo ::= someTerm(A, B)
syntax Foo ::= someAlias(B, A) [binder]
rule someTerm(A, B) => someAlias(B, A) [alias]
```

**Comment by dhsorens** [comment]
Thank you for the PR!

**Comment by dhsorens** [comment]
I just implemented an example with the rule tagged `[alias]`. Using your syntax, if I write:

```
someAlias(x, 
	someTerm(x, A)
)
```

then K does not know to shadow x using someTerm( ) and will bind/substitute x, rendering incorrect syntax.

For the full code/example, see:
**Code**
```
require "substitution.k"

module BIND-SYNTAX
imports SUBSTITUTION
imports DOMAINS

syntax Body ::=
	  Proc
	// Alias
	| "sub" Proc "into" Id "in" "{" Body "}"
	// Binder
	| "sub" Id "with" Proc "in" "{" Body "}" [binder]
	| Id
	| Body "|" Body [left]

syntax Proc ::=
	  "Nil"
	| Proc "|" Proc [left]

syntax MoreProc ::=
	  Proc

syntax MoreBody ::=
	  MoreProc
		// Alias
		| "sub" MoreProc "into" Id "in" "{" MoreBody "}"
		// Binder
		| "sub" Id "with" MoreProc "in" "{" MoreBody "}" [binder]
		| MoreBody "|" MoreBody [left]

syntax KVariable ::= Id

endmodule

module BIND
imports BIND-SYNTAX

rule sub P:Proc into X:Id in { B:Body } => sub X with P in { B } [alias]

rule sub X:Id with P:Proc in { B:Body } => B[ P / X ]

endmodule
```

**Example**
```
sub y with Nil in {
        sub Nil | Nil into y in { y }
  }
```

The example should return `Nil | Nil`, since the inner binder shadows `y`. Instead, the outer binder binds `y` and K returns `sub Nil | Nil into Nil in { Nil }`.

**Comment by dwightguth** [comment]
I cannot reproduce the behavior you report: I tested with that example and it works exactly as expected and yields the correct result.

**Comment by dhsorens** [comment]
Must be something on my end then, this is very good. Thank you!

**Comment by dwightguth** [comment]
You might try deleting the bind-kompiled directory and see if that helps, sometimes there are issues with caching  when you change only the attributes of a sentence.

**Comment by dhsorens** [comment]
That didn't do it, but it's been a couple weeks since I updated K. Maybe that's the problem.

I actually have a question for you re the aliases. Right now I have a construct that comes in this form:
```
f(A1, B1 ; A2, B2 ; ...  ; A_n, B_n){ C }
```
where we bind free vars in the `A_i`, receive input from the `B_i` and substitute the `B_i` into the `A_i` contained in `C`. I would ideally like to write an alias that rewrites 
```
f(A1, B1 ; A2, B2 ; ...  ; A_n, B_n){ C } => f( {A1 ; A2 ; ... ; A_n} , {B1 ; B2 ; ... ; B_n} ){ C }
```
in one go (I have some intermediary steps but they are giving me a bit of trouble). Is it (a) possible to compose aliases, and (b) can you think of some way to write a rule of that form—like some for all feature?

**Comment by dwightguth** [comment]
You can essentially view an alias as a rewrite rule without a side condition that applies statically before rewriting begins and applies statically in reverse after rewriting ends.

I haven't tested it, but something like this should work:
```
rule f(A, B ; Rest) { C }

**Comment by dwightguth** [comment]
You can essentially view an alias as a rewrite rule without a side condition that applies statically before rewriting begins and applies statically in reverse after rewriting ends.

I haven't tested it, but something like this should work:
```
rule A, B; ({ As }, { Bs }) => { A; As }, {B; Bs} 
rule .ABs => { .As }, { .Bs }
```

**Comment by dhsorens** [comment]
Is there/will there be a nightly build that incorporates this PR?
