### ISSUE TITLE
Cell names are case sensitive

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1391]
Currently you cannot have two cells with the same name but different capitalization, because of the way the sorts which are produced get named. Example (with `kompile --backend haskell test.k`):

```
module TEST
    imports BOOL
    imports STRING

    configuration <k> $PGM:String </k>
                  <pot-pie> 0 </pot-pie>
                  <pot-Pie> 0 </pot-Pie>
endmodule
```

Produced output (on latest release at time of writing v5.0.0-71d191f):

```
[Error] Compiler: Too many productions for cell sort: PotPieCell
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

Expected behavior: give different sort names for the two cells so that we can have our pie and eat our Pie too.

**Comment by ehildenb** [comment]
We don't have a backwards compatible way to do this, so it's become low priority.

**Comment by dwightguth** [comment]
Closing this as stale. Feel free to reopen if you still believe you would currently benefit from this.
