### ISSUE TITLE
Update styling on K GitHub pages

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1404]
The current page https://kframework.github.io/k looks pretty bad. Let's update it with some styling, and then point https://kframework.org at it.

-   Update `index.md` to have some text from runtimeverification.com.
-   Add some custom themes to K flavor these pages.
-   Check for inconsistencies in styling on all links.
-   Check for dead links.
-   Point kframework.org DNS at this page (need a CNAME file).

**Comment by shd101wyy** [comment]
I hope @bogdan-stanciu could help design the page 😀

**Comment by bogdan-stanciu** [comment]
I'm partial to this design https://doks.themejack.com/blue/ but I can see
how this template https://hyde.getpoole.com/ fits the job better.

**Comment by bogdan-stanciu** [comment]
So, after the second consideration, Yiyi and I decided to go with a design
similar to Firefly, but with the global navigation on the left.

K logo replaces the Firefly logo, and the Global Navigation goes
underneath.

Then the second task becomes the content migration.

**Comment by ehildenb** [comment]
Website is updated, happy with new styling.
