### ISSUE TITLE
kprove - Java backend does not compute remainder configuration when no rules are matched

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#1418]
This is a known soundness issue. Issue is not present in Haskell backend.
To reproduce: https://github.com/kframework/k/pull/993
File `assert.k`
```
module ASSERT
  imports BOOL
  imports INT

  configuration <T>
    <k> $PGM:K </k>
  </T>

  syntax Assert ::= "assert" Bool
  rule assert B => .
    requires B

endmodule
```
File `assert-spec.k`
```
module ASSERT-SPEC
  imports ASSERT
  rule <k> assert (A ==Int 0) => . </k>
endmodule
```

This spec is expected to fail because there's no rule to match the case `A =/=Int 0`, but instead it passes.

File `Makefile`
```
DEF=assert
EXT=test
KOMPILE_BACKEND?=java
TESTDIR=.
include ../../../include/ktest.mak
```

**Comment by ehildenb** [comment]
This is a long-term known issue with Java backend, not worth our time to fix, and was a motivating example for why to develop a new (more sound) backend.

**Comment by daejunpark** [comment]
It is the user's responsibility to ensure that the definition is complete (for the java backend).

**Comment by denis-bogdanas** [comment]
Yes, I found that in the meantime. Put it here for posterity. Maybe we'll add this issue to some list of Java Backend limitations some day.
