### ISSUE TITLE
[KIP] - Rename #True and #False

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#1467]
I propose that we rename 

-   `#True` to `#Top`, and
-   `#False` to `#Bottom`.

Motivation
----------

The Matching Logic papers and the Kore backend use the `\top` and `\bottom` terminology. Changing the vocabulary in the K frontend would bring all three into harmony and reduce the potential for miscommunication between users and the backend team.

There is potential confusion between the `#True` and `#False` Matching Logic predicates and `Bool` values `true` and `false`. Mistaking `true` with `#True` is a real bug that has actually happened.

Documentation
-------------

`#Top` is the Matching Logic predicate pattern that matches all values. Conversely, `#False` matches no values.

Potential Alternatives/Work-arounds
-----------------------------------

We could instead do nothing. Most users will internalize the difference between `#True` and `true` after tripping over it once or twice. It is also likely that many users aren't reading the Matching Logic papers or the backend documentation anyway.

**Comment by dwightguth** [comment]
One middle ground would be to support both, but unparse as `#Top`

**Comment by ehildenb** [comment]
Initially just support both, and unparse to `#Top` and `#Bottom`, and train ourselves and our documentation to prefer these:

```
syntax {Sort} Sort ::= "#Top" [klabel(mlTop)] | "#Bottom" [klabel(mlBottom)] | "#True" [klabel(mlTop)] | "#False" [klabel(mlBottom)]
```

Agnostic at the moment about deprecating `#True` and `#False`. Can worry about it later.
