### ISSUE TITLE
Separate out `domains.md` into many files for easier browsing of the "standard library"

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1478]
The thought is that `domains.md` is quite large, which makes it harder to have a cohesive story about all the documentation.

Separating out into individual files may offer better compartmentalization.

**Comment by ehildenb** [comment]
Thoughts are:

-   Not much point separating it now. @radumereuta makes the point that it's easier to search the file if it's a single file.
-   @dwightguth argues that we shouldn't do too much splitting, maybe numbers in one module, data-structures in another, etc...

**Comment by Baltoli** [comment]
This is an old issue now; closing as there hasn't been any desire to revive this and it would be easy to do so if we wanted.
