### ISSUE TITLE
Constructor attribute on parametric symbols that aren't functions in ModuleToKORE

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#1479]
Essentially, the idea would be that a parametric symbol whose return sort is a sort variable, but is not a function, would be a constructor only on a certain finite set of sorts which are described in an attribute. This involves modifying ModuleToKORE to track all the used instantiations of a parametric symbol and adding them to the no junk axioms and the constructor attributes on the symbol itself.

**Comment by ehildenb** [comment]
This requires changes to the Haskell backend to even have sensible support in the frontend, so we will wait until the backend supports it and we have a more clear need for it.

**Comment by ttuegel** [comment]
> This requires changes to the Haskell backend to even have sensible support in the frontend, so we will wait until the backend supports it and we have a more clear need for it.

I'm not sure why the backend needs to change first, but we do have a clear need for it now: the C semantics.

There is another way we could support polymorphic constructors at the K level: Generate a corresponding monomorphic constructor in Kore in its own, distinguished sort, and make that sort a subsort in Kore of the sorts where the polymorphic constructor appears in K. Generate patterns using a sort injection where necessary.

I think this would not require more changes to the frontend (compared to the original plan) and it would not require any changes in the backend. Under the original plan, the backend would have to make this transformation anyway, or we would not be able to send expressions involving constructors to Z3 (which lacks user-defined polymorphic symbols).

**Comment by ttuegel** [comment]
Actually, the more I think about this problem, I don't think the backend should support this. I don't think that a "polymorphic constructor" says in Kore what the user would want it to say. For example, I think the user would need to write (at least) twice as many rules to have complete coverage, except in special cases.
