### ISSUE TITLE
Built-ins in K

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#148]
Hello guys,

I am writing a seminar work with the title "Introduction into K framework".

So far I have been using a few official paper guides from Grigore Rosu.
Everything is well-written and understandable. There is only one section about
the Built-ins which is too short in my opinion. I want to expand this by creating a list.
This list should contain all Built-ins with description being used in K.

I have found these k-files in the k-distribution directory:
![liste](https://user-images.githubusercontent.com/43268150/45545446-926bd100-b81a-11e8-8d9e-882ad9de94f4.PNG)

Is this list of files complete regarding semantic/syntactic datatypes/categories complete?

If you guys can help me with building up a list with all Built-ins, it would be great and helpful.

Thanks!

**Comment by dwightguth** [comment]
Take a look at `k-distribution/include/builtin`. The files in this directory contain the complete list of builtins. The `builtins` (with an s) directory is out of date and should probably be deleted.
