### ISSUE TITLE
bug with /tutorial/simple_untyped 

### ISSUE THREAD

**Issue by dexter-qjq** [runtimeverification/k#150]
i just install the K5.0, and successfully kompiled the imp.k. when i try to kompile the simple_untyped.k. i found there is something wrong with the definition of BAG.  the log just follow:

kompile simple-untyped.k (i have committed all rules for simplifying)
40 states, 1247 transitions, table size 5228 bytes
File "realdef.ml", line 2322, characters 81-82:
Error: Syntax error: ')' expected
File "realdef.ml", line 2322, characters 61-62:
Error: This '(' might be unmatched
[Error] Critical: ocamlopt returned nonzero exit code: 2
Examine output to see errors.
[Warning] Compiler: missing entry for hook BAG.concat
[Warning] Compiler: missing entry for hook BAG.element
[Warning] Compiler: missing entry for hook BAG.unit

**Comment by ehildenb** [comment]
We're deprecating the OCaml backend in the next few months. Please switch to the LLVM backend and if you have issues there then re-open.
