### ISSUE TITLE
Error if `=>` appears inside `#as`

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#1518]
I accidentally wrote something strange in K today and I wanted to get some people's thoughts on whether they think this ought to be an error or not:

```
rule k (foo => bar) #as X .../k
     foo X /foo
```

This rule actually made the definition loop forever, because the right hand side of P #as X is treated as X. X is bound to the left hand side of the rewrite, so the right hand side of this rule just becomes "X" and the rewrite is silently discarded. There is possibly some case to be made that this rule is correct and should result in bar, but this would make it difficult to put as patterns outside of a rewrite and get an efficient implementation. What does everyone think about just making it an error for a rewrite to be nested inside an as pattern?

**Comment by ehildenb** [comment]
Consensus is to make this an error for now.
