### ISSUE TITLE
[KIP] - Introduce a new keyword "const" for defining named constants

### ISSUE THREAD

**Issue by malturki** [runtimeverification/k#1527]
[KIP] - Introduce a new keyword "const" for defining named constants

It's generally good programming practice to use named constants and most programming languages provide specific ways to define them. However, defining a named constant in K requires two steps: declaring the syntax of the named constant using "syntax" and defining its value using a macro "rule", which is inefficient and prone to errors. An example follows:

```k
syntax Int ::= "SPEEDOFLIGHT"
rule SPEEDOFLIGHT => 299792458 [macro]
```

This is inefficient, especially when there is a good number of named constants that need to be defined (see e.g. https://github.com/runtimeverification/beacon-chain-spec/blob/master/constants-minimal.k).

I suggest introducing a new keyword "const" to the frontend for declaring and defining named constants in one step. "const" only needs three pieces of information: the name, the sort and the value. It could have the following format:

```k
const CONST_NAME : SORT = CONST_VALUE
```

For example, the above K specs defining the `SPEEDOFLIGHT` named constant could be written using "const" simply as follows:

```k
const SPEEDOFLIGHT : Int = 299792458
```

Generally, any use of "const" is re-written using a pair of "syntax" statement and a "rule" statement as illustrated above. So "const" can be actually be dealt with as a pseudo-keyword. Furthermore, instead of just using a value for CONST_VALUE on the right-hand side, we may allow any well-formed expression (of the right sort), so that the general form of the "const" statement becomes:

```k
const CONST_NAME : SORT = EXPR
```

Note that EXPR may use named constants defined before. Finally, type inferencing can in principle be extended to support "const" statements, so the user won't need to specify the sort if it can be inferred from the value. So for the `SPEEDOFLIGHT` example, and using an expression instead of a value, we may use:

```k
const SPEEDOFLIGHT = 871490 *Int SPEEDOFSOUND
```

Sort inference will then be used in the process of generating the corresponding pair of "syntax" and "rule" statements.

**Comment by ehildenb** [comment]
I like this idea, would make a lot of the tables of values in KEVM more readable, for example.

It seems to me that the general syntax should be:

```
syntax ConstSentence ::= "const" KVariable "=" K
```

should be the outer syntax, and then adding the sort annotation (which may be inferred) is just because a `KVariable` can be parsed with or without the sort annotation.

Also, would it be nice to be able to declare a constant expression without the corresponding macro, for uninterpreted constants?

```
const LARGEST_PRIME:Int
```

with outer syntax:

```
syntax ConstSentence ::= "const" KVariable
```

**Comment by malturki** [comment]
Sure. Supporting uninterpreted constants would probably improve readability. It may not help much in terms of conciseness of code though. Also, once a named constant is declared uninterpreted, it should not be possible to later modify the constant to have a concrete value (otherwise we lose much of the value added by having this specific syntax, I think).

**Comment by ehildenb** [comment]
Some issues:

-   `const` is often a keyword in languages, so it may complicate outer/rule parsing which use that keyword.

Low priority because it can already be done in the more verbose.

What about (to avoid introducing a new keyword):

```
syntax SPEEDOFLIGHT = 299792458
```

this may be ambiguous with the sort alias parser:

```
syntax Wad = Int
syntax Rad = Int
```

Perhaps this (second part is a bubble):

```
syntax SPEEDOFLIGHT => 299792458
```

@malturki any thoughts?

**Comment by malturki** [comment]
We can use `constant` instead of `const` (or maybe `konst`?). Overloading `syntax` too much can be a problem in itself. I can easily imagine people mistyping similarly looking symbols like `=` and `=>` and running into hard-to-discover problems because of this.

**Comment by malturki** [comment]
Another issue here is that we might want to consider implementing constants using something other than macros, as they are not supported by the bison parser.

**Comment by ehildenb** [comment]
Perhaps another option would be `syntax const`, or `syntax constant`

**Comment by dwightguth** [comment]
This is over two years old, so I'm going to close it. @malturki , feel free to reopen if you still believe it would provide value to you.
