### ISSUE TITLE
Forbid functions in arguments outside simplification rules

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#1545]
The frontend should produce an error message for function rules where functions appear in arguments on the left-hand side; such rules must have the `simplification` attribute after #1252.

For example, this rule is not valid, because `+Int` and `-Int` appear as arguments of `+Int` on the left-hand side:

```.k
    rule (A +Int I2) +Int (I3 -Int A) => I2 +Int I3
```

**Comment by ehildenb** [comment]
The frontend already has such a check, which is disabled in Java and Haskell backend (because we used to not have the simplification attribute). We need to re-enable this check for Java and Haskell backends but only on function rules which don't have `simplification` attribute.

**Comment by ehildenb** [comment]
@dwightguth please post where the code location to change is.

**Comment by radumereuta** [comment]
I need a bit more information to properly implement this.
Should this check apply to claims as well?
How about `trusted` claims?

I got this failing test and I'm not sure what is the best approach:
https://github.com/kframework/k/blob/master/k-distribution/tests/regression-new/proj-attribute/a-spec.k#L13

**Comment by ehildenb** [comment]
It should not apply to claims, and I think not to `trusted` claims either.

**Comment by ttuegel** [comment]
@radumereuta The original issue is only concerning _function_ rules, not claims or rewrite rules.

**Comment by radumereuta** [comment]
@ttuegel if I remember correctly, a function rule is a rewrite rule with a few restrictions:
- at the top there is a function symbol
- no other function symbols are on the LHS
So this step is part of determining if a rule is a function rule. Please correct me if I'm missing something.
(I have omitted claims as Everett said, and a few other changes, and waiting for the test results to see what else breaks)

**Comment by ttuegel** [comment]
When kompiling for the Haskell backend, function rules and rewrite rules are completely unrelated. A function rule has a function symbol at the top of the left-hand side. If there is any other function symbol on the left-hand side, the frontend _should_ produce an error; it currently doesn't, which is the motivation for this issue.
