### ISSUE TITLE
[Bug] kompile - kompile crashes with z3 4.8.9

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#1550]
This is with the latest master branch of K.

Description
-----------

When the installed version of z3 is equal to 4.8.9, kompile will crash with errors in z3 arising from the type inferencer that look like the following:

```
line 230 column 208: invalid named expression, declaration already defined with this name constraint1_Sort#RuleBody
```

This can be reproduced with any K definition, as the error is manifested when parsing the K prelude.

**Comment by dwightguth** [comment]
This seems to be the result of an upstream regression in z3 in version 4.8.9. I have reported it upstream here: Z3Prover/z3#4701. In the meantime, we should think about directing users on arch linux and Mac OS to install z3 4.8.8 manually somehow.

**Comment by dwightguth** [comment]
This is fixed upstream and should work in z3 4.8.10, assuming no further regressions. Should we add a known issues warning to the install page for K? Or do you guys think it is worth coming up with a solution that works on z3 4.8.9?

**Comment by sskeirik** [comment]
Given that z3 has binary releases as zipfiles, we could direct the user to download the 4.8.8 release zipfile, unzip it, and put it first in their path. Alternatively, we could provide a script that does this. Thoughts?

**Comment by sskeirik** [comment]
BTW, it appears that our packaging CI builds are failing due to this bug.

From what I can tell, depending on execution order, either the Homebrew or Arch package test fails with this z3 error.

Given that we are still months out likely from a new release, I think we should either modify the Arch/Homebrew CI build process to make sure that the correct version of z3 is on the path when tests are run (or) disable the tests temporarily while this gets fixed.

Thoughts?

**Comment by dwightguth** [comment]
Well, in theory this bug happens because we pop a symbol that was declared, then push a different symbol with the same name. It ought to be possible to change the code for z3 type inferencing so that we never reuse the same symbol name inside the same process. As a result of which, you could have z3 4.8.9 installed and the bug wouldn't be triggered. I'd rather explore such a solution instead of decreasing test coverage or modifying the CI. But if this bug is really so serious, oughtn't we at least talk to Nikolaj Bjorner first and ask for some kind of bugfix release? It seems bad to have the latest release of z3 to just be unusable for six months.

**Comment by sskeirik** [comment]
Ultimately, I think it's your call, since you know how the inferencer works better than anybody else and what would be needed to make the change. But I agree, there is no harm in asking for a bugfix release from upstream.
