### ISSUE TITLE
Add option `--emit-latex-prelude` to `kompile`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1560]
Currently we are not taking into account any of the latex formatting attributes, which kdoc used to rely on, but can emit latex ASTs for any of the commands.

If we add `--emit-latex-prelude` to `kompile`, which defines all the `newcommands` (using the same name-munger that `--output latex` uses), then we should be able to build nice latex documents again.

**Comment by Baltoli** [comment]
We no longer support Latex output; closing this for now.
