### ISSUE TITLE
Update install instructions to inform users that they cannot use Z3 4.8.9

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1561]
Currently Z3 version 4.8.9 (which is available on at least Arch and MacOS) does not work with K. We should inform users of this.

Put this in the `INSTALL.md` (for release pages), and maybe in `Troubleshooting` on the `README.md` (for devs).

Also delete the stale file `k-distribution/README.md`. This is currently being used in the `package/....` directories for packaging. You should instead use the top-level `README.md` instead.

**Comment by sskeirik** [comment]
In particular, the README used in the packaging is set here: https://github.com/kframework/k/blob/0ff5c9bbe664528d438daf7acacb4603a698e102/k-distribution/src/main/assembly/bin.xml#L25

This StackOverflow note about maven parent POMs base directories might be useful: https://stackoverflow.com/questions/19511785/getting-parent-directory-of-basedir-from-maven --- or I could try using `${project.basedir}/..` and see if that works.
