### ISSUE TITLE
Question mark "?" not pretty-printed

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#1564]
In final configuration we get output like this:
```
    (InfoReachability) while checking the implication:
    The claim cannot be rewritten further, and the claimed implication is not valid.
  #Ceil ( #buf ( 32 , #lookup ( 'QuesUnds'STORAGE , keccak ( #buf ( 32 , ?ACCT1 ) ++ b"0000000000000000000000000000000000000000000000000000000000000000" ) ) ) )
#And
```

Not sure whether `#Ceil` is a problem btw. This is vanilla KEVM without `#Ceil(#buf)`.

https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/erc20-verification/detail/PR-143/6/pipeline/

@ttuegel

**Comment by ehildenb** [comment]
@denis-bogdanas can you make a minimal example of this? What it would look like is the Kore of the term `#lookup(?STORAGE, #buf(32, ?ACCT1))`, and then make sure that calling `kast` on that (with a minimal definition) incorrectly unparses it.

If you post those here it will make fixnig this easier.

**Comment by ehildenb** [comment]
I believe this should be sorted now, we had some problems with the unmunger. Re-open if not sorted.
