### ISSUE TITLE
[Bug] [kompile] - LLVM backend crashes with non-intuitive error message when non-function/non-builtin symbols are used in side-conditions

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#1568]
K Version
---------

```
kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 39291c7
Git branch: master
Build date: Wed Sep 30 14:09:24 CDT 2020
```

Description
-----------

Running `kompile` causes the LLVM backend to crash when non-function/non-builtin symbols are used in side-conditions.

The error message returned to the user talks about LLVM IR types and is unable to be linked to the root cause without experimental verification.

Input Files
-----------

File: `test.k`

```
module TEST-SYNTAX
  syntax Foo ::= "Foo" | "Bar"
endmodule

module TEST
  import TEST-SYNTAX
  import BOOL

  configuration <k> $PGM:Foo </k>

  syntax Bool ::= "myCond" // [function]

  rule <k> Foo => Bar </k>
    requires myCond
endmodule
```

Note: the author forgot to add the `[function]` attribute to `myCond` 

Reproduction Steps
------------------

```
kompile test.k --backend llvm
```

Expected Behavior
-----------------

The user should receive an error message which states that a non-function/non-builtin symbol was used in a side-condition. This lets the user know how to fix the problem.

This error should be generated for any backend that does not support this functionality.

**Comment by dwightguth** [comment]
One thing I am wondering is, do we want to restrict the contents of `requires` and `ensures` clauses to be of sort `Bool` in the syntax? This would in theory be a breaking change, but I don't think we actually have any such rules that it would break. The advantage is we would get a parse time error if the user puts the wrong sort there. Obviously we also want to have an error if the user defines constructors of sort Bool, though.

**Comment by sskeirik** [comment]
My feeling is that non-boolean side-conditions should be forbidden, because the semantics of such a side-condition is unclear, and because, as far as I know, we don't expose underlying logical operators that could replace it.

Maude avoids this issue because it:

- has equality as a built-in operator in side-conditions
- imports `BOOL` by default
- automatically converts boolean side conditions `P(x)` into `P(x) = true`

In Maude, if you don't import `BOOL` by default or if you have a non-boolean side-condition you want to check, you need to explicitly write out the equality, e.g. `P(X) = Q(Y)`. As far as I know, K does not have a builtin equality/predicate symbol that we can use in that way.

EDIT: conjunction is also built into Maude side-conditions, so you can have conjunctions of equalities in a Maude side-condition without importing any module. To have useful side-conditions without importing the booleans, we would probably want a built-in notion of conjunction as well.

**Comment by ehildenb** [comment]
:+1: on restricting side-conditions to sort Bool, and I thought we already restricted users from adding constructors of builtin sorts?

**Comment by ehildenb** [comment]
@ttuegel reports that the Haskell backend rejects adding constructors to builtin sorts anyway, so we should be making that check in the frontend anyway.

Any side-conditions not of sort `Bool` will cause nonsense, and _likely_ will cause the Haskell backend to crash anyway. So it sounds like we should also just check that at definition parse time.

So action items are:

-   Restrict in the frontend that no constructors of builtin sorts are added.
-   Restrict in the frontend that side-conditions are sort Bool.
