### ISSUE TITLE
Allow putting `macro` on productions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1584]
Rather than requiring `macro` on `rule`, we should allow `macro` on productions (and `macro-rec`), and then that will just be propogated down to the appropriate rules before macro expansion so that none of the frontend logic needs to change.

This makes it possible to:

-   Eventually disallow `macro` on rules, in favor of declaring the function itself a macro.
-   Easier to determine which declared symbols are constructors or not for the purpose of disallowing constructors declared in builtin sorts.

**Comment by ehildenb** [comment]
Because of #1568

**Comment by radumereuta** [comment]
1. Allow macros on productions
2. emit a warning for rules that use macros
This should be a transition period before we disallow the label on rules.

**Comment by SchmErik** [comment]
After disallowing the label on rules, we can close #1956

**Comment by radumereuta** [comment]
We have an issue when we have the same LHS that can be marked by the same macro production.
In this case we should add a warning, or maybe even an error.
They should have either a side condition or a priority or owise attribute that is different.

**Comment by radumereuta** [comment]
Apparently, we still have a few corner cases we need to handle:
- if a rule has the `simplification` attribute, don't consider it as a macro
- add a check that looks for leftover macro symbols in the AST and gives an error message. This should be integrated somewhere in or right after the macro expander.
