### ISSUE TITLE
[Bug] kompile rejects non-concrete simplification rule in the presence of concrete function rule

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#1591]
I am using K from fec13504826f02ea16cfd5638dc8b72a8b000340.

Description
-----------

`test.k`:

```.k
module TEST
  import INT

  // An uninterpreted function to trigger the simplification rule below.
  syntax Int ::= i(Int, Int) [function]

  syntax Bool ::= fun ( Int ) [function]

  // A concrete definition rule for our function. The content of this rule is
  // irrelevant, but being concrete forces all other definition rules to be
  // concrete.
  rule fun(X) => X >Int 0 [concrete]

  // A simplification rule defined over the uninterpreted function. This rule
  // should not be subject to the restriction on the concrete attribute because
  // it is not part of the definition of fun(_).
  rule fun(i(_, _)) => false [simplification]
endmodule
```

Running `kompile --backend haskell test.k` gives:

```
[Error] Compiler: Found concrete attribute without simplification attribute on
function with one or more non-concrete rules.
        Source(/home/ttuegel/evm-semantics/./test.k)
        Location(12,8,12,26)
[Error] Compiler: Had 1 structural errors.
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

Expected behavior: `kompile` should accept this definition.

Having the `concrete` attribute on one function definition rule constrains all other definition rules for the same function to have the `concrete` attribute, but there should be no constraint on `simplification` rules for the function.

See also: kframework/kore#2190

**Comment by ehildenb** [comment]
What about:

```
syntax Int ::= f ( Int , Int ) [function]

rule f(X, Y) => X requires X >Int 3 [concrete(X)]
rule f(X, Y) => X requires X <=Int 3 [concrete(X)]
```

This one should be OK. But detecting this gets tricky because `X` may be named something different or may have constructors.

Or we could switch to having `concrete` attribute on klabels instead of on rules:

```
syntax Int ::= f(Int, Int) [klabel(foo), symbol, concrete]
```

and also support this:

```
kprove --concrete-klabels foo,bar,baz
```

Or we could make it so that _all_ semantic rules are `concrete`.

**Comment by ehildenb** [comment]
The code which checks that all function rules for a given klabel have the same set of concrete/simplification attributes, we _should not_ be considering rules which also has the `simplification` attribute.
