### ISSUE TITLE
Allow specifying max memory usage  for the Bison generated parser

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1602]
Motivation
----------

I'm moving the KWasm semantics to the bison parser. I'm experimenting with some primitive versions of the grammar. When using parametric `List{Sort, Delimiter}` in the grammar and feeding the parser a large input file (~2Mb), it crashes with a "memory exhausted" error. Inspection with Valgrind reveals the total heap allocation is around ~12Mb. I'm willing to offer much more memory to the parser. The file contains a list of ~6000 elements, which I assume is causing the problem.

Using `--bison-lists`, `NeList` and adding an extra production for the empty list case everywhere the list is used seems to get around the issue.
```
syntax TypeDecls ::= NeList{TypeDecl, ""}
syntax TypeDefn ::= "(" "type" OptionalId "(" "func" ")" ")" // Empty case
                  | "(" "type" OptionalId "(" "func" TypeDecls ")" ")"
```

But this will be very invasive in the syntax and semantics.

According to the Bison documentation:

> By defining the macro YYMAXDEPTH, you can control how deep the parser stack can become before memory is exhausted. Define the macro with a value that is an integer. This value is the maximum number of tokens that can be shifted (and not reduced) before overflow.
> ...
> The default value of YYMAXDEPTH, if you do not define it, is 10000. 

https://www.gnu.org/software/bison/manual/html_node/Memory-Management.html

Example K Code
--------------

The easiest way would probably be to allow adding extra macros on the command line, rather than introducing one flag per relevant option.

```
kompile --gen-bison-parser --extra-bison-macros "YYMAXDEPTH=2000000,YYINITDEPTH=2000" myfile.k
```

Documentation
-------------

"You can specify extra macros to the generated Bison by passing the `--extra-bison-macros` with a comma-separated list of macros and values."

Potential Alternatives/Work-arounds
-----------------------------------

I can try to optimize the grammar further and avoid long cons-lists or deeply nested structures.
I can easily modify the Bison genarator locally and maintain my own K fork.

Testing Approach
----------------

Use a simple list grammar:
test.k:
```
module TEST
   imports DOMAINS
   configuration <k> $PGM:Pgm </k>

   syntax Pgm ::= List{Int, ""}
```

Then generate a parser:
```
kompile --gen-bison-parser test.k
```

Then one could (dynamically) feed the number `1` 99000 (or other suitable number) times into the parser expecting success, and again with 11000 numbers, verifying failure.

Then generate a new parser with new macros:
```
kompile --gen-bison-parser --extra-bison-macros "YYMAXDEPTH=20000" test.k
```

Ensure this succeeds with 11000 numbers, and fails with 21000 numbers.

**Comment by ehildenb** [comment]
Let's just go with the simplest thing initially, `--bison-stack-max-depth NNN`, and then if we discover another use-case for generalization, we can do it then.
