### ISSUE TITLE
for-loop in IMP

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#161]
Hello,

how can I define a for-loop in IMP?

Is it possible to transform for-loop into while-loop?

Help me, thx!

**Comment by dwightguth** [comment]
You can think of a for loop of the form:
```
for (D; E1; E2) S
```

as equivalent to the code:
```
{
D;
while(E1) { S; E2 }
}
```

This is actually slightly simplistic in a real language as the behavior of for loops is a little different than this when you take into account continue (which executes the increment expression of the for loop), but it serves the purpose for a language without continue.

**Comment by Qais87** [comment]
Hello,

can you tell me how to write it using formal semantics.
In IMP language, it should be implemented in syntax and semantics part.

Thx

Am Do., 4. Okt. 2018 um 16:38 Uhr schrieb dwightguth <
notifications@github.com>:

**Comment by ehildenb** [comment]
Add the following (or something like it):

```
syntax Stmt ::= "for" "(" Stmt ";" BExp ";" Stmt ")" Block

rule <k> for (D ; E1 ; E2) S => { D while (E1) { S E2 } }
```

Closing this since it's not related to the K frontend code itself. Feel free to ask more questions about K at our public chatroom: https://riot.im/app/#/room/#k:matrix.org
