### ISSUE TITLE
Kore symbol attributes should refer to Kore symbols, not K labels

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#1614]
Certain Kore symbol attributes produced by the frontend refer to K label names instead of Kore symbol names. For example, the declaration for the built-in `_Map_` symbol is:

```.kore
hooked-symbol Lbl'Unds'Map'Unds'{}(SortMap{}, SortMap{}) : SortMap{}
    [unit{}(".Map"), element{}("_|->_"), hook{}("MAP.concat"), /* elided */ ]
```

Note that the `unit` and `element` symbols are referenced by their K labels, which are not canonical in Kore. It would be more useful to the backend if these were listed by their Kore symbols, which are canonical, i.e.

```
    [unit{}(Lbl'Stop'Map{}), element{}(Lbl'UndsPipe'-'-GT-Unds'{}), /* elided */]
```

@dwightguth Is this reasonable?

**Comment by ehildenb** [comment]
Looks like we need to modify ModuleToKORE. We will put this on backlog for this week, and if it doesn't get scheduled by next week, we'll get someone on Haskell backend to learn ModuleToKORE and take this task.

**Comment by ttuegel** [comment]
@MirceaS In `ModuleToKORE`, we probably need to change the strings in the attributes to `KApply` objects.
