### ISSUE TITLE
[KIP] - Kompile: Generate the lexical scanner so that the order of its rules is the same as the order of the token definitions in the K syntax module

### ISSUE THREAD

**Issue by malturki** [runtimeverification/k#1630]
Motivation
----------

As far as I can tell, there is currently no obvious way to control the order of the lexical scanning rules generated from a K syntax definition module. Furthermore, this order seems to be determined by the internals of the generator, and thus seems quite random to the user.

Of course, the order becomes unimportant if we always ensure that all the tokens are defined using non-overlapping regular expressions. But this requirement can in practice be hard to achieve, and can result in overly complicated regex specifications. These are the main reasons why lexical analyzers, like flex, allow patterns to overlap while giving priority to lexical rules appearing earlier in the file when tokenizing input. It would be useful to be able to use this facility of the lexical analyzer from within K.

Example K Code
--------------

Below is a complete specification (in test.k) of a (rather useless) language whose programs can either be a FooToken or BarToken. The tokens are defined in the parser syntax module, with overlapping regexes. FooToken is defined first though.

```k
module TEST-SYNTAX
  syntax FooToken [token]
  syntax BarToken [token]
  syntax Pgm ::= FooToken | BarToken
endmodule

module TEST-PARSER-SYNTAX
  import TEST-SYNTAX
  syntax FooToken ::= r"[a-z]+"    [token]
  syntax BarToken ::= r"[a-zA-Z]+" [token]
endmodule

module TEST
  import TEST-SYNTAX
  import STRING

  configuration
    <k> $PGM:Pgm </k>
    <r> ""       </r>

  rule <k> _:FooToken => .K ... </k>
       <r> _          => "Foo"  </r>

  rule <k> _:BarToken => .K ... </k>
       <r> _          => "Bar"  </r>
endmodule
```

Currently compiling with `kompile --syntax-module TEST-PARSER-SYNTAX test.k` and running with `krun input.pgm`, where the file `input.pgm` has the string "input" in it, results in the following configuration:

```k
<generatedTop>
  <k>
    .
  </k>
  <r>
    "Bar"
  </r>
</generatedTop>
```

meaning that the string "input" was tokenized as a BarToken (In the generated scanner, the rule for BarToken appears before the rule for FooToken, so the FooToken pattern can never match).

Documentation
-------------

The only thing here is to highlight that the order of syntax definitions of tokens in the parser module matters if the tokens have overlapping regexes, and that the more general token definitions should come after the more specific ones.

Potential Alternatives/Work-arounds
-----------------------------------

The only way it seems right now is to only have mutually disjoint regexes defining all the tokens in a parser module.

Testing Approach
----------------

The above example can be used as a test.

**Comment by dwightguth** [comment]
This is not true. You can control where in the file a token appears with the `prec` attribute. Note that this isn't the same as making that production higher priority in all cases; flex will always pick the longest token first, and only uses ordering in the file to disambiguate if both tokens are the same length.

**Comment by malturki** [comment]
Thanks for the clarification. Somehow I missed this part of the documentation describing `prec` with tokens. I'm linking it here for reference: https://github.com/kframework/k/blob/master/pending-documentation.md#prec-attribute.

What's the default precedence value for tokens that do not have this attribute specified? Is there a recommended user range to stay within?

**Comment by dwightguth** [comment]
The default precedence is zero. Some tokens in the k prelude are given a precedence of 1 or 2, so there's not a lot of wiggle room. I think there was some discussion of trying to widen the range of numerical values used by the prelude so there's more unused values in between. If you have trouble getting the behavior you want with the existing code, we can revisit that.

**Comment by malturki** [comment]
Thanks. I don't think the precedence value is causing any trouble at the moment. I am closing this issue.
