### ISSUE TITLE
[KIP] - Enable more modular token definitions using name expansion

### ISSUE THREAD

**Issue by malturki** [runtimeverification/k#1633]
Motivation
----------

It would be really useful to be able to use names of sorts of which tokens are defined within the regexes defining these tokens, in the same way a scanner allows name definitions and then name expansions in lexical rules. This would allow more modular token definitions and more readable specs, which can be especially helpful for semantics using multiple complex token definitions.

Example K Code
--------------

The following is a very simple example. In a language where the size of an integer is indicated by a prefix `n` for 64-bit and `u` for 128-bit integers, using name expansion, we would be able to do the following:

```
module TEST-SYNTAX
  syntax Num ::= r"[0-9]+" [token]
  syntax UInt64Token ::= r"n{Num}" [token]
  syntax UInt128Token ::= r"u{Num}" [token]
endmodule
```

Documentation
-------------

A syntactic production for a token type associates the sort's name with the regular expression defining that token, so that this name may be used in the regular expression defining other tokens. For example, suppose we have the following token definitions:

```k
  syntax Digit ::= r"[0-9]" [token]
  syntax Alpha ::= r"[a-zA-Z]" [token]
```

Then, the sort names `Digit` and `Alpha` may be used in the regex defining other tokens by enclosing the name with curly braces: `{Digit}` and `{Alpha}`, and these names will be expanded into their regexes above. For example, we can define a new token type:

```k
  syntax Alnum ::= r"{Alpha}|{Digit}" [token]
```
This process can be repeated. For example, using these definitions, an identifier token in a language can now be defined as:

```k
  syntax Identifier ::= r"{Alpha}({Alnum})*" [token]
```

Potential Alternatives/Work-arounds
-----------------------------------

I can think of at least two ways to implement this:

- Direct expansion at the level of K module processing, where the regexes themselves are expanded in place (so that the generated scanner does not have to be made aware of name abstractions)

- Injections of name definitions in the scanner (so that the regexes won't have to be expanded) 

Testing Approach
----------------

The above examples may be used for testing.

**Comment by dwightguth** [comment]
Flex is capable of giving specific regexes specific names, so this ought to be doable. We just need to come up with a way to give certain names to certain regexes at the terminal level. I'm a little unsure about using sort names to do this given that there is not a 1-1 correlation between sorts and regexes, though. We need to discuss and pick a design in the meeting tomorrow.

**Comment by ehildenb** [comment]
We could have `token` take an optional identifier, and then the regex associated with that terminal would be given that name. If you do not supply a name, then it uses the Sort name + some unique identifier?

**Comment by ehildenb** [comment]
Actually, since it's the user who would be using the token identifiers, we probably don't need to put auto-generated ids on non-labeled ones.
