### ISSUE TITLE
Adding arithmetic operations into IMP

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#164]
Hello,

I want to add arithmetic operations for evaluating expressions 
with "-" and "*". I can define them both in syntax and semantic
which should be written as:
![imp](https://user-images.githubusercontent.com/43268150/46610825-27a57100-cb0c-11e8-912b-32bde3ce4a7d.PNG)

The semantic rules are these ones:
![sem](https://user-images.githubusercontent.com/43268150/46610871-486dc680-cb0c-11e8-9e56-3fd1d3b739e2.PNG)

Anyway, if I write s small programm like: 
![prog](https://user-images.githubusercontent.com/43268150/46610957-94207000-cb0c-11e8-8e2d-bd67e85a374e.PNG)

Using krun fails with parsing error. The symbol "-" is unknown for the parser. I have defined syntax and semantic rules but why does the parser fail to calculate it?

I suppose it has something to do with the attributes.

Thanks!

**Comment by dwightguth** [comment]
First of all, it would help to have a complete example. With only part of the code present, it's hard to know what the problem might be or to reproduce the issue. 

Second, this is unlikely to solve your issue, but you have given minus a lower priority than plus, which is probably not what you intend. The effect of such a behavior will be that the term `a - b + c` will actually parse as `a - (b + c)`, which is probably not what you intended.

**Comment by Qais87** [comment]
I can understand your position. The code is exactly the same IMP language
from the tutorials archive.
I have just extended it with adding "-" and "*" operators. That's why I
didn't post the rest.

Can you better explain the strictness attributes? I think I have not
understood them.

Am Mo., 8. Okt. 2018 um 17:31 Uhr schrieb dwightguth <
notifications@github.com>:

**Comment by Qais87** [comment]
Ok, problem has been solved. It works now.
