### ISSUE TITLE
Module signatures supporting public/private syntax and imports

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1658]
This would enable more incremental parsing.

We want to be able to:

-   Declare that a piece of syntax is `private`, so it cannot be used in either (i) modules which import the module it's declared in, or (ii) programs.
-   Declare that you are importing a module `A` into module `B` in a `private` manner, meaning that the module `B` may use the syntax of module `A`, but any module importing `B` may not use the syntax of module `A`.

This will cause problems with the existing lexer generation, because currently we only generate a single lexer for the entire definition. Roughly we can start with "the lexer should ignore the public/private status, while the parser should respect them".

For reference, we should profile the processes of (i) lexer generation and (ii) grammar generation. Currently we think that (i) takes on the order of seconds, and (ii) takes on the order of milliseconds (for "normal" definitions).

**Comment by ehildenb** [comment]
A use-case for module syntax renaming: #837.

**Comment by ehildenb** [comment]
Only goal for first cut: hide some symbols from importees. This consists of hidden imports, and hidden productions.

```
module A [private]

  syntax Foo ::= foo() // <- B may not use this symbol
               | bar() // <- B may not use this symbol

  syntax Foo ::= baz()          // <- B may not use this symbol
  syntax Foo ::= bam() [public] // <- B may use this symbol

  syntax Foo ::= fu() [private] // <- B may not use this symbol

  syntax Foo ::= "bar" [public, token] // <- B may use this token
               | r"ba." [token]      // <- B may not use this token

endmodule

module B
  imports private A // <- B may use the _public_ syntax of A, but C may not
endmodule

module C
  imports B
endmodule
```

So the only added outer syntax is `imports private`. And we will use `public` and `private` attributes on `module` and `syntax` declarations. The module attribute will set the default mode for the whole module, and attribute on productions will override that.

If you named a module `private`, it would become an outer-parsing error, which is a change in behavior. We should double-check that it's an actual syntax error.

**Comment by nishantjr** [comment]
@ehildenb @dwightguth 

I think we also want `import public` for this case:

```
module C1 [private]
  imports public B
endmodule
```
