### ISSUE TITLE
Bug: Krun: Domain values for Bytes in Kore is not consistent between frontend and haskell backedn

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1676]
K Version
---------

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: ada1ae8
Git branch: UNKNOWN
Build date: Sun Nov 29 17:43:14 CST 2020
```

Description
-----------

The Frontend produces kore that the backend cannot consume. 

The empty Bytes produced by the front end is represented by `\dv{SortBytes{}}("b\"\"")`.
The backend produces `\dv{SortInt{}}("0")` instead.

The frontend is able to consume the backend's version, but `kore-exec` chokes on kore produced by the frontend.
Since kore is the language that the various K tool use to communicate is important that the various tools have the same notion of kore.

Input/Reproduction
-----------

```
$ cat test.k 
module TEST
    imports BYTES
    configuration <k> Int2Bytes(0, 0, LE) </k>
endmodule
```

Produces this kore with `krun`:

```
$ krun --debug --verbose --output kore
Parse command line options                                   =  0.023s
Executing command: kore-exec /.../test-kompiled/definition.kore --module TEST --pattern /.../.krun-2020-.../execute-initial.kore --output /..../.krun-2020-.../execute-result.kore
inj{SortGeneratedTopCell{}, SortKItem{}}(Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortBytes{}, SortKItem{}}(\dv{SortBytes{}}("b\"\"")),dotk{}())),Lbl'-LT-'generatedCounter'-GT-'{}(\dv{SortInt{}}("0"))))
```

However, the kore produced by `kore-exec` is:

```
/* Fl Fn D Sfa Cl */
Lbl'-LT-'generatedTop'-GT-'{}(
    /* Fl Fn D Sfa Cl */
    Lbl'-LT-'k'-GT-'{}(
        /* Fl Fn D Sfa Cl */
        kseq{}(
            /* Fl Fn D Sfa Cli */
            /* Inj: */ inj{SortBytes{}, SortKItem{}}(
                /* Fl Fn D Sfa Cl */ \dv{SortBytes{}}("")
            ),
            /* Fl Fn D Sfa Cl */ dotk{}()
        )
    ),
    /* Fl Fn D Sfa Cl */
    Lbl'-LT-'generatedCounter'-GT-'{}(
        /* Fl Fn D Sfa Cl */ /* builtin: */ \dv{SortInt{}}("0")
    )
)
```

Expected Behavior
-----------------

Backend and Frontend should use the same format for bytestrings.

**Comment by dwightguth** [comment]
Basically, it looks like the code path that converts our kast data structures back to kore is not invoking the code to convert this back to the kore representation. It's unfortunately not possible to use the same representation both places, but it ought to still be fixable.

**Comment by ehildenb** [comment]
When converting K back to Kore, you need to de-escape Byte and String. String may already be handled, so look for that code.

**Comment by ehildenb** [comment]
Also, looking at the issue, it appears that there is an extra injection being added at the top of term from KItem -> GeneratedTopCell, even though the term underneath is already a GeneratedTopCell. So when converting K -> Kore, we need to also pass in an expected sort which the algorithm takes into account.

**Comment by radumereuta** [comment]
@nishantjr I think I have a quick fix for the Haskell backend, but I'm not sure about the LLVM. Can you provide more details for that?
I'm not sure what this is: `--some-weird-option` and the contents of `input.test`. And probably `test.k` changes also since you have input now.

**Comment by nishantjr** [comment]
@radumereuta I've been able to unblock myself re this bug, by using the K internal plumbing directly (`llvm-krun`), instead of `krun`. I'm not sure I understand why the fix woud be different for LLVM vs Haskell? Wouldn't this issue happen whenever the frontend performs kore to kore parsing/unparsing?

Oh, that last section is accidentally left over from the template. I'll fix it.

**Comment by radumereuta** [comment]
When going from Kore to K (the Java/Scala internal representation) Bytes and Strings get escaped:
https://github.com/kframework/k/blob/master/kore/src/main/scala/org/kframework/parser/kore/parser/KoreToK.scala#L161
(Let it be noted that I don't agree with this representation)
The problem was they were not being escaped back when converting from K to Kore:
https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L1878
So this is my quick fix.
`kx` works fine because it just dumps the output from the Haskell backend. In the regression-tests, `kx` is also the default runner for the llvm-backend and haskell-backend.
