### ISSUE TITLE
[Bug] krun/kore-exec: No error message when missing configuration arguments

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1683]
K Version
---------

```
RV-K version 1.0-SNAPSHOT
Git revision: ada1ae8
Git branch: UNKNOWN
Build date: Sun Nov 29 17:43:14 CST 2020
```

Description
-----------

`krun` prints `#Bottom` for the haskell backend when missing arguments for the config variables.
I expect an error message such as "Missing configuration variable "$Foo". Use `-cFoo=<Value>` to set".

Reproducing
-----------

```
$ cat test.k 
module TEST
    imports INT
    configuration <k> .K </k>
                  <foo> $Foo </foo>
endmodule
$ kompile test.k --backend haskell
$ krun 
#Bottom
```

Expected Behavior
-----------------

I expect an error message such as "Missing configuration variable "$Foo". Use `-cFoo=<Value>` to set."

**Comment by ehildenb** [comment]
This check will have to happen in the frontend, so the frontend will need to know about the variables.

Since it already does, it should be possible.

Modify both the old and new krun/kx code-paths to make this check.
