### ISSUE TITLE
[KIP] - Improved "let" bindings

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1685]
Motivation
----------

K currently supports let bindings via the `#fun` construct. 
However, this syntax is complex looking nested expressions when multiple variables are bound.
Moreover,  `#fun`  is difficult(impossible?) to use when the let binding needs to be used in multiple cells.

Proposal 1
--------------

Introduce new `where` clause in rules. 

Pros: Clear and concise
Cons: Might be backward incompatible since "where" is a common keyword in languages.

Possible syntax:

```
rule <k> foo(X, Y, Z) => BAR </k>
    <foo> BAR </foo>
  where BAR = complex(expression(!Fresh, X, BUZZ, Z))
      and BUZZ = f(g(Y, Y, !Fresh))
```

Proposal 2
-------

Repurpose `when` clause and existential variables.

Pros:
* No new syntax introduced, so completely backward compatible.
* May already be supported by the haskell backend

Cons:
* `when` does not communicate the purpose of the clause as clearly as `where`.
* May be complex to implement in the frontend.

```
rule <k> foo(X, Y, Z) => ?BAR </k>
    <foo> ?BAR </foo>
  when ?BAR ==K complex(expression(!Fresh, X, ?BUZZ, Z))
     and ?BUZZ ==K f(g(Y, Y, !Fresh))
```

Documentation
-------------

> K rules may also have `where` clauses that act like let bindings in functional programming languages.
> An example is shown below:
>
> 
> ```
> rule <k> foo(X, Y, Z) => BAR </k>
>    <foo> BAR </foo>
>   where BAR = complex(expression(!Fresh, X, BUZZ, Z))
>       and BUZZ = f(g(Y, Y, !Fresh))
> ```

Potential Alternatives/Work-arounds
-----------------------------------
Do Nothing

Testing Approach
----------------

1. Copy tests for `#fun`. 
2. Add new test for cross-cell use case, below:

test.k

```
module TEST
   syntax KItem ::= foo(Int, Int, Int)
   syntax KItem ::= bar(Int)
   configuration <k> foo(1, 2, 3) </k>
                    <bar> .K </bar>

   rule <k> foo(X, Y, Z) => BAR </k>
       <bar> _ => BAR </bar>
     where BAR = bar(X +Int Y +Int Z +Int !Fresh)
endmodule
```

output (`!Fresh` should evaluate to `0`):

```
<k> bar(6) </k>
<bar> bar(6) </bar>
```

**Comment by ehildenb** [comment]
Limited support that we could start with:

-   Each `where` clause may define one new RHS variable, and the definition on the rhs of the `where` clause may only use (i) variables from the LHS of the rule, or (ii) variables defined on the lhs of previous `where` clauses.
-   No recursive bindings in where clauses.

Haskell backend will compile these to an `ensures`, LLVM backend will have special support for it (to avoid evaluating it more than once). LLVM backend will have to identify which part of the RHS is the term being constructed by the let bindings, then for each let binding create a new llvm instruction which evaluates that instructions and binds it to a virtual register which is then placed in the substitution for constructing the RHS.

**Comment by dwightguth** [comment]
This is fixed.
