### ISSUE TITLE
[KIP] - Introduce DSL for generating Makefiles  and `kfoo` runner scripts

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1686]
Motivation
----------

The build infrastructure for typical K semantics is highly structured, and more of less identical across languages.
At the moment, we hand write Makefiles, test infrastructure and runner scripts.
This makes them difficult to update across projects, difficult and tedious to maintain.

Proposal
------

I propose introducing a python-based DSL that allows::

1. generation of `Makefile` recipes/targets for building definition
2. generation of `Makefile` recipes/targets for running tests
3. generation of a `kfoo` runner script (for basic usage) or library (for advanced usage).

More advanced build infrastructure (such as building of additional libraries, hooks;  tools needed for testing, more complex pipelines)
may be built using a Makefile that imports this generated one, or a python script that imports the generated runner library.

Example Code
--------------

One possible python DSL may look like:

```
proj = KBuilder(builddir = '.build', ksubmodule = 'ext/k')
main = 'foo.md'
other = ['syntax.md', 'bar.md']
foo_llvm = proj.definition( name = 'foo-llvm'
                           , main = main
                           , other = other
                           , backend = 'llvm'
                           , flags = '--gen-bison-parser'
                           )
foo_hask = proj.definition( name = 'foo-haskell'
                           , main = main
                           , other = other
                           , backend = 'haskell'
                           , flags = '--md-tags "k|symbolic"'
                           )
proj.testsuite(foo_llvm.krun_runner(), 'test-concrete', glob('tests/concrete/*.foo'))
proj.testsuite(foo_hask.krun_runner(), 'test-symbolic', glob('tests/symbolic/*.foo'))
proj.testsuite(foo_hask.kprove_runner(), 'test-proofs', glob('tests/proofs/*-spec.k'))
```

This DSL is borrowed from the `KNinja` project that fulfills a similar goal, but generates [ninja-build](https://ninja-build.org/) scripts instead. A more complex KNinja script can be seen here: https://github.com/runtimeverification/michelson-semantics/blob/kninja/build

Documentation
-------------

To be provided inline via python docstrings etc.

Potential Alternatives/Work-arounds
-----------------------------------

1. Place a set of Makefile recipes that may be imported into each semantics.
I feel that Makefiles quickly get complex for large projects, and this approach is not very flexible, and less user friendly than the proposal.
2. Use KNinja.

**Comment by ehildenb** [comment]
Problem with a `kinit` approach to make a skeleton project means that updating your semantics to the latest K means re-running and reporting any changes you make.

We favor an approach where libraries are included in the K repo directly (in the library path) which you can include into your Makefile/runner script, so that the project specific makefile/runner script could import them.

Also open to the approach where a custom DSL is used to specify the endpoints needed for that semantics and the runner(s) is generated automatically.

**Comment by ehildenb** [comment]
This will be subsumed by https://github.com/runtimeverification/pyk/issues/30
