### ISSUE TITLE
Document version requirements for dependencies

### ISSUE THREAD

**Issue by boggle** [runtimeverification/k#1706]
Hi,

I run into test failures coming from z3 trying to build k on os x (both release 5.0 and master). I suspect this may be due to a z3 version mismatch. Could you please document versions of all dependencies used per platform for successful (major) releases for people installing from source? Thanks!

**Comment by ehildenb** [comment]
We require Z3 to be at least 4.6, and recommend  at least 4.8.

**Comment by boggle** [comment]
Thanks but how about you keep this information in the installation instructions and up to date? Even better, if the build would detect a bad version and produce a meaningful error message.

**Comment by ehildenb** [comment]
The simplest thing to do is inspect the `Dockerfile`, which is used on CI. The documentation may fall out of date, but that must be kept up to date because it is run on every PR.

**Comment by boggle** [comment]
Good advice, thanks. Still might be worth documenting that in the installation instructions somewhere.
