### ISSUE TITLE
[Bug] [kompile] - simplification rule translation to kore

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#1737]
K Version
---------

I'm using the following version of K:

```
RV-K version 1.0-SNAPSHOT
Git revision: 5701be4
Git branch: UNKNOWN
Build date: Wed Dec 02 00:56:01 EET 2020
```

Description
-----------

`simplification` rules should get translated to match what the user wrote as closely as possible, so that the Haskell backend can apply them directly onto matching terms, without having to simplify the rules first.

Input Files
-----------

Minimized example module:
```
module SIMPLIFIED
  imports INT

  syntax Int ::= f(Int) [function, functional]

  rule (f(X) >Int 0) => (X >Int 0)    [simplification]

endmodule
```

Reproduction Steps
------------------

`kompile --backend haskell -d . simplified.k` will produce a definition containing the following corresponding `kore` rule:

```
  axiom{R} \implies{R} (
    \top{R}(),
    \and{R} (
      \equals{SortBool{},R} (
        Lbl'Unds-GT-'Int'Unds'{}(Lblf'LParUndsRParUnds'SIMPLIFIED'Unds'Int'Unds'Int{}(VarX:SortInt{}),\and{SortInt{}}(\dv{SortInt{}}("0"),Var'Unds'1:SortInt{})),
        Lbl'Unds-GT-'Int'Unds'{}(VarX:SortInt{},Var'Unds'1:SortInt{})),
      \top{R}()))
```

Notice the `\\and(0,V1)` in the first child of the `\\equals`.

Expected Behavior
-----------------

This `\\and` should not exist, it should be `\\dv{SortInt{}}("0")` directly. Also, the other appearance of `Var'Unds'1` should be substituted with `\\dv{SortInt{}}("0")`.

**Comment by ehildenb** [comment]
We need to disable the pass which inserts `\and` on the rules (to make re-construction of terms cheaper) for `simplification` rules.

This lives in https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/compile/MinimizeTermConstruction.java.

This pass should also be disabled on the term `true`, because it can turn non-existent side-conditions into existent ones.
