### ISSUE TITLE
[Bug] make doesn't fail when kprove returns error code but the output is correct

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1738]
```
kprove max-fail-spec.k --def-module VERIFICATION  -d . | diff - max-fail-spec.k.out // pass because exit code is taken from diff
kprove max-fail-spec.k --def-module VERIFICATION  -d . > max-fail-spec.k.out // fails because the return code is taken from kprove
```
This means that `make` passes, but `make update-results` fails, which makes it really annoying to test.

The solution is to add `SHELL=/bin/bash -o pipefail` to `ktest.mak` but now a lot of tests fail.

**Comment by radumereuta** [comment]
Well... that doesn't really work because of this:
```
cat $@.in 2>/dev/null | $(KRUN_OR_KX) $@ $(KRUN_FLAGS) $(DEBUG) -d $(DEFDIR) $(CHECK) $@.out
```
`cat` is used to give input to `krun`, but not all tests have input so it returns exit code 1 when it doesn't find a file.

Suggestions?

**Comment by radumereuta** [comment]
Got over the cat issue with:
```
if [ -f "$@.in" ]; then cat $@.in; fi | $(KRUN_OR_KX) $@ $(KRUN_FLAGS) $(DEBUG) -d $(DEFDIR) $(CHECK) $@.out
```
But I would also like to overhaul the output checks.
I would like to have 3 files: *.out, *.err and *.exitcode. If one is missing then the output should be empty, or exit code 0. `update-results` should update only the existing files, it should not create new ones.
This way we could unify ktest.mak and ktest-fail.mak

One disadvantage is that the command for each file is going to get bigger and maybe harder to read.

Optionally, I would also like an option to run all tests even if some fail.

**Comment by ehildenb** [comment]
You can do `-k` to `make` to keep running if any tests fail.

Note that this isn't new, we rely on output checks and not error code in many cases on purpose. That's because many of the tests rely on non-zero output codes, but we want to make sure the output is correct.

I'm not opposed to overhauling the build system, just keep in mind that it's setup how it is to allow us to have tests which do exit with non-zero exit code, but we check that the error output is correct.

**Comment by ehildenb** [comment]
```
ALWAYS_SUCCEED=true
kprove max-fail-spec.k --def-module VERIFICATION  -d . > max-fail-spec.k.out || $(ALWAYS_SUCCEED)
$(CHECK) *.expected *.out
```

`make CHECK=cp`

`make ALWAYS_SUCCEED=false`
