### ISSUE TITLE
Lambda.k out of date in lesson 2

### ISSUE THREAD

**Issue by davidstreader** [runtimeverification/k#1752]
Hi I am slowly working through the tutorial and although I know almost nothing I am learning. The file tutorial/1_k/1_lambda/lesson_3/lambda.k is out of date:

```
// Copyright (c) 2012-2019 K Team. All Rights Reserved.

require "substitution.md"

module LAMBDA
  imports DOMAINS
  imports SUBSTITUTION

  syntax Val ::= KVar
               | "lambda" KVar "." Exp  [binder]
  syntax Exp ::= Val
               | Exp Exp              [strict, left]
               | "(" Exp ")"          [bracket]
  syntax KResult ::= Val

  rule (lambda X:KVar . E:Exp) V:Val => E[V / X]
endmodule
```
The following compiles

```
// Copyright (c) 2012-2019 K Team. All Rights Reserved.

require "substitution.md"

module LAMBDA-SYNTAX
  imports DOMAINS-SYNTAX
  imports SUBSTITUTION

  syntax Val ::= KVar
               | "lambda" KVar "." Exp  [binder]
  syntax Exp ::= Val
               | Exp Exp              [strict, left]
               | "(" Exp ")"          [bracket]
  syntax KResult ::= Val

  rule (lambda X:KVar . E:Exp) V:Val => E[V / X]
endmodule

module LAMBDA
  imports LAMBDA-SYNTAX
  imports DOMAINS
  
endmodule
```
I will be working on K for a few days and if it helps I am happy to send other changes (if my understanding is sufficient) but if you prefer to deal with such issues your self I will  not hassle you.   kind regards david

**Comment by ehildenb** [comment]
@davidstreader can you try again with the latest K from git? There have been recent changes to the lambda tutorial and this is likely fixed.

--pdf is no longer supported, we should have removed all references to that in the tutorial now

**Comment by ehildenb** [comment]
This change has been made to the current tutorial, closing.
