### ISSUE TITLE
Investigate improving ship-abilitly of K definitions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1754]
Motivation
----------

Packaging K definitions is somewhat difficult right now, which is exasperated by the fact that many of K's functionalities require (i) an install of K, an (ii) a `*-kompiled` directory that we can point at. This makes it hard to install standalone semantics as tools, except for those specific tools that are compiled to binaries directly with the LLVM backend.

Proposals
-------------

This is brainstorming ideas for improving this situation, not necessarily concrete proposals about what to do.

- Serialize entire `*-kompiled` directory into a single file which can be unpacked into the correct place.
- Support generating runner scripts which wrap `krun ....` and `kprove ....` with the correct arguments like `--directory ...` already applied to them for each semantics.
- Produce standalone binaries for the kompiled definition with Haskell backend (build the definition.kore into the ELF file?).
- Provide a way to package K directly into other packages (so KEVM would come with its own local K install in the users installation directory). This is space-intensive, but avoids the problem where a user has to first download the K deb file and install it, then can download and install the KEVM deb file.

**Comment by sskeirik** [comment]
-    Since the LLVM backend now can generate binaries for:
    
     - parsers,
     - macro expanders
     - interpreters
     - and output printers

     If the LLVM backend could generate a combined binary which includes all of the above plus:
     
     - a few command line options including, at least, input file handling
     
     Then the combined binary could be downloaded and run on any architecture which our LLVM compilation path supports without needing anything else.

**Comment by ehildenb** [comment]
Related: #1302

**Comment by ehildenb** [comment]
We will limit this to open-source definitions in the beginning so we don't have to worry about obfuscating or leaked sources.

The approach we'll take is to bundle the K utilities necessary with the semantics directly, and put them on PATH just for execution of that semantics. This includes the LLVM backend binaries, the K frontend, and the Haskell backend (each as needed).

**Comment by ehildenb** [comment]
I am attempting a standalone installation of KEVM with this PR: https://github.com/kframework/evm-semantics/pull/965

So far, it seems to be working (and uses the correct K subdirectory), but the problem is that when it goes to call `kompile` in the `kprove` pipeline, it remembers the original lookup directories that were passed in the original invocation. This means it looks in the directory where the files were originally built, not in the global install.

We can either make this smarter (maybe we can make `-I` relative, or we can add it to `kprove`), or we can remove `kompile` from the kprove pipeline altogether.
