### ISSUE TITLE
[Bug] krun - dry-run option does not save intermediate files

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#1775]
K Version: 95b467bdfceb61e51c67b9d4a3f11d7698c9ac86

`krun --dry-run` prints the command that would be used to run the backend, but it deletes the temporary files that the backend would use!

**Comment by radumereuta** [comment]
`--save-temps         Do not delete temporary files when krun terminates.`
Maybe it should be enabled by default, or combine the options.

**Comment by ttuegel** [comment]
Thanks! I think I missed `--save-temps` because it used to be called `--debug`, but that option is no longer. I think it should be the default; otherwise I'm not sure what good `--dry-run` is.
