### ISSUE TITLE
Clarify the `symbol` attribute in the pending document

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/k#1777]
After reading the pending document, it is still unclear to me what does `symbol` attribute do. In the pending document, it says that symbol and klabel are used together. However, I found that in the evm semantics, some places only use klabel.

**Comment by ehildenb** [comment]
I second this, I want an operational description of what the symbol attribute will do, how it's different than the klabel attribute, and when to use each, with some specific examples.

I have just been telling people "just use symbol whenever using klabel, I don't know why".

**Comment by ehildenb** [comment]
`symbol` attribute tells the kore generation process to use the value of the `klabel` attribute as the value of the symbol that the backend will see. It will still be munged. If you don't provide the `symbol` attribute, but do provide the `klabel` attribute, the backend will see the munged version of the auto-generated `klabel` attribute, _not_ the user-specified one.

If you don't add `symbol` attribute, then `klabel` is only used to handle overloading.

A different approach would be to have `klabel` attribute default to what we currently say `klabel(...), symbol` for, and then have a separate way to determine overloading.

**Comment by yzhang90** [comment]
what does `it will still be munged` mean? I think an example will clarify a lot here.

**Comment by ehildenb** [comment]
Munged means "escaped". So something like `_+Int_` becomes `'UndsPlus'Int'Unds'`, for example. It's the process of converting the input symbol to use only characters that the backends allow by escaping not-allowed sequences of characters.
