### ISSUE TITLE
Users are confused about package filenames

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#1779]
Issue: Clients have complained to me because of confusion about package versions:

1. They download the K package from GitHub to install K as needed by a K project. The downloaded filename is something like `kframework_5.0.0_amd64_bionic.deb`. Let's assume this user does not clean-up their downloads folder very regularly.
2. Later, the K project incorporates a new K feature, which requires updating the global K to the latest installed K.
3. They now download the latest K package from GitHub to re-install K because the project requires this. The downloaded filename for this new version is also `kframework_5.0.0_amd64_bionic.deb`. The system automatically renames this file to avoid clobbering the original.
4. The user now believes that they have downloaded the _same file twice_, when, in fact, they have not, and questions whether the re-installation instruction procedure is correct.

Proposal: Append git commit ids to downloadable packages from GitHub.

This solution would solve the problem because the two downloaded package files would, with very high probability, have different package names.

**Comment by ehildenb** [comment]
We'll append the date/time to the package name, with `%Year%Month%Day%Hour%Minute`, which should be enough to keep from name clashes there. Use the date of the commit, not the date of the time the job runs.

eg. `kframework_5.0.0_amd64_bionic_%Year%Month%Day%Hour%Minute.deb`
