### ISSUE TITLE
[Bug] ModuleToKore should handle parametric productions correctly

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1780]
This is an intermediate step in trying to fix #1415.
After fixing:
```
lazy val productionsForSort: Map[SortHead, Set[Production]] =
    productions
      .filter(prd => !prd.isSortVariable(prd.sort)) // line added
      .groupBy(_.sort.head)
      .map { case (l, ps) => (l, ps) }
```
things started to crash in ModuleToKore.java, specifically 'no junk' and  'no confusion different constructors' axiom generation don't take into consideration parameters and it results in `key not found exception`.

I will post more questions here when I find more issues.

**Comment by ehildenb** [comment]
https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L665

We will skip productions that have a sort parameter as the return sort (not necessarily if it just contains a sort parameter in the production). We will skip it for both no-confusion-different-constructor and no-confusion-same-constructor.

**Comment by dwightguth** [comment]
I'm going to close this as this is a part of #1415 and we need to properly break that issue into subtasks at some point in the future.
