### ISSUE TITLE
[KIP] - Profiling info for kompile

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1782]
There have been some complaints recently from different users about kompile being slow. I'm trying to make an easy to use profiler that can give users hints about what makes their definition slow to kompile.

I'm proposing an overhaul of `--profile-rule-parsing`:
* [x] for performance reasons, each thread prints its rules in a separate file. There should be a step that aggregates all of them into a single file for easy reading. Maybe order them so we can diff different runs.
* [ ] move the log files from `*-kompiled` to `.kompile-*`. The files are specific to a run of kompile, not the definition.
* [ ] extend the logging to the kompile steps. Maybe there is a generic way for low maintenance.
* [ ] activate it when using `--debug`

Ideas for extra information we could print out:
* [x] Fix new scanner print when verbose (#1908)
* [x] Compact rule-profiling information into a single report (maybe even provide a consolidated summary of the hotspots).
* [ ] How many ambiguities each rule has.
* [ ] Which labels tend to cause ambiguities (by looking at productions present in rules with lots of ambiguities).
* [x] How long each rule takes to parse vs disambiguate (right now we're measuring total time).
* [ ] How long each kompile step tends to take.
* [ ] Warnings for rules that take longer than 1s to parse.

**Comment by ehildenb** [comment]
Ideas for extra information we could print out:

- Compact rule-profiling information into a single report (maybe even provide a consolidated summary of the hotspots).
- How many ambiguities each rule has.
- Which labels tend to cause ambiguities (by looking at productions present in rules with lots of ambiguities).
- How long each kompile step tends to take.
- How long each rule takes to parse vs disambiguate (right now we're measuring total time).

**Comment by radumereuta** [comment]
Most of the things listed here have been implemented.
The `--profile-rule-parsing` now takes a file as an argument and we dump all the info there for easy readability.
The output is ordered so it is stable between runs. It makes it easy to diff.
Total times in milliseconds and individual times for parsing and Z3.
- parsing takes long - maybe add some parens
- Z3 takes long, maybe type your variables
`--verbose` output has been updated slightly to include new scanner calls
