### ISSUE TITLE
[Bug] [kompile] - Broken #Or translation to kore in function equation

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1789]
K Version
---------

```sh
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: c305b58
Git branch: master
Build date: Sat Jan 30 02:51:41 EET 2021
```

Description
-----------

Rule whose right-hand-side consist of an `#Or` expression replaces the entire RHS with a variable during translation.

Input Files
-----------

tmp.k
```k
module TMP
  imports INT

  syntax Int ::= split(Int)  [function, functional]

  rule  split(V:Int)
        =>
          (
            (
              {true #Equals (V >=Int 0)}
              #And V
            )
            #Or
            (
              {false #Equals (V >=Int 0)}
              #And (V +Int 1)
            )
          )
    [label(xyzzy)]

endmodule
```

Reproduction Steps
------------------

```sh
$ kompile --backend haskell tmp.k
```

The `xyzzy` rule above is translated to the following, which replaces the entire right-hand side with a variable.
```kore
  axiom{R} \implies{R} (
    \and{R}(
      \top{R}(),
      \and{R} (
          \in{SortInt{}, R} (
            X0:SortInt{},
            VarV:SortInt{}
          ),
          \top{R} ()
        )),
    \and{R} (
      \equals{SortInt{},R} (
        Lblsplit'LParUndsRParUnds'TMP'Unds'Int'Unds'Int{}(X0:SortInt{}),
        Var'Unds'0:SortInt{}),
      \top{R}()))
```

Expected Behavior
-----------------

The RHS should be translated to Kore instead of being replaced with a variable.

**Comment by ehildenb** [comment]
It looks like this "GuardOrs" pass (https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/compile/GuardOrPatterns.java#L82) is affecting `#Or` patterns which appear _only_ on the RHS of a rewrite, when it should not be touching these `#Or` patterns.

Need to make sure we do not traverse inside the RHS of a rewrite when doing this transformation.

Keep in mind that the reason for this pass was to keep `#Or` patterns from appearing on the RHS of a rewrite after having split the configuration for a rule where the `#Or` was above a rewrite (to avoid the situation where you need to pick the correct disjunct in the `#Or` on the RHS). So we still need that to work.
