### ISSUE TITLE
Flex - an undocumented dependency

### ISSUE THREAD

**Issue by h0nzZik** [runtimeverification/k#18]
Class 'Scanner' runs gcc and assumes that flex library is installed. However, this dependency is not documented anywhere. Imho it should be documented in README.md.

**Comment by grosu** [comment]
@cos: can you please check this and add the necessary documentation?  thanks for reporting it, Jan.

**Comment by dwightguth** [comment]
Grigore, he's referring to changes I made to the runtime verification
version of K. I can try to add documentation, but that version of K already
doesn't support the tutorial right now, so maybe we should just warn people
that it's optimized specifically for the C semantics?

**Comment by dwightguth** [comment]
Should be listed now in installation instructions
