### ISSUE TITLE
Re-enable Arch Linux

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1805]
The Arch dockerfile is failing to build, because of some change in the Arch upstream signing keys. Somehow this needs to be fixed, because it's blocking K releases.

**Comment by ehildenb** [comment]
Example: https://office.runtimeverification.com/jenkins/job/k/job/master/1109/console

**Comment by sskeirik** [comment]
In the past, when I have run an Arch box, I often had problems when the `archlinux-keyring` package was upgraded at the same time as other packages. As a matter of course, I now always upgrade this package first in it's own command `pacman -S archlinux-keyring` and then upgrade everything else after it finishes. I don't know if this will fix the problem, but it has helped me in the past.

EDIT: As an idea, something like:

```
pacman -Sy # update package lists
pacman -S archlinux-keyring # update keys
pacman -Su # update all other packages
```
might work well.

**Comment by dwightguth** [comment]
We probably should just pull the latest version of the Arch Linux container onto each Jenkins node. That ought to fix this. I'll do it tomorrow if nobody has done it by then.

**Comment by ehildenb** [comment]
@dwightguth I've pulled in the latest archlinux/base on each CI machine, not sure it's enough. Will it know to invalidate the cache? Let's see.

**Comment by sskeirik** [comment]
So, the Arch build is still failing. Question: do we know for sure the issue is the failed keys? Because I'm also seeing this blurb at the bottom of the log:

```
(11/11) Cleaning up package cache...
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
The command '/bin/sh -c pacman -Syyu --noconfirm     && pacman -S --noconfirm                        base                            base-devel                      boost                           clang                           cmake                           curl                            git                             gmp                             hub                             jdk-openjdk                     jemalloc                        libyaml                         lld                             llvm                            maven                           mpfr                            opam                            openssh                         python                          python-pip                      stack                           z3                              zlib' returned a non-zero code: 255
script returned exit code 255
```

In particular, that message: `could not find or read directory: /var/lib/pacman` message looks suspicious. This makes me think it is actually the _second_ pacman invocation which is failing --- though that might be because the first one failed and did not do whatever initialization work was requested.
