### ISSUE TITLE
[Bug] [kompile] - Axioms not emitted for in_keys

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1814]
K Version
---------

Tell us what version of K you are using.

Example:

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: c305b58
Git branch: master
Build date: Thu Feb 11 02:07:22 EET 2021
```

Description
-----------

According to https://github.com/kframework/k/blame/master/k-distribution/include/kframework/builtin/domains.md#L440 , kompile should emit simplification axioms for `in_keys(M:Map K |-> _)`, but it does not, at least not when it compiles for the Haskell backend.

Input Files
-----------

File: tmp.k
```k
module TMP
  imports BOOL
  imports K-EQUAL
  imports MAP
  imports MAP-KORE-SYMBOLIC

  syntax A ::= a(Map) | "void"
  syntax KItem ::= A

  configuration <k color="green"> .K </k>

  syntax KItem ::= lhs(variables:Map) [function]
  rule lhs(Variables:Map) => a(6 |-> 1 7 |-> 2 8 |-> 3 Variables)

  syntax KItem ::= mapSet(key:KItem, Map)
  rule mapSet(K:KItem, M:Map) => 1
    requires K in_keys(M)

  rule  a(M) => mapSet(6, M)

endmodule
```

Reproduction Steps
------------------

```sh
kompile tmp.k --backend haskell
```
then search for all axioms for `Lbl'Unds'in'Unds'keys'LParUndsRParUnds'MAP'Unds'Bool'Unds'KItem'Unds'Map` in `tmp-kompiled/definition.kore`. None of those is a translation of, say, `rule K:KItem in_keys(M:Map K |-> _) => true`.

Expected Behavior
-----------------

`tmp-kompiled/definition.kore` should contain a translation for the `in_keys` axioms mentioned above.

I have also attached my `definition.kore` file.

[definition.kore.txt](https://github.com/kframework/k/files/5989896/definition.kore.txt)

**Comment by ehildenb** [comment]
Before trying anything else, can we see if it's fixed by pulling these rules out of the comment block so they actually are included in th edefinition? https://github.com/kframework/k/blame/master/k-distribution/include/kframework/builtin/domains.md#L440

**Comment by virgil-serbanuta** [comment]
I think this fixes the issue. BTW, the `ceil` rule in the comment seems to be generated anyway, so we would probably need to uncomment only the `in_keys` rules.

**Comment by virgil-serbanuta** [comment]
However, uncommenting them produced some infinite cycles in my semantics, not sure if it's an issue in the semantics or in the `in_keys` definition. However, this rule seems to work fine (most likely `#as _:Map` is not needed):
```
  rule X:KItem in_keys((Y:KItem |-> _:KItem M:Map) #as _:Map)
        => X ==K Y orBool X in_keys(M)
    [simplification]
```

**Comment by ehildenb** [comment]
@virgil-serbanuta can you post the example where the original rule inifinite loops?

I'm worried about your variant of the rule, because it has the potential to increase term size in general. The original rules strictly reduce termsize.

**Comment by virgil-serbanuta** [comment]
tmp.k:
```k
module TMP
  imports MAP-SYMBOLIC

  syntax KItem ::= f(Map) [function, functional]
  rule f(_:Map) => 1
  syntax KItem ::= a(KItem)

endmodule
```

tmp-proof.k:
```k
module TMP-PROOF
  imports TMP

  claim a(f(_ |-> _ _:Map) => 1)
endmodule
```

bash:
```sh
kompile tmp.k --backend haskell && kprove tmp-proof.k --debugger --debug-script kast.kscript
```

**Comment by ehildenb** [comment]
Are we able to see the list of rules in the cycle that this produces? It's really unclear how the cycle is happenning giving the original rules, but it seems like its because the definedness check for the Map is causing the cycle.

**Comment by ttuegel** [comment]
> However, uncommenting them produced some infinite cycles in my semantics, not sure if it's an issue in the semantics or in the `in_keys` definition.

Those rules are generated automatically by the frontend, when translating the semantics to Kore. The reason is that the axioms must be generated for every sort hooked to Map, especially cell collections. We can't write the rules for cell maps in K directly, so we generate the axioms in the frontend. If you uncomment those rules from `domains.md`, I'm not surprised that everything goes wrong! I will inspect the `definition.kore` to see if the generated rules are present.

**Comment by ttuegel** [comment]
I find that the `#Ceil` axiom is emitted correctly. The comment in `domains.md` is not accurate, the frontend only has [code](https://github.com/kframework/k/blob/061c0ba88dde54682cac91db5cd866b001098f92/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L546) for that axiom. It does not emit the `in_keys` axioms. The backend handles the hooked function.
