### ISSUE TITLE
[kprint] - `kprint` lack of documentation and odd failure

### ISSUE THREAD

**Issue by MirceaS** [runtimeverification/k#1822]
K Version
---------

```
RV-K version 1.0-SNAPSHOT
Git revision: acf7ead
Git branch: master
Build date: Wed Feb 17 00:44:50 EET 2021
```

Description
-----------

`kprint` command doesn't recognize `--version` option and doesn't show a help menu when given `--help` but instead, on failure shows the message:
`usage: kprint <definition.kore> <pattern.kore> [true|false|auto] [true|false]` without explanation of what those last 2 options represent.

Additionally, after providing the two `kore` files to `kprint`, it still fails because it seems to interpret the input as directories:
```
> kprint test-memory-vdefinition.kore test-memory-spec.kore 
Cannot read file: test-memory-vdefinition.kore/syntaxDefinition.kore
```

Input Files
-----------

any `kore` file, I assume

Reproduction Steps
------------------

see above

Expected Behavior
-----------------

A clearer description of how to use the command and why it looked for `test-memory-vdefinition.kore/syntaxDefinition.kore` in the example above.

**Comment by dwightguth** [comment]
I am going to close this. People interested in invoking the unparser should instead use the new `kore-print` tool.
