### ISSUE TITLE
[KIP] - Provide option to specify requested K version

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#1824]
Motivation
----------

Clients who follow our development closely and try to use our code as upstream often do not think to try updating their K installation (especially those less familiar with the shell). This leads to problems where the build breaks or execution breaks because they have an out-of-date K version. If we had an option to provide a K version we want somewhere, then `kompile`, etc. could inform the user of the problem.

Example
--------------

### Possibility 1:

```
kompile --require-version <X> ...
```

Behavior: fail if `kompile` has a different version.

### Possibility 2:

```
kompile --require-min-version <X> ...
```

Behavior: fail if `kompile` is older than version X

Note: this would require us to keep some kind of versioning information. This could be done even if it is not part of actual package version names, e.g., we could use the date information that we are now storing, as long as this information is made available when doing `kompile --version`.

### Possibility 3:

Add new K syntax `version` which lets us write:

```
version <X>
requires ...

module MY-MODULE
  ...
endmodule
```

Behavior: like possibility 1 (though we would need to work out what happens if it is requested multiple times).

### Possibility 4:

Add new K syntax `min-version` which lets us write:

```
min-version <X>
requires ...

module MY-MODULE
  ...
endmodule
```

Behavior: like possibility 2 (with the same notes as possibility 2). We also would to need to figure out what happens if it is requested multiple times.

### Addendum

If we add this, we should probably also add a way to disable version checks for testing/debug reasons `--no-version-check`

Documentation
-------------

Possibility 1/2:

A developer may update `--require-(min-)version <X>` to their Makefile as a way to indicate to users that they need to rebuild their K submodule or upgrade their K installation.

Possibility 3/4:

A developer may add `(min-)version <X>` to their module files to declare which K version they require. 

Potential Alternatives/Work-arounds
-----------------------------------

The standalone K + semantics package approach avoids this issue entirely by providing the needed K tools with the right version alongside the semantics. We may well decide that approach is superior to this one. But I think it could be good to have a discussion about what would be helpful.

Testing Approach
----------------

This feature could be tested by us generating version numbers in our test scripts that are different from the current version and passing them to `kompile` (possibility 1/2) or prepending them to other test files (possibility 3/4).

**Comment by ehildenb** [comment]
I don't think this makes much sense, I've never heard of any other project offering this as a feature (where you can specify the version you want as you call the program).

Instead, the semantics can check itself if the version that's being called is compatible, and fail with a good error if not. This is more compatible with how version checking usually works.

**Comment by sskeirik** [comment]
Some of options embed the version information in the K source files. Maybe that wasn't clear from my description. I tried to edit the issue to make that more clear.

By semantics, do you mean the runner scripts? Typically, clients complain when the build fails, and build process is normally outside the purview of the runner scripts.

In any case, we could definitely add more scripting to the build process directly to embed some kind of version check outside of the semantics. It's not a bad idea actually.

**Comment by ehildenb** [comment]
We could have a `k-check-version --less-than X.Y.Z --greater-than A.B.C` that the `Makefile` and runner scripts call to make sure that hte version of K is acceptable.

**Comment by ehildenb** [comment]
We also need to provide better versioning for version comparison. The difficultiy is bumping the minor version number (the `Z` or `C` in the above example) before each merge.

Proposed solution:

-   All K PRs have to go through automerger (no manual merging).
-   The automerger will add a commit at the end bumping version numbers throughout the repo, before merging the PR (but does not wait for tests to pass to merge the PR).

This would allow better fine-grained version comparison.

**Comment by ehildenb** [comment]
Another approach is to have a `release` branch which tracks master, but fills in the templates for version numbers. Then releases are based off these release builds, not on `master` builds.

**Comment by ehildenb** [comment]
We can have a version range feature which supports all the following:

```
// @KVERSION@ >= X.Y.Z <= A.B.C
// @KVERSION@ >= X.Y.Z
// @KVERSION@ >= X.Y
// @KVERSION@ >= X
// @KVERSION@ >= X.Y   <= A.B
// @KVERSION@ >= X.Y   <= A
// @KVERSION@ >= X     <= A
```

**Comment by Baltoli** [comment]
Closing as we have far better tools for managing K dependencies / installations / versions as part of downstream projects now; better to push this to orchestrating code than the compiler I think.
