### ISSUE TITLE
[Bug] - Homebrew K Tap broken by new deployment filenames

### ISSUE THREAD

**Issue by gtrepta** [runtimeverification/k#1825]
K Version
---------

Any version since git revision `5df2b1de7`.

Description
-----------
We changed the release tarballs to include the build date in the filenames, which broke installation of K from the `kframework/k` homebrew tap.

Reproduction Steps
------------------
On any MacOS with Homebrew installed
```bash
$ brew tap kframework/k
$ brew install kframework
```

Expected Behavior
-----------------
kframework to be installed. Instead:
```bash
Mac-mini:~ anka$ brew install kframework
==> Installing kframework from kframework/k
==> Downloading https://github.com/kframework/k/releases/download/v5.0.0-cd4ac9c//kframework-5.0.0.mojave.bottle.76.tar.gz

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "kframework"
Download failed: https://github.com/kframework/k/releases/download/v5.0.0-cd4ac9c//kframework-5.0.0.mojave.bottle.76.tar.gz
```

**Comment by dwightguth** [comment]
I could have sworn I commented on this in review and we were going to address it, but oh well. Just remove the date from the mac build. We added the date to give the file a unique filename, but the rebuild number brew creates already does that.

**Comment by ehildenb** [comment]
You did comment on the review, but my impression of your comment was "this might be a problem, we need to see", so we waited and saw.

It is an easy fix though.
