### ISSUE TITLE
[KIP] - K Bison parsers should not get stuck when passed an invalid file path

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#1843]
Motivation
----------

When developing semantics which load code at runtime, it is very helpful to wire up a simple function involving the `#system` and `#parseKORE` hooks and the generated `parser_PGM`, e.g.,

```
syntax Pgm ::= loadFile(String) [function]
             | parseFile(KItem) [function]
// ---------------------------------------
rule loadFile(Path) => parseFile(#system("parser_PGM \"" +String Path +String "\""))
rule parseFile(#systemResult(0, Stdout, _)) => #parseKORE(Stdout)
```

The problem with the above code is that, if the string `Path` does not represent a valid file, `parser_PGM` will get stuck and the semantics will get stuck too.

Ideally, the parser program will return an error code and report a message on stderr when the file path passed in is invalid.

Documentation
-------------

K Bison generated parsers will return an error code and report an error on stderr when passed an invalid file path as their first argument.

Potential Alternatives/Work-arounds
-----------------------------------

As an alternative, one could try and write a wrapper script that tries to open the file and read its contents. This script can be designed to fail when the file path is invalid. Then this script could pass the file contents to the underlying parser_PGM.

Testing Approach
----------------

This could be tested by:

- writing a simple semantics that does hot-code loading using the above approach
- checking that the semantics does not get stuck when trying to run parser_PGM on an invalid file path --- it either terminates with 0 and stdout non-empty or a non-zero return code and stderr non-empty

Or simply running parser_PGM directly and seeing that we don't get stuck (not sure if the test harness supports this).

**Comment by dwightguth** [comment]
This is actually two different problems working together. The first is that the scanner doesn't report an error if a file doesn't exist. The second is that if all the buffers passed to flex are invalid, it reads from stdin by default and hangs until the user presses Ctrl-D. We need to reconfigure the generated flex scanner to solve both of these problems.
