### ISSUE TITLE
[Bug] [krun/kompile] - Can no longer run definitions that don't use `$PGM`

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#1844]
K Version
---------

```
RV-K version 1.0-SNAPSHOT
Git revision: 7ac809a
Git branch: UNKNOWN
Build date: Fri Mar 05 00:15:13 CST 2021
```

Description
-----------

Running `krun` with a configuration that does not use `$PGM` results in a unhelpful error.
This used to work previously.

Reproducing
-----------

```
$ cat test.k 
module TEST
    imports BOOL

    syntax FOO ::= "foo"
    configuration <k> foo </k>
endmodule
$ kompile --backend haskell test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
$ krun 
kore-exec: [88663] Error (ErrorVerify):
    Error:
      symbol or alias 'LblinitGeneratedTopCell' (.krun-2021-03-05-00-18-36-U7im2v8NSF/tmp.in.1FEhIcKWgc 1:1):
        Expected 0 operands, but got 1.
Created bug report: kore-exec.tar.gz
[Error] Critical: Backend crashed during rewriting with exit code 1
```

Expected Behavior
-----------------

Either:

1. A clear and concise error message saying that the `$PGM` variable is required.
2. Successfully running the configuration, resulting in a stuck configuration `<k> foo </k>`

**Comment by ehildenb** [comment]
Some ideas about what's going on:

-    `krun` is not correctly handling the case where no variables are declared at all (not necessarily because `$PGM` is missing).

So _likely_ the `krun` script needs to detect that there are no configuration variables and handle it appropriately.

**Comment by ehildenb** [comment]
Good thing to try: does `krun-legacy` work?
