### ISSUE TITLE
[kompile] - Having `function` on `macro` symbols should be a kompile-time error

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1852]
K Version
---------

Tell us what version of K you are using.

Example:

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: aa04b03
Git branch: UNKNOWN
Build date: Sat Mar 06 18:12:48 UTC 2021
```

Description
-----------

Running `kompile` on a definition which contains a `macro` rule for a `function` symbol produces no error, but makes it so that `kore-expand-macros` fails every time with a terrible error message.

Input Files
-----------

File: `test.k`

```
module TEST
    imports INT

    syntax Int ::= foo ( Int ) [function]
    rule foo(I) => 3 +Int I [macro]
endmodule
```

Reproduction Steps
------------------

Kompiling produces no error:

```
$ kompile test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

Expected Behavior
-----------------

Calling `kompile` on this definition would result in an error about the production `foo` being both a `function` and a `macro`.

**Comment by radumereuta** [comment]
Make it an error if the symbol at the top of a macro rule is a function.
If ExpandMacro.ismacro == true 
Dwight: you should also check that if a rule has the alias or alias-rec attribute, that the symbol on the top of the rhs is not a function either
