### ISSUE TITLE
[Bug] [krun] - output json produces weird output

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/k#1861]
K Version
---------
```
RV-K version 1.0-SNAPSHOT
Git revision: aa04b03
Git branch: UNKNOWN
Build date: Wed Mar 10 08:20:41 CST 2021
```

Description
-----------
For some test input, krun-legacy --output json produces an output starting with `\`, which results in a malformed json file.

Reproduce step
---------------------
* Elrond semantics: https://github.com/runtimeverification/elrond-semantics
Install the dependency packages as instructed here: https://github.com/runtimeverification/elrond-semantics/blob/81ef74488e44f3e75183d88871507c435ff19915/Dockerfile#L6
```
make deps
make build-llvm
```

* Krun the input file 
```
cd elrond-semantics
deps/wasm-semantics/deps/k/k-distribution/target/release/k/bin/krun-legacy --directory .build/defn/llvm crypto_verify_funcs.scen.json_0_full.txt --term --debug --output json --parser cat > result.txt
```
[crypto_verify_funcs.scen.json_0_full.txt](https://github.com/kframework/k/files/6151649/crypto_verify_funcs.scen.json_0_full.txt)
[result.txt](https://github.com/kframework/k/files/6151656/result.txt)

Expected Behavior
-----------------
I expect the result.txt to start with `{`, however, it starts with `\{`.

**Comment by dwightguth** [comment]
@yzhang90 is this still an issue? It needs a minimized example.

**Comment by dwightguth** [comment]
Just to replicate the discussion I had on slack, @yzhang90 said he is working on something different at the moment and will reopen this if it becomes relevant to him again.
