### ISSUE TITLE
Better scanner handling

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1867]
`kompile` and `kprove` both need to parse rules, but when running a second time, even if none of the rules were changed, they still generate some new scanners.
Here is the output of the second run of kompile on a simple test.k file.
```
Outer parsing [124 modules]                                  =  1.128s
New scanner:TEST$SYNTAX-CONFIG-CELLS                         =  0.117s
New scanner:TEST-CONFIG-CELLS                                =  0.147s
New scanner:STDOUT-STREAM$SYNTAX-CONFIG-CELLS                =  0.211s
New scanner:STDOUT-STREAM-CONFIG-CELLS                       =  0.224s
New scanner:STDIN-STREAM$SYNTAX-CONFIG-CELLS                 =  0.215s
New scanner:STDIN-STREAM-CONFIG-CELLS                        =  0.223s
Parse configurations [0/6 declarations]                      =  1.449s
New scanner:TEST-RULE-CELLS                                  =  0.143s
New scanner:K-EQUAL-RULE-CELLS                               =  0.129s
New scanner:INT-SYMBOLIC-RULE-CELLS                          =  0.128s
New scanner:INT-SYMBOLIC-KORE-RULE-CELLS                     =  0.133s
New scanner:INT-KORE-RULE-CELLS                              =  0.153s
New scanner:K-EQUAL-KORE-RULE-CELLS                          =  0.154s
New scanner:STRING-KORE-RULE-CELLS                           =  0.162s
New scanner:INT-RULE-CELLS                                   =  0.181s
New scanner:STRING-COMMON-RULE-CELLS                         =  0.186s
New scanner:K-IO-RULE-CELLS                                  =  0.231s
New scanner:STDIN-STREAM-RULE-CELLS                          =  0.247s
New scanner:STDOUT-STREAM-RULE-CELLS                         =  0.252s
Parse rules [0/96 rules]                                     =  0.576s
```
Even though 0 rules were parsed, there are 18 scanners being generated.
This is the output of running kprove twice on a KEVM spec file:
```
New scanner:EVM$SYNTAX-CONFIG-CELLS                          =  0.494s
New scanner:EVM-CONFIG-CELLS                                 =  1.053s
New scanner:DAI-SYMBOL-PASS-SPEC-RULE-CELLS                  =  1.270s
Parse spec modules [0/1586 rules]                            =  7.210s
```
Again, 0 rules were parsed, but we're still spending time generating scanners.

The first problem is we're not properly detecting when we need to generate a new scanner:
https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java#L313
https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java#L380

The second problem is we're not taking advantage of caching these scanners when they are pretty expensive to generate.

I'm proposing we keep these scanners in `*-kompiled` and reuse them for kompiling multiple times and for kprove.
Q1: Is there a way to minimize the number of scanners? If a module doesn't introduce new syntax, can we reuse one of the included modules? This could speed up kprove significantly.
Q2: Currently we run parsing in parallel. We need to find a way to not duplicate scanner generation. This is even more complicated when running kprove in parallel. Should we make it so kprove doesn't cache scanners, or we can detect that another thread is in the process of generating one and wait until it finishes?

**Comment by ehildenb** [comment]
Several things:

-   If module A imports module B, then we should generate a scanner for module A, and use that same scanner for module B (not a new one for module B).
-   If a module doesn't contain any rules which are not cached, we do not need to generate a scanner for them (the links above) because we don't need to do any parsing.
-   We may want to cache scanners, but it may not be nearly as big of a problem once the first two are addressed.
-   STDIN-STREAM and STDOUT-STREAM end up importing a bunch of other modules, and are manually included in the list of modules here: https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java#L194. This is even _if_ the definition does not actually make use of these modules, but it's hard to detect this without first building the configuration.
