### ISSUE TITLE
[Bug] duplicate rules breaks kompile error messages

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1873]
```
module TEST
  imports INT
  claim 1 => 0
  claim 1 => 0
  claim 1 => 0
endmodule
[Error] Compiler: Claims are not allowed in the definition.
	Source(/home/radu/work/test/./test.k)
	Location(4,9,4,15)
[Error] Compiler: Claims are not allowed in the definition.
	Source(/home/radu/work/test/./test.k)
	Location(5,9,5,15)
```
Only 2 error messages (instead of 3). Second kompile only one:
```
[Error] Compiler: Claims are not allowed in the definition.
	Source(/home/radu/work/test/./test.k)
	Location(4,9,4,15)
```
It got very confusing when I was trying to add tests for rules with different attributes.
Should we disallow them?
How about rules with the same contents but different attributes?
How about a rule and a claim which has the same contents?

Also. Error messages don't get updated with the new location if I add new lines before the rule.

**Comment by dwightguth** [comment]
This looks like it's a consequence of a bug that doesn't correctly update the location information of rules after they've been retrieved from the cache. As a result, two of the three error messages are identical and thus get automatically deduped. I think if we fix this issue we should see more sensible behavior afterwards.

**Comment by ehildenb** [comment]
We won't focus on fixing the rule de-dupe, but the error message de-dupe. This can be done by correctly updating location information of rules after retrieving from cache.
