### ISSUE TITLE
[Bug] kompile/krun - `libjemalloc.so.1` cannot open shared object

### ISSUE THREAD

**Issue by crvdgc** [runtimeverification/k#1897]
K Version
---------

```
$ kompile --version
K version:    5.0.1
Build date:   Fri Apr 02 05:31:16 JST 2021
```

Description
-----------

Install with the [5.2.1 version](https://ubuntu.pkgs.org/20.10/ubuntu-universe-amd64/libjemalloc-dev_5.2.1-1ubuntu1_amd64.deb.html) of `libjemalloc-dev`, try `kompile` with any input will result in an error of missing `libjemalloc.so.1`.

Reproduction Steps
------------------

Freshly install the 5.2.1 version of `libjemalloc-dev`:

```sh
$ sudo apt install libjemalloc-dev
```

Then try `kompile` with any input

```sh
$ make kompile
/usr/bin/kompile --gen-bison-parser --backend llvm  imp.k -d .
/usr/lib/kframework/../../bin/llvm-kompile-codegen: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
[Error] Critical: llvm-kompile returned nonzero exit code: 127
Examine output to see errors.
```

also `krun`

```sh
$ krun tests/sum.imp
kore-expand-macros: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
```

Expected Behavior
-----------------

`kompile` and `krun` execute successfully.

Suggested Fix
-----------------

The unpack target `/usr/lib/x86_64-linux-gnu/libjemalloc.so` is symbolically linked to `/usr/lib/x86_64-linux-gnu/libjemalloc.so.2` instead of `/usr/lib/x86_64-linux-gnu/libjemalloc.so.1`. And `libjemalloc.so.1` is no longer installed, resulting a missing shared object error.

A temporary fix:

```sh
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libjemalloc.so /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
```

A more permanent fix should change the dependency from `libjemalloc.so.1` to `libjemalloc.so`, which will be linked to the correct version. However, I don't know where to change.

**Comment by ehildenb** [comment]
@crvdgc can you give us information about your platform? OS Distro? Did you recently update?

The linked version of jemalloc you provided looks like it's for Ubuntu 20.10, which we do not provide packages for. Did you build from source or install a packaged version?

**Comment by crvdgc** [comment]
@ehildenb Sure. Indeed I'm running Ubuntu 20.10. I installed from a package. I just saw the support is for Ubuntu 20.04. Thanks for your reply.

```
$ cat /etc/*-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Pop!_OS 20.10"
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**Comment by ehildenb** [comment]
You may try the platform independent K binary, or a from source build. But we don't plan to support non-LTS variants of OSs.
