### ISSUE TITLE
[Bug] kompile - Inconsistent symlink handling in require

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1906]
First fill in the title (template provided).
Examples:

K Version
---------

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 0cfac90
Git branch: master
Build date: Wed Mar 17 01:46:12 EET 2021
```

Description
-----------

If the main file being kompiled is a symlink, its `require`d files are resolved relative to the directory containing the symlink. However, the `require`d files for everything else are resolved relative to the directory containing the actual file.

Input Files
-----------

In a directory, let's call it `original`:

x.k:
```
require "y.k"
module X
endmodule
```

y.k:
```
require "z.k"
module Y
endmodule
```

z.k:
```
module Z
endmodule
```

Reproduction Steps
------------------

In the parent directory containing the `original` dorectory mentioned above:

```
mkdir symlink
cd symlink
ln -s ../original/x.k x.k
kompile x.k
ln -s ../original/y.k y.k
kompile y.k
```

For the first kompile, you should get an error: ```[Error] Critical: Could not find file: y.k```. I think that this is the correct behaviour. The second kompile, however, works.

Expected Behavior
-----------------

I think that all `require`d files should be resolved relative to the directory containing the symlink. If that's not reasonable, the `kompile` behaviour should at least be consistent (error in both cases above or no error in either case).

**Comment by radumereuta** [comment]
The front end uses Java to resolve the file paths. Here is the exact place in the code:
https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/parser/ParserUtils.java#L119

**Comment by dwightguth** [comment]
Java unfortunately doesn't really have a good way to give you an absolute path from a relative path that doesn't involve canonicalizing symlinks. At least, not that I'm currently aware of. If you know of a way, I'm happy to change the way we deal with resolving relative paths so it doesn't also resolve symlinks. In the absence of that information though, it's probably going to prove easier to resolve symlinks in the main file being compiled.

**Comment by virgil-serbanuta** [comment]
As requested: I'm using Ubuntu 18.04.5 LTS.

**Comment by ehildenb** [comment]
It should be possible to always resolve the symlinks, by replacing the correct call to `getAbsolutePath()` to `getCanonicalPath()`, somewhere in the code which handles resolving the main file to `kompile` on the command-line.

**Comment by ehildenb** [comment]
We should be able to also add this as a test in the regression suite (by just setting up this symlink structure).
