### ISSUE TITLE
[KIP] - Kprove should have configurable include paths

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1909]
[KIP] - Use `foo` instead of `syntax` for declaring productions

Motivation
----------

This would be useful for better access to trusted claims.

Example K Code
--------------

I would like to be able to use project relative paths for including K files in proofs, e.g. the `trusted` directory mention below could live at root of the project, while the proof below could be in a random subfolder.

```
require "trusted/claim1.k"

module MY-PROOF
  imports CLAIM1

  claim ...
endmodule
```

Documentation
-------------

A user can specify an include path with -I, e.g.

```
$ kprove -I `git rev-parse --show-toplevel` my-proof.k
```

Potential Alternatives/Work-arounds
-----------------------------------

I guess users could use relative paths (which in some contexts is fairly hard to do, e.g. when generating trusted claims with bazel) or they could concatenate files instead of requiring them.

Testing Approach
----------------

I don't know much about the existing testing harness.

**Comment by ehildenb** [comment]
Currently the workaround for this is to include the `-I` you need in the preceding call to `kompile`, because those lookup directories do get saved in the generated `compiled.bin` and other various cache files.

**Comment by ehildenb** [comment]
Let's focus on supporting this for KProveX

**Comment by SchmErik** [comment]
@radumereuta I was browsing through the codebase today and saw that https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/utils/options/OuterParsingOptions.java contains classes that are meant for the outer parser of kompile, and kdep. This file contains mentions of `-d`, `-I`, `--no-prelude`, and `--md-selector` options. Looking at kprovex, I see that the `-d` option exists and this bug asks to support `-I`. I don't mean to blow this issue out of proportion but but should we consider implementing `--no-prelude` and `--md-selector` options as well?

**Comment by radumereuta** [comment]
You may want to look at #1330
Yes, there are some inconsistencies when it comes to option names, and fully fixing them will require some nonbackward compatible changes.
Maybe since kprovex is so new, we could enforce a change to `-d` since this is the option that caused conflicts.
@ehildenb @dwightguth thoughts?

**Comment by ehildenb** [comment]
We can move `-d/--directory` out of OuterParsingOptions.java into a new class (like BackendDirectoryOptions.java). Then it can be included in all the relevant places.

The `--md-selector` for kprovex should _not_ touch/re-parse the original definition. So the `--md-selector` option should _only_ affect the spec file/module that is added, but not change the original definition.

**Comment by ehildenb** [comment]
Guice can inject the dependency for you if you just add it as an option to this constructor: https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/kprove/KProve.java#L47 (that's for kprove, you'll need to do the same for kprovex).
