### ISSUE TITLE
Do-while Statement in IMP

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#192]
Hello,

can someone explain how to make the statement within the do block static in K?

My goal is to define a do-while statement for IMP. I can show you how what I have written so far:

    syntax Stmt  ::= Block
                 | Id "=" AExp ";"            [strict(2)]
                 | Id Id ":=" AExp AExp ";"   [strict(3,4)]
                 | "if" "(" BExp ")"
                   Block "else" Block         [strict(1)]
                 | "while" "(" BExp ")" Block
                 > Stmt Stmt                  [left]
                 | "repeat" Block "until" "(" BExp ")"
                 //| "for" "(" Stmt ";" BExp ";" Stmt ")" "while" "(" BExp ")" Block [left]
                 //> Stmt Stmt
                 | "do" Block "while" "(" BExp ")" Block [left]

It is not the entire implementation from IMP, I used the existing one and changed it a little bit. Above code contains the syntactical definition. The semantic definition is shown here:

      rule S1:Stmt S2:Stmt => S1 ~> S2  [structural]

      rule if (true)  S else _ => S
      rule if (false) _ else S => S

      rule while (B) S => if (B) {S while (B) S} else {}  [structural]
      rule repeat S until (B) => S if (B) {} else {repeat S until (B)} [structural] //neue Regel
      //rule for (S B S) S => while (B) {S while (B) S} else {} [structural]
      rule do S && while (B) S => if (B) {S while (B) S} else {} [structural]

I can't compile it. What am I doing wrong?

Thanks!

**Comment by ghost** [comment]
Your use of the `&&` terminal in the semantic definition is incorrect. The `&&` construction requires a BExp on both the left and right, but you're putting `S` and `(while (B) S)` which you declared in the syntax to be a Block, and a (terminal (BExp) Block) respectively. You were probably thinking too hard. In the case of [structural] semantic rules, there's no computation going on, so you only need to concern yourself with patterns that are immediately valid syntactic constructs.

For reference, these definitions work correctly for do/while constructs depending on whether you want the first and second blocks to be the same or not.
in imp.k:
```
// syntax and semantics if the first and subsequent Blocks are the same

syntax Stmt ::= "do" Block "while" BExp                 [seqstrict]
...
rule do S while (B) => {S while (B) S}                  [structural]
```

```
// if first and subsequent Blocks are different

syntax Stmt ::= "do" Block "while" BExp Block          [seqstrict]
...
rule do S while (B) T => {S while (B) T}               [structural]

```

An example program for the first
```
int a, b;
a = 10;
b = 0;
do { 
    b = (b + 1); 
} while (b <= (a + (-1)))
```
terminates with 
a |-> 10
b |-> 10

and for the second:
```
int a, b, c;
a = 10;
b = 0;
c = 0;
do { 
    c = (c + 1); 
} while (b <= (a + (-1))) { 
    b = (b + 1);
}
```
terminates with
a |-> 10
b |-> 10
c |-> 1

**Comment by Qais87** [comment]
Thank you so much. That helps me a lot.
