### ISSUE TITLE
How to handle CHANGELOG.md

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1922]
Options include:

- Enforce on CI that every commit changes the `CHANGELOG.md` unless it's automatically generated or some small bugfix (in PR title?).
- Enforce at review time of version bumps that changelog has been updated correctly with changes since last version bump.

**Comment by ehildenb** [comment]
Perhaps we should also be making the Changelog available on the Website as well.

**Comment by ehildenb** [comment]
One potential is to have the K master job update the changelog correctly. Currently, it just updates the release branch with the newest version numbers and such, but we could also have it update a branch `v5.NEXT.0-rc`, which is automatically opened as a PR, with the updated changelog.

Then when we want to version-bump, we just approve this PR and it gets merged.

**Comment by radumereuta** [comment]
Include this information in the release issue. Then close this.
