### ISSUE TITLE
[Bug] kprove - Unhelpful error message when not pointing to the correct kompiled module

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#1925]
K Version
---------

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: e6f260d
Git branch: UNKNOWN
Build date: Thu Mar 18 15:05:27 UTC 2021

$ kprove --version 
RV-K version 1.0-SNAPSHOT
Git revision: e6f260d
Git branch: UNKNOWN
Build date: Thu Mar 18 15:05:27 UTC 2021
```

Description
-----------
Here's an error message I have run into a few times when I've used an extended semantics for proving.

The problem occurs when I point `kprove --directory` to a kompiled semantics, but the actual `--def-module` used for proving contains new syntax of configurations. 
The error is either a simple `NullPointerException` or `NoSuchElementException` without any extra useful information.
I know by now what the problem is, but I feel we could be more helpful to newcommers with the error messages.

Input Files
-----------

File: `foo.md`

    # Dummy semantics module
    
    Here's a dummy semantics we build using `kompile`.
    It represents the "main" semantics in our project.
    
    ```k
    module FOO
       imports DOMAINS
       configuration <foo>
                       <k> 0 </k>
                     </foo>
       
       rule <k> 0 => 1 ... </k>
       
    endmodule
    ```
    
    # Proving helper module
    
    Here's a common pattern: we use an exiting semantics (`FOO`) for proving, but we want to add some extra configuration and syntax, not just new lemmas.
    We may do so through configuration composition.
    
    ```k
    module BAR
        imports FOO
        
        configuration <bar>
                        <foo/>
                        <l> true </l>
                      </bar>
    endmodule
    ```
    
    We then use the new module for proving.
    However, if we need to first kompile our `BAR` semantics and point to that (using the `--directory` flag) when running `kprove`.
    If we forget and use our `foo-kompiled` directory for this, we'll get a `NullPointerException` without much more useful information.
    
    ```k
    module BAR-SPEC
        imports BAR
    
        claim <k> 0 => 1 ... </k>
    endmodule
    ```
    
    # A completely separate module
    ```k
    module BAZ
        imports DOMAINS
        
        configuration <baz>
                        <k> true </k>
                      </baz>
    endmodule
    ```
    
    # Proving a different module
    
    Similar situation to the above, except in this case there is no use of the original `FOO` module.
    We get an almost identical error message, except the exception is `NoSuchElementException`.
    
    ```k
    module BAZ-SPEC
        imports BAZ
    
        claim <k> 0 => 1 ... </k>
    endmodule
    ```

Reproduction Steps
------------------

Run:
```
kompile --backend haskell foo.md --main-module FOO
kprove --directory . foo.md --def-module BAR --spec-module BAR-SPEC
kprove --directory . foo.md --def-module BAZ --spec-module BAZ-SPEC
```

Output:
```
/home/hjort/michelson-semantics/dev/ext/k/k-distribution/bin//kompile
[Warning] Compiler: Could not find main syntax module with name FOO-SYNTAX in
definition.  Use --syntax-module to specify one. Using FOO as default.
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NullPointerException: null)
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoSuchElementException: key not found: <foo>)
```

Expected Behavior
-----------------

I would expect a message saying something like:
"The definition module <module name> does not match the kompiled one in <directory>. You should kompile <module name> first."

**Comment by radumereuta** [comment]
I think this might be a duplicate of #1887

**Comment by hjorthjort** [comment]
> I think this might be a duplicate of #1887

Looks like it, thanks
