### ISSUE TITLE
[Bug] kompile - suggests to add existing attribute (simplification)

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#1940]
First fill in the title (template provided).
K Version
---------

```
$ kompile --version
K version:    5.1.0
Build date:   Fri Apr 23 20:39:29 EEST 2021
```

Description
-----------

Running `kompile` without `--backend haskell` produces errors for simplification rules. The error message suggests adding the `simplification` attribute.

Input Files
-----------

File: `tmp.k`

```
module TMP

syntax Int ::= f(Int)  [function, functional]
syntax Int ::= g(Int)  [function, functional]

rule g(f(X)) => X [simplification]

endmodule
```

Reproduction Steps
------------------

Kompiling produces an error suggesting to add the `simplification` attribute:

```
$ kompile tmp.k
[Error] Compiler: Illegal function symbol f(_)_TMP_Int_Int on LHS of rule.
Consider adding `simplification` attribute to the rule if this is intended.
        Source(/mnt/data/runtime-verification/verified-smart-contracts/multisig/protocol-correctness/proof/functions/tmp/tmp.k)
        Location(6,8,6,12)
[Error] Compiler: Had 1 structural errors.
```

Expected Behavior
-----------------

Either `tmp.k` should just kompile, or the error message should say something like "Simplification rules not supported by default. Kompile for a backend that supports them."

**Comment by ehildenb** [comment]
`simplification` rules should not be fed to the LLVM backend anyway. So we need to inspect :+1: 

-  Where `simplification` rules are being filtered out for concrete backends.
- The check  for function symbols on LHS of rule should not worry abuot `simplification` rules, whether or not it's llvm/haskell backend.
