### ISSUE TITLE
Builtin Map should check whether keys can be unified

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#195]
The built in Map type assumes the keys of Maps to be distinct. K already throws when concatenating maps where there are multiple entries using the same key, as seen [here](https://github.com/kframework/k/blob/605c1e56f831ed76c98398e9fe544bfbab06c326/java-backend/src/main/java/org/kframework/backend/java/kil/BuiltinMap.java#L211). 

However, the check detects concrete collisions though, and if the Maps have symbolic key values then they can be concatenated even though the keys can be unified. This can potentially introduce a soundness problem in proofs where symbolic key values are identified in some parts of the proofs while referring to different Map entries.

**Comment by ehildenb** [comment]
The Haskell backend correctly checks that map keys are distict (does not have this soundness problem). If you discover any problems with map unification in the Haskell backend, please re-open. Closing because Java is not being actively developed anymore.
