### ISSUE TITLE
Unexpected non-determinism with user list

### ISSUE THREAD

**Issue by kheradmand** [runtimeverification/k#1950]
K Version
---------

Tell us what version of K you are using.

Example:

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 
Git branch: UNKNOWN_BRANCH
Build date: Thu Mar 25 04:00:09 IRDT 2021
```

Description
-----------

Running `krun` results in an unexpected output with the haskell backend.

Input Files
-----------

Examples:

File: `test.k`

```

module TEST-SYNTAX
imports ID
        syntax ControlBlock ::= "{" ControlStatements "}"
        syntax ControlStatements ::= List{ControlStatement,""}
        syntax ControlStatement ::=
                      ApplyTableCall
                    | IfElseStatement

         syntax ApplyTableCall ::= "apply" "(" Id ")" ";"

        syntax IfElseStatement ::=
              "if" "(" BoolExpr ")" ControlBlock

        syntax BoolExpr ::= Bool


endmodule

module TEST
imports DOMAINS
imports TEST-SYNTAX

    syntax KResult ::= Bool

    configuration
        <k> $PGM:ControlStatements </k>
        <ts> .List </ts>

    rule .ControlStatements => .K
    rule S:ControlStatement Rest:ControlStatements => S ~> Rest
    rule <k> apply (T); => .K ... </k>
         <ts> (.List => ListItem(T)) ... </ts>
    rule <k> if (true) { X } => X ... </k> 

endmodule

```

File: `input.test`

```
if (true){
	apply (t);
}
```

Reproduction Steps
------------------

```
$ kompile --backend haskell test14.k --syntax-module TEST-SYNTAX --main-module TEST
$ krun input.test
      <generatedTop>
        <k>
          .
        </k>
        <ts>
          ListItem ( t )
        </ts>
      </generatedTop>
    #Or
      <generatedTop>
        <k>
          if ( true ) { apply ( t ) ;  .ControlStatements } ~> .ControlStatements ~> .
        </k>
        <ts>
          .List
        </ts>
      </generatedTop>
```

Expected Behavior
-----------------

```
$ krun input.test
<generatedTop>
  <k>
    .
  </k>
  <ts>
    ListItem ( t )
  </ts>
</generatedTop>

```

**Comment by ehildenb** [comment]
This is actually a problem with the grammar @kheradmand . The rule `if (true) { X } => X` has `X` on the RHS, which is sort `ControlStatements`, and `if(_)_` is sort `ControlStatement`, so the correct most general sort to pick for that rule is `ControlStatements`.

You'll have to change your grammar to make this rule sort correctly. One option would be:

Try these things:

```
syntax ControlStatement ::= ControlBlock

rule <k> if (true) CB => CB ... </k>
rule <k> { CS } => CS ... </k>
```

Another solution may be:

```
rule <k> (if(true) { CS })::ControlStatement => CS ... </k>
```

Another solution may be:

```
rule <k> (if (true) { CS } => CS):KItem ... </k>
```

**Comment by kheradmand** [comment]
@ehildenb Thanks!
```rule <k> (if(true) { CS })::ControlStatement => CS ... </k>``` and  ```rule <k> (if (true) { CS } => CS):KItem ... </k>``` still lead to the same non-determinism but ```rule <k> (if (true) { X }) => X ... </k>``` (note the parentheses) gives the expected output.

**Comment by radumereuta** [comment]
That's very strange. Parentheses should be invisible to the type inferencer.

**Comment by dwightguth** [comment]
I'm closing this because it's unclear if this is still affecting you. Feel free to open a new issue if you are still affected by this.
