### ISSUE TITLE
Add support for unicode encoding/decoding between Bytes and String

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#1953]
It would be nice to be able to encode/decode UTF-8 strings for being able to print (in the proof configuration) error messages associated wiht Solidity's ABI encoding https://docs.soliditylang.org/en/v0.5.3/abi-spec.html#types.

Proposed signature:

```
syntax String ::= decodeBytes ( encoding: String , contents: Bytes ) [function, hook(BYTES.decodeBytes)]
syntax Bytes ::= encodeBytes ( encoding: String , contents: String ) [function, hook(BYTES.encodeBytes)]
```

**Comment by dwightguth** [comment]
I think we need more info about what exactly the problem you're trying to solve is. It's hard to tell whether some kind of encoding/decoding function would actually help solve something like this without knowing exactly the behavior you're trying to fix.

**Comment by ehildenb** [comment]
Specifically, we have the symbolic tests in the ERC20 tool, which means we're symbolically executing bytecode generated by the Solidity compiler (haskell backed).

In the symbolic tests, we attach strings to the pre/post-conditions (to indicate which ones passed/failed, and for documentation), and the Solidity compiler UTF-8 encodes them for storing them in the bytecode, assuming that whatever is consuming it will display it as a UTF-8 string.

We log these strings to a trace as the proof runs, to see how far it made it. Currently, we are just using `Bytes2String(...)`, which gives us a garbled looking string with some readable ASCII in it. So we need to call `decodeBytes("UTF-8", LOG_BYTES)` on when logging it to the trace, so that we can read these intermediate states better.

Not super high priority, but makes it a bit annoying to debug the proofs.
