### ISSUE TITLE
[Bug] kompile - [Error] Critical: llvm-kompile returned nonzero exit code: 127

### ISSUE THREAD

**Issue by NicolasRouquette** [runtimeverification/k#1955]
[Error] Critical: llvm-kompile returned nonzero exit code: 127

Examples:

see: https://github.com/kframework/k/tree/master/k-distribution/k-tutorial/1_basic/02_basics

```
module LESSON-02-A

  syntax Color ::= Yellow() | Blue()
  syntax Fruit ::= Banana() | Blueberry()
  syntax Color ::= colorOf(Fruit) [function]

  rule colorOf(Banana()) => Yellow()
  rule colorOf(Blueberry()) => Blue()

endmodule
```

[Bug] kompile - crash when compiling 

```
kompile lesson-02-a.k                 
/opt/tools/k/lib/kframework/../../bin/llvm-kompile-codegen: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory
[Error] Critical: llvm-kompile returned nonzero exit code: 127
Examine output to see errors.
[Warning] Compiler: Could not find main syntax module with name
LESSON-02-A-SYNTAX in definition.  Use --syntax-module to specify one. Using
LESSON-02-A as default.
```

K Version
---------

Tell us what version of K you are using.

Example:

```
$ kompile --version
K version:    5.1.11
Build date:   Thu Apr 29 15:14:10 PDT 2021
```

I installed the platform-independent K binary in an ubuntu 20.04 LTS VM running on Windows 10 Pro using wsl2.
 https://github.com/kframework/k/releases/download/v5.1.11/k-nightly_5.1.11.tar.gz

Note that in this environment, there is a library:

```
readlink -e /usr/lib/*/libjemalloc.so.*  
/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
```

It would be helpful if `kompile` showed what environment variables it is using to lookup libraries.
One could perhaps attempt at a workaround similar to this: https://stackoverflow.com/a/65853546

**Comment by NicolasRouquette** [comment]
FYI: I managed to work around this problem installing the Ubuntu 20.04 package:
https://github.com/kframework/k/releases/download/v5.1.11/kframework_5.1.11_amd64_focal.deb

**Comment by ehildenb** [comment]
We'll remove the platform independent K binary, because it really onlly works with LLVM backend on Ubuntu 18.
