### ISSUE TITLE
Latest z3 version makes java kprove to fail

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1957]
I've updated to Ubuntu 21.04 which comes by default with z3-4.8.10, which crashes java kprove with
`ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15` in `FastRuleMatcher.java`
Failing test: https://github.com/kframework/k/tree/master/k-distribution/tests/regression-new/proof-tests/deposit/spec
I tried z3-4.8.11 (not yet released) and it doesn't crash, but it gives a different result.

As a workaround, I've manually built z3-4.8.7

**Comment by ehildenb** [comment]
Use `--debug-z3-queries` to retrieve the query made to Z3 which causes the change in behavior. You can dump the Z3 query to a file `test.z3`, and call `z3 test.z3` on it. See what different versions of Z3 report on that query.

If Z3 does change its behavior on the query, we should report it.

Otherwise, the correct fix is to migrate this test to the Haskell backend.

**Comment by radumereuta** [comment]
```
(define-sort IMap () (Array Int Int))
(declare-fun isValidBranch (IMap Int) Bool)
(declare-fun isValidZeros (IMap Int) Bool)
(declare-fun |K_138| () Int)
(declare-fun |TREE_HEIGHT_137| () Int)
(declare-fun |M_139| () Int)
(declare-fun |Branch_135| () IMap)
(declare-fun |Zeros_136| () IMap)
(assert (and
  (and
    (= (>= |K_138| |TREE_HEIGHT_137|) true)
    (= (<= |K_138| |TREE_HEIGHT_137|) true)
    (= (< |M_139| (^ 2 |TREE_HEIGHT_137|)) true)
    (= (isValidBranch |Branch_135| |M_139|) true)
    (= (isValidZeros |Zeros_136| |M_139|) true)
    (= (>= |K_138| 0) true)
    (= (>= |M_139| 0) true)
    (= (>= |TREE_HEIGHT_137| 0) true)
  )
  (not (and
    (= (<= (+ |M_139| 1) (^ 2 |K_138|)) true)
  ))
))

(check-sat)
```
z3-4.8.7 -> unsat
z3-4.8.8 -> unsat
z3-4.8.9 -> unsat
z3-4.8.10 -> unknown
z3-master -> unknown (0c6722f48b2814e44ed98ea33b2a356579fd90f4)

There are a bunch of queries like this one, which switches from `unsat` to `unknown`. This is the first one.

**Comment by dwightguth** [comment]
Try reporting this to the z3 repo and see what they say.

**Comment by radumereuta** [comment]
Reported issue to z3: https://github.com/Z3Prover/z3/issues/5243

**Comment by radumereuta** [comment]
Response from NikolajBjorner:
>the operator ^ is non-standard (not part of SMTLIB2 definition).
The implementation prior to 4.8.10 assumed that when given two integers the result would be integer.
This assumption is wrong when the exponent is negative, so generally it returns a Real (while your context restricts the exponents to be non-negative it requires context for type inference to know this).
Unfortunately, when we don't know anything more about exponentiation and only know that the result is Real, the constraints are not shown unsat using just integer arithmetic.
You can "patch" this by inserting (to_int (^... ...)) in the places you use power. In this way you are saying you only care about integer interpretations of ^. You will get the old behavior then.

**Comment by radumereuta** [comment]
This workaround works for z3-4.8.11 (unreleased atm) but does not work with z3-4.8.10.

**Comment by radumereuta** [comment]
Check if this is still an issue.

**Comment by radumereuta** [comment]
This is being tracked by other issues.
