### ISSUE TITLE
[Bug] [krun] - segfault in padRightBytes

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/k#1966]
K Version - commit d44b4f9314371a72194980455c77d43b0f8d9710

Description
-----------
Running `krun` with a definition which uses `padRightBytes` on a very large number causes a segfault on LLVM backend.

Input Files
-----------
File: `test.k`
```
module TEST
  imports BYTES
  syntax KItem ::= "a"
  rule <k> a => padRightBytes(.Bytes, 19050717897387323458361470737746716430764484818157613748551236551847601766400, 0) ... </k>
  configuration <k> $PGM:KItem </k>
endmodule
```

File: `input.test`:
```
a
```

Reproduction Steps
------------------

Running on LLVM backend causes a segfault when division by zero:

```
$ kompile --backend llvm test.k  -d .
Successful kompilation
$ krun input.test
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Integer overflow
../.build/usr/lib/kevm/kframework/bin/krun: line 69: 62708 Aborted                 (core dumped) "$@"
[Error] Critical: Backend crashed during rewriting with exit code 134

```

**Comment by anvacaru** [comment]
I've managed to get past this issue by avoiding to use `padRightBytes`.

**Comment by ehildenb** [comment]
Won't fix, because no way we can allocate that many bytes.
