### ISSUE TITLE
Outer parsing is very slow on very large comments

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1967]
`kompile spec.k`
It should go past the outer parsing step.
If I remove the comments then it completes in less than one second.
[spec.zip](https://github.com/kframework/k/files/6473122/spec.zip)

Not sure how slow it is because I closed it after one minute.
Discovered by @virgil-serbanuta

**Comment by ehildenb** [comment]
Bubble comments are tracked explicitly for being able to track beginning/end points for bubbles (for location information).

Maybe our management of those bubble comments has some non-linear behavior somewhere when parsing comments (suspect is the JavaCC code).
