### ISSUE TITLE
ConstantFoldingTest.testFloat2String() fails because of locale

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#1969]
In Romania the decimals are separated by a comma en: `1.2` ro: `1,2`
This makes this assertion fail:
```
assertEquals("1.0000000000000001e-01p53x11", cf.STRING_float2string(FloatBuiltin.of(new BigFloat(0.1, BinaryMathContext.BINARY64), 11)));
```
We should have a way to force the backend or at least this test to use the English locale. 

Discovered by @virgil-serbanuta

**Comment by dwightguth** [comment]
Ah, good point. This could be tricky to fix though because I don't believe that the Java library we are using for floats has any explicit provisions for locales. You encountered this while running `mvn test`? We may need to simply set the default locale for unit tests in maven somehow. What are your thoughts on that?

**Comment by radumereuta** [comment]
That could fix maven, but it's still going to fail if I run it from my IDE.

I found this in the library:
```
    public String toString() {
        if (this.isInfinite() && this.sign()) {
            return "-Infinity";
        } else if (this.isInfinite()) {
            return "Infinity";
        } else {
            return this.isNaN() ? "NaN" : this.toString("%Re");
        }
    }

    public String toString(String format) {
        return mpfr.mpfr_asprintf(format, this.op);
    }
```
Could we force it to use EN locale somehow?

**Comment by radumereuta** [comment]
I tried adding:
```
<configuration>
    <argLine>-Duser.language=en -Duser.region=US</argLine>
</configuration>
```
then
```
<configuration>
        <systemPropertyVariables>
            <user.language>en</user.language>
            <user.region>GB</user.region>
        </systemPropertyVariables>
        <includes>
            <include>**/*Test.java</include>
        </includes>
        <forkMode>pertest</forkMode>
    </configuration>
```
Still fails.

**Comment by virgil-serbanuta** [comment]
Would this work? https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#setDefault%28java.util.Locale%29

**Comment by radumereuta** [comment]
> Would this work? https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#setDefault%28java.util.Locale%29

I tried it already. Didn't work.

**Comment by ehildenb** [comment]
The locale we need to set is in mpfr library, so setting it in the Java code won't work. If you set the correct environment variables instead, then the C code will pick it up correctly.

This can be set automatically for `mvn *`.
