### ISSUE TITLE
K Tutorial typos/clarifications/issues

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/k#1998]
I'm going through the new K tutorial and will use this issue to document findings per @ehildenb 's recommendation.

## lesson 2
* [x] missing word: "... as `banana.color` in the **same** directory ..."
* [x] I found the tutorial smoother after automating passing code to krun without an intermediate file. I'd suggest, immediately before the section header "Productions, Constructors, and Functions," adding "We could also run this program with `krun -cPGM='colorOf(Banana())'`."

## lesson 3
* [x] missing period after "semantics treats it specially"

* [x] lesson-03-d.k cannot kompile with the `--gen-bison-parser` flag. Attempting it produces:
```
[Warning] Inner Parser: Importing a module that is tagged as not being LR(1)
when using Bison's LR(1) parser generator: [SET, LIST]
[Error] Internal: bison returned nonzero exit code: 139
```

@dwightguth says:
"I tested that it works to have a definition that didn't import BOOL , so I assumed that it should work to generate a Bison grammar for such a definition, but actually, it turns out that MAP gets imported implicitly because of the implicit initial configuration in the DEFAULT-CONFIGURATION module"

## lesson 5

* [x] "Some example~~s~~ modules include..."

## lesson 6

* [x] misspelled "functions" after module C

## lesson 7

* [x] clarify praticality of side conditions:

When working with simple K definitions, a reader will wonder why
```
rule isPositive(I) => true requires I >Int 0
rule isPositive(_) => false [owise]
```
wouldn't be written as
```
rule isPositive(I) => I >Int 0
```
In fact, it could be. To better motivate side conditions I think it would be helpful if the first couple of example rules were not predicates, e.g building towards an example like this:
```
syntax Grade ::= A() | B() | F() // harsh school
               | gradeFrom(Int) [function]

rule gradeFrom(I) => A() requires I >Int 90
rule gradeFrom(I) => B() requires I >Int 80
rule gradeFrom(_) => F() [owise]
```

* [x] Additionally, it may help to clarify why side conditions on predicates can be better than inlining the condition. However, since this is the 1-basic section, maybe that should be left for later altogether.

ehildenb: 
"If you have a rule which looks like this:
```
rule SOME_PREDICATE(X, Y, Z) => SOME_REALLY_LARGE_TERM(X, Y, Z)
```
Then the haskell backend will apply the rule when SOME_PREDICATE is around, which may make your term unnecesarily large (and thus slower to reason about).
But if instead you have:
```
rule SOME_PREDICATE(X,Y,Z) => true requires SOME_REALLY_LARGE_TERM(X, Y, Z)
rule SOME_PREDICATE(X,Y,Z) => false [owise]
```
Then unless the Haskell backend can show explicitly that SOME_REALLY_LARGE_TERM(X, Y, Z) is either uniformly true or uniformly false, it will leave it unsimplified.

Then you can write lemmas directly about SOME_PREDICATE as needed."

* [x] No link to lesson 8

## lesson 8

----------------

I'll edit this issue as I continue working through the tutorial.

**Comment by rybla** [comment]
Overall I thought this was a great tutorial, coming from someone who was superficially exposed to K a few years ago. A few suggestions:

# lesson 05

- In *Basic module syntax*: the syntax for attributes for rules and modules is given, but without any explanation about what those attributes might be used for. I'd have appreciated a real example or two rather than just `module LESSON-05-B [attr1, attr2, attr3(value)]` to define syntax.
- In *Putting it all together > Exercise*: I am told to "modify the name of the `COLOROF` module", but I was confused at first whether the "module name" was the name of the file, the name after the `module` keyword, or both. I figured it out eventually, but could have been clearer.
