### ISSUE TITLE
[Bug] homebrew k package does not work on Big Sur

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#2019]
When you install the kframework homebrew package on Big Sur, `kompile` will sometimes fail with some weird error involving not being able to find the C standard library if you try to pass C files on the command line via `-ccopt`. This seems to be because the `llvm@8` homebrew package is old enough that it wasn't fixed in Big Sur to point to the correct include paths, which means it can't find some of the necessary headers. I tested and everything works fine with llvm 12, but Mojave can't build K with llvm 12 (some complex link-time errors that aren't probably worth trying to solve).

So I think what we need to do is just update the Jenkins Anka slave to use Big Sur instead of Mojave, fix up the release system as needed, and let people know we no longer support MacOS 10.

**Comment by ehildenb** [comment]
To have llvm@8 on Mojave, and llvm@12 on Big Sur, we would need separate homebrew packages, which would mean people would do something like `brew install k-sur` or `brew install k-mojave`. Probably not worth investigating.
