### ISSUE TITLE
[Error] Critical: failed to concatenate maps with common keys

### ISSUE THREAD

**Issue by nrryuya** [runtimeverification/k#202]
I got a `[Error] Critical: failed to concatenate maps with common keys:` in `gnosis` branch at [k: 57ad13d91283a9b7b3e0aa604236f1f27d4f7f25](https://github.com/kframework/k/tree/57ad13d91283a9b7b3e0aa604236f1f27d4f7f25).

### Command
- executed `make specs/erc20/transfer-success-2-spec.k.test` at the root directory of [this repo](https://github.com/LayerXcom/verified-vyper-contracts) (my project)
- this command executes `.build/k/k-distribution/target/release/k/bin/kprove -v -d .build/evm-semantics/.build/java -m VERIFICATION --z3-executable --z3-impl-timeout 500 specs/erc20/transfer-success-2-spec.k`
- The executed spec is the same with [the one in verified-smart-contracts](https://github.com/runtimeverification/verified-smart-contracts/blob/3b0095b98d507d47cbbb8c62f51e3a8b1866c5a4/erc20/vyper/vyper-erc20-spec.ini).

### Commit
- [k: 57ad13d91283a9b7b3e0aa604236f1f27d4f7f25](https://github.com/kframework/k/tree/57ad13d91283a9b7b3e0aa604236f1f27d4f7f25)
- [evm-semantics: 9a409babcd9b77a0f9a30f52350e4c5d46e6b086](https://github.com/kframework/evm-semantics/tree/9a409babcd9b77a0f9a30f52350e4c5d46e6b086)

This spec passed at the disappeared commit of k `e36d4ce05d85a8c1f8a237c2c88ff0a7ada5c9cd` with KEVM at the [commit: e6c4b961495768a429fcffaa81418472953c8568](https://github.com/kframework/evm-semantics/tree/e6c4b961495768a429fcffaa81418472953c8568) previously. I tried downgrading only KEVM to that commit but it still cause `[Error] Critical: failed to concatenate maps with common keys` so I guess it's about k side rather than kevm side and created issue here.

### Log
I pasted the whole log in [this gist](https://gist.github.com/nrryuya/3f8a210f814ed99a6f6794173cf51618).

```
[Error] Critical: failed to concatenate maps with common keys:
[(<acctID>(ACCT_ID_1388:Int),<account>(<acctID>(ACCT_ID_1388:Int),,
<balance>(_1196_1427:Int),, <code>(1),, <storage>(hash2(Int(#"3"),,
TO_ID_1389:Int) |-> BAL_FROM_1386:Int   _1197_1428:Map),,
<origStorage>(_1198_1429:Map),, <nonce>(_+Int_(_1199_1430:Int,,
Int(#"1")))),<account>(<acctID>(ACCT_ID_1388:Int),, <balance>(_1196_1427:Int),,
<code>(1),, <storage>(hash2(Int(#"3"),, TO_ID_1389:Int) |-> BAL_FROM_1386:Int  
_1197_1428:Map),, <origStorage>(_1198_1429:Map),, <nonce>(_1199_1430:Int)))]
  while evaluating function _AccountCellMap_
[Warning] Critical: execution phase: missing SMTLib translation for
#asByteStack (missing SMTLib translation for #asByteStack)
[Warning] Critical: execution phase: missing SMTLib translation for
#parseHexWord (missing SMTLib translation for #parseHexWord)
[Warning] Critical: execution phase: missing SMTLib translation for BALANCE_EVM
(missing SMTLib translation for BALANCE_EVM)
[Warning] Critical: execution phase: missing SMTLib translation for
EXTCODESIZE_EVM (missing SMTLib translation for EXTCODESIZE_EVM)
[Warning] Critical: execution phase: missing SMTLib translation for Keccak256
(missing SMTLib translation for Keccak256)
[Warning] Critical: execution phase: missing SMTLib translation for Map:lookup
(missing SMTLib translation for Map:lookup)
[Warning] Critical: execution phase: missing SMTLib translation for Set:in
(missing SMTLib translation for Set:in)
[Warning] Critical: execution phase: missing SMTLib translation for
_:__EVM-DATA (missing SMTLib translation for _:__EVM-DATA)
[Warning] Critical: execution phase: missing SMTLib translation for
_in_keys(_)_MAP (missing SMTLib translation for _in_keys(_)_MAP)
[Warning] Critical: execution phase: missing SMTLib translation for
_xorInt__INT (missing SMTLib translation for _xorInt__INT)
[Warning] Critical: execution phase: missing SMTLib translation for
lengthString (missing SMTLib translation for lengthString)
make: *** [specs/erc20/transfer-success-2-spec.k.test] Error 113
```

### About `#hashedLocation` for Vyper
In this case I targeted Vyper contract so I modified the `#hashedLocation` rule as follows with reference to [this commit in uniswap branch](https://github.com/kframework/evm-semantics/commit/81bcba1a73188942fdc34979c59ee7be7253ece9#diff-1ef0db86ab0e9570588bbd121f32a26d).
```
rule #hashedLocation("Vyper", BASE, OFFSET OFFSETS) => #hashedLocation("Vyper", keccakIntList(BASE OFFSET), OFFSETS)
```
I tried without this modification and still got `[Error] Critical: failed to concatenate maps with common keys` with slight difference ([gist](https://gist.github.com/nrryuya/3f8a210f814ed99a6f6794173cf51618#file-unmodified-edsl-erc20_transfer-success-2)).

**Comment by denis-bogdanas** [comment]
Based on error message looks like it's an error on the spec side. You have 2 <acctID>(ACCT_ID_1388:Int)... Can you post the specification?

**Comment by nrryuya** [comment]
@denis-bogdanas 
The executed `.k` file is [this gist](https://gist.github.com/nrryuya/3f8a210f814ed99a6f6794173cf51618#file-transfer-success-2-spec-k).

This is generated from [this .ini file](https://github.com/LayerXcom/verified-vyper-contracts/blob/master/erc20/erc20-spec.ini) which is the same with [the one in verified-smart-constacts](https://github.com/runtimeverification/verified-smart-contracts/blob/master/erc20/vyper/vyper-erc20-spec.ini).

**Comment by nrryuya** [comment]
I couldn't solve that problem but the issue disappeared at the latest files, k and kevm versions in [verified-smart-contracts](https://github.com/runtimeverification/verified-smart-contracts/commit/fea6e4e8dc3192667201168dd4767574672d0b93).

**Comment by denis-bogdanas** [comment]
Thanks for letting us know. They seem related to support for IMap - a new generalized form of Map which we use in newest project. Probably there was some mismatch between VSC and KEVM versions.
