### ISSUE TITLE
Refactor of `kast` to expose fast-paths

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2028]
- `kore-print` script which takes Kore -> ANY (if ANY is pretty, it uses fast `kprint`, otherwise slow `kast`).
- `kparse` script which takes ANY -> Kore (using Bison parser if it exists, otherwise falls back to `kast`).
- `kparse-gen` which generates bison parsers. Currently users are responsible for generating these as needed ahead of time.
- Exist `kast` is renamed to `kast-util`, and then new `kast` wrapper wraps up logic calling all subscripts.

**Comment by ehildenb** [comment]
Once we have a refactor of `kast` available as `kastx`, we should change this back: https://github.com/kframework/k/pull/2166

**Comment by radumereuta** [comment]
Create a new issue if we have more concerns. The first 3 items are done.
