### ISSUE TITLE
[Feature] [kompile] - Improvements to error messages

### ISSUE THREAD

**Issue by SchmErik** [runtimeverification/k#2064]
Description
========
There were several improvements that have been brought up in the slack conversation. This issue is created to discuss two improvements to the kompile error messages. These requests aren't urgent and aim to help improve user experience.

Include filename at the top line of error messages
------------------------------------------------------------------
When compiling files that contain the `requires` directive, there could be a compiler error in the file being required rather than the file that provided as the input file on the command line. In a setting where there are two files each with a module, the main file is supplied as the parameter to the `kompile` command.

Here is one file primary.k
```
requires "secondary.k"

module PRIMARY

  syntax Foo ::= "bar"

endmodule

```
Here is secondary.k
```
module SECONDARY

  syntax Foo ::= | "baz"

endmodule

```

kompiling primary.k resulting in the following error message:
```
$ kompile primary.k 
[Error] Outer Parser: Encountered "|".
Was expecting one of: ["non-assoc", <STRING>, <STRING_REGEX>, "(", "left",
"right", "List", "NeList", <UPPER_ID>, <LOWER_ID>, <NAT>, <UPPER_ID>, "List",
"NeList", <LOWER_ID>] (ParseException: Encountered " "|" "|"" at line 3, column
18.

Was expecting one of:

"non-assoc" ...
    <STRING> ...
    <STRING_REGEX> ...
    "(" ...
    "left" ...
    "right" ...
    "List" ...
    "NeList" ...
    <UPPER_ID> ...
    <LOWER_ID> ...
    <NAT> ...
    <UPPER_ID> ...
    "List" ...
    "NeList" ...
    <LOWER_ID> ...
    )
        Source(/home/erik/k/k-distribution/k-tutorial/1_basic/09_unparsing/secondary.k)
        Location(3,18,3,18)

```

When reading this error, the user sees `ParseException: Encountered " "|" "|"" at line 3, column 18.` at the top. However, the information regarding the filename can only be found at the bottom of the error message.  This partial information forces the user to constantly look at the end of the error message to find the filename. A more helpful error message would contain the file name like so: `ParseException: Encountered " "|" "|"" in secondary.k at line 3, column 18.` By doing so, the user can get more complete error location information. We may want to consider only printing the file name rather than the full file path so that message is easy to read.

Colorize the exception summary
-------------------------------------------------------
Colorizing exception summary can make it stand out from the rest of the messages.

**Comment by ehildenb** [comment]
Proposed experiments:

- Colorize first line (or first few lines) of error messages.
- Move source location to the lines immediately following the error subject header (before the message body), and include in the colorization.

Let's make this change, then take some screenshots of the changed version.

**Comment by SchmErik** [comment]
I was digging into this and decided to make several alterations as an experiement but realized that the following error message:
```
$ kompile primary.k 
[Error] Outer Parser: Encountered "|".
Was expecting one of: ["non-assoc", <STRING>, <STRING_REGEX>, "(", "left",
"right", "List", "NeList", <UPPER_ID>, <LOWER_ID>, <NAT>, <UPPER_ID>, "List",
"NeList", <LOWER_ID>] (ParseException: Encountered " "|" "|"" at line 3, column
18.

Was expecting one of:

"non-assoc" ...
    <STRING> ...
    <STRING_REGEX> ...
    "(" ...
    "left" ...
    "right" ...
    "List" ...
    "NeList" ...
    <UPPER_ID> ...
    <LOWER_ID> ...
    <NAT> ...
    <UPPER_ID> ...
    "List" ...
    "NeList" ...
    <LOWER_ID> ...
    )
        Source(/home/erik/k/k-distribution/k-tutorial/1_basic/09_unparsing/secondary.k)
        Location(3,18,3,18)
```
contains a duplicate message. Here's a message with the duplication removed:
```
$ kompile primary.k 
[Error] Outer Parser: ParseException: Encountered " "|" "|"" at line 3, column 18.

Was expecting one of:

"non-assoc" ...
    <STRING> ...
    <STRING_REGEX> ...
    "(" ...
    "left" ...
    "right" ...
    "List" ...
    "NeList" ...
    <UPPER_ID> ...
    <LOWER_ID> ...
    <NAT> ...
    <UPPER_ID> ...
    "List" ...
    "NeList" ...
    <LOWER_ID> ...

        Source(/home/erik/k/k-distribution/k-tutorial/1_basic/09_unparsing/secondary.k)
        Location(3,18,3,18)
```
It's possible that in some error paths, the ability to add more messages might be helpful but this scenario generates error messages that are redundant.

**Comment by ehildenb** [comment]
We'll add a flag to the exception handler which controls whether we print the inner exception. We'll default that flag to `true` (current behavior), and disable it for this message.

**Comment by ehildenb** [comment]
One thing we could think about is printing out the textual source with the source location information. In the example above, we would print out lines 1-5, which would show line 3 where the parse error is.

This would likely be too verbose if we did it for every error message with a location attached. Maybe for some specific error messages we could do this.

**Comment by SchmErik** [comment]
How about we put error location information at the top like so?
```
/home/erik/samps-k/secondary.k:3:18-3:18
[Error] Outer Parser: Encountered "|".
Was expecting one of: ["non-assoc", <STRING>, <STRING_REGEX>, "(", "left",
"right", "List", "NeList", <UPPER_ID>, <LOWER_ID>, <NAT>, <UPPER_ID>, "List",
"NeList", <LOWER_ID>]
```
The idea here is that the person using the tool will first get information on the location of the error and then understand what went wrong at that location. This format of error messages starting with location is very common among programming language tools and I have developed the habit of searching for location information first. We could also differentiate the first line by coloring or underlining the path..

**Comment by radumereuta** [comment]
@SchmErik please provide an example of how you want the error message to look.

**Comment by SchmErik** [comment]
I made a branch here: https://github.com/SchmErik/k/tree/error-msg-experiment-add-lines

### Example 1:

Here's a sample error message that works well.

**Code:**
```
requires "domains.md"

module TEST
    imports INT
    imports BOOL

    configuration <k> $PGM:Foo </k>

    syntax Foo ::= "a" | "b"
 // ------------------------
    rule <k> a => b ... </k> requires ?_ ==Int _
endmodule

```
**Error message:**
```
$ kompile test.k
[Error] Compiler: Found existential variable not supported by concrete backend.
        Source(/home/erik/samps-k/error/test.k)
        Location(11,39,11,41)
        |    rule <k> a => b ... </k> requires ?_ ==Int _
        |                                      ^~~
 
[Error] Compiler: Found variable _ on right hand side of rule, not bound on
left hand side. Did you mean "?_"?
        Source(/home/erik/samps-k/error/test.k)
        Location(11,48,11,49)
        |    rule <k> a => b ... </k> requires ?_ ==Int _
        |                                               ^~
 
[Error] Compiler: Had 2 structural errors.
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.

```

### Example 2:

However, not all messages point to the right token...

**Code:**
```
module CLAIMINDEF

    claim _ => .

endmodule
```
**Error message:**
```
$ kompile claimInDef.k
[Error] Compiler: Claims are not allowed in the definition.
        Source(/home/erik/k/k-distribution/tests/regression-new/checks/claimInDef.k)
        Location(5,11,5,17)
        |    claim _ => .
        |          ^~~~~~~
 
[Error] Compiler: Had 1 structural errors.
```

**Comment by SchmErik** [comment]
Here's an example of a multiline rule:
**Code:**
```
requires "domains.md"

module TEST
    imports INT
    imports BOOL

    configuration <k> $PGM:Foo </k>

    syntax Foo ::= "a" | "b"
 // ------------------------
    rule <k> a => b ... </k>
        requires ?_ ==Int _
endmodule
```
**Error message:**
```
$ kompile test.k 
[Error] Compiler: Found existential variable not supported by concrete backend.
        Source(/home/erik/samps-k/error/test.k)
        Location(12,18,12,20)
        |        requires ?_ ==Int _
        |                 ^~~
 
[Error] Compiler: Found variable _ on right hand side of rule, not bound on
left hand side. Did you mean "?_"?
        Source(/home/erik/samps-k/error/test.k)
        Location(12,27,12,28)
        |        requires ?_ ==Int _
        |                          ^~
 
[Error] Compiler: Had 2 structural errors.
```

**Comment by radumereuta** [comment]
What happens if the error message spans multiple lines?
Like an error that spans the entire sentence (like the claim rule above). Or an ambiguity error.
Check how other tools format such error messages. @Baltoli you have some idea about other libraries?
Test on long lines and many columns. The terminal windows is limited and we don't want to wrap around.

**Comment by Baltoli** [comment]
Found it - https://github.com/zesterer/ariadne. @SchmErik this is pretty comprehensive but might give you some inspiration for how people like these to look

**Comment by SchmErik** [comment]
> What happens if the error message spans multiple lines? Like an error that spans the entire sentence (like the claim rule above). Or an ambiguity error. Check how other tools format such error messages. @Baltoli you have some idea about other libraries? Test on long lines and many columns. The terminal windows is limited and we don't want to wrap around.

I did a little more work before the holiday break. Here's my progress so far for multiple lines:
**Source code**
```
requires "domains.md"

module TEST
    imports INT
    imports BOOL

    configuration <k> $PGM:Foo </k>

    syntax Foo ::= "a" | "b"
 // ------------------------
    rule <k> a => b ... </k>
        requires ?_ ==Int _


    claim _
          =>
           .
endmodule
```

**Error message**
```$ kompile test.k 
[Error] Compiler: Found existential variable not supported by concrete backend.
        Source(/home/erik/samps-k/error/test.k)
        Location(12,18,12,20)
        12 |        requires ?_ ==Int _
           .                 ^~~
 
[Error] Compiler: Found variable _ on right hand side of rule, not bound on
left hand side. Did you mean "?_"?
        Source(/home/erik/samps-k/error/test.k)
        Location(12,27,12,28)
        12 |        requires ?_ ==Int _
           .                          ^~
 
[Error] Compiler: Claims are not allowed in the definition.
        Source(/home/erik/samps-k/error/test.k)
        Location(15,11,17,13)
        15 |    claim _
           .          ^
        16 |          =>
           .          ~~
        17 |           .
           .           ~~
 
[Error] Compiler: Had 3 structural errors.
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```
I took the tool that @Baltoli suggested as inspiration.

**Comment by Baltoli** [comment]
These look really good, Erik. I recall a discussion on this before the break, but not what the outcome of it was - is there a reason that the spans include the space after the token:
```
?_
^~~
```

**Comment by SchmErik** [comment]
Thanks @Baltoli, the space is captured from the lexer/parser as a part of the sentence's location and the error message underlines where the location points to. I guess I could solve this in the error message generation but the root of the problem is the lexer/parser

**Comment by radumereuta** [comment]
The location information is designed to 'include' the next token so when you select something in your editor, the end location includes the entire term.
You should do a -1 correction at the end. (make sure it doesn't go less than 1, just in case we missed a spot somewhere)

**Comment by radumereuta** [comment]
```
[Error] Compiler: Claims are not allowed in the definition.
        Source(/home/erik/samps-k/error/test.k)
        Location(15,11,17,13)
           .          v~~~
        15 |    claim _
        16 |          =>
        17 |           .
           .         ~~^
```
If it's more than 3 lines, display only 3 and fill with ... the middle.
Consider omitting the dot in the beginning. Or replace it with vertical bar or *

**Comment by radumereuta** [comment]
Let's introduce this change under an option to keep the diff small.
After we are happy with the results we can make that the default.
