### ISSUE TITLE
Z3 captured errors should include location information about the context

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2066]
Type inference, in particular, should include some information about what rule it was trying to parse when it got the error message.

This is so we can better debug definitions or if there is something wrong with K it can be used to get a minimized example.

**Comment by ehildenb** [comment]
In particular, this error message https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/parser/inner/disambiguation/TypeInferencer.java#L801 gives no information about where it could be coming from.
