### ISSUE TITLE
[Bug] [kompile] - Fails with Z3 warning on simple configuration composition

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2069]
K Version
---------

```
% kompile --version
K version:    5.1.93
Build date:   Thu Jul 08 21:16:33 UTC 2021
% z3 --version
Z3 version 4.8.7 - 64 bit
% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

Description
-----------

Kompile will not handle a very simple configuration composition, where the cell-sorts of the sub-configurations are mentioned directly in the super-configuration module.

Input Files
-----------

File `web3.k`

```
requires "domains.md" 
 
module EVM 
    imports INT 
 
    configuration 
      <kevm> 
        <k> $PGM:Int </k> 
        <account> 0 </account> 
      </kevm> 
 
endmodule 
 
module WEB3 
    imports EVM 
 
    configuration 
      <kevm-client> 
        <kevm/> 
        <foo> $FOO:KItem </foo> 
      </kevm-client> 
 
    syntax AccountItem ::= AccountCell 
 // ---------------------------------- 
 
endmodule 
```

Reproduction Steps
------------------

```
% kompile web3.k --backend llvm --no-llvm-kompile --main-module WEB3 --syntax-module WEB3
[Error] Compiler: Had 1 parsing errors.
[Error] Internal: Unexpected result from z3: (error "line 35 column 13: unknown
constant SortAccountCell")
```

Expected Behavior
-----------------

Either this should `kompile` correctly, or the error message it outputs should be more informative about (i) the location of the problematic sentences, and (ii) what exactly the problem is.

**Comment by radumereuta** [comment]
Repeating some slack messages:
Most likely the regression stars here: https://github.com/kframework/k/commit/b9581a3bd4d970fc585bf6b9a977d62f765f7698

Before, we would generate the cell sorts in sequence, so module WEB3 would be able to see the cell sorts from EVM. This change allowed us to parse configs in parallel and skip generating some extra scanners for a small speed bump.

The simplest workaround is to declare the missing sort:
```
syntax AccountCell
```

The problem still persists if you mistype the sort. The checks we have in place are not going to give you a proper error message, and Z3 is going to crash in the same manner.

**Comment by ehildenb** [comment]
https://github.com/kframework/k/pull/1962 is where the regression starts.

Declaring the `AccountCell` sort now is an acceptable solution, it works.
