### ISSUE TITLE
Program verification in K using IMP

### ISSUE THREAD

**Issue by Qais87** [runtimeverification/k#207]
Hi,

I want to test the krun tool to verifiy the formal specification for the while loop from IMP.
I have read the paper "Marktoberdorf '16, NATO Science for Peace and Security. 2017" (pages
9-10). In the last section they write:
"...Then invoke the krun tool with the option -prove on the sum_spec.k file. It should return true..."

I have tried to prove that but I get error messages like this one:
C:\Users\Qais\Downloads\k\tutorial\1_k\2_imp\lesson_4>krun -prove sum_spec.k
**[Error] Critical: Dynamic parameter expected a value of the form a=b but
got:rove**

What does that mean? Help me

**Comment by dwightguth** [comment]
I believe these instructions are out of date. Try `kprove sum_spec.k`

**Comment by Qais87** [comment]
I did and I got this error:
C:\Users\Qais\Downloads\k\tutorial\1_k\2_imp\lesson_4>kprove sum_spec.k
**[Error] Critical: Unknown option: --backend**

**Comment by dwightguth** [comment]
You probably have an out of date version of k. Either update to the latest version of k, or it's possible that you might be able to get it to work with `krun --prove sum_spec.k sum.imp` (note the two hyphens)

**Comment by Juanpam** [comment]
@Qais87 Did you manage to fix this? I'm getting also a lot of errors when trying to make the formal verification of the program you mention. I already tried with the last @dwightguth suggestion and it throws some syntax errors on the added rule to prove. Is there any documentation about model checking or verification I'm missing? This is not discussed in the tutorial or any paper I have read.

**Comment by charlotte-Zch** [comment]
[Error] Critical: Unknown option: --prove (Unknown option: --prove)
@dwightguth I tried the krun --prove sum_spec.k sum.imp, still failed

**Comment by ehildenb** [comment]
You should be able to `kompile --backend haskell imp.k` on the IMP definition, and then `kprove sum-spec.k` after that to do verification. Note that we're no longer actively developing the Java backend, so please try the Haskell backend instead.

Please re-open if this is still an issue.
