### ISSUE TITLE
Process diagram for frontend/backend tools/components

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2073]
The idea would be that the main entry-points (krun|kast|kprove|kompile) would be at the top, in the middle would be intermediate tools (think `k-compile-search-pattern`, `krun-legacy`, `kparse`, `kore-print`, `kprint`, etc...), and then below that would be a blob which says "Java Frontend" with sub-blobs for the different components (eg. `Kompile.java`, `KProve.java`, `KPrint.java`, etc...), and below that wolud be the backends (eg. `llvm-kompile` from llvm backend, `kore-exec` from Haskell backend).

This would serve as documentation for the architecture, as well as giving a broad overview of our capabilities.

**Comment by SchmErik** [comment]
![image](https://user-images.githubusercontent.com/11355936/128223195-fe7039c3-571a-4129-8171-a1b19a3b0b34.png)
Here's a draft of the process diagram. I'm only starting out on this. My thought is that the primary audience would be familiar with diagrams that represent compiler pipelines so I thought of this process diagram where each "node" represents the format of the input and how it changes as each tool executes.

**Comment by SchmErik** [comment]
> The idea would be that the main entry-points (krun|kast|kprove|kompile) would be at the top, in the middle would be intermediate tools (think `k-compile-search-pattern`, `krun-legacy`, `kparse`, `kore-print`, `kprint`, etc...), and then below that would be a blob which says "Java Frontend" with sub-blobs for the different components (eg. `Kompile.java`, `KProve.java`, `KPrint.java`, etc...), and below that wolud be the backends (eg. `llvm-kompile` from llvm backend, `kore-exec` from Haskell backend).
> 
One option is to somehow embed links in the image so that you can click different parts of the image to go to the code implementing the step. The downside to this is that we would need to maintain the links to change with any potential filename changes. Another option is to more generically describe what the component does. I think the first option would help newcomers get started browsing the code base much more quickly than the latter option so it might be worth the potential cost to maintain the links..

**Comment by SchmErik** [comment]
@ehildenb will this process diagram be a part of a repository? If so, we may want to consider using a format that is not binary (like graphviz) so that each change would be small..

**Comment by dwightguth** [comment]
This is done. It's saved in our google drive right now. we can share the pdf with external collaborators if need be, but any employee of RV should be able to access it via the link.
