### ISSUE TITLE
Make sure we can run `kore-parser` and `kore-check-functions` on both backends

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2155]
There are some definitinos which are supported on LLVM backend and not haskell backend, which means `kore-parser` rejects them even though it's fine for LLVM backend. We should strive to run all the same checking tools on both backends, which means we need to identify those differences.

K-REFLECTION module is on example, K-IO module. Look for tests that exercise these in `regression-new` and see if `kore-parser` works on them.

**Comment by radumereuta** [comment]
Long term goal to have the same kore definition provided to both backends.
Meanwhile blocked on this: https://github.com/kframework/k/issues/2135

**Comment by radumereuta** [comment]
See: https://github.com/kframework/k/issues/1989
