### ISSUE TITLE
[Bug] [kompile] - does not report duplicate <k> cell declaration

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2171]
K Version
---------

```
K version:    5.1.165
Build date:   Fri Aug 27 00:41:16 UTC 2021
```

Description
-----------

Importing `DEFAULT-CONFIGURATION` and declaring your own `<k>` kompiles successfully, and produces weird results when both cells use the `$PGM` variable.

Input Files
-----------

File `test.k`:

```
module TEST-PRE
    imports DEFAULT-CONFIGURATION
    imports INT

    configuration <test> 0 </test>
endmodule

module TEST
    imports TEST-PRE

    configuration <k> $PGM:Int </k> <test/> 
                                                      
endmodule     
```

Reproduction Steps
------------------

Call `kompile` on the definition:

```
% kompile --backend llvm test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

No error output. Inspect `test-kompiled/configVars.sh`:

```
% cat test-kompiled/configVars.sh 
#!/usr/bin/env bash

declaredConfigVar_PGM='Int'
declaredConfigVar_PGM='KItem'
declaredConfigVars=(
    'PGM'
    'PGM'
)
```

Expected Behavior
-----------------

`kompile` should complain that I've redeclared the `<k>` cell. Or perhaps we should detect the double-declaration of the `$PGM` variable.

**Comment by radumereuta** [comment]
Questions:
1. How would such a restriction work with https://github.com/kframework/k/pull/2083 ?
2. You should be allowed to use $PGM multiple times in a configuration.
This doesn't look right though:
```
declaredConfigVars=(
    'PGM'
    'PGM'
)
```

**Comment by radumereuta** [comment]
Dwight: there is a check in generate sentences from config that checks if a cell already exists. We should remove that check.

**Comment by SchmErik** [comment]
notes for myself: the underlying issue here is that there are multiple initKCell rules. We need to add a check to ensure that a configuration cell only has one initialization rule associated with that cell.
