### ISSUE TITLE
Better error message using `--search` with LLVM backend without having kompiled with `--enable-search`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2173]
Currently the LLVM backend with `--search` crashes with a horrible error instead of saying "You must pass `--enable-search` to `kompile` to be able to use `krun --search` with the LLVM backend". This should be improved.

See https://runtimeverification.slack.com/archives/C8DMP61DW/p1630379321002400

**Comment by radumereuta** [comment]
This should be simple. In the krun script we need to check if `--enable-search` was provided to kompile which creates an additional file (search) in the -kompiled directory.
