### ISSUE TITLE
kompile --version should include git revision

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2180]
When built locally kompile --version looks something like this:
```
$ kompile --version
K version:    5.1.0
Build date:   Fri Sep 03 21:34:37 EEST 2021
```
Which is wrong. Only the CI knows the exact version number, and the local build puts a 0 instead.
Since we introduced the version number this caused problems with local builds when reporting errors.
I think it should always include git revision. No matter what the version number says.

**Comment by nishantjr** [comment]
Using something like:

```
$ git describe --tags --dirty
v5.1.94-29-ge99248f83a-dirty
```

may be useful for generating this message.

THe `29` is the number of commits since the last tag. `dirty` indicates that there have been local uncommitted changes.

**Comment by Baltoli** [comment]
#2181 is an initial attempt to implement this, but I'm blocked on an issue with `.git` directories on Jenkins that causes the build to fail. The implementation seems fine locally but breaks the CI unfortunately
