### ISSUE TITLE
`#unparseKore` hook

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2183]
We currently have `#parseKore`, which can take a Kore term and parse it into the current runtime, but we need a counterpart call `#unparseKore`:

```
syntax {Sort} String ::= #unparseKore ( Sort ) [function, hook(KREFLECTION.unparseKORE)]
```

Currently the only way to do this is via several calls to `#system` to invoke `kast` on the pretty-output version of the string.

**Comment by dwightguth** [comment]
Are you talking about taking a term and printing kore, or are you talking about taking a term and pretty-printing? The former can probably be added, the latter was deliberately not added as a design decision so that the llvm backend doesn't depend on the frontend.

**Comment by malturki** [comment]
It's the former: taking a term and producing its kore as a string. Currently this is needed in the Algorand project. We basically need to produce as part of the final configuration in a krun execution the kore representation of some terms (of different sorts, including cell sorts). For instance, I'd like to write a rule of the form:
```
rule <k> #serializeAsKORE() => . ... </k>
       <static> S </static>
       <kore> _ => #unparseKORE(<static> S </static>) </kore>
```

**Comment by dwightguth** [comment]
This is probably something either Bruce or Erik could take on as a task to teach them about how hooks work in the LLVM backend. The place to put the hook is going to be in `runtime/io/parseKORE.cpp`. You will want to create a production in `domains.md` in the frontend in the `K-REFLECTION` module that looks like: `syntax {Sort} String ::= #printKORE(Sort) [function, hook(KREFLECTION.printKORE)]`, then add an extern "C" function `hook_KREFLECTION_printKORE` to the cpp file I mentioned above. It should return a `SortString` and take a `block *` as argument. The hook itself should be able to simply call `printConfigurationToString` and return its result.

**Comment by radumereuta** [comment]
For things that are constructors and user defined sorts shouldn't be a problem.
Things that are domain values and builtin collections should be wrapped in a fresh constructor.

**Comment by ehildenb** [comment]
This should be implementable. We _probably_ will have a restriction that we _cannot_ print domain values or builtin collections directly (eg. Int, Map, List, Bool, Float, ...).

So we can offer a wrapper hook like this, which handles putting any domain values in a fresh constructor:

```
syntax K ::= #wrapBuiltin ( K ) [private]
syntax String { Sort } ::= #printKore( Sort ) [function]
                         | #unparseKore( Sort ) [function, hook(KREFLECTION.unparseKore), private]

rule #printKore(K) => #unparseKore(K) [owise]
rule #printKore(K:Int) => #unparsreKore(#wrapBuiltin(K))
rule #printKore(K:Map) => #unparseKore(#wrapBuiltin(K))
...
```

We could also think about having `#unparseKore` remove the top-level `#wrapBuiltin` if it appears, so that users don't need to worry about removing that if it's present.

**Comment by radumereuta** [comment]
We should be aware that `#parseKore` has some limitations: runtimeverification/llvm-backend#579
