### ISSUE TITLE
Add a TLA+ backend

### ISSUE THREAD

**Issue by pron** [runtimeverification/k#219]
TLA+ is a powerful, and relatively widely used, specification language based on the Temporal Logic of Actions (TLA) and a formal set theory. It supports concurrent behaviors, arbitrary nondeterminism, refinement relations and liveness properties. Its tools include a powerful model checker and an interactive proof assistant. 

A TLA+ backend for k would allow using the TLC model checker to verify arbitrary program properties, as well as to check whether a program written in a language defined in k refines a high level TLA+  specification.

**Comment by ehildenb** [comment]
While this would be nice, it's not on the roadmap anywhere. Please re-open if someone plans to do development for this.
