### ISSUE TITLE
[Bug] [kompile|kprove] - kompile/kprove should throw an error for smt-lemma rules that can't be encoded

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#2193]
K Version
---------

Tell us what version of K you are using.

Example:

```
$ kompile --version
K version:    5.1.0
Build date:   Fri Sep 03 22:19:38 EEST 2021
```

Description
-----------

SMT Lemmas that can't be encoded because they use function symbols without `smtlib` attribute should produce an error.

Input Files
-----------

File: `tmp.k`

```
module TMP
  imports BOOL
  imports INT
  imports K-EQUAL

  syntax KItem ::= a(Int)
  syntax Int ::= f(Int)  [function, functional, smtlib(asdf)]

  rule f(0) => 0
  rule f(_) => 1  [owise]

  rule f(_) >Int -1 => true  [simplification, smt-lemma]

  rule a(X) => .K requires f(X) >=Int -1

endmodule
```

File: `proof-tmp.k`
```
module PROOF-TMP
  imports TMP

  claim a(_X) => .K

endmodule
```

Reproduction Steps
------------------

1. Check that the proof passes:
```
kompile tmp.k --backend haskell && kprove proof-tmp.k
```

2. Remove the `smtlib` attribute for `f`:

3. The proof no longer passes:
```
kompile tmp.k --backend haskell && kprove proof-tmp.k
```

Expected Behavior
-----------------

Either `kompile` or `kprove` should complain that the `smt-lemma` rule can't be sent to the SMT solver.

**Comment by ehildenb** [comment]
We need to make sure this check happens for `kompile` I believe, and should confirm that it works for `kprovex`.

**Comment by radumereuta** [comment]
The front end needs to collect all the smt-lemma symbols and make sure they have smtlib or smt-hook attributes. If not, throw an error.
https://runtimeverification.slack.com/archives/C7E701MFG/p1631039118145300
