### ISSUE TITLE
Possible duplication of effort in kompile frontend checks and kore-parser checks

### ISSUE THREAD

**Issue by SchmErik** [runtimeverification/k#2206]
K Version
---------
```
$ kompile --version
K version:    v5.1.186-0-g72a68abb7c
```

Description
----------
I am currently working on #2119. This issue talks about how kompile misses a syntactic check and generates malformed kore output. When running `kompile` with the haskell backend, the malformed kore syntax is detected and an error is generated.

Here is a simple example of a .k definition that exhibits this behavior:
```
module TEST
  syntax T ::= "a" [token]
  syntax T ::= R // token sorts should not include subsorts so this is not allowed

  syntax R ::= "b" [token]
endmodule
```
running `kompile test.k --backend haskell` on this code produces the following output:
```
$ kompile test.k --backend haskell
Error:
  module 'TEST':
  axiom declaration:
    Hooked sorts may not have subsorts.
    Hooked sort:
    SortT{}
    Its subsort:
    SortR{}
    Location in the Kore file:
    "definition.kore 176:128"
    Location in the original K file: 


[Error] Critical: Haskell backend reported errors validating compiled
definition.
Examine output to see errors.
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

This specific case is not checked in the kompile frontend and mal-formed KORE is generated. This error occurs because there is a check that is implemented in the haskell backend. Issue #2119 showcases a similar behavior between the tools. Before I proceed with #2119 and the test case in this example, I think it would be a good idea to have a discussion so that we are all of the same page about implementing checks.

Concern on Implementing kompile frontend checks
------------------------------------------------
I'm hesitant to write code for these checks in the frontend because implementing this seems to duplicate the analysis done in `kore-parser`. If we implement these checks, it would likely mean that we need the front-end checks to mirror all parsing checks done in `kore-parser` to also be done in the kompile frontend. Duplicating the analysis passes could slow down kompile. One nice advantage of checking the AST in the front end is that we have the ability to generate error messages that involve K so the messages are generally more readable.

Questions
-------------
If we run `kompile` using the haskell backend, is it acceptable to see errors from `kore-parser`? In otherwords, should the frontend do as much analysis as possible to rule out bad k/kore syntax?
Should we think about ways to consolidate checks and `kore-parser` analysis?

**Comment by radumereuta** [comment]
In this specific case we still want to have a separate check in the front end for better error messages.
We may not want to use kore-parser for bot backends because they might impose different restrictions.

**Comment by SchmErik** [comment]
thanks for the discussion. Closing
