### ISSUE TITLE
[Bug] [kompile] - macro for record production is applied to itself

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2217]
K Version
---------

Tell us what version of K you are using.

Example:

```
$ kompile --version
K version:    v5.1.188-4-g6f2b343a8f
Build date:   Tue Sep 21 16:51:08 UTC 2021
```

Description
-----------

A `macro` rule for a record production leads to `kompile` trying to attempt macro expansion on the macro itself.

Input Files
-----------

File `test.k`:

```
requires "domains.md"

module TEST
    imports INT

    configuration <k> $PGM:Int </k>

    syntax Int ::= f ( a: Int, b: Int )
 // -----------------------------------
    rule f(X, Y) => X +Int Y [macro]

endmodule
```

Reproduction Steps
------------------

Kompile the definition:

```
$ kompile --backend haskell test.k --main-module TEST
[Error] Compiler: Illegal function symbol _+Int_ on LHS of rule. Consider
adding `simplification` attribute to the rule if this is intended.
        Source(/home/dev/src/k/test.k)
        Location(10,21,10,29)
[Error] Compiler: Had 1 structural errors after macro expansion.
  while executing phase "expand macros" on sentence at
        <none>
        <none>
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```

Expected Behavior
-----------------

I expect either (i) the kompiler gives us a better error, saying "macros are not allowed for record productions", or (ii) it handles this correctly, and does not attempt to apply the macro to itself.

**Comment by radumereuta** [comment]
The macro is being applied on a rule generated by `GenerateSortProjections`.
```
rule `project:f(_,_)_TEST_Int_Int_Int:a`(`f(_,_)_TEST_Int_Int_Int`(K0,K1))=>K0
   requires #token("true","Bool")
   ensures  #token("true","Bool") 
```
after applying macro
```
rule `project:f(_,_)_TEST_Int_Int_Int:a`(`_+Int_`(K0,K1))=>K0
   requires #token("true","Bool")
   ensures  #token("true","Bool") 
```

**Comment by radumereuta** [comment]
We need a helper function that tells if a symbol is a macro. Something attached to a Module.
Don't generate the sort projections if the symbol is a macro.
