### ISSUE TITLE
KProve does not pass `--branching-allowed` through to haskell backend, only java

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2224]
The option `--branching-allowed` is there to allow limiting the number of concurrent execution paths. This can be useful for terminating proofs early.

Currently, this option is only passed through to the Java backend. But the haskell backend supports the `--breadth` option, so if `--branching-allowed N` is present on the `kprove` or `kprovex` command-line arguments, we should pass `--breadth N` to the Haskell backend.

This should probably work for krun as well I guess, but that's less important/useful.

Currently we have to do `--haskell-backend-command="kore-exec --breadth N"`

**Comment by SchmErik** [comment]
@ehildenb do you know of any existing test cases that exercises this for the java backend? I think it would be a great exercise for me to come up with a test case but I thought I'd check with you to see if you had any ideas. I grepped the k-distribution directory in the repo for "branching-allowed" and the command didn't find anything

**Comment by ehildenb** [comment]
I don't know any test cases, but here is a simple one:

```
module VERIFICATION
    imports MAP
    imports BOOL

    syntax Foo ::= "a" | "b" | "c" | "d"

    configuration <k> $PGM:Foo </k>

    rule <k> a => b </k>
    rule <k> a => c </k>
    rule <k> b => d </k>
    rule <k> c => d </k>

endmodule

module TEST-SPEC
    imports VERIFICATION

    claim <k> a => d </k>

endmodule
```

Then `kprove --branches-allowed 1 test.k --spec-module TEST-SPEC` should have a counterexample which looks something like `<k> b </k> #Or <k> c </k>`.

**Comment by SchmErik** [comment]
I see that `--branching-allowed` is implemented in a file called `JavaExecutionOptions.java`. @ehildenb, are there other options that this class has that we want to use in the haskell backend? I don't know the haskell backend very well but I think it would be good to take a little time to think about other options that could be passed through the haskell backend as well. I'll start on this task but let me know if you think of other options that might be useful/compatible

**Comment by ehildenb** [comment]
Nope, I'm pretty sure all the other options there are Java backend specific. Though I guess `--skip-backend` could be removed and `--dry-run` could serve the same purpose? Not sure.
