### ISSUE TITLE
Bug: parsing kast expressions yields KList ambiguity

### ISSUE THREAD

**Issue by mhhf** [runtimeverification/k#223]
Posting a dublicate of [this issue](https://github.com/kframework/evm-semantics/issues/286) here, since it might be a k-related issue.

I'm struggling parsing a kast expression in prefix form, in particular the following one:
```
<gas> VGas => `#if_#then_#else_#fi_K-EQUAL` ( `notBool_` ( `_==K_` ( ABI_x, #token("0", "Int") ) ), `_-Int__INT` ( VGas, #token("20491", "Int") ), `_-Int__INT` ( VGas, #token("5491", "Int") ) ) </gas>
```

Parsing it yields an ambiguity (full error [here](https://gist.githubusercontent.com/mhhf/dd371105a1cd10559d0e24c8906f46b8/raw/3873ca57a7a84cc66616229491a2081e89d30ce2/gistfile1.txt)):
```
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax KList ::= KList "," KList
...
2: syntax KList ::= KList "," KList
```

It is because KList  (defined in k repo) and _,__EVM-DATA, typedArgs, eventArgs (defined in evm-semantics) have all the same list delimiters `,`. 
A solution would either redefine KList delimiter as `,,` or redefine the evm-semantics List delimiter to be different from `,`.
@dwightguth @ehildenb @daejunpark

**Comment by ehildenb** [comment]
The structure of domains.md and kast.md has changed significantly. If this is still an issue, please open a new issue with reproduction steps following the bug report template.
