### ISSUE TITLE
Kompiling 1_simple/1_untyped with OCaml backend

### ISSUE THREAD

**Issue by ltbinsbe** [runtimeverification/k#224]
Attempted the following commands with the current latest version (fad06744fd41d624e942f120517aef263686fdff):

```
../../../../bin/kompile --backend ocaml simple-untyped.k 
40 states, 1247 transitions, table size 5228 bytes
File "realdef.ml", line 2487, characters 81-82:
Error: Syntax error: ')' expected
File "realdef.ml", line 2487, characters 61-62:
Error: This '(' might be unmatched
[Error] Critical: ocamlopt returned nonzero exit code: 2
Examine output to see errors.
[Warning] Compiler: missing entry for hook BAG.concat
[Warning] Compiler: missing entry for hook BAG.element
[Warning] Compiler: missing entry for hook BAG.unit
```

I tried 3_fun/1_untyped/1_environment with success:

```
../../../../../bin/kompile --backend ocaml fun-untyped.k 
40 states, 1247 transitions, table size 5228 bytes
```

**Comment by ltbinsbe** [comment]
Tried with PATH variable set up correctly as well

**Comment by dwightguth** [comment]
This will not work with the current version of the simple semantics. If you want it to work, you will have to modify simple-untyped.k to add `type="Set"` to each of the cells in the configuration declaration marked with `multiplicity="*"`.

**Comment by ehildenb** [comment]
Closing due to age. Feel free to ask more questions about how to _use_ K in our riot room: https://riot.im/app/#/room/#k:matrix.org
