### ISSUE TITLE
`orBool` / `andBool` parsing ambiguity

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2240]
Are parsing priorities set up for the `orBool` and `andBool` K productions from the `BOOL` module? This module produces an ambiguity, when I would expect it to resolve to `A orBool (B andBool C)`.

```k
module TEST
  imports BOOL

  syntax Bool ::= test(Bool, Bool, Bool) [function]

  rule test(A, B, C) => A orBool B andBool C
endmodule
```

**Comment by radumereuta** [comment]
No, we don't: https://github.com/kframework/k/blob/master/k-distribution/include/kframework/builtin/domains.md?plain=1#L823

**Comment by dwightguth** [comment]
This is actually deliberate behavior so that people can't write unintended behaviors by mistake. We could probably make it non associative instead of an ambiguity, but you would then just get a different error message.
