### ISSUE TITLE
Type inference is very slow because of z3

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2247]
When parsing KEVM claims the time spent doing type inference is larger than usual. For example:
```
kprovex --directory tests/specs/erc20/verification/haskell tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k -I /home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework -I /home/radu/work/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/kframework --profile-rule-parsing timings/tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k.log --format-failures -v --dry-run
```
z3-4.8.7: Parse spec modules [1/1 rules]                               = 30.434s
26305 /home/radu/work/evm-semantics/tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k:8   parse: 287 typeInf:25476
z3-4.8.11: killed after ~5 minutes

Parsing takes 287ms, and type inference 25s. When I switch to z3-4.8.11 it takes a huge amount of time. I killed it after ~5 minutes.
Times are collected using `--verbose` and `--profile-rule-parsing`.

**Comment by ehildenb** [comment]
Two things that I think could help with this:

- Add an option to print out the z3 queries sent when doing type inference so we can inspect them.
- Timeout Z3 at 10s (it's commonly accepted that if Z3 doesn't come back in a few seconds, it will take forever), and if we do have to kill Z3 during type-inference, print out which variables that are having trouble being inferred so that we can make the rule faster. We can also allow the user to set this timeout, so that if I want to optimize the rules in a given semantics I can set it very low and annotate the sorts which need it to speed up parsing on that definition.

**Comment by Baltoli** [comment]
This seems to still be a problem using a `HEAD` build of Z3, unfortunately (4.8.13).

**Comment by radumereuta** [comment]
I will try to extract a query from Z3 and do a git bisect to see where the regression started.
Although, I'm not happy with the performance before that either.
I will post my findings when I know more for sure. Might take a while though.

**Comment by radumereuta** [comment]
@Baltoli could you update us on the z3 bug now that we improved the runtime?!

**Comment by radumereuta** [comment]
I used git bisect on z3 and found the commit that makes everything slow for the type inference: https://github.com/Z3Prover/z3/commit/b1606487f08cec8d950be078ac31881fc36a7bea
I used this test from KEVM to test, and before I was getting **8s** to do rule parsing after it takes **44s**.
```
kprovex --directory tests/specs/erc20/verification/haskell tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k -I /home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework -I /home/radu/work/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/kframework --profile-rule-parsing timings/tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k.log --format-failures -v --dry-run
```
[typeInf.smt2.txt](https://github.com/kframework/k/files/7411425/typeInf.smt2.txt)
I've run only the z3 query^ and before it took **2.8s**, after **15s**.
This rule tries multiple solutions before it reaches the final one, but I think the order is the same. It's just slower.

**Comment by ehildenb** [comment]
@radumereuta does this performance regression exist on Z3 latest version? If so, you should ping NikolajBjorner (github id) and ask if they want a bug report.

**Comment by radumereuta** [comment]
Yes, latest version is equally slow. We can talk at the tech updates today.

**Comment by ehildenb** [comment]
Ok, let's ping @NikolajBjorner. Is this an example you want a test for?

**Comment by NikolajBjorner** [comment]
Do you have bandwidth to run it in a profiler? Or maybe Grigore has as he is absent from Dagstuhl "duties" (that include food and wine). If you run this example with -v:10 you can see some areas where it starts taking time. If previous versions worked, then bisection can point to something, e.g., this looks like a maxsat problem when I run it and it seems to spend time in lns even though it is not enabled by default. So: profile for hotspots, bisect for regressions.

**Comment by NikolajBjorner** [comment]
OK, you did the bisect and it correctly points to code in cmd_context where time take place. Verbose output and profiling will confirm it. Overhead is introduced when tracking non-recursive function definitions for model construction. It has some O(n^2) performance bug that is exercised thanks to your definition. It is a code optimization bug that should involve rewriting some of the pre-processing for function definitions (that are not recursive).

**Comment by NikolajBjorner** [comment]
The main overhead is not where I first expected it to be. It shows up as the model gets post-processed (compressed) when the expressions are evaluated. This post-processing is expensive and not relevant to evaluation in this case.

**Comment by NikolajBjorner** [comment]
fixed 4dad41416136ab421be54b4ee56fd17a9c6a20cd

**Comment by radumereuta** [comment]
I can confirm that all our tests are back to normal speed.
Thank you @NikolajBjorner for such a prompt reply.

**Comment by ehildenb** [comment]
@radumereuta is this particular issue still a problem? I thought we had sorted out a lot of the type inference slowness by now.

**Comment by radumereuta** [comment]
The C semantisc takes 30s to parse all the rules on a 32threads machine. The slowest rule takes 8s to do type inference.
No longer horrible, but we could still improve this by a lot.
I marked it as low priority.
We can close it if people are happy with this state. It's not such a big issue since we have caching that works pretty well.
So repeated calls to kompile don't suffer that much.
But calls to kprove do.
