### ISSUE TITLE
[Bug] [kprove|kprovex] - Expecting failure when claim contains existential in LHS

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#2264]
K Version
---------

```
$ kompile --version
K version:    v5.1.226-0-g70dd86c5c
Build date:   Tue Oct 12 15:34:16 EEST 2021
```

Description
-----------

Our encoding of claims is the following:
```
∀ X . φ(X) → mod ∃ Y . ψ(X, Y)
```
where `X` and `Y` are sets of variables and `mod` is a reachability modality.

Therefore, it is incorrect to have existentially quantified variables on the LHS of the claim. This should be caught by the frontend and explained to the user. Right now, the frontend doesn't complain at all.

Input Files
-----------

File test.k
```
module TEST
    imports INT

endmodule
```

File test-spec.k
```
module TEST-SPEC
    imports TEST

    claim <k> ?X:Int => . </k>

endmodule
```

Reproduction Steps
------------------

```
$ kompile --backend haskell test.k
```
The behavior is the same for both `kprove` and `kprovex`:
```
$ kprove test-spec.k
```
```
$ kprovex test-spec.k
```
The frontend succeeds resulting in the backend being run (the result of the backend is not important).

Expected Behavior
-----------------

I expect the frontend to throw an error signalling that `X` is existentially quantified, and that the LHS is not allowed to contain existentially quantified variables.

**Comment by ehildenb** [comment]
Note that this means that the `requires` clause _also_ should not contain existentials (so let's make sure to add a test for that as well @SchmErik).
