### ISSUE TITLE
[Bug] [kompile] - [Error] Critical: llvm-kompile returned nonzero exit code: 1

### ISSUE THREAD

**Issue by loiclizzy** [runtimeverification/k#2273]
An error occurs when compiling a tutorial code

**Environment**: macOS Cataline (v 10.15.7)
**K version:**
- K version:    5.1.223
- Build date:   Sun Oct 10 23:29:05 CEST 2021

**File: test.k**

     module TEST

       syntax Color ::= Yellow() | Blue()
       syntax Fruit ::= Banana() | Blueberry()
       syntax Color ::= colorOf(Fruit)	[function]

       rule colorOf(Banana()) => Yellow()
       rule colorOf(Blueberry()) => Blue()

      endmodule

**Output**
`$ kompile test.k`
`ld: unknown option: -platform_version`
`clang-12: error: linker command failed with exit code 1 (use -v to see invocation)`
`[Error] Critical: llvm-kompile returned nonzero exit code: 1`
`Examine output to see errors.`
`[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in`
`definition.  Use --syntax-module to specify one. Using TEST as default.`

**Comment by dwightguth** [comment]
I'm not sure that we support Catalina anymore. You probably need to use an older version of k, or else upgrade to Big Sur.

**Comment by niconaus** [comment]
I have the same issue. I'm running MacOS 12.1, and K version 5.3.47, build Tue May 17 19:27:28 EDT 2022. Any solution for this issue?

EDIT: Output:

`$ kompile lesson-02-a.k `
`ld: warning: directory not found for option '-L/usr/local/opt/libffi/lib'`
`ld: library not found for -liconv`
`clang-13: error: linker command failed with exit code 1 (use -v to see invocation)`
`[Error] Critical: llvm-kompile returned nonzero exit code: 1`
`Examine output to see errors.`
`[Warning] Compiler: Could not find main syntax module with name`
`LESSON-02-A-SYNTAX in definition.  Use --syntax-module to specify one. Using
LESSON-02-A as default.`

**Comment by dwightguth** [comment]
This looks like a different issue actually. Are you on an M1 mac? Do you have the libffi and libiconv packages installed?

**Comment by niconaus** [comment]
> This looks like a different issue actually. Are you on an M1 mac? Do you have the libffi and libiconv packages installed?

Yes, you are correct. I have installed libffi, and there was an issue where libiconv was not found, but it was installed, which I have now resolved. But now lncurses is not found. Is this a common issue with the K Framework? I am not on M1, I have a regular "old-school" Intel i5 MacBook Pro.

**Comment by dwightguth** [comment]
@niconaus are you still affected by this?

**Comment by niconaus** [comment]
Thank you for the follow-up! I was not able to resolve this issue, and have moved to a virtual machine to run the K framework. I'll give it another shot in a couple of days and report my findings.

**Comment by niconaus** [comment]
I re-ran the installation command "brew install kframework/k/kframework", and this time, no library-not-found errors. After struggling a bit to get the xcode command line tools to play nice ("xcocebuild -runFirstLaunch" was a very helpful command), everything is working perfectly now.

**Comment by Baltoli** [comment]
Closing this as the original issue is for an old version of macOS that we don't support any more, and @niconaus is no longer affected. Feel free to reopen if it becomes an issue again.
