### ISSUE TITLE
[KIP] - Apple Silicon support

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2278]
Motivation
----------

We currently offer Mac support for K, but not on Apple Silicon. As their product lineup removes legacy x86 macs, we need to work on support for K on macos/ARM.

#2276 summarises some of the early issues with AS support.

Potential Alternatives/Work-arounds
-----------------------------------

There isn't much alternative, other than dropping support for macOS entirely.

Testing Approach
----------------

For the moment, I'm using a single ARM mac mini through macstadium to prototype the necessary changes. In the future we'll need to work out how best to include an AS machine into our CI infrastructure.

**Comment by dwightguth** [comment]
As far as CI goes, I intend to replace our use of the Mac server and Anka with GitHub Actions as soon as I get the time. I can only assume that at some point, GitHub will start offering an ARM Mac GitHub Actions runner. We can probably wait until then to implement the release process, and tell people to build k from source in the meantime.

**Comment by Baltoli** [comment]
They currently seem to be tracking for a 2022 release of an Apple Silicon environment, per [this thread](https://github.com/actions/virtual-environments/issues/2187). Supporting source builds but not releases on AS until then seems like a reasonable compromise.

**Comment by radumereuta** [comment]
Look into different output formats. Just to narrow down the code path that fails.
Look into valgrind.

**Comment by Baltoli** [comment]
First blocking issue is https://github.com/kframework/llvm-backend/issues/445 - appears to be some kind of stack corruption bug in our generated code on ARM64 macos.

Looking into building the backend on ARM64 Linux to see if I can reproduce the same bug in an environment where Valgrind is available.

**Comment by Baltoli** [comment]
Once PRs https://github.com/kframework/llvm-backend/pull/446 and https://github.com/kframework/llvm-backend/pull/443 are merged, the LLVM backend will support compilation for Apple Silicon and I'll move on to the other parts of the toolchain.

**Comment by Baltoli** [comment]
The Haskell backend should support Apple Silicon without much work, though I haven't closed the loop to run the integration tests yet. https://github.com/kframework/kore/pull/2893 adds documentation for the additional stack options that are required to get a working copy of `ghc`.

This will require a change to K to allow the requisite options to be passed through to `stack` when building the Haskell backend.

**Comment by Baltoli** [comment]
I can build a working version of the [`mpfr_java`](https://github.com/kframework/mpfr-java) library on ARM macos. However, it fails unit tests (presumably either a change in MPFR from upstream - confirm the version we expect). Once this is versioned and uploaded to our maven repo, we should be able to use the `mpfr` bindings.

**Comment by Baltoli** [comment]
It seems like some Java dependencies that rely on native code will need to be updated to newer versions that properly support Apple Silicon (for example, [here](https://github.com/kframework/k/issues/2276#issuecomment-947126681) @acassimiro identifies an issue with [`JANSI`](https://github.com/fusesource/jansi)).

I'll work on updating these dependencies properly.

**Comment by Baltoli** [comment]
More on the availability of GitHub actions for Apple Silicon in [this issue](https://github.com/actions/runner/issues/805); the gist of the problem is that the .NET release GH use to run actions doesn't yet support AS properly.

If it were to become an issue for us sooner than the next 6-12 months, there seem to be plenty of hacky workarounds. Further ahead than that, it's likely we'll get some kind of official support.

**Comment by Baltoli** [comment]
The MPFR library now has support for building on Apple Silicon; once https://github.com/kframework/mpfr-java/pull/12 is merged I'll be able to get a new version of the dependency deployed to our Maven repo.

**Comment by Baltoli** [comment]
Finally tracked down the bug with Jansi - the root problem seems to be Jline bundling an incompatible version. Working on updating both at once.

**Comment by Baltoli** [comment]
Closed by #2286
