### ISSUE TITLE
[KIP] - Give a proper error message if the user forgets to use the `[token]`

### ISSUE THREAD

**Issue by Robert42** [runtimeverification/k#2281]
K Version
---------

```
$ kompile --version
K version:    5.1.230
Build date:   Tue Oct 19 12:09:42 CEST 2021
```

Description
-----------

When I define a token, then I need to use the `[token]` attribute.
If I don't, I get a confusing `std::map` exception during runtime:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
/usr/bin/kore-print: line 31: 57203 Aborted                 (core dumped) "$@"
```

Input Files
-----------

```
// foo.k

module FOO-SYNTAX
  syntax Range ::= r"[a-z]" // missing [token] attribute
endmodule

module FOO
  imports FOO-SYNTAX
endmodule
```

Reproduction Steps
------------------

```
kompile foo.k
krun -cPGM='x'
```

Expected Behavior
-----------------

A clear and concise error message during kompile. Like *regular expressions are only allowed when followed by a `[token]` attribute or when using `syntax lexical`*

**Comment by Robert42** [comment]
Feel free to swap the *bug* label with *kip*. I've figured out the mistake on my part while filling out the *bug* template and forgot after finding the solution that I had the option fill out an improvement proposal instead.

**Comment by radumereuta** [comment]
Two possible solutions come to mind:
1. use a library that tries to extract a string from this regex that we can use to pretty print
2. require a `format` attribute which tells the pretty printer directly how to represent that production.

**Comment by radumereuta** [comment]
Maybe the second variant is better.
We can force the user to provide this format attribute with an error check.
