### ISSUE TITLE
Lift kprovex restriction to allow simplification rules in proofs

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2287]
@ana-pantilie if we put simplification rules in spec.kore, does the haskell backend support that?
If not, how hard it would be? kprovex managed to avoid some bugs we had in kprove, but with added limitations which can be annoying.
definition.kore is expensive to generate for each proof so we want to avoid doing that.

**Comment by ana-pantilie** [comment]
I was unsure about this, so I tested it out. After generating the `definition.kore` with `kompile` and the `spec.kore` with `kprovex`, I manually modified them to include a kore simplification rule. I ran the backend directly, and it didn't complain about the one in `spec.kore`, but it didn't even attempt to apply it. The one in `definition.kore` got attempted and applied.

I did some digging, and I finally found the reason for this: it seems like the only thing we do with the spec module is extract the claims from it, discarding anything else. I guess we could just "move" everything else to the definition module, which I don't think would be a big change. I'm a bit concerned though if moving them would break syntactical validation in some cases, but maybe if the extra definitions are restricted to being simplification rules, then we won't have any problems.
