### ISSUE TITLE
Track downstream projects and their dependencies

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2303]
It's hard to keep track of how many semantics we have and their dependencies on K.

It would be great if we can have a page where we can view everything at a glance.

This page could be just a simple list/tree, where you can click on each project and you can see a list of dependencies, and for each dependency the number of commits behind, and time since the last update.

We can then set up a testing schedule to check which updates pass or if modifications are needed. Maybe once a week, during the weekend when there isn't that much load on CI.

I'm not sure where this page should be hosted but I like how this Jenkins page looks: https://office.runtimeverification.com/jenkins/

**Comment by radumereuta** [comment]
@ehildenb I would like to hear your thoughts on this.

**Comment by ehildenb** [comment]
Updates are tested as soon as possible basically right now. The autoupdater takes care of that. So as soon as releases of upstream dependencies are made, the downstream projects various `_update-deps_*` PRs are updated.

We could try to make a visualizer for this, but it sounds like a lot of work. I guess I could see if the data is retrievable with my current scripts and then ask @shd101wyy if we can make a private page on RV website (login via github) to show that status.

What about more targeted messages in slack channels? Totally different approach, but we could have the bot send messages when it sees PRs for updates that aren't passing to the appropriate channel on slack.

**Comment by radumereuta** [comment]
Messages on slack could work. Although if there are too many they might get ignored.
So maybe a digest would work better.

**Comment by radumereuta** [comment]
We have a list that keeps track of something like this: https://github.com/runtimeverification/devops/blob/master/deps/kframework/k
