### ISSUE TITLE
[CI] Eliminate all warnings and compare stdout

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2316]
Currently, in regression tests, we have many warnings printed that are not being tested for.

- [ ] scala and java code warnings
- [ ] kprove syntax in spec module
- [ ] macro on rules instead of syntax (loads)
- [ ] could not find main syntax module

**Comment by ehildenb** [comment]
Some notes:

- Leave any warnings due by the Java backend alone (instead of fixing them) unless the fix is easy/trivial.
- Get incremental progress merged.

**Comment by radumereuta** [comment]
First stage is done. regression-new is the first line of defense and now it's free of errors.
Moving this issue to backlog and we can come back to it when we're going to remove the java backend.

**Comment by Baltoli** [comment]
Java backend is gone now.
