### ISSUE TITLE
[Bug] [kprove|kprovex] Existential variable is allowed on LHS, but shouldn't

### ISSUE THREAD

**Issue by david-k** [runtimeverification/k#2324]
K Version
---------

```
$ kompile --version
K version:    v5.1.250-0-g07918e142
Build date:   Sat Nov 06 22:18:15 CET 2021
```

Description
-----------

The frontend should produce an error if an existential appears on the LHS, see <https://github.com/kframework/k/issues/2264>. However, this is not always the case.

Consider the following definition:
```
module TEST
  imports K-EQUAL
  imports BOOL

  syntax Program ::= "stateA" | "stateB"
  syntax Bool ::= isDone(Program) [function]

  rule stateA => stateB

  rule isDone(stateB) => true
  rule isDone(_) => false [owise]
endmodule
```

Then the following claim is successfully proven in both `kprove` and `kprovex`:
```
module TEST-SPEC
  imports TEST

  claim <k> stateA => ?STATE </k>
    requires isDone(?STATE)
endmodule

```
However, since existentials are not allowed on the LHS, this should produce an error.

Output of `kprovex`:
```
kore-exec: [357438] Warning (WarnTrivialClaim):
    Claim proven without rewriting at: /home/david/Documents/RV/k-snippets/prove-nonexistential/test-spec.k:13:9-14:28
#Top
```

**Comment by radumereuta** [comment]
@SchmErik you worked on #2280
When you find the time, can you investigate this issue?

**Comment by SchmErik** [comment]
@radumereuta I see that you added the `?_` on this line about a year ago:  https://github.com/kframework/k/blob/800875f9ff45d40dec72c1a88dc16eb56bd08ec6/k-distribution/tests/regression-new/bisimulation/examples/program-equivalence/imp-lambda/simple-spec.k#L46
was this unintentional? I have a fix to check requires for an existential variables and it's generating an error on this line. What is the solution here? I'm able to get rid of the kompile error by removing the two `?_` from this line but I'm not sure if this is correct...

**Comment by SchmErik** [comment]
I found a similar issue with https://github.com/kframework/k/blob/800875f9ff45d40dec72c1a88dc16eb56bd08ec6/k-distribution/tests/regression-new/spec-rule-application/def02-spec.k#L13
