### ISSUE TITLE
[Bug] [kprove] - Michelson LQT TOKEN TRANSFER PROXY Test Regression

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/k#2331]
## Test Regression Information

The Michelson semantics has not been updated for a long time because some kprove tests would fail on newer versions of K.
In order to update the K submodule of K-Michelson, a few tests were disabled on CI.
We want to fix and re-enable these tests.
This issue contains information about how to run the tests (both the K versions and Michelson versions).

Here is the version information:

Prev K Submodule Commit/Version: bf17ff178 (v5.1.64)
Prev Michelson Commit (HEAD^): runtimeverification/michelson-semantics@ea0a99c81faddb1df39ac9cbc89a87269653a9e4

Curr K Submodule Commit/Version: b725ebd75 (v5.2.4)
Curr Michelson master Commit (HEAD): runtimeverification/michelson-semantics@d4b9cc89d

The test in question can be run on either Michelson commit by doing the following:

```
git clone https://github.com/runtimeverification/michelson-semantics/
cd michelson-semantics
git checkout <version-number>
git submodule update --init --recursive -- ext/k
make deps-k build-lqt
make lqt-prove_LQT-TOKEN-TRANSFER-PROXY-SPEC
```

In order to more easily test K-Michelson against both versions of K, I recommend checking out the michelson-semantics repo into two separate git worktrees.

## Additional Info

None

**Comment by ehildenb** [comment]
Closing as duplicate: https://github.com/runtimeverification/k/issues/2326
