### ISSUE TITLE
[Bug] [kompile] - Java backend, problem with macros

### ISSUE THREAD

**Issue by vasil-sd** [runtimeverification/k#2342]
K Version
---------

K was built from git repo, commit is 97358b0

```
$ kompile --version
K version:    v5.2.13-0-g97358b032
Build date:   Mon Nov 22 12:58:35 MSK 2021
```

Description
-----------

Java backend has problem with macros, but llvm and haskel have not.

Input Files
-----------

```
module BUG
  imports DOMAINS

  syntax KResult ::= Bool

  syntax Stmt ::= "var" Exp ";"
                | "var" Exps ";" [macro-rec, avoid]

  syntax Exp ::= Id "[" Exp "]"
  syntax Exps ::= List{Exp, ","}
  syntax Stmt ::=  Exp ";"
  syntax Stmt ::= Stmt Stmt [right]

  rule var E1:Exp, E2:Exp, Es:Exps; => var E1; var E2, Es;

  context var _:Id[HOLE];

endmodule
```

Reproduction Steps
------------------

```
$ kompile --backend java  --syntax-module BUG bug.k
Error] Compiler: Cannot compute macros with side conditions.
  while executing phase "expand macros" on sentence at
        Source(bug.k)
        Location(16,11,16,26)
        Source(bug.k)
        Location(16,11,16,26)
$
```

Expected Behavior
-----------------

Haskel and llvm backends are ok.

```
$ kompile --backend haskell  --syntax-module BUG bug.k
$
```

```
$ kompile --backend llvm  --syntax-module BUG bug.k
$
```

**Comment by SchmErik** [comment]
Looks like there's something strange going on with the macro propagation for the java backend. When running kompile with the java backend, I see that it tries to propagate the `macro-rec` label to line 16 which is this code here: `context var _:Id[HOLE];` I'm going to keep looking at this...

**Comment by SchmErik** [comment]
In the example that's been provided here, kompiling with java backend produces different klabels than the llvm/haskell backends and this is causing the `macro-rec` labels to be placed on different sentences.

**Compiling the example using the java backend**

- The productions `"var" Exp ";"` and `"var" Exps ";" [macro-rec, avoid]` both have the klabel `var_;_BUG`

- `context var _:Id[HOLE];` and `rule var E1:Exp, E2:Exp, Es:Exps; => var E1; var E2, Es;` both have LHS that have the klabel `var_;_BUG`

This means that the `macro-rec` label on the production gets propagated to both the `context` and the `rule`. Kompile is complains that `macro-rec` on 

**Compiling the example using llvm/haskell backends**
- the production `"var" Exps ";" [macro-rec, avoid]` has a klabel `var_;_BUG_Stmt_Exps`
- the production `"var" Exp ";"` has a klabel `var_;_BUG_Stmt_Exp`
- The rule `rule var E1:Exp, E2:Exp, Es:Exps; => var E1; var E2, Es;` has an LHS with the klabel var_;_BUG_Stmt_Exp**s**
- `context var _:Id[HOLE];` is a rule with a LHS with the klabel  `var_;_BUG_Stmt_Exp`
So the macro-rec label doesn't get propagated to the `context` rule.

**Conclusion**
This issue stems from the behavior in the java backend that generates klabels with less information than the llvm/haskell backend. I'm not sure what the correct solution so we will discuss this internally and get back to you. In the meanwhile, if you want to get this to work on the java backend, place the `macro-rec` label on the rule for now.

**Comment by radumereuta** [comment]
Not actively developing the java backend. Closing this for now.
