### ISSUE TITLE
Kore variable name encoding discussion

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2356]
Right now `encodeStringToAlphanumeric` and `decodeKoreString` are not implemented properly.
let's discuss in the meeting what is the best approach here since we would like the kore encoding to be somewhat readable.

`'Unds'V'Unds'9` -> `_V_9`
`'QuesUnds'0` -> `?_0`

**Comment by dwightguth** [comment]
https://github.com/kframework/llvm-backend/blob/master/lib/ast/AST.cpp#L10

**Comment by radumereuta** [comment]
This code path is not doing what we expect. Those dashes do appear in some cases.
We need to do integration test with llvm and haskell backends.
Since that table is used in multiple tools, we should have that table in a single file (maybe json).
