### ISSUE TITLE
KEVM proof takes a really long time to parse

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2364]
The following KEVM PR adds a proof that takes about 120s to parse altogether on my machine, with about 90s spent in Z3: https://github.com/kframework/evm-semantics/pull/1169

Steps to reproduce (clone that branch, and update submodules):

```
make deps RELEASE=true
make tests/specs/examples/long-parse-time-spec.k.prove TEST_OPTIONS=--verbose
```

**Comment by ehildenb** [comment]
BTW, I'm using Z3 4.8.13

**Comment by radumereuta** [comment]
Can confirm. The same happens with Z3 4.8.7
`82982 /home/radu/work/evm-semantics/tests/specs/examples/long-parse-time-spec.k:16   parse: 134 typeInf:82595`
I'm going to prioritize work on making the type inferencer faster. It seems to be a bottleneck in development for several semantics.
This is a subtask of: #2247
