### ISSUE TITLE
[Bug] [kompile] - Kompile generates a broken parser_PGM link

### ISSUE THREAD

**Issue by IljaZakharov** [runtimeverification/k#2365]
K Version
---------
K version:    v5.2.21-16-g3d65e6392
Build date:   Mon Dec 06 12:08:25 MSK 2021

Description
-----------

The kompile command generates a broken parser_PGM link on Ubuntu 20.04. 

Input Files
-----------

I used the lesson-03-d.k file from the lesson 3 of [tutorial](https://github.com/kframework/k/tree/master/k-distribution/k-tutorial/1_basic/03_parsing#brackets).

Reproduction Steps
------------------

Run the following command for a lesson-03-d.k file from the K tutorial to reproduce the issue:
`kompile --gen-bison-parser lesson-03-d.k`

Expected Behavior
-----------------

The `lesson-03-d-kompiled/parser_PGM` symlink should point to `lesson-03-d-kompiled/parser_KItem_LESSON-03-D`.

**Comment by dwightguth** [comment]
I cannot reproduce this on my machine, which runs Ubuntu 20.04. Can you please provide an exact K file you used to reproduce this, and an exact sequence of shell commands? I also need to know the results of `java -version`.

**Comment by IljaZakharov** [comment]
Sure, please, find the detailed description below.

The input file: [lesson-03-d.zip](https://github.com/kframework/k/files/7701899/lesson-03-d.zip)
My java version:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

The path to K binary files is: `~/src/k/k-distribution/target/release/k/bin`
The input file is placed in `~/workspace/tutorial/lesson 3/bug/`. 
I run the following command in the directory given above:
`kompile --gen-bison-parser lesson-03-d.k`

**Comment by dwightguth** [comment]
This appears to be because of a bug in java.nio.file.Path.relativize on Java 8. I would suggest installing Java 11 and this error should be fixed. I am currently exploring what exactly to do with our codebase in response to this bug, but my personal preference would simply to be to end support for Java 8, so I suggest you upgrade.

**Comment by IljaZakharov** [comment]
Yes, it works perfectly with Java 11.
