### ISSUE TITLE
[Bug] [krun] - kore-print crash

### ISSUE THREAD

**Issue by IljaZakharov** [runtimeverification/k#2374]
K Version
---------
K version:    v5.2.21-19-g04cec62cc-dirty
Build date:   Thu Dec 09 18:00:33 MSK 2021

Description
-----------
*krun* crashes with the following error:

```
/home/zakharov/rv/k/k-distribution/target/release/k/bin/kore-print: line 31: 34161 Aborted                 (core dumped) "$@"
```

Input Files
----------- 

The module is:
```k
module EXC1
  imports BOOL

  syntax Stmt ::= "{" Stmt "}" [color(red), format(%1%i%n%2%d%n%3)] 
                | "{" "}" [color(red), format(%1%2)]
                > right:
                  Stmt Stmt [format(%1%n%2)]
                | "if" "(" Bool ")" Stmt [colors(blue,red,red), format(%1 %2%3%4 %5)]
                | "if" "(" Bool ")" Stmt "else" Stmt [avoid, colors(blue,red,red,blue), format(%1 %2%c%3%r%4 %5 %6 %7)]
endmodule
````
The program I am trying to interpret:

```
if (true) {
  if (true) {}
  if (false) {}
  if (true) {
    if (false) {} else {}
  } else {
    if (false) {}
  }
}
```

Reproduction Steps
------------------

The crash happens when I add *%c* and *%r%* expressions. Everything works smoothly without them.

Expected Behavior
-----------------

Either a normal termination or error message is expected.

**Comment by radumereuta** [comment]
This should be an error in the front end.
We need to update the check for colors: https://github.com/kframework/k/pull/2358
This example specifies 4 colors instead of 5.
