### ISSUE TITLE
Add more checks to K frontend

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#239]
* [x] Check that the left-hand side of any function definition rule is a function-like pattern.
* [x] Check that no two productions with the `symbol` attribute have the same `klabel` attribute or the name of any builtin symbol in KORE.
* [ ] Check that collection patterns are valid.
* [x] Check that module names are unique.
* [ ] Check that the configuration declaration does not refer to functions requiring context.
* [x] Check that hooked sorts do not declare constructors
* [ ] Check that hooks are declared correctly.
* [ ] ~Check that parametric functions are not used since they are not supported yet (only hooks).~
---
* [ ] Check that an ensures clause is either #True, true, or contains at least one free variable.
* [x] Check that the user does not declare productions of sort K that are not functions.
* [x] Warning if the user extends the isSort predicates (except KResult)
* [x] Check that rule labels are unique.
* [x] Check that axioms do not contain function symbols on lhs (except for at the top)
* [x] Check that bracket attribute is used correctly. #1764 
* [ ] Check that contexts don't contain rewrites outside of K cell or rewrites whose LHS is not a HOLE or whose RHS does not contain a HOLE
* [ ] Check that contexts either mention no cells or a k cell.
* [ ] Check that the BOOL module is imported by the main module of the definition
* [ ] Check that the user doesn't import any modules in kast.k except BASIC-K

**Comment by denis-bogdanas** [comment]
Check that a function symbol cannot be used if it was not declared. I've seen cases when this doesn't trigger kompilation error.

**Comment by dwightguth** [comment]
There is definitely a check that the user doesn't use klabels or productions that weren't declared anywhere, do you have an example where this is failing?

**Comment by denis-bogdanas** [comment]
I don't remember the context, it only happens in specific situations. When I'll encounter this issue again I'll post an example.

**Comment by hjorthjort** [comment]
A more helpful inner parser would go a long way. For example, if I accidentally screw up a closing cell in the configuration, like so

```
<foo> 0 <foo>
```

the error can look something like this:

```
[Error] Compiler: Had 215 parsing errors.
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/home/hjort/code/wasm/ewasm-semantics/deps/wasm-semantics/.build/defn/llvm/wasm.k)
	Location(19,24,19,25)
[Error] Inner Parser: Scanner error: unexpected character sequence '/'.
	Source(/home/hjort/code/wasm/ewasm-semantics/deps/wasm-semantics/./.build/defn/llvm/test.k)
	Location(112,65,112,66)
[Error] Inner Parser: Scanner error: unexpected character sequence '/'.
	Source(/home/hjort/code/wasm/ewasm-semantics/deps/wasm-semantics/./.build/defn/llvm/test.k)
	Location(116,70,116,71)
...
```

If I misspell a sort name the error points me to a later part of the line:

```
rule ( module OID:OptionaId DEFNS ) => ...
```

Above an `l` is missing, easy to miss. Error message:

```
Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected token 'DEFNS'.
	Source(/home/hjort/code/wasm/ewasm-semantics/deps/wasm-semantics/.build/defn/llvm/wasm.k)
	Location(1512,37,1512,42)
make: *** [Makefile:114: .build/defn/llvm/test-kompiled/interpreter] Error 113
```

------

I find these kinds of error messages are common. They describe how the system failed internally rather than try to point at plausible mistakes. 

I find these are no big deal after you get used to K and know what to look for and when a rule is malformed, but for someone starting out they are super annoying because they misdirect attention and don't really teach you anything about what you should be doing when you are unsure yourself. I remember quite a lot of time being spent when I just started with K struggling to understand why my programs didn't kompile correctly.

**Comment by dwightguth** [comment]
I have been aware of the issue when the configuration fails to parse for some time and just never got around to fixing it. Fortunately, there is an easy fix; simply don't parse any rules if there are configurations that didn't parse.

This second issue, with the error message not being very informative, I am interested in investigating, but you will have to give me a minimal example because there is some interaction between different productions that is causing the behavior you see.

**Comment by radumereuta** [comment]
Check that parametric functions are not used since they are not supported yet (only hooks).
This example makes llvm-kompile to crash with Segmentation fault. (for documentation purposes)
```
module TEST
  imports STRING
  imports K-REFLECTION
  syntax S1 ::= "inits1"
  syntax S2 ::= "inits2"
  syntax {S} S ::= f(String) [function]
  rule f(S) => #parseKORE(S) // this fails
  configuration <k> inits1 </k>
  rule inits1 => f("\\dv{SortS1}(\"s1\")")
  rule inits2 => f("\\dv{SortS2}(\"s2\")")
endmodule
```

**Comment by Baltoli** [comment]
Closing this as there's been no meaningful update in 4 years.
