### ISSUE TITLE
[Bug] - Incorrect version reported on `master` checkouts of K

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2391]
K Version
---------

Any version newer than 5.2.21.

Description
-----------

See https://github.com/kframework/k/issues/2384 for an example.

The logic which determines the K version was dependent on the version tags being on the `master` branch. But we switched to having the release tag on the `release` branch, which is based on the master branch. So currently, our approach walks backwards towards the last tag on the master branch, which was 5.2.21.

Input Files
-----------

No input files needed.

Reproduction Steps
------------------

Clone K, build it, and run `kompile --version`.

```
git clone 'https://github.com/kframework/k'
cd k
git submodule update --init --recursive
mvn package -DskipTests
./k-distribution/target/release/k/bin/kompile --version
```

Expected Behavior
-----------------

Instead, we should walk backwards from the `release` branch, and use the newest tag that has a commit ancestor commit to the current commit.

**Comment by shd101wyy** [comment]
Please ignore this comment. For testing GitHub API only
