### ISSUE TITLE
[KIP] - Improvements to build & test infrastructure

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2414]
This issue is an index of potential improvements we could make to the K build and test infrastructure.

* [**Separate krun and check**](https://github.com/kframework/k/issues/2414#issuecomment-1021339859)

Some relevant issues / PRs / discussion from other projects:

* **Testing**:
    * [Use LLVM `lit` to test LLVM backend](https://github.com/kframework/llvm-backend/pull/466)
    * [Use LLVM `lit` to test C semantics](https://github.com/runtimeverification/c-semantics/pull/441)
* **Build systems**:
    * [KNinja](https://github.com/nishantjr/kninja) from @nishantjr 
    * [Michelson KNinja setup](https://raw.githubusercontent.com/runtimeverification/michelson-semantics/kninja/build)
* **General discussion on Slack:**
    * [Build systems, makefiles](https://runtimeverification.slack.com/archives/CC360GUTG/p1639493801316000)
    * [Pipefail](https://runtimeverification.slack.com/archives/C7E701MFG/p1643123434171900)

**Comment by Baltoli** [comment]
## Separate `krun` and `check`

For example, we can have `KRUN_ALLOW_FAILURE = false`.
Then each recipe can instead always have `PIPEFAIL` turned on, and we can change the `krun` recipe to look something like:
```
CHECK = diff -R

krun:
    (cat ... || true) | $(KRUN) ... > $(OUTPUT) || $(KRUN_ALLOW_FAILURE)
    $(CHECK) $(OUTPUT) $(EXPECTED)
```

This change in structure allows us to set `KRUN_ALLOW_FAILURE` if we're expecting a stuck configuration, and then still run `CHECK`. It also allows just setting `CHECK=cp` to update results, instead of messing with weird piping.

But basically instead of piping into `CHECK`, just have that be a separate step that also needs to pass. That makes the recipes a bit easier to read to, and also makes it easier to pinpoint where failure happened. Specifically, is it the `krun` step that failed, or the `check` step that failed? Currently, we only can know if `check` step failed. In your approach, we can know that `krun || check` failed, but not which.

(_from @ehildenb [on Slack](https://runtimeverification.slack.com/archives/C7E701MFG/p1643123664172700?thread_ts=1643123434.171900&cid=C7E701MFG)_)

**Comment by ehildenb** [comment]
Related: https://github.com/runtimeverification/pyk/issues/30

**Comment by Baltoli** [comment]
We're starting to standardise on Pyk-based `kdist` etc. so I think this can probably be closed.
