### ISSUE TITLE
Fix release and tags

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2423]
Currently we have a problem with the docker container.
We need to make sure we install `make` in the docker container.

**Comment by DHARUNKUMAR7** [comment]
Hi I am interested in working on this issue help me to get started

**Comment by radumereuta** [comment]
First attempt: https://github.com/runtimeverification/k/pull/2424
Doesn't seem to fix the problem.

**Comment by Baltoli** [comment]
Yep. Looking into this in more detail just now

**Comment by Baltoli** [comment]
Closed by #2427
