### ISSUE TITLE
[Draft] Alternative ways for passing spec to kprovex 

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2429]
Currently, `kprovex` requires the spec to be proved to be written to file in pretty format. When scripting the prover using `pyk`, this is inconvenient, as

- the AST for the spec has to be unparsed, which requires a custom unparser for each language, and is a source for bugs;
- the unparsed spec has to be written to file, which introduces side effects and additional complexity;
- the unparsed spec will be parsed again, which is inefficient (especially if many easy claims are passed to the prover).

There are two features that have to be implemented to solve this issue:

- Let `kprovex` read the spec from `stdin`, e.g. if the positional argument `-` is passed to it.
- Let `kprovex` read the spec directly in json format, e.g. with a flag `--input {pretty | json}`.

**Comment by ehildenb** [comment]
This will require that we audit the data-structures used in pyk and those in the frontend and make sure they have the same meaning and fields.

It should be the case, because they both serialize/deserialize through the JSON representation, but it would be good to check.

**Comment by tothtamas28** [comment]
> This will require that we audit the data-structures used in pyk and those in the frontend and make sure they have the same meaning and fields.

Created issue: https://github.com/runtimeverification/k/issues/2453

**Comment by gtrepta** [comment]
What is the term in the spec json expected to be, `KFlatModule` or `KDefinition`?

I noticed `--emit-json-spec` returns a `KFlatModule`, so I started hacking the prover to accept it in `ProofDefinitionBuilder.build`. I ran into a problem though, after running `FlatModule.toModules` on the parsed flat module, a step where `Kompile.structuralChecks` gets called fails with these errors:
```
[Error] Compiler: Symbol isBool is not unique. Previously defined as: syntax
Bool ::= "isBool" "(" K ")" [function, functional, predicate(Bool)]
[Error] Compiler: Symbol isK is not unique. Previously defined as: syntax Bool
::= "isK" "(" K ")" [function, functional, predicate(K)]
[Error] Compiler: Symbol isKItem is not unique. Previously defined as: syntax
Bool ::= "isKItem" "(" K ")" [function, functional, predicate(KItem)]
[Error] Compiler: Symbol project:Bool is not unique. Previously defined as:
syntax Bool ::= "project:Bool" "(" K ")" [function, projection]
[Error] Compiler: Symbol project:K is not unique. Previously defined as: syntax
K ::= "project:K" "(" K ")" [function, projection]
[Error] Compiler: Symbol project:KItem is not unique. Previously defined as:
syntax KItem ::= "project:KItem" "(" K ")" [function, projection]
```

I'm guessing that there's either an issue with the implementation of `FlatModule.toModules` or that there's a required step after calling it that I'm unaware of. Unless the spec is expected as a `KDefinition` I don't see a way without resolving this `FlatModule` problem.

**Comment by radumereuta** [comment]
Try to see if this fails with this branch: https://github.com/runtimeverification/k/pull/2642

**Comment by ehildenb** [comment]
I was planning on passing in `KFlatModule`

**Comment by radumereuta** [comment]
No longer a priority since we have the JSON RPC

**Comment by radumereuta** [comment]
Obsolete.
