### ISSUE TITLE
[Bug] [kompile|krun]- llvm backend crash when krun functions with no evaluator

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/k#2446]
K Version
---------

```
$ kompile --version
```
```
K version:    v5.2.85-0-gcba885f37-dirty
Build date:   Wed Feb 16 08:15:01 AEDT 2022
```
Description
-----------

The llvm backend is crashing if you define a function with no rules to evaluate it.

Input Files
-----------
File name: foo.k
File content:
```
module FOO
   syntax Foo ::= foo() [function]
   syntax KItem ::= Foo
endmodule
```
testing example in a file <a.foo>:
```
foo()
```
Reproduction Steps
------------------
file <foo.k> and <a.foo> under the same folder.
run commands as follows:
```
$kompile foo.k
$krun a.foo
```

Expected Behavior
-----------------
Everette expects "Frontend catches that there are no evaluators for function symbol foo() at kompilation time."
Well, I would expect an error message after ```krun``` with "No evaluator was give for functions". I guess this error message should not appear when ```krun --output kast a.foo```.

**Comment by ehildenb** [comment]
Note that we have `no-evaluators` attribute for specifying that a `function` symbol has no rules, so we could check that every function symbol has rules, and error out unless the user also supplies `no-evaluators`.

**Comment by ehildenb** [comment]
The LLVM backend should give a better error message at `krun`, but we don't need to restrict this at `kompile` time.

At the very least, it could print out the unevaluated function itself instead of crashing.

In this case it should print `foo()` as a stuck function.

**Comment by radumereuta** [comment]
This requires too much time to get right.
I think the error message returned by the backend should suffice for now.
Please reopen if it is a problem in the future.
