### ISSUE TITLE
Missing Table of Contents in Tutorial

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/k#2463]
Everett asked me to copy this here from Slack. Related to #1655.

The tutorial at https://kframework.org/k-distribution/k-tutorial/ does not have a useful table of contents. I know there are things I want to refer to in there but I have to spend quite a while finding them.

**Comment by radumereuta** [comment]
One thing that I find helpful is a _one page_ viewing option. It makes it easy to search for things. Shouldn't be that hard to automate something like this.

**Comment by ehildenb** [comment]
@shd101wyy can we generate the ToC for the k-tutorial instead of writing it? How easy is that for you?

Also, is it possible to make a one-page view of it? Perhaps as a PDF that is viewed in browser? Or just as HTML viewed in browser?

How hard are each of these tasks?

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/k/pull/2629

**Comment by Baltoli** [comment]
https://kframework.org/k-distribution/k-tutorial/ - this seems to be fixed now.
