### ISSUE TITLE
[Bug] [kompile] - Bison parser for `Bytes` in `BYTES-SYNTAX` is incorrect

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/k#2469]
K Version
---------

```
$ kompile --version
K version:    5.2.94
Build date:   Fri Feb 25 08:26:57 CST 2022
```

Description
-----------
Generating a bison parser for the `Bytes` sort in the `BYTES-SYNTAX` module produces an incorrect parser.

```
$ kast --gen-parser -s Bytes -m BYTES-SYNTAX parser_Bytes
$ echo 'b"\x00\x00"' > bytes
$ ./parser_Bytes bytes
\dv{SortBytes{}}("b\"\\xf0\"")
```

The output should be `\dv{SortBytes{}}("\xf0")`. The extra quotes and escaping cause the Byte array, when consumed, to start with byte `0x42` (ASCII 'b') and continue with an ASCII quote etc. instead of containing the single byte `0xf0`.

Input Files
-----------
```
module TEST
    imports BYTES
    configuration <k> $PGM:Bytes </k>
endmodule

module TEST-SYNTAX
    imports BYTES-SYNTAX
endmodule
```
Reproduction Steps / Expected Behavior
--------

See description.

**Comment by dwightguth** [comment]
I'm fairly sure we have a special case in the bison parser for the String sort. We just need to modify the code to do something very similar with Bytes also.
