### ISSUE TITLE
Templated K definitions, easier set up of new repos

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2481]
Currently, several downstream projects are using the same basic structure for their runner scripts. The two most clean runner scripts currently are KEVM's and KAVM's. We should investigate how to make a common runner-script library that can be imported by downstream projects.

A good start for this is the `k-util.sh` script. Maybe it can be extended with a default `run_kompile()` command which can make writing the downstream runner scripts easier.

Another option is to have a configuration file for each downstream project, and generate a default runner-script using that configuration file. We could also think about generating the Makefile. Maybe a new command like `kinit` to generate these files.

**Comment by radumereuta** [comment]
We could consider doing something custom for building definitions, but we have to maintain it.
Alternatives: ninja, basel, cmake
If we generate such config files, might be hard to debug if something goes wrong.
We would like to have more options for measuring performance.
Other ideas: have all the command line options in a JSON which we will pass as arguments to the build system.

**Comment by ehildenb** [comment]
Related: https://github.com/runtimeverification/pyk/issues/30
