### ISSUE TITLE
Compiler error whan adding `imports BOOL` to the builtin MAP module

### ISSUE THREAD

**Issue by dfilaretti** [runtimeverification/k#249]
I came across this issue while working on https://github.com/kframework/k/pull/221. 
There are several tests that fail because of this (e.g. https://github.com/kframework/k/blob/master/k-distribution/tests/regression-new/is-variable/a.k).

Here's some repro steps:

1) let's say `a.k` contains
```
requires "domains.k"

module A
    // empty
endmodule
```

2) run `kompile --backend java --syntax-module A  a.k -d .` (same command used in the tests). No problem here!

3) Open `k-distribution/include/builtin/domains.k` and locate the `MAP` module, then add `imports BOOL` :

```
module MAP
  imports LIST
  imports SET
  imports BOOL // new

  // ...
```

4) run `kompile --backend java --syntax-module A  a.k -d .` again, and this time we get `[Error] Compiler: Module Map must be visible at the configuration declaration`.

5) Going back to `a.k`, we can "fix it" by importing `MAP`:

```
requires "domains.k"
module A
    imports MAP // Not it kompiles! (same command as above)
endmodule```

Alternatively, this is another way:

```
module A
    imports DOMAINS // This also kompiles
endmodule```

**Comment by ehildenb** [comment]
If this is still an issue, please re-open with the new bug report template and reproduction steps against newest K.
