### ISSUE TITLE
Rename kprovex => kprove, kprove => kprove-legacy

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2490]
- [x] KEVM defaults to kprovex: https://github.com/runtimeverification/evm-semantics/blob/master/kevm#L349
- [x] KAVM only uses kprovex: https://github.com/runtimeverification/avm-semantics/blob/master/kavm#L137
- [x] KMichelson still uses kprove: https://github.com/runtimeverification/michelson-semantics/blob/master/kmich#L61
- [x] KWasm still uses kprove: https://github.com/runtimeverification/wasm-semantics/blob/master/kwasm#L84
- [x] Elrond Multisig uses kprovex: https://github.com/runtimeverification/elrond-multisig/blob/967d0e4fb875f4dafd5530a8caf91a425e4f906a/kompile-tool/kprovex.sh#L20

**Comment by radumereuta** [comment]
Might need to adjust things in the test harness:
- rename kprovex -> kprove in the K repo and the semantics repo.
- check Makefiles and configuration files

**Comment by Baltoli** [comment]
WASM semantics update: https://github.com/runtimeverification/wasm-semantics/issues/449

**Comment by Baltoli** [comment]
As of https://github.com/runtimeverification/k/pull/2579, `kprove` has been deprecated and we're ready to rename `kprovex`.

This will be a multi-stage process again:
* [x] Rename current `kprovex` script to `kprove` now that the name is available, but keep a shim called `kprovex`.
* [x] Update downstream semantics that call `kprovex` to instead call `kprove`:
    * [x] WASM
    * [x] EVM
    * [x] AVM
    * [x] Michelson
    * [x] ??? any more
* [x] Delete `kprovex` shim

**Comment by radumereuta** [comment]
I think this list is outdated.
@Baltoli can you check if this can be closed?

**Comment by Baltoli** [comment]
Not quite - I need to see what's breaking the Haskell backend's PR [here](https://github.com/runtimeverification/haskell-backend/pull/3069); once that's merged we can delete `kprovex` and this will be done.

**Comment by radumereuta** [comment]
@Baltoli is this #2622 the final piece of the puzzle?

**Comment by Baltoli** [comment]
Yes - I've closed the issue as it's all done now.
