### ISSUE TITLE
`predicate` attribute

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2499]
Currently if you look at compiled.txt and definition.kore, you end up seeing some `predicate` attributes in the generated files on the `isSort(...)` function definitions.

As far as I know, this is only used for OCaml backend. Either it should be removed entirely from the codebase and not generated, or it should be documented in USER_MANUAL.md.

**Comment by amelieled** [comment]
The `predicate` attribute is present in KAST file (compiled.txt) but not in Kore file (definition.kore).
For the Dedukti backend, it will be useful to add the `predicate` attribute in Kore file too.
I use it to sort axioms, and I feel that the `predicate` attribute has the same status as the `projection` or `initializer` attributes.
