### ISSUE TITLE
"mvn package" is failing

### ISSUE THREAD

**Issue by pinaganti** [runtimeverification/k#25]
Tried to build from k-distribution and also k-master folder. Both are failing with the following message.

[INFO] Scanning for projects...
Downloading from runtime-verification.snapshots: http://office.runtimeverificati
on.com:8888/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNA
PSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.runtimeverification.rv_match:parent:1.
0-SNAPSHOT/maven-metadata.xml from/to runtime-verification.snapshots (http://off
ice.runtimeverification.com:8888/repository/snapshots): Connect to office.runtim
everification.com:8888 [office.runtimeverification.com/76.191.23.163] failed: Co
nnection timed out: connect
Downloading from runtime-verification.snapshots: http://office.runtimeverificati
on.com:8888/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNA
PSHOT/parent-1.0-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.runtimeverification.k:parent:[unknown-
version]: Could not transfer artifact com.runtimeverification.rv_match:parent:po
m:1.0-SNAPSHOT from/to runtime-verification.snapshots (http://office.runtimeveri
fication.com:8888/repository/snapshots): Connect to office.runtimeverification.c
om:8888 [office.runtimeverification.com/76.191.23.163] failed: Connection timed
out: connect and 'parent.relativePath' points at wrong local POM @ line 5, colum
n 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.runtimeverification.k:parent:[unknown-version] (C:\kfr
amework\k-master\k-master\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.runtimeverification.k:parent:[unkn
own-version]: Could not transfer artifact com.runtimeverification.rv_match:paren
t:pom:1.0-SNAPSHOT from/to runtime-verification.snapshots (http://office.runtime
verification.com:8888/repository/snapshots): Connect to office.runtimeverificati
on.com:8888 [office.runtimeverification.com/76.191.23.163] failed: Connection ti
med out: connect and 'parent.relativePath' points at wrong local POM @ line 5, c
olumn 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

**Comment by dwightguth** [comment]
Should be fixed now
