### ISSUE TITLE
[Bug] `krun` pretty-printing breaks on Apple M1 K

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2503]
This issue was raised in the K public channel by `lucach`:

> Hi, krun seems to crash before printing the final configuration when one of the cells is tied to stdout (e.g., <out stream="stdout"> .List </out>, as in the IMP++ tutorial for I/O). Both streams work perfectly (i.e., I can both input and output values), but then I always get this crash instead of the (I assume) final configuration. Adding --output none doesn't seem to help.

The observed output is:
```console
$ krun io.imp --output none
Input two numbers: 1 2
Their sum is: 3
/opt/homebrew/bin/../lib/kframework/k-util.sh: line 74: 70478 Bus error: 10           "$@"
[Error] krun: Backend crashed during rewriting with exit code 138
```

Because the Homebrew prefix is in `/opt`, I'm pretty sure that this is an Apple M1 machine (hence why a serious memory error in the LLVM backend wasn't identified by CI).

**Comment by lucach** [comment]
It's indeed `arm64`, Apple Silicon.

Verbose output:

```bash
$ krun io.imp --output none -v
+ false
+ kparse --directory . io.imp
+ false
+ llvm-krun -c PGM tmp.in.PGM.Shx6KZovld Stmt korefile -c IO '\dv{SortString{}}("on")' String kore -c STDIN tmp.stdin.rjhZfHR76V String korefile --directory /Users/lucach/k-tutorial/imp++/imp-kompiled -v --dry-run -nm -o tmp.in.dAHQcIc1hl
+ false
+ kore-expand-macros ./imp-kompiled .krun-2022-03-24-16-25-25-edUSTuWJFF/tmp.in.dAHQcIc1hl
+ false
+ ./imp-kompiled/interpreter .krun-2022-03-24-16-25-25-edUSTuWJFF/tmp.in.Jqk8jtjIuc -1 .krun-2022-03-24-16-25-25-edUSTuWJFF/result.kore
Input two numbers: 1 2
Their sum is: 3
/opt/homebrew/bin/../lib/kframework/k-util.sh: line 74: 72647 Bus error: 10           "$@"
[Error] krun: Backend crashed during rewriting with exit code 138
```

It's (almost) the latest version:
```
K version:    5.2.117
Build date:   Wed Mar 23 09:45:45 CET 2022
```

Let me know if there is something more I should run to help.

**Comment by Baltoli** [comment]
@lucach I'm looking into this, and the problem seems to be specific to the Homebrew installation of K. I'm not yet sure exactly why this is, but for now I _think_ you should be able to get the example working by [building + installing K from source following the documentation here](https://github.com/runtimeverification/k#build-and-install-guide).

It would be great if you could try the following on this example and let me know what happens with each:
* Upgrade to the newest K version on Homebrew (5.3.x)
* Use a K version built from source

**Comment by Baltoli** [comment]
This seems to be some kind of code generation bug[^1] in LLVM 12 that's fixed in version 13; I'll bump the version in the Homebrew formula. The version I built from source seemed to be working because I was using LLVM 13 as my default version there.

We've seen weird code generation issues on this platform before so if upgrading the version fixes the problem, it's probably not worth spending loads of effort chasing down in detail.

[^1]: Attaching to the compiled interpreter with LLDB didn't seem to reveal anything of particular note; the stack frame is completely wiped out by the time the crash manifests, which makes it tricky to work out exactly what's caused it.

**Comment by lucach** [comment]
Just finished building everything from scratch on my machine and I can confirm it works now (after having re-`kompile`d). I indeed used LLVM 13. Thanks for digging @Baltoli !

(BTW: I think that homebrew also builds locally, given that the `mvn` step takes 20 mins on a quite performant machine).

**Comment by Baltoli** [comment]
Homebrew does indeed build locally; it does a couple of steps _very_ slightly differently to the build instructions and I wanted to make sure there wasn't anything stranger going on. We hope to be able to offer M1 CI infrastructure (including bottled ARM releases) in the future to avoid having to build from scratch every time!

Do let us know if you run into any further issues or would like more help using / learning K!

**Comment by lucach** [comment]
I tried to reinstall it with homebrew and now it works smoothly. I think we can close this, thanks for looking into it!
