### ISSUE TITLE
Build fails to download from the mvn repository

### ISSUE THREAD

**Issue by hierophantos** [runtimeverification/k#251]
After running `mvn package` in the root directory:

```
[INFO] Scanning for projects...
Downloading from runtime.verification.snapshots: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.runtimeverification.rv_match:parent:1.0-SNAPSHOT/maven-metadata.xml from/to runtime.verification.snapshots (https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots): Access denied to: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/maven-metadata.xml
Downloading from runtime.verification.snapshots: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/parent-1.0-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.runtimeverification.k:parent:[unknown-version]: Could not transfer artifact com.runtimeverification.rv_match:parent:pom:1.0-SNAPSHOT from/to runtime.verification.snapshots (https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots): Access denied to: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/parent-1.0-SNAPSHOT.pom and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.runtimeverification.k:parent:[unknown-version] (/Users/sophia/dev/k/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.runtimeverification.k:parent:[unknown-version]: Could not transfer artifact com.runtimeverification.rv_match:parent:pom:1.0-SNAPSHOT from/to runtime.verification.snapshots (https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots): Access denied to: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/parent-1.0-SNAPSHOT.pom and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by dwightguth** [comment]
Unfortunately our maven repo was hacked recently and we're still in the process of making sure everything is secure before we bring it back up again. I'm sorry for the inconvenience, but source builds are going to be broken a little bit longer. In the meantime, if you want to use a specific recent commit of k, you can extract the binary nightly release from github into the k-distribution/target/release/k directory of your repo.

**Comment by dwightguth** [comment]
This issue should be fixed in #259.

**Comment by sjmackenzie** [comment]
be good to make a release so that I can package this software.

**Comment by dwightguth** [comment]
Release is actually on the list of items to do in the immediate future.

**Comment by sjmackenzie** [comment]
a quick innocent question, how long does it take to build K from source (including running unit tests)

**Comment by dwightguth** [comment]
I haven't timed it recently, but if it takes longer than five minutes and doesn't show progress throughout that period, something is wrong. If you have fast internet and cpu it should be even faster than that.

**Comment by sjmackenzie** [comment]
hmmm

It was doing things for the whole of last night throwing these messages:
```
/tmp/tmp-kompile-5435211481190156209.l: In function 'main':
/tmp/tmp-kompile-5435211481190156209.l:820:3: warning: ignoring return value of 'freopen', declared with attribute warn_unused_result [-Wunused-result]
   freopen(NULL, "rb", stdin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp-kompile-5435211481190156209.l:821:3: warning: ignoring return value of 'freopen', declared with attribute warn_unused_result [-Wunused-result]
   freopen(NULL, "wb", stdout);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp-kompile-5435211481190156209.l:840:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
     fread(buffer, length, 1, stdin);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp-kompile-8457056538466363317.l: In function 'main':
/tmp/tmp-kompile-8457056538466363317.l:864:3: warning: ignoring return value of 'freopen', declared with attribute warn_unused_result [-Wunused-result]
   freopen(NULL, "rb", stdin);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp-kompile-8457056538466363317.l:865:3: warning: ignoring return value of 'freopen', declared with attribute warn_unused_result [-Wunused-result]
   freopen(NULL, "wb", stdout);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dwightguth** [comment]
This looks like a warning you should be able to ignore, and I should think this might be expected behavior under certain compiler versions as the build runs unit tests as part of a source build of k, and the unit tests test k's parser which invokes gcc on code generated from flex as you can see here. But I can't see why it would be doing that repeatedly for a period of hours since those tests usually only take a couple seconds. You can skip the unit tests with `mvn package -DskipTests`, but if there's a bug on your platform that makes the parser unfeasibly slow, I would just expect it to occur again when you try to invoke kompile. If you pipe standard error to /dev/null does it work? It's possible if it's generating too many such warnings somehow that it could be slowing down trying to display them all on your terminal, but I can't think what else might be wrong.

What os are you on?

**Comment by sjmackenzie** [comment]
I'm writing a nix expression and I pulled the basic structure from this incorrect commit https://github.com/NixOS/nixpkgs/commit/de0211090334c2d562ee8560a298d5f5f76b40b3
Under the assumption there is at least a bit correct in this expression. I see they've done a while loop, anyway I've pulled that out and am running this without tests as we speak.

Thanks for your help!

**Comment by sjmackenzie** [comment]
seems like i'm getting more access denied error  messages, despite me using https://github.com/kframework/k/commit/b84f29a544e3479eebc3209208fec304ed01588d
```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.1:add-source (scala-compile-first) on project kore: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.3.1:add-source failed: Plugin net.alchim31.maven:scala-maven-plugin:3.3.1 or one of its dependencies could not be resolved: Could not transfer artifact com.typesafe.sbt:incremental-compiler:jar:0.13.9 from/to runtime.verification (https://s3.us-east-2.amazonaws.com/runtimeverificationmaven/internal): Access denied to: https://s3.us-east-2.amazonaws.com/runtimeverificationmaven/internal/com/typesafe/sbt/incremental-compiler/0.13.9/incremental-compiler-0.13.9.jar -> [Help 1]
```

**Comment by dwightguth** [comment]
Are you sure you have this configured right? It should be able to download that artifact from maven central.

**Comment by sjmackenzie** [comment]
considering I'm able download *many* other runtimeverification files except that one. Have you guys got a selective block just on that file listed?

**Comment by dwightguth** [comment]
I mean, s3 returns 403 when the object doesn't exist, but when I test maven just downloads that dependency from maven central. What OS are you on and what version of maven are you using?

**Comment by sjmackenzie** [comment]
I'm trying to write a nixos package for this. I cannot reproduce the issue, it downloads successfully.

**Comment by ehildenb** [comment]
Closing as the transient issue with our S3 bucket has since passed. Feel free to re-open if you still have download issues for K.

**Comment by eacamiling** [comment]
Hi, I'm also getting the same error.

$ mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM C:\Users\Probook 4540s\newprojects\minimal\pom.xml: Unrecognised tag: 'groupID' (position: START_TAG seen ...</modelVersion>\r\n\t<groupID>... @6:11)  @ C:\Users\Probook 4540s\newprojects\minimal\pom.xml, line 6, column 11
[FATAL] 'groupId' is missing. @ line 4, column 45
[FATAL] 'artifactId' is missing. @ line 4, column 45
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project [unknown-group-id]:[unknown-artifact-id]:1.0 (C:\Users\Probook 4540s\newprojects\minimal\pom.xml) has 3 errors
[ERROR]     Malformed POM C:\Users\Probook 4540s\newprojects\minimal\pom.xml: Unrecognised tag: 'groupID' (position: START_TAG seen ...</modelVersion>\r\n\t<groupID>... @6:11)  @ C:\Users\Probook 4540s\newprojects\minimal\pom.xml, line 6, column 11 -> [Help 2]
[ERROR]     'groupId' is missing. @ line 4, column 45
[ERROR]     'artifactId' is missing. @ line 4, column 45
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
