### ISSUE TITLE
[Bug] [kast] - `ArrayIndexOutOfBoundsException` on term with top-level `#And`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2522]
K Version
---------

```
$ kompile --version
K version:    v5.3.2-4-g3884c6e34
Build date:   Fri Mar 25 13:20:52 CET 2022
```

Description
-----------

`kast` fails with `ArrayIndexOutOfBoundsException` on term with top-level `#And`.

Input Files
-----------

`example.k`:

```k
module EXAMPLE-SYNTAX
    imports INT-SYNTAX
endmodule


module EXAMPLE
    imports EXAMPLE-SYNTAX
    imports INT

    configuration <k> $PGM:Int </k>
endmodule
```

`term.json`:

```json
{
  "format": "KAST",
  "version": 1,
  "term": {
    "node": "KApply",
    "label": "#And",
    "variable": false,
    "arity": 2,
    "args": [
      {
        "node": "KApply",
        "label": "<k>",
        "variable": false,
        "arity": 1,
        "args": [
          {
            "node": "KVariable",
            "name": "N",
            "originalName": "N"
          }
        ]
      },
      {
        "node": "KApply",
        "label": "_>=Int_",
        "variable": false,
        "arity": 2,
        "args": [
          {
            "node": "KVariable",
            "name": "N",
            "originalName": "N"
          },
          {
            "node": "KToken",
            "sort": "Int",
            "token": "0"
          }
        ]
      }
    ]
  }
}
```

Reproduction Steps
------------------

```bash
$ kompile example.k --backend haskell
$ kast term.json -i json -o pretty -m EXAMPLE --debug
```

Expected Behavior
-----------------

Expected output:

```k
<k>
  N
</k>
#And N >=Int 0
```

Actual output:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at scala.collection.mutable.WrappedArray$ofRef.apply(WrappedArray.scala:193)
        at org.kframework.unparser.KPrint.filterConjunction(KPrint.java:252)
        at org.kframework.unparser.KPrint.filterSubst(KPrint.java:229)
        at org.kframework.unparser.KPrint.abstractTerm(KPrint.java:197)
        at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:122)
        at org.kframework.unparser.KPrint.prettyPrint(KPrint.java:114)
        at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:147)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type
ArrayIndexOutOfBoundsException (ArrayIndexOutOfBoundsException: Index 0 out of
bounds for length 0)
```

**Comment by radumereuta** [comment]
Can you tell me how you got the json file?
One of the problems is we're trying to pretty print a json file that is not exactly valid.
`#And` is a parametric production, but that's not reflected in the json file.

**Comment by tothtamas28** [comment]
> Can you tell me how you got the json file?

This example has been manually constructed for https://github.com/runtimeverification/ksummarize/issues/42.

> #And is a parametric production, but that's not reflected in the json file.

What would the valid json look like? I'd like to try running `kast` with the correct input.

**Comment by radumereuta** [comment]
Turns out this is a duplicate of #1509
Still unsure how to fix this.

**Comment by radumereuta** [comment]
Maybe find a solution that works if they don't have parametric labels.
If they have parametric labels, use a structure instead of plain text.
Basically, find a solution that works in both cases.

**Comment by radumereuta** [comment]
Bump the JSON version and include more information about labels.
Sort parameters for parametric productions.
The other issue is the EXAMPLE module doesn't include the `#And` label directly. Right now it's working because the `#And` label is hardcoded.

**Comment by ehildenb** [comment]
@radumereuta here is where you need to modify `pyk` to make the adjustment and add `params` as a key to a `KApply`. https://github.com/runtimeverification/k/blob/master/pyk/src/pyk/kast.py#L229

You need to modify the `to_dict` and `from_dict` functions to serialize/deserialize the new key too.

@tothtamas28 can help with pyk.
