### ISSUE TITLE
Add kompile feature to pyk.ktool

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2536]
This can be done on two levels:

1. A function `kompile` that does some simple validation on its parameters, then invokes `kompile` as a subprocess.
2. A class, perhaps `Kompiler`, that fixes some `kompile` parameters, and wraps a `KDefinition` to transparently manage its recompilation on modification. It can expose methods like `add_sentence` that mutate the wrapped `KDefinition`.

**Comment by tothtamas28** [comment]
Relevant discussion: https://github.com/runtimeverification/k/pull/2538#discussion_r850738230

**Comment by ehildenb** [comment]
I'm working on replacing the KEVM runner script (kprove and kompile portions) with calls into pyk. I'll add the needed `kompile` features to pyk to achieve this.

**Comment by ehildenb** [comment]
https://github.com/runtimeverification/evm-semantics/pull/1258
