### ISSUE TITLE
Eliminate "Dot" variables from the Haskell Backend Match/Search Output  

### ISSUE THREAD

**Issue by traiansf** [runtimeverification/k#254]
The result of Search/Match operations is a substitution.

Th Haskell backend represents this substitution as an ML conjunction (`#And`) of ML equalities (`#Equals`) between a variable and a term.  However, some of the variables are generated when compiling the matching pattern and thus not interesting to the users.  The assignments corresponding to these variables need to be removed from the conjunction.

Related Slack context: around https://runtimeverification.slack.com/archives/CC360GUTG/p1547571211721400

**Comment by ehildenb** [comment]
@traiansf is this still an issue?

**Comment by traiansf** [comment]
I think not. And it seems to old for us to care anyway; moreover, lots of things have changes in the way we pretty print things, so I would say we can close this.
