### ISSUE TITLE
01_basic Tutorial Navigation Improvement

### ISSUE THREAD

**Issue by ColmBhandal** [runtimeverification/k#2547]
Many of the lessons in the [K Tutorial](https://kframework.org/k-distribution/k-tutorial/1_basic/) refer to previous lessons. For example, in [lesson 18](https://kframework.org/k-distribution/k-tutorial/1_basic/18_equality_and_conditionals/), exercise 2, there is a back-reference to lesson 16:

> Modify your solution to Lesson 1.16...

However, on the tutorial site hosted at [kframework.org](https://kframework.org/k-distribution/k-tutorial/1_basic/), as opposed to the source code on GitHub, there is no easy way to navigate back to earlier lessons.

Note: I'm just scoping this issue to the [01_basic](https://github.com/runtimeverification/k/tree/master/k-distribution/k-tutorial/1_basic) tutorial sections. Depending on how this turns out, my thinking is that other issues can be opened for the [intermediate](https://github.com/runtimeverification/k/tree/master/k-distribution/k-tutorial/2_intermediate) and [advanced](https://github.com/runtimeverification/k/tree/master/k-distribution/k-tutorial/3_advanced) sections if necessary.

Potential Solutions
-----------------------------------

These are not mutually-exclusive. Any subset of them could be done together:

1. Add a navigation tree or list in the sidebar of the [tutorial page](https://kframework.org/k-distribution/k-tutorial/1_basic/) allowing a user to expand and navigate to whatever page they like. For example, perhaps this [sidebar.html](https://github.com/runtimeverification/k/blob/382a862f0fe5fd1ca00c4c5d187939db2b4b0506/web/static_content/html/include/sidebar.html) file could be modified to include collapsible content under the various headers.
1. Add "Previous lesson" links to all the lessons in the tutorial - I'd be happy to do this and open a PR.
1. Whenever a previous lesson is referenced from another lesson in the tutorial, link to that lesson explicitly - I'd be happy to do this and open a PR (although I couldn't promise to catch 100% of the back-links).

Potential Alternatives/Work-arounds
-----------------------------------

1. If you work through the tutorial directly from GitHub or from the same repository cloned locally, instead of from kframework.org, then you can navigate through the tutorial lessons easily by navigating from the parent directory.
1. If you navigate through the lessons on kframework.org, and need to go back to an earlier lesson, as a workaround you can always visit the top-level [GitHub page](https://github.com/runtimeverification/k/tree/master/k-distribution/k-tutorial/1_basic) for the tutorial, then find out what a previous lesson is called, then type it into the URL in the address bar following "https://kframework.org/k-distribution/k-tutorial/1_basic/". This is tedious though.

**Comment by radumereuta** [comment]
@shd101wyy how hard is it to do something automatic for this?

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/k/pull/2629
