### ISSUE TITLE
Kompile/kprove doesn't complain about bad command line arguments

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2548]
Talking to @tothtamas28 we got to the conclusion that one way to improve the usability of K is to have a better CLI
For example, if you give a bad argument, kompile/kprove is not going to complain, and it's going to send that argument to the backend.

Maybe we can find a better way to send arguments to the backend and have the front end sanitize its arguments.

Another solution would be to make sure we get a complaint from the backend if we send it bad arguments.

Ex: kompile doesn't complain
```
 kompile test.k -v -xxxxxxx
```

**Comment by dwightguth** [comment]
It's fairly normal for command line arguments that are passthroughs to other sets of options to be validated by the tool they are ultimately passed to. I don't think we should try to change that. I'm a little unclear about your example though as that would seem to be a flag passed to the frontend and I don't see how that would end up being passed to the backend. I would think that the frontend argument parser would reject it. Is that not happening? That would be a bug, but it would have nothing to do with the backend or with pass throughs

**Comment by radumereuta** [comment]
You are correct. I got confused by `-ccopt` options used by kompile to send to the llvm backend.
But in the case mentioned above, kompile completes without any complaint. Which is a problem.

**Comment by Baltoli** [comment]
It turns out that we actually _do_ rely on extra options being silently dropped in some places. In my [preliminary PR](https://github.com/runtimeverification/k/pull/2557), the CI fails with the following error:
```
== python3 -m unittest [+    0.00]: kprovex .emit-json-spec-test/looping-1-spec.k --backend haskell --directory definitions/imp-verification/haskell -I definitions/imp-verification/haskell --spec-module LOOPING-1-SPEC --output json -I k-files

[Error] Critical: You have to provide exactly one main file in order to do outer parsing. The main files provided were: [.emit-json-spec-test/looping-1-spec.k, --backend, haskell]
```

**Comment by Baltoli** [comment]
[Here](https://github.com/runtimeverification/k/blob/c1e1e080aad596779c69ad0c2ed66095ec783251/pyk/src/pyk/ktool/kprove.py#L113) we can see that pyk constructs a `--backend` argument to `kprovex`.

However, [here](https://github.com/runtimeverification/k/blob/c1e1e080aad596779c69ad0c2ed66095ec783251/kernel/src/main/java/org/kframework/kprovex/KProveFrontEnd.java#L39-L47) we can see that the KProveX frontend doesn't get a `KompileOptions` injected (which is where `--backend` is defined). This means that `kprovex` is relying on the behaviour in this issue to silently drop the unused arguments.

The possible solutions I see are:
* Drop the `--backend` argument in pyk (@ehildenb @tothtamas28 can possibly weigh in on whether this makes sense - it seems fine to me but I might be missing something).
* Factor out `--backend` into a common option in case the prover needs it in the future.
* Don't fix this issue; I'd rather not do this as the silent drop behaviour isn't intuitive.

**Comment by tothtamas28** [comment]
> Drop the --backend argument in pyk

I think this can be safely done (@ehildenb, please confirm). I've pushed a commit (9d8397014dec58374a7db89cf29bcd8b53b9a099) with the fix to the PR.
