### ISSUE TITLE
[kompile] Allow removing ACU collection patterns from definition

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2558]
Currently we have limited support for ACU collection patterns in K. A backend for K is being built that targets Dedukti, which is a language that does not support ACU collection patterns (or at least, the languages that Dedukti targets do not support them).

So a simple rule like these can be problematic:

```
    rule [r1]: <k> X:Id => I ...</k> <env>... X |-> I ...</env>

    rule [r2]: <k> X = I:Int; => . ... </k>
         <env>... X |-> (_ => I) ...</env>

    rule [r3]: <k> var (X,Xs => Xs);_ </k>
         <env> Rho:Map (.Map => X |-> 0) </env> requires notBool (X in_keys(Rho))
```

We would want the frontend to translate them to this:

```
    // _|->_ turned into _in_keys(_) constraint + lookup
    rule [r1.translated]: <k> X:Id => ENV[X] ...</k> <env> ENV </env> requires X in_keys(ENV)

    // _|->_ turned into _in_keys(_) constraint + write
    rule [r2.translated]: <k> X = I:Int; => . ... </k>
         <env> ENV => ENV [ X <- I ] </env>
      requires X in_keys(ENV)

    // .Map is removed from LHS
    rule [r3.translated]: <k> var (X,Xs => Xs);_ </k>
         <env> ENV => ENV ( X |-> 0 ) </env>
      requires notBool (X in_keys(ENV)) 
```

This could be done in two ways.

- Add option `--no-acu-maps` to the `kompile` command, which does this transformation.
- Add an option `--pyk-transfom <pyk-definition-transformer>`, which will call the given definition transformer at kompile time after the existing kompile pipeline. This makes it easier for people to write their own transformations of the K definition. We could ship `no-acu-maps.py` as a built-in transformation they can turn on.

**Comment by radumereuta** [comment]
@tothtamas28 can you come up with a skeleton script that does some sort of transformation to the rules described above.
This will be called by `kompile --post-process <script.py>` and it expects the JSON file at stdout.

**Comment by tothtamas28** [comment]
> a skeleton script that does some sort of transformation to the rules described above

Created a PR for it: #2729

**Comment by radumereuta** [comment]
@tothtamas28 can we close this now?

**Comment by tothtamas28** [comment]
> can we close this now?

If we decide not to implement this, then I think so:

> We could ship `no-acu-maps.py` as a built-in transformation they can turn on.

**Comment by radumereuta** [comment]
If one needs to do such a transformation we have the `--post-process` kompile option.
The pyk repo contains an example on how to implement such a transformation easily: https://github.com/runtimeverification/pyk/tree/master/pyk-tests/post-process
