### ISSUE TITLE
Organize methods for KCFG node creation

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2575]
Context: https://github.com/runtimeverification/erc20-verification/pull/425#discussion_r862659454

Potential solutions: in `pyk.kcfg.KCFG`,

* `get_or_create_node(node_id)` (instead of `find_or_create_node`), or
* `create_node(node_id, allow_exists=True)`,
* `get_node(node_id) or create_node(node_id)`.

Something to consider: before creating a node, it probably makes sense to check whether the node already exists (to handle the two cases accordingly, to avoid looping behavior, etc). If `create_node` does not raise an exception, this is not enforced.

**Comment by radumereuta** [comment]
@tothtamas28 can you update the description of this issue so we can process it properly in the KDev meeting?

**Comment by ehildenb** [comment]
Closing in favor of batching this with other upstream changes: https://github.com/runtimeverification/erc20-verification/issues/431
