### ISSUE TITLE
Better distinction between stuck backend and crashed backend

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#2576]
Whenever the backend crashes, the first message the user sees is the final configuration, and only after scrolling up they can see the particular error log. This can be confusing because the user might not be aware that the backend actually crashed, and the backend couldn't continue execution due to the error and not because of some problem the user can fix in the semantics/spec.

**Comment by ana-pantilie** [comment]
@sskeirik 
- investigate differences in exit codes
- one-line error message at the end explaining the cause of the issue

**Comment by ana-pantilie** [comment]
From @ChristianoBraga
```
kplc prove --directory unit-tests/verification/haskell unit-tests/flat-unit-test.md 
== /data/RV/plutus-core-semantics/.build/usr/bin/kplc: kprovex --directory unit-tests/verification/haskell unit-tests/flat-unit-test.md -I /data/RV/plutus-core-semantics/.build/usr/lib/kplutus/include/kframework -I /data/RV/plutus-core-semantics/.build/usr/lib/kplutus/blockchain-k-plugin/include/kframework
#Top
kplc prove --directory simple-proofs/verification/haskell simple-proofs/simple-symbolic.md 
== /data/RV/plutus-core-semantics/.build/usr/bin/kplc: kprovex --directory simple-proofs/verification/haskell simple-proofs/simple-symbolic.md -I /data/RV/plutus-core-semantics/.build/usr/lib/kplutus/include/kframework -I /data/RV/plutus-core-semantics/.build/usr/lib/kplutus/blockchain-k-plugin/include/kframework
kore-exec: [2455043] Error (ErrorException):
    Error: missing hook
    Symbol
        LblED25519VerifyMessage'LParUndsCommUndsCommUndsRParUnds'KRYPTO'Unds'Bool'Unds'String'Unds'String'Unds'String{}
    declared with attribute
        hook{}("KRYPTO.ed25519verify")
    We don't recognize that hook and it was not given any rules.
    Please open a feature request at
        https://github.com/kframework/kore/issues
    and include the text of this message.
    Workaround: Give rules for LblED25519VerifyMessage'LParUndsCommUndsCommUndsRParUnds'KRYPTO'Unds'Bool'Unds'String'Unds'String'Unds'String{}
    CallStack (from HasCallStack):
      error, called at src/Kore/Simplify/Simplify.hs:468:6 in kore-0.60.0.0-FrNGZ4JxOFhgS8jfNbRB1:Kore.Simplify.Simplify
Created bug report: kore-exec.tar.gz
  <generatedTop>
    <k>
      #lookup ( RHO , X0 ) ~> [ #eval ( addInteger , ListItem ( < con integer X:Int > )
      ListItem ( < con integer Y:Int > ) ) _] ~> _DotVar2 ~> .
    </k>
    <env>
      RHO
    </env>
    <trace>
      _5
    </trace>
  </generatedTop>
#And
  {
    M
  #Equals
    X0:UplcId
  }
#And
  {
    _DotVar1
  #Equals
    [_ X0:UplcId RHO ] ~> _DotVar2 ~> .
  }
make: *** [Makefile:338: simple-proofs/simple-symbolic.md.prove] Error 1
```

**Comment by radumereuta** [comment]
One way to improve the visibility of error messages from the backend is to pretty print labels by calling something like:
https://github.com/runtimeverification/k/blob/master/kore/src/main/java/org/kframework/utils/StringUtil.java#L674

**Comment by ana-pantilie** [comment]
Moving this back to triage because it needs discussing in the K dev meeting.

**Comment by ana-pantilie** [comment]
The backend should be returning different exit codes for each case: TODO report table of exit codes and transfer task to frontend.

**Comment by ana-pantilie** [comment]
Exit codes for `kore-exec`:
- passing proof, returning `\\top`: `ExitCode 0`
- stuck proof, returning stuck state: `ExitCode 1`
- backend crashed with uncaught exception: any other exit code

There's one special case here, when the user provides an exit code in the K exit code cell. Maybe the frontend can check if that's the case?

Let me know if you need more information and I'll do some more investigation.

**Comment by SchmErik** [comment]
@ana-pantilie I noticed that the stuck claim error could be really nice if the haskell backend could pass back the claim to the kfrontend when it gets stuck. Not sure how difficult this is to do but this could help kprove point to the actual line number of the claim that's stuck and print the contents of the source code at that location.

**Comment by ana-pantilie** [comment]
@SchmErik We could log the source location of the claim which got stuck, would that solve your problem?

**Comment by SchmErik** [comment]
> @SchmErik We could log the source location of the claim which got stuck, would that solve your problem?

@radumereuta do you know how this log file is represented?

**Comment by ana-pantilie** [comment]
@SchmErik The backend emits the log directly to either stderr or a file the user provides, the frontend doesn't really have anything to do with this.

I think that the cleanest solution would be to have the frontend support processing these logs. We have a `--oneline` format so that they're easier to parse.
