### ISSUE TITLE
Nix improvements

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/k#2577]
There are a few issues with the nix derivations in this repo, which cause issues when trying to use a K shell in a different project like the [evm-semantics](https://github.com/runtimeverification/evm-semantics). Namely:

* When compiling the EVM semantics repo within a K nix shell, the nix derivation for K should re-export/link the `include` folder from the `llvm-backend` derivation as well as the `cmake` folder from `llvm-backend` source.
* the release flag is not being passed down to `haskell-backend` in `default.nix`
* cannot use `import ./deps/k {}` when K is a submodule inside `evm-semantics` (fails with `getting attributes of path '/.git/modules/deps/k': No such file or directory`)

Other suggestions:
* the version of Z3 is currently unpinned in the nix derivation. Given how sensitive K seems to be to the right version of Z3, Niv + overlay could be used to select a specific version from github.
* it seems more nix-y for `nix/k.nix` to read in the version number from `package/version` rather than the current way of replacing the version via `package/version.sh`.

**Comment by radumereuta** [comment]
Waiting on feedback from Sam

**Comment by goodlyrottenapple** [comment]
I have a semi workable solution for the issues mentioned above with a few caveats and potential additions, namely:

1) nix does seem to care for submodules within a repo, as evidenced by the use of the custom [`cleanGitSubtree`](https://github.com/ttuegel/nix-lib/blob/main/lib/clean-git-subtree.nix) function, which unfortunately breaks if there are several layers of submodule nesting. Namely, since `evm-semantics` has `k` as a submodule, which in turn has `haskell-backend` and `llvm-backend` as submodules, things break if I try to create a nix expression in the `evm-semantics` repo which imports the `k` sumbodule and its nix expression. 

    An easy way out, that I found, involves sidestepping the `k` submodule in the `evm-sematics` entirely, i.e. use niv intead to pin the exact revision of the `k` repo to build against. For me this is easier than trying to modify the `cleanGitSubtree` function, but would mean more effort in keeping the pinned nix nersion of k in sync with the submodule of k...

2) Another change to the nix derivation of k that might be useful, would be to optionally pass in a custom `haskell-backend` (and potentially `llvm-backend`), given we want to do this when profiling the `evm-semantics` proofs, as mentioned in [this issue](https://github.com/runtimeverification/evm-semantics/issues/1165). Atm, we test agains ta different haskell-backend commmit by checking out said version of the `haskell-backend` submodule and re-compiling/re-proving everything against this backend. We could ?potentially? get some caching from nix by instead locally pinning different versions of the `haskell-backend` with niv, which would be passed down to the `k` derivation. The way I set this up locally is to add the haskell-backend dependency at a specific commit to niv, then build the `evm-semantics` derivation/shell, 

    > niv add runtimeverification/haskell-backend --branch <commit_hash_here>
    > nix-shell

    run the tests here, and then switch back to the current `haskell-backend` version by removing the custom pinned version in niv

    > niv drop haskell-backend

@radumereuta should I make a PR with some/all of these changes in the `k` repo and discuss further there?

**Comment by radumereuta** [comment]
That would be great!
