### ISSUE TITLE
[KIP] - Deprecate Ubuntu bionic; support Ubuntu Jammy

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2578]
We discussed this a while ago on Slack, and from what I can remember the consensus was that we'd like to support 2 LTS releases of Ubuntu.

Now that 22.04 (Jammy) is out, we should begin the process of investigating the upgrade / deprecation process.

Things we'll need to do:
* [x] Audit projects downstream of K for uses of the bionic docker image, and update them to focal.
* [x] Test K builds etc. on Jammy
* [x] LLVM backend on Jammy
* [x] Haskell backend on Jammy

**Comment by radumereuta** [comment]
I've updated my desktop to 22.04LTS and it still has quite a few bugs when it comes to normal usage.
K tests run fine without any modifications. There might be some issues with LLVM tough.

**Comment by Baltoli** [comment]
* [x] https://github.com/runtimeverification/blockchain-k-plugin/pull/138 
* [x] https://github.com/runtimeverification/elrond-semantics/pull/86
* [x] https://github.com/runtimeverification/haskell-backend/pull/3051
* [ ] ~~https://github.com/runtimeverification/iele-semantics~~
    * CI broken on K release
* [ ] ~~https://github.com/runtimeverification/beacon-chain-verification~~
* [ ] ~~https://github.com/runtimeverification/deposit-contract-verification~~
* [ ] ~~https://github.com/runtimeverification/firefly-iele~~
