### ISSUE TITLE
[KIP] - `comm` attribute on `simplification` rules

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#2587]
Motivation
----------

Now that the user can write simplification rules over the `\equals` KORE construct, we frequently find ourselves in situations where we write rules like the following:

```
rule { A #Equals B } => C [simplification]
rule { B #Equals A } => C [simplification]
```

While it might be nice for the backend to recognize these are in fact the same axiom (since equals is commutative), it would be difficult in practice to make the equation matcher in the backend handle this, and would also likely be slower than simply using both forms of the equation.

We would like instead to be able to automatically generate the second form of the rule from the first. This makes it easier to specify both forms of the rule, which means we are less likely to run into reasoning errors where we forgot to specify the second form, which in turn will lead to faster verification.

Example K Code
--------------

Instead of writing:

```
module LEMMAS
  rule { I +Int J #Equals I} => #Bottom
    requires J =/=Int 0 [simplification]
  rule { I #Equals I +Int J} => #Bottom
    requires J =/=Int 0 [simplification]
endmodule
```

One would write:

```
module LEMMAS
  rule { I +Int J #Equals I} => #Bottom
    requires J =/=Int 0 [simplification, comm]
endmodule
```

Documentation
-------------

If the `comm` attribute is added to a rule, then it means that the top symbol on the left hand side, being commutative, should match in either order of operands. In order to implement this, a second rule is generated by the compiler which swaps the order of operands but otherwise leaves the axiom unchanged. It is an error if the rule does not have the `simplification` attribute or if the top symbol on the LHS does not have the `comm` attribute.

Testing Approach
----------------

A simple test to ensure both forms of the lemma simplify is all that is required.

**Comment by radumereuta** [comment]
Why only the top level? `+Int` is also commutative?
Why do you have to tag the simplification rule with `comm` when you can already detect that the top level term is comm?

Here are more details about this topic: https://runtimeverification.slack.com/archives/CC360GUTG/p1652111700331299

**Comment by dwightguth** [comment]
I suggested only the top because otherwise you might end up with an exponential number of rules generated from a single axiom. I suggested the attribute because we want this to be done intentionally so that the definition doesn't end up with axioms the user didn't expect to be there.

**Comment by ehildenb** [comment]
Another use: https://github.com/runtimeverification/evm-semantics/pull/1270/files#r926049105

This would be very nice for reducing chances of fat-finger mistakes or typos.
