### ISSUE TITLE
[Bug] [kparse] - Attribute `prec` doesn't work

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#2591]
K Version
---------

```
$ kompile --version
```
5.2.110

Description
-----------
The command `kparse` (or `kompile`) doesn't use the attribute `prec` to resolve parsing ambiguities.
With a semantics which defines  `AExp "+" AExp [left, prec(50), seqstrict]` and `AExp "*" AExp [left, prec(42), strict]`, I obtained the following error with the program `20 * 2 + 2`:

```
[Error] Inner Parser: Parsing ambiguity.
1: syntax AExp ::= AExp "*" AExp [left, prec(42), strict]
    `_*__AEXP-SYNTAX_AExp_AExp_AExp`(#token("20","Int"),`_+__AEXP-SYNTAX_AExp_AExp_AExp`(#token("2","Int"),#token("2","Int")))
2: syntax AExp ::= AExp "+" AExp [left, prec(50), seqstrict]
    `_+__AEXP-SYNTAX_AExp_AExp_AExp`(`_*__AEXP-SYNTAX_AExp_AExp_AExp`(#token("20","Int"),#token("2","Int")),#token("2","Int"))
	Location(1,1,1,11)
```

Input Files
-----------

```
module AEXP-SYNTAX
   imports INT
   imports ID

   syntax AExp ::= Int | Id
    | AExp "+" AExp [left, prec(50), seqstrict]
    | AExp "*" AExp [left, prec(42), strict]
    | "(" AExp ")"  [bracket]

   syntax KResult ::= Int

endmodule

module AEXP
   imports AEXP-SYNTAX
   imports MAP

   configuration <k> $PGM:AExp </k>
endmodule
```

Expected Behavior
-----------------

`20 * 2 + 2` should be parsed as `(20 * 2) + 2`.

**Comment by Baltoli** [comment]
The `prec` attribute deals with tokenisation, rather than parsing ambiguities: https://github.com/runtimeverification/k/blob/master/USER_MANUAL.md#prec-attribute

I think you're looking for the `syntax priorities` mechanism instead: https://github.com/runtimeverification/k/blob/master/USER_MANUAL.md#symbol-priority-and-associativity

**Comment by radumereuta** [comment]
Bruce is correct here. What you want is this:
```
syntax AExp ::= Int | Id
    | AExp "*" AExp [left, strict]
    > AExp "+" AExp [left, seqstrict]
    | "(" AExp ")"  [bracket]
```
If it fixes your problem, please close the issue.

**Comment by amelieled** [comment]
Oh, OK I didn't understand that this attribute only works for regexp! Sorry, and thanks!
