### ISSUE TITLE
Remove `to_rule` from `KCFG`

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2604]
Currently we have `to_rule` in `KCFG`, which we used to be using for all sorts of things.

But over time we've realized that we need more specialized or different routines for turning edges into rules, and in fact only one use of `to_rule` remains, which I plan to remove.

So we should remove `to_rule` which makes the KCFG datastructure more agnostic about what it's storing a control-flow-graph of.

**Comment by ehildenb** [comment]
I'm not sure if it should be removed or just updated, I have local work wihch uses this slight variation:

```
def edge_to_rule(cfg: KCFG, edge: KCFG.Edge, claim: bool = False, priority: int = 50) -> Tuple[KRuleLike, Dict[str, KVariable]]:
    claim_id = f'BASIC-BLOCK-{edge.source.id}-TO-{edge.target.id}'
    init_cterm = CTerm(mlAnd([edge.source.cterm.term, edge.condition]))
    target_cterm = edge.target.cterm
    return proof_obligation_spec(claim_id, init_cterm, target_cterm, claim=claim, priority=priority, abstract_target=False)
```

So maybe `proof_obligation_spec` should be upstreamed instead.

**Comment by tothtamas28** [comment]
Depending on how `proof_obligation_spec` is defined on your local branch, this might be very close to how `KCFG.Edge.to_rule` is already implemented, so we might be able to extend the latter to be more flexible.

**Comment by ehildenb** [comment]
This was not a good idea, `to_rule` is a good thing.
