### ISSUE TITLE
Add a whitelist of attributes

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2625]
This would allow us to give better error messages in case of typos.
Add a group attribute that takes a comma separated list of names.
At first it behaves identically to a list of unstructured attributes `[group(foo,bar,baz)]` == `[foo,bar,baz]`. This happens only at parse time. We still need the internal attributes to be structured.
Add a warning for unstructured attributes.
Go downstream and fix all the warnings we are maintaining.
Then turn the warning into an error.

Steps:

- [x] Opt-in error for attributes not implemented.
- [x] Try with KEVM, document issues here.
- [x] Try with KAVM, document issues here.
- [x] Try with KCC, document issues here.
- [x] Fix issues that have come up.
- [x] Switch to opt-out behavior, get working downstream.
- [x] Update documentation (in `user-manual.md` and tutorials)
- [x] Remove option to opt-out.

**Comment by ehildenb** [comment]
Related: https://github.com/runtimeverification/k/issues/843 and https://github.com/runtimeverification/k/issues/1585, #3193

**Comment by radumereuta** [comment]
Is `group` the best word for this?
How about `tag`? I feel it's more appropriate and intuitive.
@ehildenb @dwightguth @Baltoli @Scott-Guest @Robertorosmaninho

**Comment by Scott-Guest** [comment]
`group` seems appropriate if the only usage is for defining syntax groups. Are there other use cases for user defined attributes?

**Comment by Robertorosmaninho** [comment]
Probably `group` is best @radumereuta, as we already use `tag` a lot on the LLVM Backend 😄

**Comment by Scott-Guest** [comment]
I've created an initial whitelist consisting of everything in `Att.scala`, the K User Manual, and the minimum I needed to add to get a simple test passing:

| Attribute | Read | Written | Documented |
|-----------|------|---------|------------|
| alias | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| alias-rec | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| all-path | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| anywhere | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| applyPriority | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| assoc | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| avoid | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| bag | :heavy_check_mark: | :heavy_check_mark: | :x: |
| binder | :heavy_check_mark: | :heavy_check_mark: | :medical_symbol: |
| bitwidth | :x: | :x: | :x: |
| bracket | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| bracketLabel | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| cell | :heavy_check_mark: | :heavy_check_mark: | :x: |
| cellFragment | :heavy_check_mark: | :heavy_check_mark: | :x: |
| cellName | :heavy_check_mark: | :heavy_check_mark: | :x: |
| cellOptAbsent | :heavy_check_mark: | :heavy_check_mark: | :x: |
| color | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| colors | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| comm | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| concrete | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| context | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| cool | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| digest | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| element | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| exponent | :x: | :x: | :x: |
| format | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| freshGenerator | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| function | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| functional | :heavy_check_mark: | :heavy_check_mark: | :x: |
| generatedByListSubsorting | :heavy_check_mark: | :x: | :x: |
| heat | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| hybrid | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| hook | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| idem | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| impure | :heavy_check_mark: | :heavy_check_mark: | :x: |
| initializer | :heavy_check_mark: | :heavy_check_mark: | :x: |
| injective | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| internal | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| kast | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| klabel | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| kore | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| label | :heavy_check_mark: | :heavy_check_mark: | :x: |
| latex | :heavy_check_mark: | :heavy_check_mark: | :medical_symbol: |
| left | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| lemma | :heavy_check_mark: | :x: | :x: |
| org.kframework.attributes.Location | :heavy_check_mark: | :heavy_check_mark: | :x: |
| locations | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| macro | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| macro-rec | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| maincell | :heavy_check_mark: | :heavy_check_mark: | :x: |
| matching | :x: | :x: | :x: |
| memo | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| non-assoc | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| non-executable | :heavy_check_mark: | :heavy_check_mark: | :x: |
| noThread | :x: | :heavy_check_mark: | :x: |
| one-path | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| originalPrd | :heavy_check_mark: | :heavy_check_mark: | :x: |
| owise | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| pattern | :heavy_check_mark: | :x: | :x: |
| pattern-folding | :heavy_check_mark: | :x: | :x: |
| prec | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| predicate | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| prefer | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| priority | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| private | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| org.kframework.definition.Production | :heavy_check_mark: | :heavy_check_mark: | :x: |
| proj | :x: | :x: | :x: |
| public | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| recordPrd | :heavy_check_mark: | :heavy_check_mark: | :x: |
| refers_RESTORE_CONFIGURATION | :x: | :x: | :x: |
| refers_THIS_CONFIGURATION | :x: | :x: | :x: |
| result | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| returnsUnit | :x: | :heavy_check_mark: | :x: |
| right | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| seqstrict | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| significand | :x: | :x: | :x: |
| simplification | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| smtlib | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| smt-hook | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| smt-lemma | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| smt-prelude | :heavy_check_mark: | :heavy_check_mark: | :x: |
| org.kframework.attributes.Source | :heavy_check_mark: | :heavy_check_mark: | :x: |
| specification | :x: | :x: | :x: |
| stream | :heavy_check_mark: | :heavy_check_mark: | :medical_symbol: |
| strict | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| symbol | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| symbolic | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| syntaxModule | :heavy_check_mark: | :heavy_check_mark: | :x: |
| tag | :heavy_check_mark: | :heavy_check_mark: | :x: |
| token | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| topcell | :x: | :heavy_check_mark: | :x: |
| topRule | :x: | :x: | :x: |
| total | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| transition | :x: | :heavy_check_mark: | :x: |
| trusted | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| unblock | :heavy_check_mark: | :heavy_check_mark: | :x: |
| unboundVariables | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| unit | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| UNIQUE_ID | :heavy_check_mark: | :heavy_check_mark: | :x: |
| unparseAvoid | :heavy_check_mark: | :heavy_check_mark: | :x: |
| unused | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| userList | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

Note that many of these are undocumented, or mentioned in the documentation but not fully explained (the :medical_symbol: mark). Additionally, a few appear to be "dead code" in the sense that they're never read (i.e. we never check for the attribute anywhere) or never written (i.e. no K file uses the attribute and we never add it programmatically).

I'm going to remove the dead ones soon and see if anyone complains. I put this together just using `grep` and glancing at the results, so there are likely mistakes. I'd appreciate if anyone can give it a quick look over for obvious issues: @ehildenb @dwightguth @Baltoli @radumereuta

**Comment by Scott-Guest** [comment]
Also @radumereuta per your tag vs group remark, it looks like tag already exists (although, it's undocumented and only used in some test files).

**Comment by radumereuta** [comment]
`generatedByListSubsorting` can be removed.
Some of the labels are used only internally, so they may be missing documentation (like `originalPrd`).

I think you have the right approach when trying to remove unused labels, but maybe they should not be in the scope of this PR.

**Comment by Scott-Guest** [comment]
For building KEVM, the only unrecognized attribute is `preserves-definedness`

**Comment by radumereuta** [comment]
> For building KEVM, the only unrecognized attribute is `preserves-definedness`

This might be used only temporarily. See this: https://github.com/runtimeverification/k/pull/2963/files
@jberthold is that the case?

**Comment by jberthold** [comment]
> > For building KEVM, the only unrecognized attribute is `preserves-definedness`
> 
> This might be used only temporarily. See this: https://github.com/runtimeverification/k/pull/2963/files @jberthold is that the case?

IMHO we will need `preserves-definedness` to be available to users permanently. The reason is that a rule may use a _partial_ function but guarantees (via side conditions or statically) that it is only called on arguments where the function is defined.

**Comment by Scott-Guest** [comment]
KAVM builds fine with the existing whitelist

**Comment by Scott-Guest** [comment]
After adding `group(_)` in a few places (runtimeverification/c-semantics#894), the C semantics also builds with the existing whitelist

**Comment by Scott-Guest** [comment]
Closed by #3499
