### ISSUE TITLE
Kore data-structures and parser in pyk

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2626]
We eventually want the pyk library to be able to read/write Kore terms directly, and do some small manipulations of them without having to go through frontend Kast. For example, if we are just adding a constraint to a state, or renaming some variables, then there should be no reason to go through frontend Kast.

Additionally, pyk should be able to directly translate Kore => Kast without going through the frontend unparsing routines (the other direction is harder, and we will have to rely on the frontend for that).

To facilitate this long-term, we should add Kore data-structures in `kore.py` in the pyk library, and a parser/unparser for it.

The Kore language should be LL1 or LL2, se we should be able to role a fast parser for it. Several examples exist, here is the most recent rewrite of the Haskell backends kore-parser, I guess this can just be translated 1-for-1: https://github.com/runtimeverification/haskell-backend/pull/2967. Here is some documentation on the Kore language itself: https://github.com/runtimeverification/haskell-backend/tree/master/docs (look at kore-syntax.md)

**Comment by ehildenb** [comment]
Ideally actual parsing wouldn't happen in Python I think, but with some hooked parser library that gives back the AST.

Parsing kore does become a significant bottleneck on the C semantics, so we should be performance conscious here.

**Comment by radumereuta** [comment]
We could use JSON to transfer information from the haskell backend to pyk.
For this, we need the haskell/llvm backends to generate a JSON representation. The initial tests should make sure the identity transformation works for all backends. ([here](https://github.com/runtimeverification/k/commit/4d9f0b2543f83849b437e0aa95a64becee46434f) is an example from the front end)

Here is how the front-end [generates](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/unparser/ToJson.java) json, and how it [loads](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/parser/json/JsonParser.java) it.

@ana-pantilie: here is some starting example
```
KORE: \\and{Sort1}(\\fLabel{Sort1}(), VarX) [attribute1, attribute2]
JSON: {connective: "\\and", sorts: [...], args: [..., ...]}
```
@jberthold here are the [data structures](https://github.com/runtimeverification/haskell-backend/blob/6f1041006305e3be7f456f36e2b60a3aa5bf7c76/kore/src/Kore/Internal/TermLike/TermLike.hs#L647) that we need to store from the haskell backend.
This should follow the ideas behind [textual kore](https://github.com/runtimeverification/haskell-backend/blob/master/docs/kore-syntax.md).

Eventually, we need to make sure that all our tools can communicate with the same JSON format: front-end, haskell, llvm, pyk.
If I missed something from the meeting, please add it as a comment.

**Comment by goodlyrottenapple** [comment]
We discussed a potential JSON definition of kore with @jberthold in the Haskell standup today and thought it might be a good idea to use JSON Schema + https://github.com/quicktype/quicktype to automatically generate types and JSON parsers for Haskell, C++, Java and Python.

**Comment by radumereuta** [comment]
As we discussed today at the KDev meeting, we want to move out in phases:
- pyk library and haskell backend should come up with a version of json-kore that is makes sense in their environment.
- we will compare and make sure we reach a consensus. This should eventually lead to something similar to [textual kore](https://github.com/runtimeverification/haskell-backend/blob/master/docs/kore-syntax.md)

**Comment by jberthold** [comment]
@tothtamas28 I have implemented a JSON format for _patterns_ alongside the "textual kore" description. The [Json schema is here](https://github.com/runtimeverification/haskell-backend/pull/3131/files#diff-4bf2d0a62a49b8ccfe0b66ed7607f89193836062f505c4157dac26c5c167eaa5) but please consider the Haskell code in case of doubt.
Hope we can talk about this proposal tomorrow in the meeting.
here is a random-generated [example.](https://github.com/runtimeverification/k/files/9046275/json-kore-example.txt)

**Comment by radumereuta** [comment]
We could use this set of tests https://github.com/runtimeverification/haskell-backend/tree/master/test/parser
as a starting point for testing the JSON conversion. It contains lots of simple corner cases.
Most importantly is to make sure the round trip test works for both Haskell and PYK library.

**Comment by jberthold** [comment]
> We could use this set of tests https://github.com/runtimeverification/haskell-backend/tree/master/test/parser

https://github.com/runtimeverification/haskell-backend/issues/3145#issuecomment-1183938504 :
Unfortunately all test data files in `test/parser` contain _entire modules_ instead of simply _patterns_. I have implemented a way to extract all patterns from modules into a _json array_ of patterns so we can still work with the files.
