### ISSUE TITLE
Include pyk in debian package

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2627]
All uses of pyk currently rely on the git submodule being present. `This is suitable for development, but for packaging we should be deploying actual packages to PyPi.`

- ~[ ] Add an RV account to PyPi.~
- ~[ ] Deploy pyk to PyPi on CI deployments.~
- [ ] Add a line in [here](https://github.com/runtimeverification/k/blob/master/package/package) to build the pyk virtualenv and copy it into `DESTDIR` at the appropriate location. Downstream CI doesn't need to build it.
- [ ] Adjust downstream CI to use this deployment instead of the submodule.
- [x] https://github.com/runtimeverification/devops/issues/51

**Comment by ehildenb** [comment]
We can call it `kframework` on PyPi, so people can do `pip install kframework`. Or `lib-kframework` or `kframework-pyk` or something.

No need to commit to `pyk` name.

**Comment by radumereuta** [comment]
We might not need virtualenv for deployments. We can discuss this after the first iteration.
