### ISSUE TITLE
Add structure to the pyk prelude

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2631]
Blocked on: runtimeverification/pyk#45 

- [ ] Introduce python module structure for `pyk.prelude.ml`, `pyk.prelude.bool`, and `pyk.prelude.int`.
- [ ] Move current prelude defintiions in `prelude.py` into these more specific modules.
- [ ] Allows users to import `prelude` module directly, to get everything (by adding an `__init__.py`).

**Comment by tothtamas28** [comment]
In these modules I think it is OK to deviate from Python naming conventions, and have e.g.

```python
GeneratedTopCell = KSort('GeneratedTopCell')
```
so that the DSL's look and feel is closer to K, and is also visually separated from glue code.
