### ISSUE TITLE
[Bug] krun - Crashes after successful compilation of incorrect rule

### ISSUE THREAD

**Issue by uhbif19** [runtimeverification/k#2634]
K Version
---------

```
$ kompile --version
K version:    5.3.64
Build date:   Sun May 29 15:04:48 MSK 2022

```

Description
-----------

Using (incorrect, as far as I understand) rule, compiles okay, but crashes on krun.

Getting this error:

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Duplicate keys in map concatenation
/usr/bin/../lib/kframework/k-util.sh: line 85: 3429037 Aborted                 (core dumped) "$@"
[Error] krun: Backend crashed during rewriting with exit code 134
```

Input Files
-----------

```
    rule <k>X = Y => . ...</k>
        <env> ... .Map => X |-> N ... </env>
        <store> ... (N |-> (_ => Y)) ...</store>
```

Full file: https://pastebin.com/xU95uHNd

Reproduction Steps
------------------

kompile then krun file with this rule.

Expected Behavior
-----------------

Rule does not get compiled.

**Comment by radumereuta** [comment]
We ran into this issue recently: https://github.com/runtimeverification/k/issues/2565

**Comment by radumereuta** [comment]
This is a limitation of the LLVM backend, and it's hard for the front end to give a proper error message every time.
In this case, using the _map-update_ operator would have been preferred.

**Comment by Baltoli** [comment]
By the way @uhbif19, the reason that you see a message related to _map concatenation_ specifically here is that the line:
```k
<env> ... .Map => X |-> N ... </env>
```
in your example ends up looking something like this internally:
```k
<env> M => M X |-> N </env>
```
which is closer to what you can see in #2565.
