### ISSUE TITLE
Nix (macos-11) is slow

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2635]
This step usually takes a lot longer than the rest of the steps.
One thing we noticed is we're rebuilding Z3 every time.
Maybe we can have a separate step in here: https://github.com/runtimeverification/k/blob/master/.github/workflows/test.yml
Before `- name: 'Build K Framework'` we could have `-name: 'Fetch from cache'`

Bonus: The Mac build should focus mainly on ensuring we have the right dependencies. We shouldn't run too many tests. Maybe only `regression-new`.
Bonus2: All the nix stuff should be in a separate directory. Maybe `package/nix`

**Comment by radumereuta** [comment]
Looking over the build log, it looks that we are still rebuilding too much:
```
these derivations will be built:
  /nix/store/2m0drnp6ndr144gk1fshh51g43g11mym-llvm-backend-0.drv // could be cached
  /nix/store/d3cbnk1fkjl03x71m1fv45v8pcfyhflm-kore-0.60.0.0.drv  // could be cached
  /nix/store/sh42a46582cbz44k5lc7qcn3r15dxx9s-z3-4.8.15.drv      // could be cached
  /nix/store/jxzy5hpc65dl4xz0bfj0gc5875lnba6a-k-5.3.0.drv        // duplicate 1?
  /nix/store/ijq9mw2ypwv5afrb51adhr9r06szgxs7-k-5.3.0.drv        // duplicate 2?
```
Taken from this PR which changed only some documentation: https://github.com/runtimeverification/k/pull/2665

Another thing which is odd, we're rebuilding K twice. The hash is different but the human readable part is the same.

Probably the Nix Flake stuff should take care of this.

**Comment by radumereuta** [comment]
We need to update the `flake.lock` file with the proper revision for each dependency in the automatic pull requests that update the main K repo.

**Comment by goodlyrottenapple** [comment]
Closing. This has been fixed by correctly caching builds in the cachix cache, which was not functional in github actions in this repo. Any further specific improvements to the nix build speed should have a new issue.
