### ISSUE TITLE
[Bug] GDB support on Ubuntu Jammy

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2637]
@jberthold identifies that GDB support for K might not work out of the box on Ubuntu Jammy: https://runtimeverification.slack.com/archives/C7E701MFG/p1653962702305949

We should investigate this to see what's going on.

**Comment by jberthold** [comment]
Just re-tested this with binary K packages (5.3.67) on two machines which had no K installed or built prior. 
`gdb` support works on Ubuntu Focal but not on Ubuntu Jammy, output on Jammy is 
```
Temporary breakpoint 1, 0x0000555555594b10 in main ()
0x000055555558ce70 in step (subject=Python Exception <class 'gdb.error'>: No type named string.
0x7ffff5400138) at /home/jost/work/RV/test-gdb/test.k: <LINE>
```
where LINE seems to always be the line of the last rule in the compiled main module.

**Comment by Baltoli** [comment]
It seems like with LLVM 14, the debug information isn't being emitted to the interpreter object file correctly. The exception we see here is thrown [here](https://github.com/runtimeverification/llvm-backend/blob/036de597eea7125974539f198714d70974ffa241/gdb/kllvm.py#L363), when the GDB script tries to look up the backend's runtime types.

On Focal / LLVM 12, I can see that references to these types exist in the debug section for kompiled interpreters:
```console
root@3eafa567b392:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
root@3eafa567b392:~# objdump -g test-kompiled/interpreter 2>/dev/null | ag stringbuffer
    <37d29>   DW_AT_name        : (indirect string, offset: 0x291683): stringBuffer
...
```

These `DW_AT_name` entries are not present on Jammy; this may be to do with a change in the DWARF version that we emit: https://github.com/runtimeverification/llvm-backend/pull/517

@dwightguth @gtrepta any ideas?

* [Debug info codegen]( https://github.com/runtimeverification/llvm-backend/blob/c40f82fd0079af9208abe49ee3013626d28f1dc4/lib/codegen/Debug.cpp)
* [GDB script](https://github.com/runtimeverification/llvm-backend/blob/master/gdb/kllvm.py)

**Comment by Baltoli** [comment]
In fact, I think the problem is actually GDB here: https://discourse.llvm.org/t/gdb-10-1-cant-read-clangs-dwarf-v5/6035

**Comment by Baltoli** [comment]
In GDB on Focal I see (using `stringbuffer` as a more unique grep target; the problem is the same as for `string` above in the original issue):
```
(gdb) info types stringbuffer
All types matching regular expression "stringbuffer":

File ./llvm-backend/src/main/native/llvm-backend/include/runtime/header.h:
70:	stringbuffer;
74:	typedef stringbuffer stringbuffer;
```

On Jammy:
```
(gdb) info types stringbuffer
All types matching regular expression "stringbuffer":
```

**Comment by Baltoli** [comment]
Interestingly, `lldb` on Jammy is able to look up the types correctly:
```
(lldb) image lookup --type stringbuffer
5 matches found in /root/test-kompiled/interpreter:
id = {0x0003b8c3}, name = "stringbuffer", byte-size = 24, decl = header.h:74, compiler_type = "typedef stringbuffer"
     typedef 'stringbuffer': id = {0x0003b8cc}, name = "stringbuffer", byte-size = 24, decl = header.h:70, compiler_type = "struct stringbuffer {
    blockheader h;
    uint64_t strlen;
    string *contents;
}"id = {0x0003b8cc}, name = "stringbuffer", byte-size = 24, decl = header.h:70, compiler_type = "struct stringbuffer {
    blockheader h;
    uint64_t strlen;
    string *contents;
}"id = {0x0005e349}, name = "stringbuffer", byte-size = 24, decl = header.h:74, compiler_type = "typedef stringbuffer"
     typedef 'stringbuffer': id = {0x0003b8cc}, name = "stringbuffer", byte-size = 24, decl = header.h:70, compiler_type = "struct stringbuffer {
    blockheader h;
    uint64_t strlen;
    string *contents;
}"id = {0x00067815}, name = "stringbuffer", byte-size = 24, decl = header.h:74, compiler_type = "typedef stringbuffer"
     typedef 'stringbuffer': id = {0x0003b8cc}, name = "stringbuffer", byte-size = 24, decl = header.h:70, compiler_type = "struct stringbuffer {
    blockheader h;
    uint64_t strlen;
    string *contents;
}"id = {0x0025bc08}, name = "stringbuffer", byte-size = 24, decl = header.h:74, compiler_type = "typedef stringbuffer"
     typedef 'stringbuffer': id = {0x0003b8cc}, name = "stringbuffer", byte-size = 24, decl = header.h:70, compiler_type = "struct stringbuffer {
    blockheader h;
    uint64_t strlen;
    string *contents;
}"
```

Using `llvm-dwarfdump-{12,14}` to see what's in the files confirms that the information _is_ in fact in the files. The output is verbose so I've not included it here, but you can run:
```
llvm-dwarfdump-12 test-kompiled/interpreter --name=stringbuffer
llvm-dwarfdump-14 test-kompiled/interpreter --name=stringbuffer
```
and compare the outputs.

**Comment by radumereuta** [comment]
Try to minimize this and check to see if we need to report this upstream to GDB.
In the short term, we could add support for lldb as an alternative.
Use llvm-reduce to produce a smaller intermediate file.

**Comment by Baltoli** [comment]
I've done some more investigation into this, and I suspect that the problem is in the way that we're doing debug codegen [here](https://github.com/runtimeverification/llvm-backend/blob/master/lib/codegen/Debug.cpp). On Jammy, _no_ type information except the explicitly-added `.debug_pubtypes` section is available in the generated executable. This means that no types declared in the runtime library or any object files are visible.

I've tested the following scenario:
* Kompile two instances of the same semantics, one on Jammy and one on Focal (i.e. using LLVM 14 and 12 respectively).
* Verify that GDB can read the debug type information for the version compiled on Focal / 12, but _cannot_ for the version compiled on Jammy / 14.
* Swap the compiled `asm.o` from Focal into the Jammy `llvm-kompile` process, such that all other steps are unmodified.
* Observe that the debug type information is now available in the resulting executable.

This suggests to me that there's some problem with the way we're emitting debug information that prevents GDB from properly reading type information from the resulting executable.

My next step is to build a version of the LLVM backend on Jammy that doesn't try to do _any_ debug code generation, but is otherwise unmodified. If that succeeds, it will give me a way to narrow down the source of the problem.
* Confirmed this is the case by explicitly setting `0` as a flag to `llvm-kompile-codegen` even when `-g` is present.
* This probably means that we're trampling on something when emitting _our_ custom debug information.

Otherwise, it will be a case of examining the LLVM IR and object files produced for each code-generated module and inspecting them for breakages between versions.

**Comment by Baltoli** [comment]
It's a bit tricky to do because of the dependencies between the bits of debug information that we're emitting, but the problem does seem to be that emitting our own debug information causes the _existing_ debug information to get trampled for some reason.

You can verify this by looking at the output of `info functions` for a Focal / Jammy interpreter binary respectively. On Focal, the backend runtime functions have debug information attached; on Jammy, they're listed as non-debugging symbols.

The next step is to figure out exactly where in the `llvm-kompile` pipeline this is happening. This will most likely be a process of working through the same compilation steps using `llc` 12 / 14.

**Comment by dwightguth** [comment]
@Baltoli is it possible that the metadata we emit about the debug information is incorrect on Jammy somehow?

**Comment by dwightguth** [comment]
You might want to compare the global metadata we emit to the global metadata emitted by clang.
