### ISSUE TITLE
[kompile] `unused` and `no-evaluators` seem to do similar things

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#2663]
The attributes for syntax `unused` and `no-evaluators` seem to do similar things.
`unused` gives a hidden warning from kompile if it hasn't been used in any rule, in any location.
`no-evaluators` seem to be used mostly by the haskell backend.

@ana-pantilie can we merge them somehow?

Found this issue while working on #2618 and #2446

**Comment by ana-pantilie** [comment]
`no-evaluators` means that the function symbol is _meant_ to not have any rules for evaluating it (rules where it appears specifically at the top). `unused` seems to mean something else, from your description.
