### ISSUE TITLE
Forbid `anywhere` attribute on `simplification` rules

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2688]
Now that we don't need to put `anywhere` on simplification rules targeting ML predicates, we should forbid this behavior so that lemmas written in this way need to be updated.

Later, if it makes sense, we can un-forbid it.

**Comment by dwightguth** [comment]
I don't think it makes sense to allow this; `anywhere` as an attribute is intended to indicate that something is an "anywhere rule", which is essentially a type of axiom over which something constructor-like is defined. The Haskell backend doesn't currently support these, but it doesn't make sense for something to be both an anywhere rule and a simplification rule.

**Comment by ana-pantilie** [comment]
I agree, but what was the limitation before? When was this fixed?

**Comment by dwightguth** [comment]
The limitation was that simplification rules would be compiled to kore incorrectly if they didn't have that attribute. I'm reasonably sure that's no longer the case.
