### ISSUE TITLE
Display suggestions for KCFG printer

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2703]
- [x] Substitutions on abstraction edges should be displayed as Maps, not as ML constraints. Otherwise you get constraints which look like `X #Equals f(X)`, which seems to imply some fixed-point of `f` being computed, when actually what's meant is "replace `X` with `f(X)`".
- [x] I would move the constraint display to _after_ the node instead of before it on branches. Maybe even on the same line if it's a 1-liner.
- [x] Let's display constraints as `Bool` instead of ML predicates, they are more readable/compact, and closer to what the user writes in claims.
- [x] Should display, for each edge, if it's verified or not.
- [x] Abstractions should be indented, for easier visualization.
- [x] #2715
- [x] Move to pretty printing to own module.

**Comment by ehildenb** [comment]
![Screenshot from 2022-07-09 09-55-15](https://user-images.githubusercontent.com/12721972/178113182-7e627c98-2d1a-45bd-b508-009e5f46540e.png)

Example diff-output that should be much smaller, but because our sorting is dependent on node-hashes and the node-hashes changed, then the sub-tree order changed.

Another option would be to sort substrees to display by the contents of their edges, so use the constraints on the edge or abstractions on the edge as the sort-key.

**Comment by nishantjr** [comment]
Fixed in https://github.com/runtimeverification/k/pull/2725 and https://github.com/runtimeverification/k/pull/2714
