### ISSUE TITLE
K Tutorial on literate programming needs to be viewed from source

### ISSUE THREAD

**Issue by charala1** [runtimeverification/k#2707]
Viewed on a browser, the section doesn't make sense because tags aren't visible. We need to either
a) make it explicit that it should be viewed from source (and include a link), or
b) fix what the user sees and forget about the file itself being correct in terms of being parse-able

Here is what it currently looks like: https://kframework.org/k-distribution/k-tutorial/1_basic/08_literate_programming/

**Comment by radumereuta** [comment]
@shd101wyy can we do something in the web interface?
