### ISSUE TITLE
[Bug] [kompile] - Compilation fails for simplifications with #Exists on right-hand side

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/k#2709]
K Version
---------

```
$ kompile --version
K version:    v5.3.98-5-g993674655
Build date:   Thu Jul 07 14:35:59 BST 2022
```

Description
-----------

Compilation fails for either of the following two simplification, which have the Matching-Logic `#Exists` on right-hand side:

```
rule { C #Equals { C }:>Int } => #Exists I1. { C #Equals I1:Int } [simplification]
rule { C #Equals { C }:>Int } => #Exists ?I1. { C #Equals ?I1:Int } [simplification]
```

Input Files
-----------

File `exists-simpl.k`, version 1:
```
module EXISTS-SIMPL-SYNTAX 
endmodule

module EXISTS-SIMPL

  rule { C #Equals { C }:>Int } => #Exists I1. { C #Equals I1:Int } [simplification, anywhere]

endmodule
```

File `exists-simpl.k`, version 2:
```
module EXISTS-SIMPL-SYNTAX 
endmodule

module EXISTS-SIMPL

  rule { C #Equals { C }:>Int } => #Exists ?I1. { C #Equals ?I1:Int } [simplification, anywhere]

endmodule
```

Reproduction Steps
------------------

Run: `kompile exists-simpl.k --backend haskell`

For version 1: 
```
[Error] Compiler: Cannot encode equations with existential variables to KORE.
 If this is desired, please use #Exists with regular variables.
 Offending variables: [?I1]
```

For version 2:
```
[Error] Compiler: Found variable I1 on right hand side of rule, not bound on
left hand side. Did you mean "?I1"?
        Source(/Users/petarmax/Projects/RV/exists-simpl.k)
        Location(6,44,6,46)
        6 |       rule { C #Equals { C }:>Int } => #Exists I1. { C #Equals I1:Int }
[simplification]
```          .                                

Expected Behavior
-----------------

At least one of the two simplifications being allowed by the compiler.

**Comment by radumereuta** [comment]
Offending check is in [ModuleToKORE](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L943)
Is there something special about `#Exists_._` that these checks should pay more attention to?

**Comment by PetarMax** [comment]
I'm not sure how to answer that. Perhaps that, unlike other `?X`-type existentials, `#Exists` introduces the existential explicitly before using it?

**Comment by radumereuta** [comment]
I was hoping to get the opinion of @traiansf since he is the original developer of that check.
Or at least @ehildenb or @dwightguth.

**Comment by PetarMax** [comment]
Yes, definitely, I'm curious as well, I'm not quite understanding what's happening and why/why not.

**Comment by traiansf** [comment]
The rationale for disabling `?` variables in equations was to prevent them being used by mistake in a function definition rule, as usually that would make the function non-functional. That is why the suggested alternative was to explicitly use #Exists instead.
Unfortunately, that conflicts with another check in [CheckRHSVariables](https://github.com/runtimeverification/k/blob/ab1b32ac19a05a57e8f52a74d4bd2c8dd465520c/kernel/src/main/java/org/kframework/compile/checks/CheckRHSVariables.java#L119)

I see, though, that CheckRHSVariables allows for the user to annotate some variables as unBound: `unboundVariables`. Maybe that could help? Or maybe we could automatically add the RHS-bound `#Exists` variables to be otherwise unbound?

**Comment by PetarMax** [comment]
My guess is that it should be fine to add explicit RHS-existentials to `unboundVariables`, but I don't have enough experience to properly assess and I'm not sure how big of a change that would be. Since it wasn't allowed until now, nothing should break?

**Comment by PetarMax** [comment]
Update: I've tried 

```rule { C:Constant #Equals { C }:>Int } => #Exists I. { C #Equals I:Int } [simplification, unboundVariables(I)]```

and I get an error:

```
kore-exec: [1469469] Error (ErrorException):
    Could not make sort
        SortKItem{}
    match sort
        SortConstant{}
    This is a program bug!
```

Attaching the bug report...
[kore-exec.tar.gz](https://github.com/runtimeverification/k/files/9094577/kore-exec.tar.gz)

**Comment by radumereuta** [comment]
Can you post the front-end input?
I'd like to have a look at the entire pipeline.

**Comment by ana-pantilie** [comment]
What's wrong with having `rule lhs(X) => rhs(X, ?Y) requires req(X) ensures ens(X, ?Y) [simplification]` translated to
```
rule \\implies(req(X), \\equals(lhs(X), \\exists(Y, \\and(rhs(X, Y), ens(X, Y))))
```

Ideally, we'd also support writing the ML version in K, without using that `unboundVariables` attribute. We should just take care to not combine ML syntax with question mark variables.

Now that we support simplification rules on other constructs like `#Equals` (and other ML connectives in the future), I think it would be sensible to fully support this feature. Thoughts?

**Comment by ehildenb** [comment]
I think the "free variable checker" probably has a  bug. `#Exists X . f(X)` should not consider `X` to be a free variable, so the free variable on RHS checker shouldn't care about it.

**Comment by radumereuta** [comment]
The free variable checker should be aware of ML binders. #Exists and #Forall.
There might be a few things that break. We can decide what to do then.

**Comment by dwightguth** [comment]
@PetarMax is this still affecting you?

**Comment by PetarMax** [comment]
@radumereuta @ehildenb Could the free variable calculation be adapted to not include `X` as a free variable (which would be correct), so that `unboundVariables` doesn't have to be used in these scenarios?

Otherwise, the issue is resolved.

**Comment by radumereuta** [comment]
`ComputeUnboundVariables` should have an extra set with `boundVariables`
And modify the case for KApply and when found in `#Exists` and `#Forall` it should not report it.
Add tests.
https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/checks/ComputeUnboundVariables.java#L46
