### ISSUE TITLE
KCFG should display output in a somewhat stable order even when hashes change

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#2715]
Everett:

> Instead of sorting edges to display by hash, which results in tree-re-arrangements as tests update and nodes change, sort them by how many lines it takes to display that node. Shorter ones first. Or sort by how deep the subtree is underneath it, deeper subtrees first. This will make test-output more stable, and probably will be more visually appealing.

**Comment by ehildenb** [comment]
Another option for sorting is lexicographically by the constraint. It would be visually random, but would be stable as long a the branching structure of the graph doesn't change.

**Comment by nishantjr** [comment]
Fixed in https://github.com/runtimeverification/k/pull/2725
