### ISSUE TITLE
Use Ubuntu Focal for main CI image

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2717]
Currently CI is failing (probably for everyone?) because of an outdated libc version when building Calibre for making the website.

We can just switch the main CI image to use focal instead of bionic. Focal's libc is sufficiently new to not trigger this issue with Calibre, and I think packaging for Bionic should continue to work fine (which does not require Calibre).

This is the line/file in question: https://github.com/runtimeverification/k/blob/99367465571438c11850838a6411ce690be8968d/Dockerfile#L1

This Dockerfile is hardly used for much, just building the source tarball and putting together the release (in blocks like this: https://github.com/runtimeverification/k/blob/master/Jenkinsfile#L30). It probably can be trimmed down quite a bit, I doubt it even needs to be able to build K.

**Comment by F-WRunTime** [comment]
https://github.com/runtimeverification/k/issues/2720#issuecomment-1180808615

**Comment by F-WRunTime** [comment]
Sam's comment from other "would it be worth consolidating the effort from nix and building the docker images from nix? e.g. https://thewagner.net/blog/2021/02/25/building-container-images-with-nix/ "

**Comment by F-WRunTime** [comment]
I think this is interesting. @goodlyrottenapple  this would Consolidate also the caching effort of nix and docker, I think. Focus 
on reducing the shared size of nix cache data across builders.

**Comment by F-WRunTime** [comment]
@goodlyrottenapple Just pinging you. This is where the issue got consolidated to. We can continue the discussion here as part of reducing Dockerfile complexities / sizes

**Comment by F-WRunTime** [comment]
TODO to close this issue: 
6/13/22
- [ ] Collect Dockerfiles within github/org look for common places to reduce 'RUN apt-get install <package>' -- this is time consuming and space inefficient across build systems. 
- [ ] Publish a common image to internal registry for reference 
- [ ] Create a workflow to publish a new image based on updates to "Build Image Base" Dockerfile
- [ ] Propagate usage of Base "Build Image Base" to repositories building their own image on every CI run
