### ISSUE TITLE
[nix] Keep haskell-backend and llvm-backend flake inputs in sync with submodules

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/k#2718]
We need to add the following to the script which updates the haskell/llvm submodules and pushes to master:

```
nix flake lock \
  --override-input haskell-backend github:runtimeverification/haskell-backend/<hash> \
  --override-input llvm-backend github:runtimeverification/llvm-backend/<hash> \
  --recreate-lock-file
```

@F-WRunTime not sure where exactly we update and push the submodules?

**Comment by radumereuta** [comment]
Is this the one? https://github.com/runtimeverification/devops/blob/master/update-deps.sh
You might need to explore the entire repo though. The dependency graph seems to reside [here](https://github.com/runtimeverification/devops/tree/master/deps/runtimeverification).

**Comment by goodlyrottenapple** [comment]
Yeah, I think `update-deps.sh` is the one: https://github.com/runtimeverification/devops/blob/f27618641a4eb4fcc7195cca730814639c38fe37/update-deps.sh#L68

Not sure if `rv_jenkins` is set up with `nix` atm tho.

**Comment by radumereuta** [comment]
This might be a potential solution: https://github.com/runtimeverification/evm-semantics/pull/1274

**Comment by F-WRunTime** [comment]
@goodlyrottenapple Is this something we're currently doing already? This was also causing merge issues with the flake.lock file?

**Comment by goodlyrottenapple** [comment]
we have a check in github ci which fails if they are not in sync, but we probably want to automate the sync when we update submodules via the automated rv-jenkins script

**Comment by ehildenb** [comment]
Let's move [this `nix-flake-submodules`](https://github.com/runtimeverification/k/blob/master/.github/workflows/test-pr.yml#L80) step to a new file called `.github/workflows/update-deps.yml`, which is only run on update-deps branch, similar to [how KEVM does it](https://github.com/runtimeverification/evm-semantics/blob/master/.github/workflows/update-version.yml).
