### ISSUE TITLE
Reduce 'k' Dockerfile Complexity to use a common dockerfile stored in devops-actions

### ISSUE THREAD

**Issue by F-WRunTime** [runtimeverification/k#2720]

**Comment by goodlyrottenapple** [comment]
would it be worth consolidating the effort from nix and building the docker images from nix? e.g. https://thewagner.net/blog/2021/02/25/building-container-images-with-nix/

**Comment by F-WRunTime** [comment]
Interseting. Closing as duplicate of another issue in 'k' repository
