### ISSUE TITLE
[nix] - Enable a subset of the `regression-new` tests for the CI

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/k#2726]
We should enable these tests in the CI: https://github.com/runtimeverification/k/tree/master/k-distribution/tests/regression-new
However, the full test suite takes too long to be ran on every commit, so we either only enable it for e.g. release or only run some core subset on every push... or ideally both?

**Comment by radumereuta** [comment]
Running regression-new takes 2 minutes on my machine. (32 threads) Running all the tests should take ~5min. At most 10min. That includes the pl-tutorial, and the k-exercises.
Why do you say it takes too long?
Are you sure you are running the `kserver` before running the tests? That improves the time spent ~3X.

**Comment by goodlyrottenapple** [comment]
no, running the `kserver` setup in the CI environment has not been investigated.

**Comment by radumereuta** [comment]
You can take a look at how Jenkins is using it: https://github.com/runtimeverification/k/blob/master/Jenkinsfile#L77

**Comment by radumereuta** [comment]
Please double check if this is actually an issue.
We should strive to have tests for each repo that will catch errors as soon as possible.

**Comment by goodlyrottenapple** [comment]
Running these on the public runners would take too long. Perhaps if we migrate Jenkins to Github workflows, re-opening this might make sense.
