### ISSUE TITLE
Better handling of post-processing script path

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2730]
Suppose we want to run `kompile` with post-processing. Assume the following directory layout:

```
.
├── process.sh
└── test.k
```

Kompilation is successful if we give an absolute path to the post-processing script:

```bash
$ kompile test.k --post-process $(pwd)/process.sh
```

However, kompilation fails if we provide a relative path:

```
$ kompile test.k --post-process process.sh
[Error] Critical: Error while running process:Cannot run program "process.sh"
(in directory "."): error=2, No such file or directory (IOException: Cannot run
program "process.sh" (in directory "."): error=2, No such file or directory)
```

For the user, the directory pointed to in the error message is not informative. The path where `kompile` tried to look for the script should be printed as either an absolute path or a path relative to the working directory. More importantly, `kompile` should look for the script relative to the working directory.

**Comment by radumereuta** [comment]
We should discuss this.
Right now we do output stdout and stderr if we get an `exit code != 0`, and we do the same in different places.
```java
if (output.exitCode != 0) {
    throw KEMException.criticalError("Post-processing returned a non-zero exit code: "
            + output.exitCode + "\nStdout:\n" + new String(output.stdout) + "\nStderr:\n" + new String(output.stderr));
}
```

**Comment by radumereuta** [comment]
```
$ ./process.sh 1.test 
1 , 2 , 3 , 4
$ cat 1.test 
1 , 2 , 3 , 4
$ kompile test.k --post-process cat
$ kompile test.k --post-process process.sh 
[Error] Critical: Error while running process:Cannot run program "process.sh"
(in directory "."): error=2, No such file or directory (IOException: Cannot run
program "process.sh" (in directory "."): error=2, No such file or directory)
$ kompile test.k --post-process ./process.sh 
radu@radu:~/work/test$ cat process.sh 
#!/usr/bin/env sh

cat $1 
```
I think we already have the correct behavior.
Your script is local, so if you want to run it with a relative path, then you have to specify it with `./<my-local-script>`
If you add your script to `PATH`, then it's going to work the way you want it.

**Comment by tothtamas28** [comment]
> Your script is local, so if you want to run it with a relative path, then you have to specify it with `./<my-local-script>`

:facepalm: Right, forgot the dot. Closing this issue.
