### ISSUE TITLE
Structured bug report templates

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2745]
Our issue templates can be improved. Look at Foundry's: https://github.com/foundry-rs/foundry/issues/new?assignees=&labels=T-bug&template=BUG-FORM.yml

We can similarly have a structured input form for issues.
- [x] front end
- [x] haskell backend (@ana-pantilie )
- [x] llvm backend

**Comment by F-WRunTime** [comment]
Check out the provided bug-report.yaml on the working feature/bug-performance-testing branch on k. 
Please provide some feedback @ana-pantilie if you have any. Tackled this while making the template for Performance.

**Comment by F-WRunTime** [comment]
I can assign multiple people. Or we can look to break this out into 3 different templates and have 3 different default assignees? 
This intended just for triage and expect others to be assigned. 
Alternatively we stick with a single person who handles triage and is the default assignee. 

FrontEnd - @radumereuta ?  
Haskell backend - @ana-pantilie 
llvm - @Baltoli  ?

**Comment by ehildenb** [comment]
I think we don't need a default assignee. It would be nice if it could automatically be put onto the K Development board though, in the Triage column.

**Comment by ehildenb** [comment]
Also, can you open it as a PR so it's easier to see the new template?

**Comment by ana-pantilie** [comment]
> Check out the provided bug-report.yaml on the working feature/bug-performance-testing branch on k.

Looks good to me! 👍

**Comment by Baltoli** [comment]
That template looks great @F-WRunTime - big improvement over the current setup!

I agree that we don't necessarily need a default assignee - at least for the LLVM backend, a new issue is equally likely to get picked up by me or Theo. Making sure that it doesn't get lost and does end up on the triage list so we remember to look at it in the K meeting is the important thing really.

**Comment by F-WRunTime** [comment]
Opened as a PR here: https://github.com/runtimeverification/k/pull/2868 for easier viewing @ehildenb 

I don't unfortunately see a way for it to automatically go to the board. But Maybe I'm missing some configurations. I'm still working with this for the haskell-backend side. If I learn something new I can come back and apply it to k.

**Comment by F-WRunTime** [comment]
Okay did some diving into the community forums for github and looks like the feature to have repository created issues pushed straight into a project board is still open: 
https://github.com/github/roadmap/issues/286 

Subscribed to the issue see if we see any progress on it. Worst case we can dive into the API and see if we can make some automation around bundling together repositories a single board if they're not assigned already.
