### ISSUE TITLE
Could not initialize class org.fusesource.jansi.internal.CLibrary

### ISSUE THREAD

**Issue by sharonz2006** [runtimeverification/k#275]
Using latest builds/src of KFramework running KSolidity tests, the error is the output. Am I missing some Java libraries? Please advise. Thanks in advance.

 ./ksol run tests/t1.sol
[Error] Internal: Uncaught exception thrown of type NoClassDefFoundError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (Could not
initialize class org.fusesource.jansi.internal.CLibrary)
sharon@ubuntu:~/ksolidity/solidity-semantics$ ./ksol run tests/t1.sol --debug
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.CLibrary
        at org.kframework.utils.inject.CommonModule.ttyInfo(CommonModule.java:52)
        at org.kframework.utils.inject.CommonModule$$FastClassByGuice$$afc7bd66.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:230)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:148)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:107)
        at org.kframework.main.Main.main(Main.java:53)

**Comment by dwightguth** [comment]
NoClassDefFoundErrors usually result from improperly built code that has stale or incorrect classpaths. Can you try doing `mvn clean; mvn package` in K and see if this resolves the issue? If not, I will need the result of `kompile --version`.

**Comment by sharonz2006** [comment]
Can't use "mvn package" in K now due to issue with artifacts download failure from S3 from Amazon. So I am using the latest pre-built package from  https://github.com/kframework/k/releases. 

kompile --version output:

RV-K version 1.0-SNAPSHOT
Git revision: dc09401
Git branch: UNKNOWN
Build date: Tue Jan 29 10:46:54 PST 2019

**Comment by sharonz2006** [comment]
Here is output for `mvn clean`
sharon@ubuntu:~/ksolidity/solidity-semantics/.build/k$ mvn clean
[INFO] Scanning for projects...
Downloading: https://s3.us-east-2.amazonaws.com/runtimeverificationmaven/internal/com/github/platform-team/aws-maven/6.0.0/aws-maven-6.0.0.pom
Downloading: https://repo.maven.apache.org/maven2/com/github/platform-team/aws-maven/6.0.0/aws-maven-6.0.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.github.platform-team:aws-maven:6.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.platform-team:aws-maven:jar:6.0.0 @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.runtimeverification.k:parent:1.0-SNAPSHOT (/home/sharon/ksolidity/solidity-semantics/.build/k/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin com.github.platform-team:aws-maven:6.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.platform-team:aws-maven:jar:6.0.0: Could not transfer artifact com.github.platform-team:aws-maven:pom:6.0.0 from/to runtime.verification (https://s3.us-east-2.amazonaws.com/runtimeverificationmaven/internal): Connect to s3.us-east-2.amazonaws.com:443 [s3.us-east-2.amazonaws.com/52.219.88.43] failed: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by dwightguth** [comment]
If you're outside the united states, it could just be timing out because it's slow. Try increasing the timeout.

**Comment by dwightguth** [comment]
What OS are you on?

**Comment by sharonz2006** [comment]
I am in Champaign, not outside of US. my OS is Ubuntu 16.04, 0 LTS. How does one increase the timeout?

**Comment by dwightguth** [comment]
That's definitely not it if you're in Champaign. Are you behind any kind of proxy that blocks internet access by default?

**Comment by sharonz2006** [comment]
Yes, it is behind a corporate proxy

**Comment by sharonz2006** [comment]
I can access github and other outside URL via this proxy

**Comment by sharonz2006** [comment]
But, some sites may be blacklisted which I will not be able to access

**Comment by dwightguth** [comment]
Not much I can do about that if s3 is blacklisted. I will test to make sure that the built binary distribution works though.

**Comment by sharonz2006** [comment]
Is my mvn package issue the same as https://github.com/kframework/k/issues/251?

**Comment by dwightguth** [comment]
No, that issue is resolved. Your issue is that your company is blocking connections to our S3 bucket containing the dependencies it needs to download in order to build K from source. We plan to migrate everything to maven central which should hopefully resolve the issue but that will take time and won't happen overnight or even in the next couple weeks.

**Comment by dwightguth** [comment]
I cannot reproduce your NoClassDefFound error by the way. I believe the problem is that an exception is being thrown in a static initializer in the jansi library, but your report does not include that stack trace. Without being able to reproduce, I can't investigate further. But the source of the error would seem to suggest that there is a problem loading the native jansi library. Have you done anything funny with the installation of libc on your machine?

**Comment by sharonz2006** [comment]
OK, I will try outside of the proxy tomorrow and see if I can get it running. Thanks for your help!

**Comment by sharonz2006** [comment]
After trying to install from the pre-built binaries from outside of our company firewall, I was able to run the program fine. Thanks for the hints. I therefore close the issue now...
