### ISSUE TITLE
Error when compiling the sample kernelc semantics

### ISSUE THREAD

**Issue by daparpon** [runtimeverification/k#277]
Hi! I downloaded and installed the latest, master branch version of K 5.0, and executed "kompile" with the kernelc example specification in "samples-kore/kernelc". However, every time that I try it I get the following error message:

[Error] Compiler: Had 23 parsing errors.
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(104,5,104,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(112,5,112,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(121,5,121,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(147,5,147,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(156,5,156,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(163,5,163,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(209,5,209,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(229,5,229,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(256,5,256,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(261,5,261,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(271,5,271,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(276,5,276,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(286,5,286,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(291,5,291,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(412,5,412,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(428,5,428,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(439,5,439,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(451,5,451,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(461,5,461,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(469,5,469,6)
[Error] Inner Parser: Parse error: unexpected token '<'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(477,5,477,6)
[Error] Inner Parser: Parse error: unexpected token 'struct'.
	Source(/Users/elp/Documents/KFramework/K5.0/k-distribution/samples-kore/kernelc/kernelc-semantics.k)
	Location(21,8,21,14)

I did not modify anything in the provided files, everything remains as-is. What might be the reason for this problem and how can I solve it?

Thanks in advance.

**Comment by dwightguth** [comment]
I believe kernelc was never ported over to K 5.0, which has some particular idiosyncrasies to its parser. I would recommend renaming the `<struct>`, `<in>`, and `<out>` cells and see if that helps. There may be other minor things that need to be changed though. I don't have time to update the definition myself, but a pull request would be welcome if you get it working.

**Comment by ehildenb** [comment]
If this is still an issue, feel free to re-open.
