### ISSUE TITLE
kore-expand-macros takes a long time to do nothing

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2780]
In KEVM, we can run the script in 2 modes, (i) where we are invoking the `krun` frontend (https://github.com/runtimeverification/evm-semantics/blob/master/kevm#L117), and (ii) where we are directly invoking the `interpreter` binary (https://github.com/runtimeverification/evm-semantics/blob/master/kevm#L231). This is because it used to be that `krun` was calling the Java frontend, and we wanted to be able to bypass that. Now though, we have the bash `krun` script, and I am attempting to update `kevm`, and found this curious performance behavior.

I am experimenting with timing how much overhead each method has (so I can compare to a python runner script). Here is the delta I was using on the script:

```
diff --git a/kevm b/kevm
index c10c0dec4..b77e9237a 100755
--- a/kevm
+++ b/kevm
@@ -251,8 +251,9 @@ run_interpret() {
                  ;;
                 
         llvm)    run_kast kore > "$kast"
-                 if $debugger; then cmdprefix="gdb --args"; fi
-                 execute $cmdprefix "$interpreter" "$kast" -1 "$output" "$@" || exit_status="$?"
+                 ! ${debugger} || krun_args+=(--debugger)
+                 run_file="${kast}"
+                 run_krun --parser cat --term --output kore "$@" > "${output}"
                  if ${unparse} || [[ "$exit_status" != '0' ]]; then
                      cat "$output" | "${KEVM}" kast --backend "$backend" - pretty --input "$output_format" --sort GeneratedTopCell
                  fi
```

This, to my surprise, caused a massive slowdown! In particular, one test went from ~10s to ~60s. In general, the fastest tests had about ~100ms of overhead introduced (and many tests were running in ~5ms before any changes on my machine, so 20X slowdown). I added `--profile` to `kevm run ...` script, and found this trace (*~50s in `kore-expand-macros`!!!*):

```
% kevm interpret tests/ethereum-tests/BlockchainTests/GeneralStateTests/stStackTests/underflowTest.json  --backend llvm                                            \
    --mode NORMAL --schedule LONDON --chainid 1 --profile
0m2.245s 0m2.109s 0m0.136s kore-json.py tests/ethereum-tests/BlockchainTests/GeneralStateTests/stStackTests/underflowTest.json LblLONDON'Unds'EVM{}() LblNORMAL{}() \dv{SortInt{}}("1")
0m0.047s 0m0.000s 0m0.047s cat /tmp/tmp.mhsmSQZhcl
0m48.635s 0m47.731s 0m0.888s kore-expand-macros /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm .krun-2022-08-07-18-18-10-3ThRs4d5dp/tmp.in.0YpVPAEwNP
0m8.843s 0m8.261s 0m0.576s /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm/interpreter .krun-2022-08-07-18-18-10-3ThRs4d5dp/tmp.in.JQKVIUf3rY -1 .krun-2022-08-07-18-18-10-3ThRs4d5dp/result.kore
0m0.013s 0m0.010s 0m0.004s kore-print --definition /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm --output kore .krun-2022-08-07-18-18-10-3ThRs4d5dp/result.kore --color off
0m57.625s 0m56.017s 0m1.587s krun --definition /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm -cSCHEDULE=LblLONDON'Unds'EVM{}() -pSCHEDULE=cat -cMODE=LblNORMAL{}() -pMODE=cat -cCHAINID=\dv{SortInt{}}("1") -pCHAINID=cat /tmp/tmp.mhsmSQZhcl --parser cat --term --output kore --profile
```

Whereas, the original call to `kevm run ... --profile` with direct calling to `interpreter` binary, gives:

```
% kevm interpret tests/ethereum-tests/BlockchainTests/GeneralStateTests/stStackTests/underflowTest.json  --backend llvm                                            \                                                                         
    --mode NORMAL --schedule LONDON --chainid 1 --profile
0m2.253s 0m2.071s 0m0.168s kore-json.py tests/ethereum-tests/BlockchainTests/GeneralStateTests/stStackTests/underflowTest.json LblLONDON'Unds'EVM{}() LblNORMAL{}() \dv{SortInt{}}("1")
0m8.858s 0m8.256s 0m0.596s /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm/interpreter /tmp/tmp.ZCOO0WL5Fn -1 /tmp/tmp.cqirXm1pmj --profile
```

So, after adding `--no-expand-macros` to the invocation of `krun` that we use, we get this from `kevm run ... --profile`

```
% kevm interpret tests/ethereum-tests/BlockchainTests/GeneralStateTests/stStackTests/underflowTest.json  --backend llvm                                            \                                                                   
    --mode NORMAL --schedule LONDON --chainid 1 --profile
0m2.217s 0m2.100s 0m0.116s kore-json.py tests/ethereum-tests/BlockchainTests/GeneralStateTests/stStackTests/underflowTest.json LblLONDON'Unds'EVM{}() LblNORMAL{}() \dv{SortInt{}}("1")
0m0.046s 0m0.000s 0m0.045s cat /tmp/tmp.po2jFeWp5L
0m0.071s 0m0.000s 0m0.070s cp .krun-2022-08-07-18-30-57-BcGXJE8rwC/tmp.in.aXT0Epojnl .krun-2022-08-07-18-30-57-BcGXJE8rwC/tmp.in.PtwazRl3RF
0m8.832s 0m8.246s 0m0.580s /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm/interpreter .krun-2022-08-07-18-30-57-BcGXJE8rwC/tmp.in.PtwazRl3RF -1 .krun-2022-08-07-18-30-57-BcGXJE8rwC/result.kore
0m0.013s 0m0.011s 0m0.003s kore-print --definition /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm --output kore .krun-2022-08-07-18-30-57-BcGXJE8rwC/result.kore --color off
0m9.029s 0m8.275s 0m0.749s krun --definition /home/dev/src/evm-semantics-pr/.build/usr/lib/kevm/llvm -cSCHEDULE=LblLONDON'Unds'EVM{}() -pSCHEDULE=cat -cMODE=LblNORMAL{}() -pMODE=cat -cCHAINID=\dv{SortInt{}}("1") -pCHAINID=cat /tmp/tmp.po2jFeWp5L --parser cat --no-expand-macros --term --output kore --profile
```

Back down to ~10s or so. In general, it appears that invoking the `krun` bash script has about ~5ms overhead over direct invocation of `interpreter` binary.

------------------------------------------------------------

The thing is, this input is generated by the file [`kore-json.py`](https://github.com/runtimeverification/evm-semantics/blob/master/scripts/kore-json.py), which _directly_ generates Kore that can be executed by the backend, and has no macros in it. Why is `kore-expand-macros` taking so long on this one input file in particular?

Attached is the necessary inputs (`macros.kore`, `syntaxDefinition.kore`, and ` tmp.in.UMrAtAKE0e` - [if only there was a way to collect this information automatically](https://github.com/runtimeverification/k/issues/2525)). You can run:

```
% tar -xvf kevm-kore-expand-macros.tar.gz
% time kore-expand-macros kevm-kore-expand-macros kevm-kore-expand-macros/tmp.in.UMrAtAKE0e
.... bunch of kore output ....
kore-expand-macros    46.88s user 1.10s system 98% cpu 48.487 total
```

[kevm-kore-expand-macros.tar.gz](https://github.com/runtimeverification/k/files/9277275/kevm-kore-expand-macros.tar.gz)

**Comment by ehildenb** [comment]
This isn't blocking anything, I can use option `--no-expand-macros`. Just figure we should identify the performance issue here.

**Comment by Baltoli** [comment]
I found a bit of low-hanging fruit [here](https://github.com/runtimeverification/llvm-backend/pull/543); this took the running time from 2m30 to 1m54 on my machine.

There are macros in the definition you provide, so we can't elide the macro expansion step completely without walking the entire input term to check it doesn't use any (_you_ know this because you generated the term, of course). I think it would need a more substantial redesign to improve the performance further.

A `perf` trace of the new version reveals that most of the time spent (after the above PR) is in the recursive call stack to `expandMacros`; the only other point that's close to being a hotspot is the matching function for composite patterns (~20% of run time on my machine).

**Comment by ehildenb** [comment]
The LLVM backend can surely do this macro expansion faster? Is the reason it's slow because we're using a separate less-standard rewriting for this macro expander? Is it possible to use the LLVM backend directly (like kompile a definition for it to consume?)

**Comment by Baltoli** [comment]
Yes, sorry for not expanding on what I meant by a "more substantial redesign" - the macro expansion is done at the AST level, rather than on runtime terms. This is why there's so much overhead compared to actually executing terms; it's essentially a tree-walk interpreter for a different semantics of the definition.

Conceptually I _think_ you could work out a way to compile that semantics to something the backend could execute directly. You'd have to emit + compile a definition where the macros are the _only_ rules, while also ensuring that the "at most once" property is maintained. I haven't thought through that in any detail though - @dwightguth any thoughts?

**Comment by dwightguth** [comment]
I mean, conceptually, we can't do better than linear in the size of the input term. That being said, if the input term contains no productions over which macros have been defined, it ought to basically just walk the term once and do nothing. Is it doing substantially more work than that currently?

**Comment by Baltoli** [comment]
It's `O(size of term * number of macros)` currently.

For each node in the AST, it iterates through the list of macros and checks whether they've been applied yet (or are recursive), then tries to match the current node against the LHS of the macro and apply the RHS with the resulting substitution if possible.

**Comment by dwightguth** [comment]
Okay. We ought to be able to do better than that. Why don't we preprocess the axioms to generate a set of symbols that have macros associated with them, and then skip testing the axioms if the symbol we're currently at isn't in the set.

**Comment by ehildenb** [comment]
I guess it should probably be something more like `O(size of term * log(number of macros))` at most (should be very quickly able to decide "no macros apply at this position" using a simple bloom filter).

Are we using the exact same code that LLVM backend uses for applying `anywhere` rules? Because if not, I guess that would be faster.

**Comment by dwightguth** [comment]
@ehildenb we are using a very different code path for macros, but it would be nontrivial to change. I don't think it's worth trying until we see if we can effectively optimize the current code path.

**Comment by Baltoli** [comment]
Yes, the problem is the current `O(no. of macros)` logic for determining "no macros apply here". Let me take a look at optimising that a bit and see where I can get it to.
