### ISSUE TITLE
Follow modifications to HS-Backend JSON-RPC protocol 

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/k#2804]
https://github.com/runtimeverification/haskell-backend/pull/3192 modifies the HS backend's JSON-RPC endpoint for `execute`. Specifically:
* The reason value `final-state` was removed;
* The `states` field was renamed to `next-states`;
* A new field `state` was added;
* The `condition` field within the list elements of `next-states` was flattened into the parent. States in the `execute` response are now always triplets of `term` (previously another `state`), `predicate` and `substitution`, each containing a kore json term;
* The `depth` fields in the state list were replaced by a single `depth` field at the top level;
* A new `rule` field was added, which is filled if `reason` is `cut-point-rule` or `terminal-rule`.
More details on these changes can be found [in the related issue](https://github.com/runtimeverification/haskell-backend/issues/3143#issuecomment-1210068504) and [in the JSON RPC server API documentation](https://github.com/runtimeverification/haskell-backend/blob/master/docs/2022-07-18-JSON-RPC-Server-API.md) as soon as the pull request is merged

**Comment by tothtamas28** [comment]
Related issue on backend: https://github.com/runtimeverification/haskell-backend/issues/3143
