### ISSUE TITLE
[KProve]Support rules with #Not at the top

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/k#2813]
With the following simplification rule added:

```
rule #Not ({ false #Equals X }) => { true #Equals X } [simplification]
```
I get an error when trying to prove the following claim:

```
claim #Not ({ false #Equals X }) => { true #Equals X } [symbolic, kore]
```

Current output is 
```
[Error] Compiler: Attempting to split non-cell term
#Not(#Equals(#token("false","Bool"),X))
```

**Comment by radumereuta** [comment]
We should be able to write simplification rules with any kind of ML connectives at the top.
@anvacaru can you provide a self contained minimal example? If you can't figure it out, let me know.
Also, the version of K.

**Comment by ana-pantilie** [comment]
Please move the issue to the Haskell backend repo when the frontend support is added.

**Comment by radumereuta** [comment]
Apparently, we are mismanaging the handling of sentences tagged with `kore`.
This should fix the front-end, but the backend still fails with:
```
kore-exec: [161378] Error (ErrorException):
    Unexpected empty set of claims.
    Possible explanation: the frontend and the backend don't agree on the representation of claims.
    CallStack (from HasCallStack):
      error, called at src/Kore/Exec.hs:745:26 in kore-0.60.0.0-FTbNwHSXtNTFc0vsLaZKzQ:Kore.Exec
```

**Comment by radumereuta** [comment]
@ana-pantilie: this claim should be handled as an equational claim, but we don't have that implemented yet.
The other issue is that the `kore` attribute takes a special path through the kompile pipeline which is not very clear to me.
Maybe @dwightguth or @ehildenb can shed some light on what `kore` means as an attribute on rules or claims.

I tried to fix the front end, and return valid KORE, but tests fail. One of the failing examples from `kbmc` started to return `#Top` which I find very surprising.

**Comment by radumereuta** [comment]
@anvacaru can you be more specific with regard to what you are trying to do?
After some investigation into why it was failing, we're still not sure what the proper fix would be.

**Comment by anvacaru** [comment]
@radumereuta I apologize for not being able to provide a minimal example. I was working on a claim and the backend got stuck with the following contradiction.
```
#And
  #Not ( {
    false
  #Equals
    #newAddr ( 1032069922050249630382865877677304880282300743300 , _Gen7 ) in _ACTIVEACCOUNTS_CELL
  } )
#And
  #Not ( {
    true
  #Equals
    #newAddr ( 1032069922050249630382865877677304880282300743300 , _Gen7 ) in _ACTIVEACCOUNTS_CELL
  } )
#And
<kevm>
...
```
I assumed that a lemma like `rule #Not ({ false #Equals X }) => { true #Equals X } [simplification]` would unblock the proof and wanted to first try the claim posted in the description of the issue.  Later I found out that in ML this is only an `implication`, and in order to be a  `simplification` it needs to also be `equivalent`. In the end, the main claim I was working on was incomplete and so I didn't need a simplification anymore.

**Comment by radumereuta** [comment]
Is this still an issue for your or can we close it?

**Comment by anvacaru** [comment]
We can close it.
