### ISSUE TITLE
Process failure in `k-util.sh` should be more informative

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2817]
I had a definition that was failing at macro expansion stage.

It only became apparent to me that this was the failure stage after adding `-v` to `krun`.

`k-util.sh` https://github.com/runtimeverification/k/blob/master/k-distribution/src/main/scripts/lib/k-util.sh should print out failing commands, so that the user knows what phase failed. But then it should still fail overall.

**Comment by radumereuta** [comment]
Minimal example?

**Comment by radumereuta** [comment]
Should look for every location in the scripts where we run external tools and report an error message where they fail.
There might be some exceptions though.
