### ISSUE TITLE
[pyk] factor out `get_singleton` or `single` method

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2820]
We use an idiom quite a bit when searching through K definitions, which is to get a list of things, and then check that the list length is 1, and error out otherwise.

This pattern could be factored out into `utils.py` as a `singleton` or `single` method: https://github.com/runtimeverification/k/pull/2808#discussion_r948821400

I'm not sure it's worth it, we should see the change in isolation. If it's only a handful of places it's used, the more complicated error message production may not be worth it.

**Comment by tothtamas28** [comment]
Closed by #2824
