### ISSUE TITLE
[kprove] - Allow `--input json`

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#2836]
Motivation
----------

Several constructs that come up in a programs semantics cannot be parsed with the rule parser---for example, the freezers generated by strictness. When unparsing with the pyk parser we also lose information such as operator precedence, unless parens are added.

Documentation
-------------

Add a `--input json` that allows passing a JSON/KAST encoded K definition.

Potential Alternatives/Work-arounds
-----------------------------------

We may move `ksummarize` to using the JSON RPC, though I'd rather not wait for that.

Testing Approach
----------------

Test that the frontend can accept a spec file emitted using `--emit-json-spec --dry-run`.

**Comment by radumereuta** [comment]
We want to skip parse time completely since it takes a substantial time for KEVM proofs.
We might want to insert right before ModuleToKORE.
This is a stopgap solution until we implement KORE-RPC.

**Comment by ehildenb** [comment]
We will be implementing this via kore-rpc instead, so that we skip parse-time entirely.
