### ISSUE TITLE
`kprove-error-status` test is flaky

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2885]
The test implemented in #2862 is flaky because it contains a Cabal hash in its expected output. This means that any change to the backend source code is going to cause this test to start failing.

It should be redesigned so that the hash is stripped out of that line in the test and expected output (as we do with absolute filenames).

**Comment by goodlyrottenapple** [comment]
specifically this one: https://github.com/runtimeverification/k/blob/16b3dc1d0d9c5418c3e91977576a6ccba747bd07/k-distribution/tests/regression-new/kprove-error-status/crash-spec.k.out

**Comment by goodlyrottenapple** [comment]
also, the line in the source code (`called at src/Kore/Rewrite/Function/Evaluator.hs:274:6`) will be prone to change, tho maybe not as often

**Comment by radumereuta** [comment]
Changing the sed script from the Makefile might be the easiest way.

**Comment by SchmErik** [comment]
This is definitely my bad! Why don't we make the sed script to ignore this part: 
`error, called at src/Kore/Rewrite/Function/Evaluator.hs:274:6 in kore-0.60.0.0-C6NIGnCldg2CHYuzj5V8fi:Kore.Rewrite.Function.Evaluator`

So the sed pattern looks something like `s/error, called at .*.hs:[0-9]\+:\[0-9]\+ in .*$//g`

**Comment by SchmErik** [comment]
we could actually keep `error, called at` so maybe the patter would look like this: `s/\(error, called at \).*.hs:[0-9]\+:\[0-9]\+ in .*$/\1/g`
