### ISSUE TITLE
`kup` command for managing Nix K versions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#2894]
Many of our users complain about our installation process, and we historically have trouble tools with different versions of K and such.

One installation process that everyone seems to like is the `curl SOME_URL | bash -` approach, especially if it does version management for the user. The Foundry tool, for example, has you [install `foundryup`](https://github.com/foundry-rs/foundry#installation), then you just run `foundryup` when you need to update, and automatically get the newest version, all installed in the users home directory. Similarly, the Rust compiler `rustc` has [`rustup`](https://rust-lang.github.io/rustup/) for managing compiler toolchains. [dapp.tools](https://github.com/dapphub/dapptools#installation) does similarly, they have a user run `curl https://dapp.tools/install | sh`, which does (i) install Nix, (ii) install the nix expression for that package at that version. Then we just have to rely on having Nix derivations for everything, which may be easier long-term than having platform specific binaries produced on CI (though we probably _do_ still want to populate some public Nix caches so that users can have super fast installation).

Here is `rustup help`:

```
rustup 1.24.3 (ce5817a94 2021-05-31)
The Rust toolchain installer

USAGE:
    rustup [FLAGS] [+toolchain] <SUBCOMMAND>

FLAGS:
    -v, --verbose    Enable verbose output
    -q, --quiet      Disable progress output
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <+toolchain>    release channel (e.g. +stable) or custom toolchain to set override

SUBCOMMANDS:
    show           Show the active and installed toolchains or profiles
    update         Update Rust toolchains and rustup
    check          Check for updates to Rust toolchains and rustup
    default        Set the default toolchain
    toolchain      Modify or query the installed toolchains
    target         Modify a toolchain's supported targets
    component      Modify a toolchain's installed components
    override       Modify directory toolchain overrides
    run            Run a command with an environment configured for a given toolchain
    which          Display which binary will be run for a given command
    doc            Open the documentation for the current toolchain
    man            View the man page for a given command
    self           Modify the rustup installation
    set            Alter rustup settings
    completions    Generate tab-completion scripts for your shell
    help           Prints this message or the help of the given subcommand(s)
```

### `kup` command

Here is what I would propose as the help message of this command:

```
kup 5.4.3 (ce5817a94 2021-05-31)
The K Framework installer

USAGE:
    kup [FLAGS] <SUBCOMMAND>

FLAGS:
    -v, --verbose    Enable verbose output
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    setup          Install the kup command locally
    list           Show the active and installed K versions
    list --all     Show all versions available (including remote ones)
    install        Download and install the stated version (do not switch default)
    update         Update K Framework default version and kup
    default        Set the default K version
    run            Run a command with an environment configured for a given K version
    shell          Give a shell with an environment configured for a given K version
    help           Prints this message or the help of the given subcommand(s)
```

And we should make it available at https://kframework.org/kup, via `curl https://kframework.org/kup | bash -s setup`.

We should support one special version name called `latest`, which saying `kup default latest` makes the installation track that version. If the installation is tracking the `latest` version, then `kup update` should also affect the default version (by updating to the latest available).

We should aim to not have to do any global installs or `sudo` commands other than what's required to get Nix set up on their system.

**Comment by ehildenb** [comment]
Related: https://github.com/runtimeverification/k/issues/2886

**Comment by goodlyrottenapple** [comment]
I definitely support the nix approach. We do in fact populate a public cache https://app.cachix.org/cache/kore. It would probably be good to bring the self-hosted M1 runners online so that the CI also pushes M1 builds to the cache.

**Comment by F-WRunTime** [comment]
> I definitely support the nix approach. We do in fact populate a public cache https://app.cachix.org/cache/kore. It would probably be good to bring the self-hosted M1 runners online so that the CI also pushes M1 builds to the cache.

I'm working on the M1 runner there is an issue with keeping it online. But we have been getting builds running with haskell-backend

**Comment by ehildenb** [comment]
@goodlyrottenapple I modified the main issue body with a more concrete specification of the script that needs to be `curl`able for the `kup` command.

**Comment by ehildenb** [comment]
Slack coversation: https://runtimeverification.slack.com/archives/C7E701MFG/p1664227496058109?thread_ts=1663938750.906789&cid=C7E701MFG

**Comment by ehildenb** [comment]
`kup` is working, we'll make new issues for problems we have with it.
