### ISSUE TITLE
Kompile should check for faulty simplification rules

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/k#2899]
See comments at the bottom.

~In the generated kore code for https://github.com/kframework/kore/blob/master/src/main/k/working/tests/set-vars/setvars.k#L16 the symbol for `i()`, `Lbli'LParUndsRParUnds'SETVARS'Unds'KItem'Unds'Int`, is included in the no-junk axiom for `KItem`. Most likely it should not be there, given that it has a simplification axiom.~

**Comment by ana-pantilie** [comment]
Most likely this is the new link: https://github.com/runtimeverification/haskell-backend/blob/6b37a7de8cd977d2640cfcdef84510288f30f8a7/test/setvars/setvars.k#L17

We  need to check if this is still happening or not.

**Comment by jberthold** [comment]
Re-tested with current K release, and using code quoted above (`haskell-backend/test/setvars/setvars.k`)

Modified module `setvars.k` contains
```
module SETVARS
  imports K-EQUAL
  imports INT
  syntax KItem ::= Int
  syntax KResult ::= Int

  syntax KItem ::= f(Int)
  rule f(@X:Int) => @X +Int 1 [simplification]

  syntax KItem ::= i(Int)
  rule i(@X:Int) => @X +Int 1 [anywhere]
endmodule
```
(the two "not yet supported" items from the original)
`kompile --backend haskell setvars.k` yields a `definition.kore` which contains (in the `generated axioms` section) axiom
```
axiom{} \or{SortKItem{}} (\exists{SortKItem{}} (X0:SortInt{}, Lblf'LParUndsRParUnds'SETVARS'Unds'KItem'Unds'Int{}(X0:SortInt{})), \or{SortKItem{}} (\exists{SortKItem{}} (X0:SortInt{}, Lbli'LParUndsRParUnds'SETVARS'Unds'KItem'Unds'Int{}(X0:SortInt{})), \or{SortKItem{}} ...)))))) [constructor{}()] // no junk
```
i.e., `Lblf'LParUndsRParUnds'SETVARS'Unds'KItem'Unds'Int` and `Lbli'LParUndsRParUnds'SETVARS'Unds'KItem'Unds'Int
are still included in the `no-junk` axiom.

Whether or not they should be present in this axiom is another question: "no-junk" states that all values of a sort must be in the image of at least one constructor. Are  `f` and `i`  indeed constructors?

**Comment by ana-pantilie** [comment]
Declaring something like `syntax Foo ::= f` makes `f` a constructor. If the `function` attribute is present then it's not a constructor but a function. The frontend should detect if we are writing simplification rules like the one for `f` there and throw an error. @radumereuta what do you think?

**Comment by radumereuta** [comment]
We have such a check but it's only active for `kprove`.
```
[Error] Compiler: Simplification rules expect function/functional/mlOp symbols at the top of the left hand side term.
	Source(/home/radu/work/test/test.k)
	Location(14,8,14,30)
	14 |	  rule f(@X:Int) => @X +Int 1 [simplification]
	   .	       ^~~~~~~~~~~~~~~~~~~~~~

```

**Comment by ana-pantilie** [comment]
Additional reading material for `anywhere`: https://github.com/runtimeverification/haskell-backend/issues/2405#issuecomment-780444275

**Comment by ehildenb** [comment]
`anywhere` rule is not relevant here, `kompile` should be erroring out on the `simplification` rule.
