### ISSUE TITLE
[K-Improvement] [Dedukti Project] Interoperability between tests for K and Dedukti

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#2907]
I just saw that the Dedukti project has been added to the list of projects around K, and I thank you for that.
It is probably best to put the following link, which corresponds to the translator’s code repository: `https://gitlab.com/semantiko/kamelo`.

The current link (`https://gitlab.com/semantiko/K-semantics`) contains a state of the current K-semantics, but at this stage it doesn't really highlight the translator. Once it does, I will add this link to the README of the translator's repository (`https://gitlab.com/semantiko/kamelo`).

I suggest something to help me in the development of this translator, especially in testing it: would it be possible to find a way for me to run K tests with my translator?

At this point, when my translator runs tests, it expects the following format:
```
tests/
  001_X/
  001_X/X.k
  001_X/X-exec/    <- this folder has some files for `krun`
  015_Y/
  015_Y/Y.k
  015_Y/Y-exec/    <- this folder has some files for `krun`
  [...]
```
where `X` can be `IMP` and `Y` can be `dico` for instance.
So, each folder name needs to start with 3 digits and a underscore, and the folder content needs at least one K file (the main one need to have the same name) and a folder `...-exec` with some files that respect the semantics.

In the future, we can extend this format to get also KProver claims, and we can also imagine a way to do the same thing, but with the current K semantics.

**Comment by ehildenb** [comment]
The easiest way to test the translator directly is if we can expose a simple `krun` like interface for the Dedukti backend, or a `kprove` interface. Can you remind me exactly the functionality the Dedukti backend gives? My understanding is that it was able to take `kprove` proof obligations and validate that they are correct reductions? So then it would be consuming `KClaim` like `kprove` does?

Is there other functionality that should be exposed? It may be that the easiest thing to do is to make wrappers around the Dedukti backend that make it able to accept inputs in the same form as the other backends.

**Comment by amelieled** [comment]
The Dedukti backend doesn't yet take `kprove` proof obligations, but it could be the case in few weeks (or days).
The main interface of the Dedukti backend is similar to `krun`.
Its current interface is explained here: `https://gitlab.com/semantiko/kamelo/-/blob/master/README.md`.

But yes, I can implement a `krun`-like interface and `kprove`-like interface but I don't know how to start, and maybe it is almost done.

**Comment by ehildenb** [comment]
Nice, I see this here:

![image](https://user-images.githubusercontent.com/12721972/192161577-767150e4-9c57-44bb-aa57-ddc4f82179f9.png)

This `translate_pgm.sh` is language agnostic, or only works for IMP?

**Comment by amelieled** [comment]
It is language agnostic (I hope) ! 

```
# Requirements: 
#   - Run this script at the root.  ~ where there is the Kamelo executable and the folder ...-kompiled, I think
#   - The first  argument is the Kore file of the K semantics. ~ a path
#   - The second argument is the program which needs to be translated. ~ a path 
```
That's it! :)

**Comment by ehildenb** [comment]
I think you'll likely have to make the adaptions to the Dedukti tool directly, instead of us changing the structure of our current tests.

The tests you want to make work are in `k-distribution/pl-tutorial`. Currently, to run those tests, you can do `cd k-distribution/pl-tutorial` and then run `make`. You likely need to override the `KOMPILE` variable to point at a script which calls `kompile ... --post-process ...` in the way you need, and then also calls the aditional kore -> Dedukti translator you have.

**Comment by amelieled** [comment]
Is it possible to get the exhaustive list of the K tests?
I don't understand why I got very often "Parsing Ambiguity" for the semantics in `k-distribution/pl-tutorial` and `k-distribution/k-tutorial`.
