### ISSUE TITLE
`kompile --version` requires `mvn clean` to work

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2914]
When K is rebuilt without `mvn clean`, command `kompile --version` reports the version and build date for the last clean build.

```bash
% git checkout v5.4.6
% mvn clean package
% kompile --version

K version:    v5.4.6-0-g9178b8bd09
Build date:   Tue Sep 27 13:01:10 CEST 2022

% git checkout v5.4.7
% mvn package
% kompile --version

K version:    v5.4.6-0-g9178b8bd09
Build date:   Tue Sep 27 13:01:10 CEST 2022

% mvn clean package
% kompile --version

K version:    v5.4.7-0-g0b0189cc60
Build date:   Tue Sep 27 13:07:12 CEST 2022
```

**Comment by ehildenb** [comment]
The current version identifier is read from a file, which is not being updated on mvn package. Likely `mvn package` just needs to call the version bumper before calling the java build.

**Comment by radumereuta** [comment]
@Baltoli you are the last one to touch version calculation.
Can you look into this? I've managed to reproduce the bug, but I found all sorts of inconsistencies.
For example, this [line](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/utils/file/JarInfo.java#L86) is looking for a version embedded in the jar file, but that doesn't seem to be updated.
I think the recent workflow changes silently broke this feature.
