### ISSUE TITLE
Small inconsistency between git and package install in format of reported version 

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#2915]
There is a small discrepancy in the format of the reported version number between K installed from git repository and that installed from package.

Git:

```
% kompile --version
K version:    v5.4.7-0-g0b0189cc60
Build date:   Tue Sep 27 13:19:45 CEST 2022
```

Package:

```docker
% docker run --rm runtimeverificationinc/kframework-k:ubuntu-focal-5.4.7 kompile --version
K version:    5.4.7
Build date:   Mon Sep 26 17:46:17 CDT 2022
```

It would be more consistent if the packaged version also reported its version number with a prefix `v`. Then
- parsing / regex matching would be simpler;
- the version number would still indicate whether it's a git or a package install (due to the git version using `--long` format of `git describe`).

**Comment by radumereuta** [comment]
Leave it as is. We like to have the hash at the end to know if someone built K from git or got it from a package.
Fixed by: https://github.com/runtimeverification/k/pull/2989
