### ISSUE TITLE
How to minimize config output in kore-repl

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/k#2917]
When one is working with kore-repl and looking at specific configurations using `config`, sometimes the configurations can be huge.

The easiest way to make them smaller is to use the new `pyk` toolkit. `pyk` is a new package that contains a Python toolkit for manipulating with K terms. We will use the pipeline operator `|` to translate our configs to JSON and then send them to `pyk`, which will postprocess this output and make it more compact.

**pyk print**

One of the tools in `pyk` is called `print`, which has several handy options. We are going to use `--minimize` (which is actually used  automatically when printing with `pyk`). This will filter out many uninteresting cells for the current config and make the result more compact.

In your current directory, save a new script `pykprint.sh`:

```sh
#!/bin/bash

kast --input kore --output json --definition $1 /dev/stdin | jq .term | pyk print $1 /dev/stdin --omit-labels $2
```

Now call `config | bash pykprint.sh {PATH_TO_DEFINITION}` in Kore REPL to make the output smaller.

**pyk print --omit-labels**

If the previous isn't enough, you can also explicitly use the `--omit-labels` flag. This flag will tell `pyk` what cells *not to include*. 

With the previous script, simply call `config | bash pykprint.sh {PATH_TO_DEFINITION} "<cell1>,<cell2>"` to minimize the output *and* surely omit the cells `cell1, cell2`. These cells will not be in the minimized output. 

Note: Make sure that there is no whitespace around `,` in the omit list, otherwise you'll get an error (`,` is a list separator, so this requirement is strict).

**Comment by ehildenb** [comment]
This should go into the USER_MANUAL.md for now.

**Comment by fiedlr** [comment]
I see that printing kore terms is in TODO in the manual:
```
Pending Documentation
---------------------

Backend features not yet given documentation:
...
* Print kore terms
...
```
Do you mean I should try to write a part of the section?

**Comment by fiedlr** [comment]
**Troubleshooting**

It might happen that you come across an error like this: 

`parse error: Exceeds depth limit for parsing at line x, column y`

One of the options how to overcome this is to increase the bison stack depth and force `jq` to use stream parsing.
Edit your `pykprint.sh` to the following:

```sh
#!/bin/bash

kast --input kore --output json --definition $1 /dev/stdin --bison-stack-max-depth 10000 | jq --stream 'fromstream(1|truncate_stream(inputs|select(.[0][0] == "term")))' | pyk print $1 /dev/stdin --omit-labels $2
```

**Comment by fiedlr** [comment]
**pyk print --keep-cells**

Starting with `pyk@0.1.16`, there is a new functionality in `pyk print` called `--keep-cells` that is sort of inverse to `--omit-cells`. The flag `--keep-cells` allows you to keep selected cells and remove the rest, leading to a very compact (sub)configuration. This is especially useful for tracking a handful of cells with primitive values when debugging a claim. Actually, only cells with primitive values are supported currently. For more details, check [the corresponding PR](https://github.com/runtimeverification/pyk/pull/42).
