### ISSUE TITLE
Does krun consume more memory in the latest version? [bug]

### ISSUE THREAD

**Issue by PumpkinDemo** [runtimeverification/k#2934]
I updated my kframework from version 5.2.100 to version 5.4.2 recently.

But today I find one of my old test case cannot be finished and throw an OutOfMemoryError.
```
[Error] Internal: Uncaught exception thrown of type OutOfMemoryError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(OutOfMemoryError: Java heap space)
```
I allocate more memory by prepending `K_OPTS+=-Xmx10G` before the `krun` command and then the test job is finished successfully.

And when I switch back to the old version 5.2.100, the test case is finished successfully as well without more memory.

Why does the new version cost more memory?

**Comment by Baltoli** [comment]
How much memory do you have on your machine, and are you able to share the exact test case you're referring to here? It's hard for us to narrow this down otherwise.

**Comment by PumpkinDemo** [comment]
> How much memory do you have on your machine, and are you able to share the exact test case you're referring to here? It's hard for us to narrow this down otherwise.

I use a 16G-memory machine and usually allocate 8G for `krun`

Sorry for no exact test code can be shared because it's a big project containing thousands lines

**Comment by Baltoli** [comment]
You might find [this issue thread](https://github.com/runtimeverification/k/issues/2866) useful; it deals with `kompile` rather than `krun`, but it gives some pointers on how to do heap dumps for Java. If at some point you have a reproducible example we can help you more specifically.

**Comment by radumereuta** [comment]
We should start doing performance measurements on the llvm-backend and add it to CI to track performance degradation.

**Comment by radumereuta** [comment]
This doesn't have enough information to properly test.
For high performance applications, the java code path should be avoided.
We have the krun script and the bison parser for that.
If you add the `--verbose` flag to the commands you are running, we could provide more insight into what is failing and how to fix it.

**Comment by Baltoli** [comment]
This relates to an old K version and has not been updated or reproduced.
