### ISSUE TITLE
`kup` install seems to fail silently

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/k#2964]
`kup install k` seems to silently fail on my mac. need to investigate whether the python script prints the stderr output.

**Comment by ehildenb** [comment]
It should also be exiting with non-zero exit code on failure (to be verified).

**Comment by Baltoli** [comment]
Is this closed by #2965 @goodlyrottenapple?

**Comment by goodlyrottenapple** [comment]
yes
