### ISSUE TITLE
New Ubuntu Jammy packaging fails on release job

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2983]
https://github.com/runtimeverification/k/actions/runs/3240999414/jobs/5312347235

The release job fails because it's unable to find the asset `kframework_ubuntu_jammy.deb`. Looking at the action that's responsible for building the package, it seems like the name we use in the release job is wrong (and should possibly be `kframework_amd64_jammy.deb`): https://github.com/runtimeverification/k/blob/4d2c5f18c90c6ad537ff2fcb8c99cfb5a29838b9/.github/actions/test-package/action.yml#L77-L81

**Comment by F-WRunTime** [comment]
@ehildenb checkout the merge @Baltoli and I worked on last week. This may have fixed the issue, and this didn't get closed out yet. There may be an additional problem we didn't identify yet
