### ISSUE TITLE
[Warning] Compiler: missing entry for hook SUBSTITUTION.substMany

### ISSUE THREAD

**Issue by winnielin4** [runtimeverification/k#299]
Hi. I am using nightly-710fd91a5 K now. I kompile the lambda.k and ran into some warning. I further krun some test program with "letrec", which can't output the correct answer.

~/Desktop/github/k/k-distribution/tutorial/1_k/1_lambda/lesson_8$ kompile lambda.k
40 states, 1247 transitions, table size 5228 bytes
[Warning] Compiler: Could not find main syntax module with name LAMBDA-SYNTAX
in definition.  Use --syntax-module to specify one. Using LAMBDA as default.
[Warning] Compiler: missing entry for hook SUBSTITUTION.substMany
[Warning] Compiler: missing entry for hook SUBSTITUTION.substOne

~/Desktop/github/k/k-distribution/tutorial/1_k/1_lambda/lesson_8$ krun ./tests/fibbo.lambda
( lambda x . if x <= 1 then x else ( ( f ( x + -1 ) ) + ( f ( x + -2 ) ) ) ) [ mu f . ( lambda x . if x <= 1 then x else ( ( f ( x + -1 ) ) + ( f ( x + -2 ) ) ) ) / f ]

**Comment by dwightguth** [comment]
Try `kompile --backend java lambda.k` or alternatively, `make kompile`. The default backend is the ocaml backend which does not support substitution.

**Comment by JParisFerrer** [comment]
This worked for me, thanks!
