### ISSUE TITLE
Submodule update jobs don't respect new PR workflow

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#2991]
The LLVM / Haskell backend jobs don't respect our new workflow for opening PRs. This means that they end up pulling in version changes when they shouldn't (screenshot taken 14 Oct - will only get worse as we keep bumping the version), and so we have to rebase these out manually. If a PR is merged without rebasing them out, we can end up with versions jumping back in time.

@F-WRunTime @ehildenb feel free to move this to devops if it's more appropriate there.

<img width="914" alt="Screenshot 2022-10-14 at 11 21 59" src="https://user-images.githubusercontent.com/1329034/195824254-7da74658-79d4-4cdb-bcd5-41ee52d5a6e6.png">

**Comment by F-WRunTime** [comment]
@Baltoli  Good question @ehildenb and I can sync on this to avoid any toe stepping while Everett was in the middle of working on some Jenksfile transitions.

**Comment by Baltoli** [comment]
This no longer happens.
