### ISSUE TITLE
Rename `functional` into `total-function` for better clarity

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3008]
The name `functional` is non-descriptive of what it actually means.
The description in the user manual is good enough, but during training people always had to ask what this means.

We could add the `total-function` attribute as an alias for a while and slowly phase out `functional`.
Also, we shouldn't require `function` when we add `total-function`. This will make some conditions in the code a bit more complex.

**Comment by dwightguth** [comment]
Just `total` and it does not imply `function` but implies `functional` if `function` is also present.
