### ISSUE TITLE
[K-Bug] Tangle tags from kompiled definition behave unexpectedly

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#3020]
### What component is the issue in?

Front-End

### Which command

- [ ] kompile
- [ ] kast
- [ ] krun
- [X] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

5.5.4 - 43f56ac166

### Operating System

Linux

### K Definitions (If Possible)

File `test.md` has these contents:

`````
```k
module EVM-TYPES
    imports BOOL
```

```{.k .bytes}
    syntax Memory ::= ".Memory"
```

```{.k .nobytes}
    syntax Memory ::= ".Memory"
```

```k
endmodule
```

```k
module EVM-OPTIMIZATIONS-LEMMAS [kore, symbolic]
    imports EVM-TYPES

    configuration <k> $PGM:Pgm </k>

    syntax Pgm ::= "#execute" | "#halt"
endmodule

module EVM-OPTIMIZATIONS [kore]
    imports EVM-OPTIMIZATIONS-LEMMAS

claim <k> #execute => #halt ... </k> [priority(40)]

endmodule
```
`````

Note that the module `EVM-TYPES` has two different tangle tags in use, one with `bytes` and one with `nobytes`.

### Steps to Reproduce

First, `kompile --md-selector 'k & ! nobytes & ! node' ...` the definition:

```
+ kompile test.md --backend haskell --md-selector 'k & ! nobytes & ! node' --main-module EVM-OPTIMIZATIONS-LEMMAS --syntax-module EVM-OPTIMIZATIONS-LEMMAS
```

Then, try running the proof:

```
+ kprove test.md --spec-module EVM-OPTIMIZATIONS
[Error] Outer Parser: Module EVM-TYPES differs from previous declaration at
Source(/home/dev/src/k/test.md) and Location(2,1,15,10)
        Source(/home/dev/src/k/test.md)
        Location(2,1,15,10)
           .    v~~~~~~~~~~~~~~~
        2 |     module EVM-TYPES
           |            ...
        15 |    endmodule
           .    ~~~~~~~~^
[Error] Outer Parser: Had 1 outer parsing errors.
```

This works:

```
+ kprove test.md --spec-module EVM-OPTIMIZATIONS --md-selector 'k & ! nobytes & ! node'
kore-exec: [170331] Warning (WarnStuckClaimState):
    The configuration's term doesn't unify with the destination's term and the configuration cannot be rewritten further. Location: /home/dev/src/k/test.md:30:7-30:37
Context:
    (InfoReachability) while checking the implication
<k>
  #execute ~> _DotVar1 ~> .
</k>
[Error] Prover: backend terminated because the configuration cannot be
rewritten further. See output for more details.
```

### Expected Results

I would expect _both_ commands to work. For modules defined at `kompile` time, the tangle tag selections set at that time should be used. For modules at `kprove` time, their separate tangle tags should be used.

**Comment by ehildenb** [comment]
This is urgent, it is affecting KEVM.

**Comment by radumereuta** [comment]
>And we now are getting that the backend sees no claims, because the claim is in a block that the tangle tag does not select? It's not really clear to me why this one does not work.

You are using the wrong module to call kprove. 
```
$ kprove test.md --spec-module EVM-OPTIMIZATIONS --md-selector 'k & ! nobytes & ! node'
kore-exec: [123853] Warning (WarnStuckClaimState):
    The configuration's term doesn't unify with the destination's term and the configuration cannot be rewritten further. Location: /home/radu/work/test/test.md:30:7-30:37
Context:
    (InfoReachability) while checking the implication
<k>
  #execute ~> _DotVar1 ~> .
</k>
[Error] Prover: backend terminated because the configuration cannot be
rewritten further. See output for more details.
```

**Comment by ehildenb** [comment]
Oh good point. I've updated the example with the correct tangle tags. It's still inconvenient that at `kprove` time, which may be using a packaged semantics on a different machine by a different person than the one who did `kompile`, that I need to know the tangle tags that were used at `kompile` time.

This is not blocking anymore, because I can make KEVM adjust it's arguments

**Comment by Baltoli** [comment]
Old issue that's been addressed in the relevant build system; if another project bumps into the same issue we can reopen.
