### ISSUE TITLE
Current releases are not being marked correctly

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#3028]

**Comment by radumereuta** [comment]
Details from the meeting:
Specifically, v5.5.8 got released as a draft: https://github.com/runtimeverification/k/releases/tag/untagged-cfe6dfff545d05bd4a35
Because of that, other builds that depended on this started to fail.
Funny thing is v5.5.9 went through correctly.

**Comment by Baltoli** [comment]
This seems to have been fixed now; the most recent releases are going through. Can reopen if this starts happening again.
