### ISSUE TITLE
[K-Bug] Uncaught error when a cell is named `GeneratedCounter`

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#3031]
### What component is the issue in?

Front-End

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    5.4.14

### Operating System

Linux

### K Definitions (If Possible)

```
module BUG-SYNTAX

  syntax T ::= T "and" T | "top"

endmodule

module BUG
  imports BUG-SYNTAX
  imports INT
  configuration <k> $PGM </k> <generatedCounter> 0 </generatedCounter>

  rule top and top => top

endmodule
```

### Steps to Reproduce

Just run: `kompile bug.k`.

### Expected Results

Generation of the folder `bug-kompiled`.

But, I obtained:
```
[Error] Internal: Uncaught exception thrown of type MatchError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(MatchError: null)
```

This is probably because of the cell `GeneratedCounter`.

**Comment by radumereuta** [comment]
Timeboxed this for 30 mins and the error comes from somewhere in [ConcretizeCells.java](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/ConcretizeCells.java#L75)
[`<generatedCounter>`](https://github.com/runtimeverification/k/blob/master/kore/src/main/java/org/kframework/builtin/KLabels.java#L28) is a reserved cell name and it appears we're not handling this very gracefully.

**Comment by ehildenb** [comment]
This should be a better error message, but I don't think there is a reason to support user-declared `<generatedCounter>`.

**Comment by Baltoli** [comment]
Is it worth documenting this behaviour somewhere in the user manual, as well as having a better error message? The list doesn't have to be exhaustive, but just that it's possible for the implementation to reserve cell names that are _lexically_ valid.

**Comment by amelieled** [comment]
I suggest something: it might be interesting to be able to re-display the K semantics after each transformation performed by K.
For example, the attributes `strict` and `seqstrict` generate rewrite rules, so it is conceivable to re-display the new K semantics obtained. 
With this in mind, at most a warning should be generated if a user wants to use a cell named `<GeneratedCounter>`.

**Comment by ehildenb** [comment]
We'll make an explicit check (and document in the user manual), that the user is not allowed to use `<generatedTop>` or `<generatedCounter>` for cell names, or `<s>`.

The issue about exporting the definition after every compile step is another one. Please open a separate issue for it describing your use case, and we'll see if the simple approach we have in mind will work for you.
