### ISSUE TITLE
Remove "antiLeft" priority predicates from rewrite rules

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/k#3035]
Rewrites rules which get assigned priorities get parsed into Kore which looks like:
```
  axiom{} \rewrites{SortGeneratedTopCell{}} (
    \and{SortGeneratedTopCell{}}(
      \not{SortGeneratedTopCell{}}(priorityLE2{}()),
      rule38LHS{}(VarX:SortInt{},Var'Unds'DotVar0:SortGeneratedCounterCell{},Var'Unds'DotVar1:SortK{})),
    \and{SortGeneratedTopCell{}} (
      \top{SortGeneratedTopCell{}}(), Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortS{}, SortKItem{}}(Lblone'Unds'PRIORITY'Unds'S{}()),Var'Unds'DotVar1:SortK{})),Var'Unds'DotVar0:SortGeneratedCounterCell{})))
  [org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/Users/anapantilie/RV/haskell-backend/test/priority/priority.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol]"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(13,8,13,23)"), priority{}("3"), UNIQUE'Unds'ID{}("6cd5667589c7d76f6e1b18e23fa939ee02476bb24c4229d69331b460c555490c")]
```

That `\not{SortGeneratedTopCell{}}(priorityLE2{}())` encodes the priority of the rewrite rule into Kore, and it was deemed necessary a long time ago for constructing proof objects. This is no longer one of our goals, and the Haskell backends do not (and shouldn't) use this priority predicate in any way. I suggest we modify the frontend to avoid producing these predicates in the first place.

Can we also avoid keeping the actual LHS of rules in those `rule38LHS{}` aliases? Why do we need this?

- [x] Frontend flag to generate semantics axioms in new way. For a `rule LHS => RHS requires REQ ensures ENS`, we should generated `\rewrites(\and(LHS, REQ), \and(RHS, ENS))`. No aliases, no antileft (`#Not ...`) pattern.
- [x] runtimeverification/haskell-backend#3567
- [x] Same for LLVM backend.
- [x] Test with downstream semantics.
  - [x] Full regression test suite
  - [x] C semantics: https://github.com/runtimeverification/llvm-backend/issues/747
- [ ] ~~Remove frontend flag for generating old encoding.~~
- [ ] ~~Remove old encoding from both backends.~~

We can remove support for the old format from the LLVM and Haskell backends, but should keep it in the frontend.

**Comment by ana-pantilie** [comment]
I guess the bigger discussion here is if we still want the Kore definition to be as similar to a ML theory as possible. There is a lot of stuff being generated which we don't actually use (what is described above, constructor axioms etc.).

Argument for removing them: simplifies Kore generation by the frontend and internalization by the backends and might have performance benefits (we should measure that).

Counterargument: I believe people are using the Kore definition as a ML theory for other purposes (the ML in other logical frameworks research projects).

Stepping back even further, is the Kore language even suitable for fast symbolic execution? I believe Kore was designed with other goals in mind. Is there still a plan for generating ML proof objects from symbolic execution traces? Do we need the execution engine and the proof generator to speak the same language (Kore)?

**Comment by ehildenb** [comment]
We can have, by default, that `priority` attribute is not resolved into aliases for the LHS of the rules, and the antiLeft patterns are not added. The adding the `--gen-antileft-patterns` flag will recover the original behavior.

It should not affect any of our definitions/backends, but other tools may rely on those antiLeft patterns that we don't know about. So we'll turn off generation of them by default.

**Comment by ehildenb** [comment]
This will now be annoying for the `add-module` endpoint, if the frontend is expected to insert the antilefts for the backend (so the backend can recognize the structure of the rule). This is because when we are using `add-module` to add rules at a higher priority than the original esmantics, with the antilefts in place, we now have to regenerate the entire K definition with the new `#Not priorityNEWPRIORITY` antilefts in place on the original rule.

This to me means that the backends which need the antilefts should handle putting them there. The two current backends are not using them, instead are using the `priority` attribute.

Related: https://github.com/runtimeverification/hs-backend-booster/issues/154

**Comment by Baltoli** [comment]
Going to close this issue for now as we've removed the patterns from the frontend, have a flag to re-enable them if for some reason they're needed, and neither backend relies on them to execute.
