### ISSUE TITLE
[K-Improvement] functional -> total in Kore also

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#3069]
I could be useful to do this https://github.com/runtimeverification/k/pull/3016 for Kore also.

**Comment by amelieled** [comment]
I'm not sure if I can close with issue because now the problem is there are both `functional` and `total` in Kore file.

**Comment by amelieled** [comment]
My bad, it's not correct for instance, for functional axiom:
```
\exists{R} (Val:SortInt{}, 
    \equals{SortInt{}, R} (Val:SortInt{}, 
         Lblsize'LParUndsRParUnds'MAP'Unds'Int'Unds'Map{}(K0:SortMap{}))) 
[functional{}()] // functional
```

**Comment by Baltoli** [comment]
Going to close this issue as it appears the proposed change wouldn't be correct @amelieled; please let me know if that's not the case.

**Comment by amelieled** [comment]
I'm not sure to understand: is it normal that in Kore there are both `functional` and `total`?
