### ISSUE TITLE
[K-Bug] Dependencies of the K standard library

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#3072]
### What component is the issue in?

None

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v5.5.38

### Operating System

Linux

### K Definitions (If Possible)

```
module ARITH
  imports BOOL
  imports INT
  imports ID
  imports MAP
  
  syntax Aexp ::= Int
                | Id
        | Aexp "*" Aexp [left]
        | Aexp "/" Aexp [left]
        | Aexp "+" Aexp [left]
        | Aexp "-" Aexp [left]
        | "(" Aexp ")" [bracket]

  configuration <T>
                  <k> $PGM:K </k>
          <state> .Map </state>
                </T>

  rule N1:Int + N2:Int => N1 +Int N2
  rule N1:Int - N2:Int => N1 -Int N2
  rule N1:Int * N2:Int => N1 *Int N2
  rule N1:Int / N2:Int => N1 /Int N2 when N2 =/=Int 0

  context HOLE + _
  context _:Int + HOLE
  context HOLE * _
  context _:Int * HOLE
  context HOLE - _
  context _:Int - HOLE
  context HOLE / _
  context _:Int / HOLE

endmodule

module BEXP
  imports ARITH

  syntax  Bexp ::= Bool // true and false
             | Aexp "<=" Aexp
             | Aexp "<" Aexp
           | Aexp "==" Aexp
           | "not" Bexp
           |  Bexp "and" Bexp [left]
           |  Bexp "or" Bexp [left]
               | "(" Bexp ")" [bracket]
  rule not true => false
  rule not false => true
  rule N1:Int == N2:Int => N1 ==Int N2
  rule N1:Int <= N2:Int => N1 <=Int N2
  rule N1:Int < N2:Int => N1 <Int N2
  rule true and B2 => B2
  rule false and _ => false
  rule true or _ => true
  rule false or B2 => B2

  context not HOLE
  context HOLE == _
  context _:Int == HOLE
  context HOLE <= _
  context _:Int <= HOLE
  context HOLE < _
  context _:Int < HOLE
  context HOLE and _
  context HOLE or _

endmodule

module IMP-CONTEXT-SYNTAX
  imports BEXP

  syntax CVal ::= "skip"
  syntax Com ::= CVal
             | Id ":=" Aexp
             | Com ";" Com [left]
             | "if" Bexp "then" Com "else" Com
             | "while" Bexp "do" Com
             | "begin" Com "end"

endmodule

module IMP-CONTEXT
  imports IMP-CONTEXT-SYNTAX

 syntax KResult ::= CVal | Int | Bool

rule <k> X:Id => Rho[X] ...</k> <state> Rho </state>

rule <k> X := A:Int => skip ...</k> <state> Rho => Rho [X <- A] </state>

rule <k> X := A:Int => skip ...</k> <state> Rho:Map => Rho ( X |-> A)  </state>
when notBool(X in_keys(Rho))

context _ := HOLE

rule skip ; C => C
rule if true then C else _ => C
rule if false then _ else C => C
rule begin C end => C

context HOLE ; _
context if HOLE then _ else _

rule while B do C => if B then begin C ; while B do C end else skip

endmodule
```

### Steps to Reproduce

`kompile imp-context.k`

### Expected Results

In the Kore file, the symbols `Bool2String`, `freshInt` and `freshId` aren't hooked.

**Comment by amelieled** [comment]
The main question here is: why these 3 symbols haven't the attribute `hook` in the K standard library?

**Comment by amelieled** [comment]
Moreover, is it possible to separate what comes from the K standard library from the rest in the Kore file?
I mean, the section `symbols` could start by K standard library symbols and then the other symbols, and same for the section `rules`.

**Comment by Baltoli** [comment]
You can search for `Bool2String` in `domains.md` to see that it's just a regular K rule; it doesn't need a hooked implementation.

**Comment by amelieled** [comment]
OK, but I can say also that every thing in the module `Bool` is regular K rule. And these things are hooked.

**Comment by radumereuta** [comment]
As Bruce said, those symbols are defined locally through rewrite rules, no need for hooks.

To separate what comes from the standard library, you could do a filter over location information.
Every sentence in the kore file should have something like this:
```
org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/home/radu/work/k/k-distribution/include/kframework/builtin/domains.md)")
```

Note that there are some generated sentences that may not have location information.

**Comment by amelieled** [comment]
Yes I understand and thanks for the advice!
But It's not clear for me why Bool2String is defined locally as andBool or Map:update, but the first one is not hooked compare to the others.

**Comment by radumereuta** [comment]
@dwightguth you are the author of the BOOL module from domains.md. Maybe you can share the reasoning behind having symbols defined by both rewrite rules and hooks.

My take would be that it was just easier and more transparent to have rewrite rules.
But if performance is an issue a backend could decide to implement those operations in a more efficient way.

I hope I'm understanding your question correctly.

**Comment by Baltoli** [comment]
Yes, that's correct Radu. For `Bool2String` specifically, it's not likely to be a performance bottleneck, but `andBool` or `Map:update` might be.

Implementing a hook in the backends imposes a substantial additional burden on K maintenance and development - the hook needs to be implemented separately for both backends. If we can avoid doing this (because the performance gain from doing so would be marginal), and just write a K rule, it's much easier for us to maintain.

Is this distinction causing you a specific problem @amelieled?

**Comment by dwightguth** [comment]
If we're going to remove one or the other of these implementations, the one that ought to be removed is the one made using rewrite rules. Booleans are pretty fundamental to the inner workings of any given backend and trying to implement their representation in the backend without implementing them using native boolean types is a bad idea.

**Comment by amelieled** [comment]
OK, yes, I understand your performance/maintenability issues.
But there may be a gap between the implementation with rewriting rules and the effective implementation because the K standard library is not precise enough in specifying the functions it contains. For example, the function `Map:update` does not only update the map: it also adds an element if it is not already in the map.

Furthermore, in my opinion, all functions in the K standard library should have an implementation with rewriting rules, because otherwise the Kore file does not contain the full semantics.
In the case of the Dedukti backend, I will need an implementation of the K standard library with rewriting rules, and it would be better if I could take the rewriting rules that are in the K standard library.

**Comment by ehildenb** [comment]
@amelieled we're happy to have K implementations of everything in the K prelude that it's possible to do for. We've implemented them basically as-needed. Hooked implementations are much faster usually,  but are bad for symbolic reasoning (indeed probably bad for Dedukti backend too). But we've implemented modules like `MAP-SYMBOLIC` to provide K implementatinos of hooked symbols as-needed for our symbolic reasoning purposes.

So we're happy to accept more pull requests with implementations of the hooked symbols as you need them! Just make sure to provide some examples/tests of your new modules, and follow the same module naming scheme `{MODULE_NAME}-SYMBOLIC`.

**Comment by Baltoli** [comment]
No updates here in a long time; closing and we can reopen if needed.
