### ISSUE TITLE
Sort modularity issues

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#309]
I just managed to parse with
```
module TEST1
  syntax A ::= "a"
endmodule

module TEST2
  syntax A ::= "b"
endmodule

module TEST
  imports TEST1
  imports TEST2
  configuration <k> $PGM:A </k>
endmodule
```
A doesn't have a common ancestor when reaching TEST, but I managed to get an AST from kast for both `a` and `b` as inputs.
I think kompile should give an error message or at least a warning of some sort.
Version K5 from February.

**Comment by ehildenb** [comment]
I don't think this is a bug. Sorts in K are open, so you can add to them as much as you like in other modules. When you do `improts TEST1` and `imports TEST2`, the sort `A` will be the union of the sorts from both modules.

Closing this for now, feel free to re-open if you do believe it's a bug or needs more discussion.

**Comment by radumereuta** [comment]
This is different from K4. But if this is the consensus, then it's fine. Sorts are no longer qualified with the module name, they are global.
