### ISSUE TITLE
[K-Bug] `kore-print` cannot unparse claims from `kore-repl`

### ISSUE THREAD

**Issue by Sereja313** [runtimeverification/k#3105]
### What component is the issue in?

Front-End

### Which command

- [ ] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v5.5.55 Build date:   Tue Jan 10 10:42:05 MSK 2023

### Operating System

Linux

### K Definitions (If Possible)

I used the integration test from the [haskell-backend](https://github.com/runtimeverification/haskell-backend/tree/master/test/imp) repo.
I am also attaching the kore-represented claim 
[claim.txt](https://github.com/runtimeverification/k/files/10391001/claim.txt)

### Steps to Reproduce

```
$ git clone git@github.com:runtimeverification/haskell-backend.git

$ cd haskell-backend/test/imp

$ kompile --backend haskell imp.k 

$ kprove  double-sum-spec.k --debugger

Kore (0)>  claim 0 | kore-print --definition /home/sereja/projects/work/haskell-backend/test/imp/imp-kompiled/ /dev/stdin

terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
/nix/store/g51dd82lcf9wv4qzfi61k29c4k50y532-k-5.5.55-682cbf58409cda757e852a9ebbb5959f91ea007e-maven/bin/../lib/kframework/k-util.sh: line 103: 286466 Aborted                 (core dumped) "$@"
/home/sereja/projects/work/haskell-backend/test/imp/double-sum-spec.k:9:5-21:19
```
I get the same error when trying to unparse other claims from integration tests. However, configurations and axioms are unparsed correctly.

### Expected Results

`kore-print` successfully unparses the claim and prints it.

**Comment by ehildenb** [comment]
Suspicion is that we cannot handle ML connectives, which it currently has `\implies`, `\and`, `\equals`, `\weakAlwaysFinally`.
