### ISSUE TITLE
[K-Improvement] Installation instructions are wrong

### ISSUE THREAD

**Issue by niconaus** [runtimeverification/k#3129]
I'm not sure I'm posting this in the right place, but the installation instructions that come with the last few releases seem to be incorrect. For example, for the latest release, instructions for Ubuntu 22.04 list the following command:
```Markdown
sudo apt install ./kframework_X.Y.Z_amd64_jammy.deb
```
Even though the file offered for Jammy is: K.Framework.Ubuntu.Jammy.22.04.Deb

In addition, the capitalized extension seems incorrect and causing issues for some of my students. This example is taken from this release page: https://github.com/runtimeverification/k/releases/tag/v5.5.71

Not a huge issue, but would be good to correct this.

**Comment by radumereuta** [comment]
@niconaus, this is the right place.
Thank you for letting us know about this. We will look into it as soon as possible.

Note that the easiest way to install K right now is using the [`kup` tool](https://github.com/runtimeverification/kup#kup---the-k-framework-installer).
It's a script that takes care of all dependencies. The only prerequisite is [Nix](https://nixos.org/download.html).

**Comment by radumereuta** [comment]
@niconaus this should be fixed now.
Also, we started working on a VSCode extension that brings up to date syntax highlighting
and integration with a Language Server Protocol (under active development).
But if you get the latest version of K, you should be able to get limited support for code suggestions
and go to definition.
https://marketplace.visualstudio.com/items?itemName=RuntimeVerification.k-vscode
