### ISSUE TITLE
`::set-output` deprecated in Github actions

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3147]
Github actions are reporting warning that the `set-output` command is deprecated and will be removed on the **31st May 2023**: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Example occurrence: https://github.com/runtimeverification/k/blob/af90a054a0baca9468ee09229ec1f1019088b03c/.github/workflows/release.yml#L232-L234

We should follow the guidance in the article above and migrate our workflows away from this command.

**Comment by Baltoli** [comment]
There are still some uses of this deprecated syntax in **actions that we consume**, such as `actions/upload-release-asset@v1`.

We should audit the versions of these that we use and make sure they're up to date.

**Comment by Baltoli** [comment]
@ehildenb @F-WRunTime to investigate what actions are responsible

**Comment by ehildenb** [comment]
Is this still a problem:

- **Here** is a release job that does end up emitting any warning: https://github.com/runtimeverification/k/actions/runs/4437973700
- **Here** is a master job that does emit a warning for NodeJS-12: https://github.com/runtimeverification/k/actions/runs/4437732854
- A test PR job that doesn't emit any warning: https://github.com/runtimeverification/k/actions/runs/4430883818

So it seems to me that NodeJS-12 is the only warning we need to fix now?

**Comment by Baltoli** [comment]
There are still a few `set-output`s on those jobs

**Comment by ehildenb** [comment]
`workflow/nix-shell-action@v3` has this problem, but newer versions seem to have a bug. Not sure if it affects us.

**Comment by F-WRunTime** [comment]
Note I did not touch repositories that haven't been committed to in a year or more.. I thought I made a list btu must have not pushed "comment".. I can make a new one tomorrow. If we need an additional list for repositories with updates needing the nix-shell-action update. Do you have a link to the bug @ehildenb

**Comment by F-WRunTime** [comment]
Remaining Repositories using set-output (BUT haven't been updated in over a year)

- [x] https://github.com/runtimeverification/iele-semantics/blob/4f998c2c4093a6670876dcacd74a71d7d76154e9/.github/workflows/update.yml#L19
- [x] https://github.com/runtimeverification/SOMA-Finance-core-contracts/blob/49d3eab6d8a8d0d0104a60f99f73b14705906fa9/.bin/detect-environment.sh#L8
- [x] https://github.com/runtimeverification/web3-grants-program/blob/2bee7ef0fe587d88b1342a58bedcf6c10df122b9/.github/workflows/application_accepted.yml#L17
- [x] https://github.com/runtimeverification/web3-grants-milestones/blob/cf7320cc549eea05669c8e804a94896b915ec99a/.github/workflows/google_sheet_update.yml#L84
- [x] https://github.com/runtimeverification/web3-grants-milestones/blob/cf7320cc549eea05669c8e804a94896b915ec99a/.github/workflows/badge_or_last_milestone.yml#L61
- [x] https://github.com/runtimeverification/airliner-private/blob/7b43376f9b73abc7a3144a47006c48d64e9d7baa/airliner/public/tools/sitl_gazebo/.github/workflows/firmware_build_test.yml#L53 -- ignored
- [x] https://github.com/runtimeverification/algoevm/blob/2daaf5a85f490fa5f2b4b6df9e5de9aaabd2d628/.github/workflows/test-pr.yml#L27
- [x] https://github.com/runtimeverification/llvm-project/blob/022a47095aebc4e8b5b84924f74ce88f6ef25b24/.github/workflows/libclang-abi-tests.yml#L40

**Comment by Baltoli** [comment]
This seems to still get thrown from the github script v6 action during releases, but I don't know how much can be done about that. From the table above, I know that the Airliner one is definitely safe to ignore.
