### ISSUE TITLE
Remove all tests using Java backend from repo

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#3168]
This issue blocks #3167.

We need to remove all tests that use the Java backend from the repository so the backend itself can be deleted. This means converting as many tests as possible to the LLVM and Haskell backends, and deleting tests that are no longer relevant or test features that do not exist on the new backends.

**Comment by amelieled** [comment]
Hi @dwightguth !
What's new about this? Who try to do that?

**Comment by ehildenb** [comment]
@nishantjr have there been any uses of the `STRATEGY` module recently that you are aware of? We are considering removing it in order to facilitate removing teh Java backend.

**Comment by nishantjr** [comment]
@ehildenb No, I don't think so. We may have tried using it for the matching logic prover a few years ago, but that didn't work out. We ended up building our own language.
