### ISSUE TITLE
[K-Bug] Fix the compilation of toy semantics in pl-tutorial

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#3178]
Blocked on: https://github.com/runtimeverification/k/issues/3167

### What component is the issue in?

None

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v5.5.38

### Operating System

Linux

### K Definitions (If Possible)

Semantics in `https://github.com/runtimeverification/k/tree/master/k-distribution/pl-tutorial`

### Steps to Reproduce

With kompile

### Expected Results

No error

**Comment by radumereuta** [comment]
What is the problem here?
The pl-tutorial is tested with every release of K. Everything should be working.

**Comment by amelieled** [comment]
I get many `Parsing Ambiguity`.
![Capture d’écran de 2023-02-21 20-21-47](https://user-images.githubusercontent.com/62445073/220439266-9d445a7f-ea90-4a4f-96bd-134615b1c35e.png)

**Comment by radumereuta** [comment]
Can you update to the latest version of K?
Right now is around v5.5.103.
Also, if you run `make` in the `pl-tutorial`, make sure to run `make clean` before that.
There might be some outdated caches.
Let me know if that works. Those files are being tested with every release. If you get errors, it's likely something on your machine.

**Comment by amelieled** [comment]
Yes, it's done! Now my version is v5.5.102.
The command `kompile fun-untyped.md` generates: 
```
[Error] Inner Parser: Could not find any suitable production for label
`Type-TypeName`
	Source(~/k/k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/fun-untyped.md)
	Location(408,8,408,23)
	408 |	  rule `Type-TypeName`(T:Type, Tn:TypeName) => (T) Tn          [macro]
	    .	       ^~~~~~~~~~~~~~~
[Error] Inner Parser: Parsing ambiguity.
1: syntax Exp ::= "[" Exps "]" [strict]
    `[_]_FUN-UNTYPED-COMMON_Exp_Exps`(#SemanticCastToVals(#token("Vs","#KVariable")))
2: syntax Val ::= "[" Vals "]"
    `[_]_FUN-UNTYPED-COMMON_Val_Vals`(#SemanticCastToVals(#token("Vs","#KVariable")))
	Source(~/k/k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/fun-untyped.md)
	Location(521,19,521,28)
	521 |	  rule cons V:Val [Vs:Vals] => [V,Vs]
	    .	                  ^~~~~~~~~
[Error] Inner Parser: Parsing ambiguity.
1: syntax Exps ::= Exp "," Exps [right, strict, userList(*)]
    `_,__FUN-UNTYPED-COMMON_Exps_Exp_Exps`(#SemanticCastToVal(#token("V","#KVariable")),#SemanticCastToVals(#token("Vs","#KVariable")))
2: syntax Vals ::= Val "," Vals [right, userList(*)]
    `_,__FUN-UNTYPED-COMMON_Vals_Val_Vals`(#SemanticCastToVal(#token("V","#KVariable")),#SemanticCastToVals(#token("Vs","#KVariable")))
	Source(~/k/k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/fun-untyped.md)
	Location(521,33,521,37)
	521 |	  rule cons V:Val [Vs:Vals] => [V,Vs]
	    .	                                ^~~~
[Error] Inner Parser: Parsing ambiguity.
1: syntax Exps ::= Exp "," Exps [right, strict, userList(*)]
    `_,__FUN-UNTYPED-COMMON_Exps_Exp_Exps`(#SemanticCastToVal(#token("V","#KVariable")),#SemanticCastToVals(#token("Vs","#KVariable")))
2: syntax Vals ::= Val "," Vals [right, userList(*)]
    `_,__FUN-UNTYPED-COMMON_Vals_Val_Vals`(#SemanticCastToVal(#token("V","#KVariable")),#SemanticCastToVals(#token("Vs","#KVariable")))
	Source(~/k/k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/fun-untyped.md)
	Location(729,40,729,53)
	729 |	  rule <k> assignTo((X:Name,Xs => Xs),(V:Val,Vs:Vals => Vs)) ...</k>
	    .	                                       ^~~~~~~~~~~~~
[Error] Compiler: Had 4 parsing errors.
```

**Comment by Baltoli** [comment]
The problem here is that these tests were being run only on the Java backend, which from my previous investigation into the issue performs disambiguation slightly differently to the LLVM backend (which is what you get with `kompile`, rather than using the test suite Makefiles).

@dwightguth is currently in the process of modernising these tests to run on the LLVM backend, and eventually removing the Java backend entirely. This should mean that the PL tutorial will be fully up to date with K soon.

**Comment by ehildenb** [comment]
Let's re-try this after migrating off the Java backend, that should clear up a lot of old build failures on modern backends.

**Comment by radumereuta** [comment]
This should be fixed now: https://github.com/runtimeverification/k/issues/3168
