### ISSUE TITLE
Uncaught exception thrown of type InvalidPathException because of accents in the path name

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/k#3179]
### What component is the issue in?

None

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v5.5.102

### Operating System

Linux / K is installed with `sudo apt install ./kframework_...`

### K Definitions (If Possible)

Any K definition

### Steps to Reproduce

`cd Téléchargements/` (download in French :p)
`kompile toto.k`

### Expected Results

[Error] Internal: Uncaught exception thrown of type InvalidPathException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(InvalidPathException: Malformed input or input contains unmappable characters:
~/T��l��chargements/./toto.k)

**Comment by Robertorosmaninho** [comment]
Hey @amelieled, I tried reproducing your issue on my machine but got a different error. Could you provide me with more details about your setup? (OS, the code for `toto.k`, the hash of the commit you're using in K, and how it was installed? (kup, maven, homebrew))

**Comment by Robertorosmaninho** [comment]
Also, can you try to kompile it with the Haskell backend? It worked fine for me, so I want to ensure the problem is in the LLVM backend.


Try this if you're using a MacOS:
`kompile toto.k --no-haskell-binary  --backend haskell --debug`

Or this command otherwise:
`kompile toto.k --backend haskell --debug`

**Comment by amelieled** [comment]
I'm on Linux.


`toto.k` can be any file: empty, or this one for instance
```
module TOTO

endmodule
```

**Comment by amelieled** [comment]
Same problem with the Haskell backend.

`kompile toto.k --backend haskell --debug` generates:
```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ~/T��l��chargements/./toto.k
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.kframework.parser.ParserUtils.slurp(ParserUtils.java:96)
	at org.kframework.parser.ParserUtils.loadModules(ParserUtils.java:198)
	at org.kframework.parser.ParserUtils.loadDefinition(ParserUtils.java:318)
	at org.kframework.parser.ParserUtils.loadDefinition(ParserUtils.java:297)
	at org.kframework.kompile.DefinitionParsing.parseDefinition(DefinitionParsing.java:250)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:211)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:281)
	at org.kframework.kompile.Kompile.run(Kompile.java:150)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:78)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
	at org.kframework.main.Main.runApplication(Main.java:119)
	at org.kframework.main.Main.runApplication(Main.java:109)
	at org.kframework.main.Main.main(Main.java:57)
[Error] Internal: Uncaught exception thrown of type InvalidPathException
(InvalidPathException: Malformed input or input contains unmappable characters:
~/T��l��chargements/./toto.k)
```

**Comment by radumereuta** [comment]
I managed to reproduce it locally and I have:
```console
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ro_RO.UTF-8
LC_TIME=ro_RO.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ro_RO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ro_RO.UTF-8
LC_NAME=ro_RO.UTF-8
LC_ADDRESS=ro_RO.UTF-8
LC_TELEPHONE=ro_RO.UTF-8
LC_MEASUREMENT=ro_RO.UTF-8
LC_IDENTIFICATION=ro_RO.UTF-8
LC_ALL=
```
We had a similar issue before: https://github.com/runtimeverification/k/pull/1982
Note that for me it's failing in cmd, but is fine if I run it in IntelliJ.

**Comment by Robertorosmaninho** [comment]
I also was able to reproduce it with this: 
```
locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
I'm searching for methods to ensure the en_US.UTF-8.

@amelieled would you mind telling us if you're using k built with `maven` or `kup`?

**Comment by amelieled** [comment]
I've been updated the information in my first message:
K is installed with `sudo apt install ./kframework_...`

**Comment by Robertorosmaninho** [comment]
Thanks, @amelieled! Radu's #3183 PR fixes the problem, but I'd recommend you set your encoding to `en_US.UTF-8` as well!

**Comment by Baltoli** [comment]
@amelieled https://github.com/runtimeverification/k/pull/3183 fixes the issue, which was that K was forcing the `C` locale even if the user had a unicode locale enabled for their system. If you have `en_US.UTF-8` set then you should be fine from now on; let us know if anything recurs here.

**Comment by amelieled** [comment]
It works, thanks!
