### ISSUE TITLE
[KIP] Allow the debugger to tell you why a rule can't apply

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3180]
~~Blocked on: https://github.com/runtimeverification/llvm-backend/issues/666~~

A common pain point for writing K definitions is getting to a point where the user expects a rule to apply, but it doesn't.
Currently, the tools don't do a very good job of presenting information about rules failing to apply.

We should be able to get stuck configuration, and a rule identifier and present some friendly information about why that rule can't apply.
This gets a bit more complicated when we deal with generated rules, like contexts and strictness...
For generated rules, we would need a convention to label the heating and cooling rules also depending on the location of the subterm.
```
syntax Exp ::= Exp "+" Exp [strict, klabel(plus)]
MNAME.plus.heat.1
MNAME.plus.heat.2
MNAME.plus.cool.1
MNAME.plus.cool.2
```
Also, look into generated sort predicates like `isKResult(...)`.

For LLVM you get some support from GDB, but that feature seems not to be working right now. @Baltoli is looking [into it](https://github.com/runtimeverification/llvm-backend/issues/666).
Maybe we should integrate this into our testing infrastructure so we don't lose functionality in the future.

For the Haskell backend, we would rely on the pyk library. In the future, no one will be interacting directly with the backend.

**Comment by ehildenb** [comment]
For symbolic, this is a routine in pyk we used to narrow down "why isn't subsumed into RHS": https://github.com/runtimeverification/ksummarize/blob/master/ksummarize/src/ksummarize/util.py#L63

The basics are:

- First attempt to do matching of term into LHS of the rule (or into target state in case of proof).
  - If this works, then instantiate the side-conditions with the substitutino, and check each side-condition one at a time.
  - If this doesn't work, try matching each individual cell one at a time. Each cell that matches, add to the accumulated substitution, until you reach a cell that doesn't match (contradicts accumulated substitution thus far, or doesn't match on its own).

**Comment by ehildenb** [comment]
To make this easy for symbolic states

- `k-rule-find`: Command which goes from cursor position to rule identifier (unique ID).
- `k-rule-apply`: Command which takes a given rule unique id, and a text file containing a kast or kore state, and attempts to apply said rule, giving back the detailed reason it doesn't apply.

GDB will currently give you the following information:

- Tell you "this rule applies", or:
- Give you a reason the rule doesn't apply (subterm pattern match failure, side-condition failure).
- Some output debug information about actions taken while matching.
- Creates a log of things its trying to do.

So for concrete execution, we want to expose that same gdb script logic via the same interface as described above.

**Comment by ehildenb** [comment]
`k-rule-find <definition-dir> <filename> <line-number> [<column-number>]`

`<column-number>` should be optional (which could return multiple rules, which should be an error).

We could return a JSON packet with extra information, or the entire rule pretty-printed (depending on CLI flags).

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/k/pull/3063 seems to be relevant to this

**Comment by Baltoli** [comment]
@Robertorosmaninho is working on the first part of this: https://github.com/runtimeverification/llvm-backend/issues/702

**Comment by Robertorosmaninho** [comment]
The llvm implementation for the second part is being developed [here](https://github.com/runtimeverification/llvm-backend/pull/721).

**Comment by Baltoli** [comment]
Closed by https://github.com/runtimeverification/llvm-backend/pull/721
