### ISSUE TITLE
K tools by default should not create hidden temporary directories in CWD

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3237]
By default, directories like `.kprove-*` should either not be created, or if necessary created under `/tmp` and cleaned up once no longer needed.

As an option, the user should be able to tell the tool where to create these directories, e.g.

```
[--temp-directory DIR]
```

Keeping around the directories can then either be implicit if the flag is provided, or another flag can be introduced for this purpose.

**Comment by radumereuta** [comment]
Those temp dirs contain useful debugging information.
Why is this a problem?

**Comment by tothtamas28** [comment]
Unless you want access to that information it's just garbage. And after a while it really accumulates.

But just to be clear, my point is not to get rid of this feature, just to make it opt-in (it's _debugging_ information after all).

**Comment by radumereuta** [comment]
Those files are kept only if you provide `--debug`. So it is _opt-int_.

**Comment by ehildenb** [comment]
I think `--save-temps` is also another flag that causes these files to be kept.

We could possibly also put them in `/tmp/...` instead.

The temporary files, for the most part, are definitely needed to pass things between the different commands. Most of the backend commands are taking as input files, things that are too long for CLI arguments.

It is _intended_ that these files are deleted even on unsuccessful finish. Any case where this isn't happening is a bug.

**Comment by tothtamas28** [comment]
I figured out why the `.kprove` directories are not deleted after running `pyk` integration tests.

A few tests call

```
% kprove looping-spec.k --emit-json-spec spec.json --dry-run
```

to generate the spec module in KORE JSON format. Here, `--dry-run` is appended to not spend time doing the actual proof. But as a side effect, the `.kprove-*` directory is not deleted (which makes sense if one wants to successfully call the command that is printed).

Here are my suggestions.

* Flag `--dry-run` should not preserve the `.kprove-*` directory. One can add the `--debug` flag to achieve that while having the same output.
* Let the user optionally specify where to create the temp directory. By default, it should be created under `/tmp`.
* Let the user optionally specify the name of the temp directory. By default, the current naming scheme should be used.

**Comment by radumereuta** [comment]
Do you have a `clean` option for your build system?
For example, the Makefiles we use for the integration tests remove
```console
rm -rf $(KOMPILED_DIR) .depend-tmp .depend .kompile-* .krun-* .kprove-* .kbmc-* kore-exec.tar.gz
```
This is not going to solve the original problem, but it might mitigate it.
Plus, it's something that we might want anyway.

**Comment by tothtamas28** [comment]
> Do you have a clean option for your build system?

We use `pytest`'s solution for this problem, i.e. we create these resources under a designated temporary directory created for each test case by `pytest`. These directories then can be inspected after running the tests, but will eventually be cleaned automatically. The changes suggested above would enable us to do the same for `.kprove`, `.krun`, etc.

**Comment by radumereuta** [comment]
The tempDir is decided here: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/utils/inject/CommonModule.java#L40
So I don't think it will be that hard to add an option to specify a different location.

**Comment by radumereuta** [comment]
Put every temp file in /tmp (system default) and a new directory so we don't have conflicts.
Do the same for the bash scripts which might need a small refactoring.
