### ISSUE TITLE
Remove kprove-legacy

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3257]
Since we are removing the java-backend, we should consider removing kprove-legacy as well.
There are several leftover examples in regression-new that would need to be converted, but w/o the java backend to worry about, it shouldn't be that hard.

**Comment by ehildenb** [comment]
Will need to modify the K regression test suite to not use kprove-legacy anymore.

Will need to modify them so that it kompiles with the correct module ahead of time, instead of some core definition file.

**Comment by Baltoli** [comment]
Full list of proof tests to look at:

* [x] boundary-cells-opt
* [x] checkClaimError
* [x] checkWarnsClaim
* [x] concrete-function
* [x] concrete-function-cache
* [x] concrete-haskell
* [x] domains-lemmas-no-smt
* [x] domains-lemmas-smt
* [x] imp-haskell
* [x] issue-1175
* [x] issue-1471-proofSyntaxWarning
* [x] issue-1472-unboundVars
* [x] issue-1489-claimLoc
* [x] issue-1879-kproveTrans/haskell
* [x] issue-2142-markConcrete
* [x] issue-2174-kprovexParseError
* [x] issue-2287-simpl-rules-in-kprovex
* [x] issue-2321-kprovexCrash
* [x] issue-2812-kprove-filter-claims/claims
* [x] issue-2812-kprove-filter-claims/exclude
* [x] issue-2812-kprove-filter-claims/trusted
* [x] ite-bug
* [x] itp/nat-assoc
* [x] itp/nth-ancestor
* [x] kprove-append
* [x] kprove-branchingAllowed
* [x] kprove-error-status
* [x] kprove-haskell
* [x] kprove-java
* [x] kprove-macro-exp
* [x] kprove-macro-exp-productions
* [x] kprove-markdown
* [x] kprove-smt-lemma/tests
* [x] kprove-var-equals
* [x] map-symbolic-tests-haskell
* [x] markdownSelectors
* [x] profile
* [x] proof-tests/deposit/spec
* [x] set-symbolic-tests
* [x] set-symbolic-tests/failing
* [x] set-symbolic-tests/unsimplified
* [x] set_unification
* [x] spec-rule-application
* [x] spec-rule-application/fail
* [x] unification-lemmas
* [x] unification-lemmas2

```shell
find . -name '*spec.k' -o -name '*spec.md' | \
  xargs dirname | \
  sort | \
  uniq | \
  cut -c3- | \
  xargs printf '* [ ] %s\n'
```

**Comment by radumereuta** [comment]
Do not close yet. We need to remove the entire package `kernel/org.framework.kprove`. Except for the `KProveOpts` file which should be moved to `kprovex` and clean up the outdated options.
Then rename the `kprovex` package to `kprove`.

This is going to cause large conflicts with the removal of the java backend.
So delay until we merge #3251.
