### ISSUE TITLE
[K-Improvement] Hide the confusing `--directory` option from various help message

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/k#3276]
## Motivation

The `--directory` is a little quirky for historic reasons, it needs you to specify a directory with exactly one subdirectory with a `-kompiled` suffix.
This is confusing to beginners, and even gets confused with `--definition` by regular users (e.g. me). 

We should hide this option from help messages and remove it from documentation, while perhaps printing a warning.

## Alternative

Another possibility is to completely drop the option.

## Documentation

Documentation such as the usermanual and tutorial would need to be updated to not use this option

## Testing

No tests would need to change.

**Comment by radumereuta** [comment]
Not sure if we can hide the option, but we could mark it as `[DEPRECATED]`.
We still want to have the default behavior of
```console
$ kompile test.k
$ krun a.test
```
to just work. We have lots of tests, and it's a good first experience.

**Comment by Baltoli** [comment]
I think the default behaviour can still work with a hidden `--directory` flag, can't it? I agree it's a good first-touch experience.

**Comment by ehildenb** [comment]
Things to do:

- Add [DEPRECATED] to help messages.
- Make it a `WARNING` to use `--directory`, but _not_ a warning to specifiy neither `--directory` or `--definition`.
- Fix the test-harnesses we have for regression-new and pl-tutorial and k-exercises to not have these warnings.
