### ISSUE TITLE
Check that the label provided to --concrete-rules actually exists

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#3285]
As noted in runtimeverification/evm-semantics#1634, the labels provided to `--concrete-rules` are never checked to ensure they correspond to an actual rule.

For example, define `concrete.k`
```
module CONCRETE-SYNTAX
imports INT-SYNTAX
syntax Exp ::= Int
             | Exp "+" Exp

endmodule

module CONCRETE
imports CONCRETE-SYNTAX
imports INT

rule [assoc]: (X + Y) + Z => X + (Y + Z)

endmodule
```
and run
```
kompile --backend haskell --concrete-rules CONCRETE.fake concrete.k
```
No error or warning is reported.

**Comment by radumereuta** [comment]
You may find this helpful: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/kprovex/ProofDefinitionBuilder.java#L83
I'm doing the same thing but for `kprove --trusted --exclude --claims`
