### ISSUE TITLE
Question: can we print stack trace on --verbose?

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#329]
Right the stack trace of uncaught exceptions is only printed on `--debug`:
https://github.com/kframework/k/blob/91a69ed56a92897677d16bbdb2065841a4446125/kernel/src/main/java/org/kframework/utils/errorsystem/KExceptionManager.java#L32-L45

For kprove, it would be better if it would be printed on `--verbose` instead. I'm asking if you are ok with such a change.

Arguments:
1. Stack traces are important for day-to-day work of a kprove user. Duh.
2. Option `--debug` in kprove prints GBs of information, mostly irrelevant. This is why it's pretty much unusable. Still, these logs were programmed by Andrei Stefanescu and exist for a reason, so I would not remove them.
3. While it might be standard pattern for command line tools to print exceptions on `--debug`, K is more or less in perpetual alpha state, so it would make sense to print this info on a more commonly used option.

Options for verification team:
1. Print stack trace on `--verbose`.
2. Create a new experimental option, say `--debug-adv`, and move most of the kprove logs from `--debug` to `--debug-adv`.
3. Print stack trace on `--verbose` in K-gnosis only. This is the current situation.

**Comment by dwightguth** [comment]
It seems to me this is almost exactly the inverse of what you want. Logging should be printed on --verbose, not --debug, and stack traces should be printed on --debug. If there is logging printed on --debug that you would rather not deal with at all, even on --verbose, then you should simply delete it.

**Comment by denis-bogdanas** [comment]
I might be wrong, but my understanding is that `--debug` is a more verbose option than `--verbose`. On --verbose you expect an amount of output that is still readable in the terminal. On --debug - possibly more, but not GBs more. I wouldn't put any low-level logging into --verbose, this would kill this option for kprove. And I wouldn't delete old Andrei's logs either.

So is the strategy 2 above ok for you? That is, adding a new option `--debug-adv` that guards Andrei's logs. But there are too many logging options already. Ideally we would want one option with different verbosity levels, like --verbose 1, --verbose 2 etc.

What do you think?

**Comment by dwightguth** [comment]
Let me ask this a different way. If we create this --debug-adv flag, when would you or the members of our smart contracts verification team use it?

**Comment by denis-bogdanas** [comment]
I don't use `--debug`, but Jerry for example is using it.

**Comment by denis-bogdanas** [comment]
And in future I might refactor those messages into something more compact. So I still want to have them.

**Comment by dwightguth** [comment]
alright so the issue is that the logging is used but you don't want it during --debug or during --verbose. In that case, let's put it under a different flag, say, --log-claims.
