### ISSUE TITLE
K V6 Announcement

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#3290]
We should do a _short_ blog post (and twitter announcement) about K V6.

Some things to mention ("Modern K"):

- Any performance improvements (kompile, parse time, LLVM backend, haskell backend)
- Better UX
  - 1-line install, package management.
  - Adjusting CLI options to make more ergonomic.
  - New `kbuild` declarative build system.
  - KIDE/KLSP
- Programmatic API (pyk)
- RPC interface to prover (faster, more integratable)

What has this enabled?

- KAVM property testing (link to Georgy's blog post)
- KEVM foundry property (link to Foundry integration stuff)

Theme is: K enables programming language tool builders to create helpful debugging and analysis tools faster, better, stronger, prettier. Companies that need a path to market for their tools can get there quicker by using K instead of embarking on their own journey.

**Comment by radumereuta** [comment]
Document with the blog post: https://docs.google.com/document/d/1dgH8LwD8WiA1BJe3Fj2qVR6OaosBg67SK2RNZYflkhI/edit

**Comment by radumereuta** [comment]
@reekamaharaj before publishing the blog post, we should make sure we merge this: https://github.com/runtimeverification/k/pull/3405
