### ISSUE TITLE
mvn install fails

### ISSUE THREAD

**Issue by MarkoSchuetz** [runtimeverification/k#33]
I am trying to build k5 up to date to about 10 min ago.

mvn package succeeds, but sudo mvn install fails.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] K Framework Tool Parent ............................ SUCCESS [01:58 min]
[INFO] K Framework KORE ................................... SUCCESS [01:30 min]
[INFO] K Framework Tool Kernel ............................ SUCCESS [01:07 min]
[INFO] K Framework KTree .................................. SUCCESS [  0.522 s]
[INFO] K Framework Ocaml Backend .......................... SUCCESS [  0.489 s]
[INFO] K Framework Java Backend ........................... SUCCESS [ 29.130 s]
[INFO] K Framework Tool Distribution ...................... FAILURE [02:08 min]
[INFO] K Framework API .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:54 min
[INFO] Finished at: 2018-02-26T12:23:09-04:00
[INFO] Final Memory: 39M/343M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (exec-ktest) on project k-distribution: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/home/marko/src/k5/k-distribution/tutorial" executable="make">... @ 4:95 in /home/marko/src/k5/k-distribution/target/antrun/build-main.xml
```

**Comment by ylkamalesh** [comment]
I have the same problem caused by the error prior: 

     [exec] /home/ylk/Projects/k/k-distribution/target/release/k/bin/kast --output pretty --sort Bool -m IMP kast-tests/Bool.0.gen > kast-tests/Bool.0.out
     [exec] /home/ylk/Projects/k/k-distribution/target/release/k/bin/kast --output pretty --sort Bool -m IMP kast-tests/Bool.1.gen > kast-tests/Bool.1.out
     [exec] ../../../include/ktest.mak:50: recipe for target 'int-parse-kompiled/timestamp' failed
     [exec] make[2]: Leaving directory '/home/ylk/Projects/k/k-distribution/tests/regression-new/llvm-string2base'
     [exec] ../../include/ktest-group.mak:11: recipe for target 'llvm-string2base' failed
     [exec] /home/ylk/Projects/k/k-distribution/target/release/k/bin/kprove proof-tests/simple-add-spec.k -m IMP
     [exec] [Error] Critical: llvm-kompile returned nonzero exit code: 1
     [exec] Examine output to see errors.
     [exec] make[2]: *** [int-parse-kompiled/timestamp] Error 113
     [exec] make[1]: *** [llvm-string2base] Error 2
     [exec] make[1]: *** Waiting for unfinished jobs....

**Comment by ehildenb** [comment]
Re-open if the issue still exists, it probably doesn't since we have gone through several updates to K since this was opened.

You probably don't want to run `mvn install` as root anyway, perhaps try using one of our Nightly releases: https://github.com/kframework/k/releases
