### ISSUE TITLE
Give a warning/error when declaring empty terminal in the semantics

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3304]
Productions like
```
syntax OptInBounds ::= "" [klabel(#inBoundsEmpty)]
```
are causing a lot of issues for beginners.
If something like this is declared and visible in the semantics module, kompile should give a warning/error message.
The proper way to solve this would be to have a `COMMON` module with most of the syntax and `*-SYNTAX` module not included in the semantics module with the empty productions/terminals.
In the semantics module, the user can match directly on the labels or redeclare the syntax with non-empty terminals.

Check to see if we're not excluding those already.

We should also update the user_manual and the tutorial.

We can get scanner ambiguities when the user redeclares tokens like `Int`. Can we detect that and give a warning?

**Comment by ehildenb** [comment]
Emit a warning if a production like this is declared in a module that is in the `--main-module`.

**Comment by radumereuta** [comment]
After a few tests, it turns out empty productions are not the problem but rather regex clashes, which are much harder to detect.
We used to have big problems with empty productions when we had the scannerless parser, but with the tokenizer, this is not such a big problem.

I don't have a good solution for this other than getting the modular scanner working and better documentation.
