### ISSUE TITLE
Missing `comm` attributes

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#3317]
Some symbols in the prelude are missing the `comm` attribute:

- [x] `_==K_`
- [x] `_==Int_`
- [x] `_==String_`
- [x] `_==Bool_`

It leads to us writing duplicate lemmas: https://github.com/runtimeverification/evm-semantics/pull/1662/files#r1160875836

**Comment by Baltoli** [comment]
@radumereuta to provide an example

**Comment by radumereuta** [comment]
@Robertorosmaninho this is where I added the `comm` functionality: https://github.com/runtimeverification/k/issues/2587
It's supposed to reduce the number of simplification rules we write.

**Comment by Robertorosmaninho** [comment]
Fixed in #3342
