### ISSUE TITLE
Documentation pages should have unique page titles

### ISSUE THREAD

**Issue by jryans** [runtimeverification/k#3359]
Overall, the K Framework documentation is very helpful, and it appears that more tutorials are being added soon which is great to see. 😄

However, I do find it a bit hard to navigate at the moment because all of the pages on the https://kframework.org site use a `title` tag containing "K | Runtime Verification Inc". If you open several pages in different tabs, it becomes impossible to tell which page is which since they all have identical page titles.

Most (all?) pages do have a reasonable first header that could be used as the page title. I suspect there's some metadata and / or option that could be used with your page generator to produce better page titles for each page.

**Comment by Baltoli** [comment]
@yiyi-wang-rv is it possible to use the top-level heading to derive the page title when we generate the website?
