### ISSUE TITLE
Fix maven deployment

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3367]
We need to rework the way we deploy the [maven artifacts](https://github.com/runtimeverification/k/blob/master/.github/workflows/release.yml#L124)
Everet suggested doing this as a [separate job,](https://github.com/runtimeverification/k/pull/3366#issuecomment-1523558764) but Freeman [pointed out](https://runtimeverification.slack.com/archives/C04SBT101RC/p1682517932649489) this would increase the CI load since we need to build K another time.

**Comment by Baltoli** [comment]
@dwightguth is evaluating the use of CloudRepo here.
