### ISSUE TITLE
Bytes causing parse errors

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#337]
I'm having issues with working with the `Bytes` sort. I get parse errors when using Bytes that I don't get when using a regular `Int`, for example.

Minimal working example:

```k
require "domains.k"

module BYTES-ISSUE
  imports DOMAINS
  imports BYTES

    syntax Map ::= Map "[" Int ":=" Bytes "]" [function]
 // ----------------------------------------------------
    rule BM[ N := nilBytes ] => BM
    rule BM[ N := (B : BS) ] => (BM[N <- B])[N +Int 1 := BS]
endmodule
```

This gives output:

```
kompile bytes-issue.k
[Error] Compiler: Had 2 parsing errors.
[Error] Inner Parser: Parse error: unexpected token ':'.
	Source(/home/hjort/code/wasm/k-demos/bad_error_msg/./no-square-bracket.k)
	Location(10,22,10,23)
[Error] Inner Parser: Parse error: unexpected token ']'.
	Source(/home/hjort/code/wasm/k-demos/bad_error_msg/./no-square-bracket.k)
	Location(9,28,9,29)
[Warning] Compiler: Could not find main syntax module with name ...
```

The problem *persists* when I remove one of the rules (although one parse error then goes away, of course), and if I change the square brackets to parentheses, and the `:=` to something like `<-`.

The problem *goes away* if I change to using some other sort, like by defining `Ints`:

```k
require "domains.k"

module BYTES-ISSUE
  imports DOMAINS
  imports BYTES

    syntax Ints ::= ".Ints" | Int ":" Ints      // Added line
    syntax Map  ::= Map "[" Int ":=" Ints "]"   // Bytes => Ints
 // -----------------------------------------
    rule BM[ N := .Ints ] => BM                 // nilBytes => Ints
    rule BM[ N := (B : BS) ] => (BM[N <- B])[N +Int 1 := BS]
endmodule
```

The problem also *goes away for the first rule* if I change from using `nilBytes` to `.Bytes`, which I find strange.

**Comment by hjorthjort** [comment]
The minimal example is code by @MrChico that I'm trying to integrate. This seems like a sensible way to keep a byte map and write to it, so I'd like to be able to us it. I don't know if he had the same issues when trying to do this

**Comment by MrChico** [comment]
Yeah, I remember running into this issue. Can't remember exactly what it was, but I think there was a problem with competing definitions of `.Bytes` in domains.k depending on whether it's symbolic or not or Smth like that

**Comment by hjorthjort** [comment]
Seeing how the implementation of `Bytes` is pretty straight-forward I can get around the problem for now by just reimplementing it myself and making syntax modifications when necessary. But I don't want to merge anything into KWasm with that solution.

I'll see if I can hack k a bit on my end to figure out the issue.

**Comment by dwightguth** [comment]
The productions in the BYTES-IN-K module are not a part of the public interface of the Bytes type and will not work in the ocaml or llvm backends. If you want to use the BYTES module, you should only rely on the functions in the BYTES-HOOKED module. If you just want a cons list, I'd recommend implementing it yourself, but note that the BYTES sort is memory efficient and has constant time update and lookup, which cannot be said of a cons list of ints.

**Comment by hjorthjort** [comment]
For future reference: When defining a moudle or looking to import one, how do I know what is part of a module's public interface?

**Comment by dwightguth** [comment]
That's a good question. In general I would say you can assume that you can use any productions in the module unless some productions are included conditionally only on some backends (via the kore, kast, symbolic, and concrete module attributes). There may be a few irregularities where this rule doesn't hold, but at the very least if you do that it should compile.

**Comment by dwightguth** [comment]
One feature we may consider adding to k is explicitly annotating the syntax exported by a module, but nothing like this has been created yet.

**Comment by hjorthjort** [comment]
Thanks for the explanation. I think an explicit keyword would be a nice touch. At least for ease of learning: public and private is intuitive to most if not all programmers. And it would be nice to be able to hide auxiliary stuff in an explicit manner when writing a module.

**Comment by hjorthjort** [comment]
Also, perhaps the best feature would be some sort of helpful error message, or just a hint in the error message saying something like "X hasn't been defined and isn't part of the public interface of any imported module". That way at least you would know there is such a thing as public interface, i.e., that not everything is always exported, and try to reverse-engineer what's public.

**Comment by ehildenb** [comment]
@hjorthjort is this still an issue?

**Comment by hjorthjort** [comment]
No, it isn't, let's close it.

Everett Hildenbrandt <notifications@github.com> schrieb am Di., 17. Nov.
2020, 6:57 PM:
