### ISSUE TITLE
Restrict `Bytes` token syntax

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3396]
`Bytes` tokens, currently defined as:

https://github.com/runtimeverification/k/blob/badf9c880ed615474d02f2df1b539673cfaf0243/k-distribution/include/kframework/builtin/domains.md?plain=1#L1757

should be restricted to only allow the following lexical elements:

* Any printable ASCII character (i.e. `0x20` to `0x7E`), except `"` (`0x22`) and `\` (`0x5C`)
* `\"` - `0x22`
* `\\` - `0x5C`
* `\t` - `0x09`
* `\n` - `0x0A`
* `\f` - `0x0C`
* `\r` - `0x0D`
* `\xHH` where `H` stands for a hexadecimal digit (`[0-9a-fA-F]`) - `0xHH`

**Comment by dwightguth** [comment]
Just fyi, this is probably a one line change in domains.md.

**Comment by Scott-Guest** [comment]
Closed by #3412
