### ISSUE TITLE
kompile -h shows too many options

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3399]
After looking at other tools that do similar things, `kompile -h` shows too many options, which makes it intimidating and hard to read.
Maybe we should have two tiers of options. We used to have `-X` for experimental.
Could we have a `man kompile` option in the system? This way, we could reduce the amount of text presented.

**Comment by Baltoli** [comment]
LLVM tools use `--help-hidden` for this, if you want to bikeshed the actual syntax. I'm in favour of the change generally speaking

**Comment by radumereuta** [comment]
See if the library we're using has support for different help lists.
Put the most egregious options into the secondary list and move more and more over time.

**Comment by ehildenb** [comment]
We could start by looking at which options the downstream semantics are actually using, and considering everything else as hidden.
