### ISSUE TITLE
`kdep` does not see new `--definition` option

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3404]
The only way to specify the location of a kompiled semantics for `kdep` is to use the deprecated flag `-d` / `--directory`. This will prevent us from fully removing `-d` from projects that also use `kdep`.

Motivating example from the [C semantics](https://github.com/runtimeverification/c-semantics/blob/84c8b9b7b19d66dbb25003a681b92620e4d830f8/Makefile#L180-L183)

**Comment by Baltoli** [comment]
@Robertorosmaninho I think the solution is to give `kdep` a `DefinitionLoadingOptions` rather than an `OutputDirectoryOptions`, which seems more semantically correct anyway.

**Comment by Robertorosmaninho** [comment]
@Baltoli, the `--definition` option is mainly used for `kprove` and `krun`. `kdep` as `kompile` should use `--output-definition` that have the same meaning.
