### ISSUE TITLE
Missing Section 2 of K Tutorial

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/k#3410]
The [first lesson](https://github.com/runtimeverification/k/tree/master/k-distribution/k-tutorial/2_intermediate/01_macros) of the K Tutorial - Intermediate section is already available on our repository but not on our webpage. So, we'll need to create a section for this second chapter and add the first lesson there. Further, lessons will be written later and should be updated incrementally.

**Comment by Baltoli** [comment]
@yiyi-wang-rv Can the website extractor be updated to include section 2 of the tutorial?
