### ISSUE TITLE
Investigate constant-folding collection functions

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3421]
If we see a function application like:
```
_List_(.List, L)
```
we should be able to constant-fold it in the compiler frontend to:
```
L
```

More generally, this would be nice for general collections with unit + append operations (possibly user-defined as well?)

**Comment by dwightguth** [comment]
@Baltoli I actually wrote a function that does this as part of my work on the Maude backend. The function you're looking for is called flattenLists.

https://github.com/runtimeverification/maude-backend/blob/11f2b999c6c2fecfd582bca18c896ace4ee47a43/src/main/java/org/kframework/backend/maude/RemoveUnit.java#L57

Feel free to use this as the starting point for creating a compiler pass in the frontend that does this. Don't try to replicate the rest of that file, though; it's doing something different.

**Comment by Baltoli** [comment]
Nice one, thanks for the pointer @dwightguth

**Comment by dwightguth** [comment]
You can use this function to take the function in the maude backend and turn it into a ModuleTransformer that can be put into the compilation pipeline of the frontend. https://github.com/runtimeverification/k/blob/8d1843daa095f403eedbf6b45fc90e4c0b8038c3/kore/src/main/scala/org/kframework/definition/transformers.scala#L45

The pipeline itself is in KoreBackend.java
