### ISSUE TITLE
`kompile --version` is slow

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3453]
Due to slow JVM startup, `kompile --version` takes around 0.3s. This is not ideal for tools like `kbuild` that rely on K version information but are expected to be fast.

Consider introducing a new tool, `kversion` or `kver`, that emits the same output as `kompile --version`, but without starting the JVM. This way, the time it takes to obtain the K version can be reduced to the 0.001s scale.

**Comment by radumereuta** [comment]
Currently, the version calculation is done here: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/utils/file/JarInfo.java#L75
We could move this functionality to this file: https://github.com/runtimeverification/k/blob/master/k-distribution/src/main/scripts/lib/k
which is being used by all the tools to start the JVM with the appropriate options.
We will need to run through all the options and if it finds `--version` print the version and exit.

**Comment by ehildenb** [comment]
Would just having a simple bash script `kversion` not work? It could read the version file from disk, and just print it. Might be simpler than modifying the `k` script, but I'm not sure I understand fully how the `k` script works.

**Comment by radumereuta** [comment]
It could work, but with a separate bash script, you will split/duplicate the functionality.
What I'm proposing is to move it all into that library which is being called by all the tools.
This way, we make kompile and kast and all the other tools get the benefit at the same time.
Also, `krun --version` just calls `kompile --version`.

**Comment by dwightguth** [comment]
https://github.com/runtimeverification/k/blob/8d1843daa095f403eedbf6b45fc90e4c0b8038c3/k-distribution/src/main/assembly/bin.xml This is where the files get packed into the final distribution. You might not need to edit this file if you can place the version file inside one of the directories that gets copied entirely.

**Comment by Robertorosmaninho** [comment]
> Currently, the version calculation is done here: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/utils/file/JarInfo.java#L75 We could move this functionality to this file: https://github.com/runtimeverification/k/blob/master/k-distribution/src/main/scripts/lib/k which is being used by all the tools to start the JVM with the appropriate options. We will need to run through all the options and if it finds `--version` print the version and exit.

kserver doesn't use the k script. Instead, it calls the Java Main by itself:
https://github.com/runtimeverification/k/blob/a017998b1e2c8c8e6c84a4349cd2374005fe595b/k-distribution/src/main/scripts/bin/kserver#LL15C1-L17C19

**Comment by Robertorosmaninho** [comment]
Fixed in #3454
