### ISSUE TITLE
Include booster backend in pom.xml build

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#3470]
Similar to how the `haskell-backend` is built, we need to:

- Clone the booster repo
- Build with `stack build` in a similar way to `haskell-backend/pom.xml`
- Modify the `k-distribution/src/main/assembly/bin.xml` to look for the appropriate binaries using the assemblies path.
- Add a CI test that the booster is launchable with the installed Ubuntu package.

**Comment by Robertorosmaninho** [comment]
Hey @ehildenb, could you give more details about the last task?

**Comment by ehildenb** [comment]
@Robertorosmaninho maybe you could just call the booster binary with `--version` to make sure it works on the installed package?

For example, here: https://github.com/runtimeverification/k/blob/ba7873e2e5daf8ed8be3d010ae8091c832396052/.github/workflows/release.yml#L84, we call tests that are supposed to work on the debian package. That is this script: https://github.com/runtimeverification/k/blob/ba7873e2e5daf8ed8be3d010ae8091c832396052/package/debian/test-package#L12. Which calls this script: https://github.com/runtimeverification/k/blob/ba7873e2e5daf8ed8be3d010ae8091c832396052/package/test-package. So you could add a line to that final `test-package` script saying:

```
kore-rpc-booster --help
```

To make sure that the booster is on `PATH` in the installed package. See the booster README here: https://github.com/runtimeverification/hs-backend-booster.

**Comment by Robertorosmaninho** [comment]
Closed by: #3475
