### ISSUE TITLE
`kompile` pipeline performance improvements

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3491]
The increased usage of `kompile` in interactive contexts means that we need to improve its performance. Hotspots are currently scattered throughout, so we need to audit and figure out how to improve things.

* [x] #3517
* [ ] #3444 is likely to be relevant; ModuleToKore is a bit of a black box and splitting it up will help us
* [ ] There are some algorithmically inefficient helper functions somewhere in the frontend reports @radumereuta 
* [x] https://github.com/runtimeverification/llvm-backend/issues/792
* [x] https://github.com/runtimeverification/llvm-backend/pull/794
* [x] https://github.com/runtimeverification/llvm-backend/pull/796

**Comment by palinatolmach** [comment]
For further performance profiling, the [`kompile-prof` folder](https://github.com/palinatolmach/foundry-test/tree/main/kompile-prof) contains files that are used when running `kompile` within `foundry-kompile`, when executed on the Foundry project located in the same [repository `foundry-test`](https://github.com/palinatolmach/foundry-test/tree/main) (that's the same project I used for performance tests before, the verbose logs for the kompilation are available [here](https://gist.github.com/palinatolmach/7342ff3e01e0b68269e0685ea7c9c616)). The zipped `kompile-prof` folder is attached here as well: [kompile-prof.zip](https://github.com/runtimeverification/k/files/12013831/kompile-prof.zip)

To execute `kompile` on these files used during `foundry-kompile`, run:

`cd kompile-prof && \` 
`kompile foundry.k --main-module FOUNDRY-MAIN --syntax-module FOUNDRY-CONTRACTS --md-selector 'k & ! node & ! concrete' --hook-namespaces 'JSON KRYPTO BLOCKCHAIN' --emit-json --backend haskell --verbose -I .`

(please add `--no-haskell-binary` if you're running it on Apple Silicon)

**Comment by radumereuta** [comment]
Thank you Palina, I just ran some tests and there seem to be a spike in the `--emit-json` part.
Here are my test results:
```
Outer parsing [168 modules]                                  =  0.939s
Parse configurations [0/5 declarations]                      =  1.674s
  New scanner: FOUNDRY-MAIN-RULE-CELLS                       =  2.029s
Parse rules [1/2888 rules]                                   =  3.094s
Validate definition                                          =  1.573s
Apply compile pipeline                                       = 20.787s
  Emit parsed & compiled JSON                                = 43.295s
Kompile to kore                                              = 43.402s
Save to disk                                                 =  1.075s
  Print definition.kore                                      = 11.441s
  Validate def                                               =  6.553s
Backend                                                      = 17.994s
Cleanup                                                      =  0.001s
Total                                                        = 01m 30s
```
Might be worth investigating using a different object factory. After a quick search I found this multiple times: `com.fasterxml.jackson.databind.JsonNode`

**Comment by radumereuta** [comment]
I managed to identify another hotspot in the compilation pipeline: `ExpandMacros`
What I did to measure the times for each step? In [`KoreBackend.java`](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java#L139)

Add these lines:
```java
        GlobalOptions go = new GlobalOptions();
        go.verbose = true;
        Stopwatch sw1 = new Stopwatch(go);
        AtomicInteger step = new AtomicInteger(148); // first line you call this visitor
        Function1<Definition, Definition> pTime = (d -> { sw1.printIntermediate("  Step:" + step.getAndIncrement()); return d;});

        return def -> pTime
                .andThen(resolveComm).andThen(pTime)
                .andThen(resolveIO).andThen(pTime)
```
This prints something like this:
```
Validate definition                                          =  1.685s
  Step:148                                                   =  7.056s // warmup from Kompile.java - ignore
  Step:149                                                   =  0.005s
  Step:150                                                   =  0.062s
  Step:151                                                   =  0.530s // resolveFun
  Step:152                                                   =  0.116s
  Step:153                                                   =  0.005s
  Step:154                                                   =  0.023s
  Step:155                                                   =  0.029s
  Step:156                                                   =  0.214s
  Step:157                                                   =  0.031s
  Step:158                                                   =  0.598s // resolveSemanticCasts
  Step:159                                                   =  0.219s // subsortKItem
  Step:160                                                   =  0.147s
  Step:161                                                   =  0.425s // generateSortProjections
  Step:162                                                   =  0.135s
  Step:163                                                   =  0.079s
  Step:164                                                   = 15.310s // expandMacros !!!
  Step:165                                                   =  0.013s
  Step:166                                                   =  0.010s
  Step:167                                                   =  0.057s
  Step:168                                                   =  0.175s
  Step:169                                                   =  0.007s
  Step:170                                                   =  0.146s
  Step:171                                                   =  0.335s // generateSortProjections
  Step:172                                                   =  0.166s
  Step:173                                                   =  0.006s
  Step:174                                                   =  0.001s
  Step:175                                                   =  0.299s
  Step:176                                                   =  0.004s
  Step:177                                                   =  0.001s
  Step:178                                                   =  0.099s
  Step:179                                                   =  0.045s
  Step:180                                                   =  0.005s
  Step:181                                                   =  0.005s
  Step:182                                                   =  0.160s // generateSortPredicateRules
  Step:183                                                   =  0.251s // numberSentences
Apply compile pipeline                                       = 20.048s
```

**Comment by Baltoli** [comment]
I fixed an issue in the LLVM backend macro expander where we experienced accidental quadratic behaviour: https://github.com/runtimeverification/llvm-backend/pull/562

**Comment by anvacaru** [comment]
[kompile-perf.tar.gz](https://github.com/runtimeverification/k/files/12335126/kompile-perf.tar.gz)

**Comment by radumereuta** [comment]
The last definition posted by Andrei took a long time to kompile because we had a regression in K.
This has been already reverted, and we're waiting for evm-semantics to catch up with the latest version of K.

**Comment by Baltoli** [comment]
Closing this for now as it's not been updated in a while; we can reopen if meaningful bottlenecks crop back up in the future.
