### ISSUE TITLE
OCaml backend doesn't handle multiplicity *

### ISSUE THREAD

**Issue by dplyukhin** [runtimeverification/k#35]
Sorry if this is a duplicate, as I'm aware some bugs with this are already known. Compiling the code below on my machine has the following output:
```
File "realdef.ml", line 1713, characters 79-80:
Error: Syntax error: ')' expected
File "realdef.ml", line 1713, characters 60-61:
Error: This '(' might be unmatched
[Error] Critical: ocamlopt returned nonzero exit code: 2
Examine output to see errors.
[Warning] Compiler: missing entry for hook BAG.concat
[Warning] Compiler: missing entry for hook BAG.element
[Warning] Compiler: missing entry for hook BAG.unit
```
Oddly enough, removing the `Exp` category gets rid of the OCaml syntax errors but not the warnings:
```
[Warning] Compiler: missing entry for hook BAG.concat
[Warning] Compiler: missing entry for hook BAG.element
[Warning] Compiler: missing entry for hook BAG.unit
```

Minimal-ish example:

```
module FOO-SYNTAX
  imports DOMAINS-SYNTAX

  syntax Id ::= "main" [token]

  syntax Exp  ::= Int | Bool | String
                 | "(" Exp ")"              [bracket]
                 | "-" Exp
                 > Exp "(" Exp ")"
                 | Exp "/" Exp              [left, strict]
                 | Exp "*" Exp              [left, strict]
                 | Exp "%" Exp              [strict, left]
                 > Exp "+" Exp              [left, strict]
                 | Exp "-" Exp              [left, strict]
                 > Exp "<"  Exp             [strict, non-assoc]
                 | Exp "<=" Exp             [strict, non-assoc]
                 | Exp ">"  Exp             [strict, non-assoc]
                 | Exp ">=" Exp             [strict, non-assoc]
                 | Exp "="  Exp             [strict, non-assoc]
                 | Exp "!=" Exp             [strict, non-assoc]
                 > "!" Exp                  [strict]
                 > Exp "&&" Exp             [left, strict(1)]
                 | Exp "||" Exp             [left, strict(1)]
                 | "(" Exp ")"              [bracket]

  syntax Pgm ::= Id

endmodule


module FOO
  imports FOO-SYNTAX
  imports DOMAINS
  syntax KResult ::= Int | Bool | String

  configuration <T color="yellow">
                  <actors color="orange">
                    <actor multiplicity="*" color="yellow">
                      <k color="green"> $PGM:Pgm </k>
                      <env color="violet"> .Map </env>
                      <store color="red"> .Map </store>
                      <nextLoc color="gray"> 0 </nextLoc>
                    </actor>
                   </actors>
                </T>
endmodule
```

**Comment by dwightguth** [comment]
the Ocaml backend doesn't support multisets, despite this being the default category of cell collection. From the configuration you display, it looks like removing duplicates would change the behavior of your semantics, so we're going to have to get slightly creative.

I would recommend that you add a new cell under actors called `<actorId>` and then add `type="Set"` after `multiplicity="*"`. Then you can assign each actor a unique id by putting `!ID:Int` in that cell whenever you create a new actor.

**Comment by dplyukhin** [comment]
Thanks, that works! Is there anywhere I can check what the Ocaml backend doesn't support, for future reference?

**Comment by dwightguth** [comment]
Not offhand, but the main things I can think of is that a few esoteric functions aren't supported (you can check include/ocaml/prelude.ml and look for functions that raise Not_implemented to see which ones), we don't support substitution, machine integers, cell bags, and of course we also don't support search, symbolic execution, or verification. The vast majority of these features are supported with --backend java, although that is much slower.

**Comment by ehildenb** [comment]
Closing this as we're no longer actively working on the OCaml backend. If this is still an issue, feel free to re-open.
