### ISSUE TITLE
Allow `"/"` only as the first character of a `BUBBLE` token

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3501]
Redefine [`BUBBLE`](https://github.com/runtimeverification/k/blob/7e7628ca60a207ac7f5c2624dc11ba1190aef491/kernel/src/main/javacc/Outer.jj#L583) as

```
<BUBBLE: ~[" ", "\t", "\r", "\n"] (~["/", " ", "\t", "\r", "\n"])*>
```

## Motivation

Consider

```k
module TEST-SYNTAX
    imports STRING-SYNTAX
endmodule

module TEST
    imports TEST-SYNTAX
    rule/*1*/ "foo" => "bar"
    rule/*2*/ "bar" => "baz"
endmodule
```

Kompiling this definition gives the following error:

```
[Error] Inner Parser: Parse error: unexpected token 'rule' following token
'"bar"'.
        Source(/home/ttoth/git/k/test.k)
        Location(8,5,8,9)
        8 |         rule/*2*/ "bar" => "baz"
          .         ^~~~
[Error] Compiler: Had 1 parsing errors.
```

which can be confusing as having only `rule/*1*/` in the definition parses fine.

The issue is that the first rule is outer parsed as:

```
"foo" => "bar"
    rule/*2*/ "bar" => "baz"
```

This is because JavaCC tries to match the longest possbile token, hence instead of lexing `rule` as `RULE` (and then `/*2*/` as `COMMENT`), it will lex `rule/*2*/` as `BUBBLE`. Note that the first `rule` token is lexed as `RULE` as expected, because in the `DEFAULT` lexer state there is no permissive token like `BUBBLE` to overlap with `COMMENT`.

## Analysis

There are two things to consider:
* Given a token that so far lexed as `COMMENT`, it will still lex as `COMMENT`: `/**/` could only be lexed as `(BUBBLE, "/**"), (BUBBLE, "/")` otherwise, but `"/**"` is shorter than `"/**/"`.
* Except for a comment (or comments) at the end of the bubble not separated by whitespace, all other characters that so far belonged to the bubble will still do: even though `bubble/*comment*/` will no longer be lexed as a single `BUBBLE`, if there are suitable tokens following, the comment will be appended to the bubble.

**Comment by gtrepta** [comment]
~~Wouldn't this break the parsing of tokens like `=/=Int`?~~ Nvm, looks like it doesn't.

**Comment by gtrepta** [comment]
I think we run into an issue with lexing line comments here:

https://github.com/runtimeverification/k/actions/runs/6029210633/job/16359659191?pr=3612#step:7:42

I believe what's happening is that this rule:

```
  rule #discardKeys => ( SetItem("//") SetItem("_info")
SetItem("callcreates") SetItem("sealEngine") SetItem("transactionSequence")
SetItem("chainname") )
```

Is being parsed like this:

```
  rule #discardKeys => ( SetItem("
SetItem("callcreates") SetItem("sealEngine") SetItem("transactionSequence")
SetItem("chainname") )
```

**Comment by tothtamas28** [comment]
> I believe what's happening is that this rule:
> 
> ```
>   rule #discardKeys => ( SetItem("//") SetItem("_info")
> SetItem("callcreates") SetItem("sealEngine") SetItem("transactionSequence")
> SetItem("chainname") )
> ```
> 
> Is being parsed like this:
> 
> ```
>   rule #discardKeys => ( SetItem("
> SetItem("callcreates") SetItem("sealEngine") SetItem("transactionSequence")
> SetItem("chainname") )
> ```

That's indeed the problem. Making sure `//` is not on the last line of the rule solves the issue:

```
rule #discardKeys => (
  SetItem("//")
  SetItem("_info")
  SetItem("callcreates")
  SetItem("sealEngine")
  SetItem("transactionSequence")
  SetItem("chainname")
)
```

Unfortunately, outer syntax leaks into inner syntax with comments (this is to ensure that a rule can be commented out, if I understand correctly), so there are these quirks.

**Comment by radumereuta** [comment]
This needs more investigation, but we should also time box this since it's not fixing anything critical, it just creates a different standard.

**Comment by gtrepta** [comment]
> That's indeed the problem. Making sure // is not on the last line of the rule solves the issue

This confused me at first, because it looked like my example didn't have `//` on the last line either, but that's just because the text was wrapped by the printer. See [this](https://github.com/runtimeverification/k/blob/9dd4c7b46ddcd1417f7cc3987760942009d02326/k-distribution/tests/profiling/evm-semantics/test.k#L4755)

### Analysis

So, the bubble is parsed as (`#discardKeys => ( SetItem("`,BUBBLE), (`//") ...`,COMMENT).

- In the breaking example, the following token is `rule`, and the special comment token with the rest of the rule never gets appended to the bubble.
- In Tamas' example, the following token is BUBBLE, so the comment *does* get appended.

### Options

- We can change the evm-semantics to Tamas' fix.
- We can leave this alone, and users will just have to make sure that tokens like `rule` are surrounded by whitespace.
- We can make further changes to recognize string literals, so this would parse like (`#discardKeys => ( SetItem(`,BUBBLE), (`"//"`,BUBBLE), (`...`,BUBBLE). This makes more assumptions about the inner syntax, though.

**Comment by gtrepta** [comment]
On a side note, there's a case that confuses me

```
  rule #discardKeys => (
    SetItem("//") // item 1
    SetItem("a")  // item 2
  )
```

This still parses without issue, but wouldn't the line comment in the `//") // item 1` token get mixed in with the bubble?

**Comment by tothtamas28** [comment]
> On a side note, there's a case that confuses me
> 
> ```
>   rule #discardKeys => (
>     SetItem("//") // item 1
>     SetItem("a")  // item 2
>   )
> ```

In both the current and the proposed solution, this would produce a bubble

```
#discardKeys => (
  SetItem("//") // item 1
  SetItem("a")  // item 2
)
```

The line comments are then discarded by the inner (rule) syntax.

**Comment by gtrepta** [comment]
> The line comments are then discarded by the inner (rule) syntax.

From the `#Layout` production? I tried setting no layout with `syntax #Layout` but it still parsed.

**Comment by tothtamas28** [comment]
> From the `#Layout` production? I tried setting no layout with `syntax #Layout` but it still parsed.

Are you sure that also overrides rule syntax, not just program syntax?

**Comment by radumereuta** [comment]
This is taking to long to get right.
The current solution is working fine.
Please reopen if it becomes an actual issue.
