### ISSUE TITLE
Dump inputs to Z3

### ISSUE THREAD

**Issue by bl4ck5un** [runtimeverification/k#352]
Thanks for the great project!

When generating proofs, is it possible to dump the inputs to Z3 solver?

**Comment by denis-bogdanas** [comment]
Yes, please use option `--debug-z3-queries`. Z3 inputs will be mixed with tons of other logs however, but you'll see what are z3 queries.

**Comment by bl4ck5un** [comment]
Should I use it with `kprove` or some other executable?

**Comment by denis-bogdanas** [comment]
kprove

**Comment by bl4ck5un** [comment]
Maybe it's because I'm using the Java backend from kevm?

~~~
+ kprove --directory ~/tmp/evm-semantics/.build/java tests/proofs/specs/vyper-erc20/totalSupply-spec.k --def-module VERIFICATION '' --debug-z3-queries
[Error] Critical: Unknown option: --debug-z3-queries (Unknown option:
--debug-z3-queries
~~~

**Comment by denis-bogdanas** [comment]
it only exists in Java backend. Option is recent. Please use latest K from branch `master`.

**Comment by denis-bogdanas** [comment]
or if you use proofs from VSC, use K from branch `gnosis`.
