### ISSUE TITLE
[K-Improvement] Create `Ordering` instance for `Sentence`'s subclasses

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/k#3530]
## Motivation
We may need in the future to sort all sentences from a module to test a property or apply a transformation.

Following the last comment of #3523.

**Comment by Robertorosmaninho** [comment]
We need to find which subtypes of sentences need to implement the ordering like we already have for [Rules](https://github.com/runtimeverification/k/blob/a91e8fd25a0eaea0ca2acc901132b220f1f3007d/kore/src/main/scala/org/kframework/definition/outer.scala#L446) and Productions.

We also need a way to order all sentences between the types. Ex: Order -> Production

Also, we would like to have a lazy val within this types sorted like in [sortedProdutions](https://github.com/runtimeverification/k/blob/a91e8fd25a0eaea0ca2acc901132b220f1f3007d/kore/src/main/scala/org/kframework/definition/outer.scala#L141)

**Comment by radumereuta** [comment]
Unit tests should help here.
We don't have tests like this anywhere else.

**Comment by radumereuta** [comment]
This was reverted because it may have been the cause of the release failing.
Revisit with more testing.

**Comment by radumereuta** [comment]
Try to investigate by comparing `definition.kore` from mac and linux.
The order in which we put axioms in the kore file will have an effect on the search results.
OSx and linux might have different versions of the C++ std library.

We're putting the search results in a standard unordered set.
We're supposed to sort the output in the pretty printer. Investigate why that's not working.
https://github.com/runtimeverification/llvm-backend/blob/master/lib/ast/AST.cpp#L897

Ask Freeman for access to a Mac machine.

**Comment by gtrepta** [comment]
This `sortCollections` method that Radu linked doesn't look like it gets called when doing search.

Search calls `printConfigurations` in `runtime/util/ConfigurationPrinter.cpp`, which loops through the search results with `PrintConfigurationInternal`, which doesn't use `sortCollections`.

`sortCollections` gets used by `printKORE`, used by `printMatchResult`, used by the `k-rule-apply` tool.

**Comment by gtrepta** [comment]
Had a deeper look, my above comment can be ignored.

In the error case, the bad output is coming from `kprint`, which does make use of `sortCollections`. I'll keep investigating.
