### ISSUE TITLE
Tutorial lesson 1.4 doesn't mention maximal-munch lexing

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3539]
The exercise in question asks the user to identify why this grammar isn't ambiguous for the input `abb`:
```k
module EXERCISE4
  syntax Expr ::= "a" Expr "b"
                | "abb"
                | "b"
endmodule
```

For experienced K users, the answer is clearly that the lexer tokenises `abb` before the parser is ever called, but I don't see where we explain longest-match lexing in the tutorial. We should add a short section explaining this when we introduce lexing and parsing.

**Comment by radumereuta** [comment]
It might be sufficient to mention that the lexer will choose the max length. If there are ambiguities after that, it will choose the max precedence token.
Adding a link to the Flex documentation would be great.
