### ISSUE TITLE
add timeout flags to krun

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#3573]
kprove has flags to set the z3 timeout. The integration tests of K are failing inconsistently due to the z3 timeout being reached. We should modify the krun script so that we have the option to customize the timeout that gets passed to z3.

This is high priority since it is interfering with the release.

**Comment by dwightguth** [comment]
I know on slack I mentioned two timeouts since that's what flags kprove offers, but it looks like the haskell backend only supports one timeout, so the flag name should just be --z3-timeout.

**Comment by dwightguth** [comment]
I was wrong; this is not blocking currently.

**Comment by Scott-Guest** [comment]
Closed by #3575
