### ISSUE TITLE
[K-Bug] `kompile` throw a raw llvm error message when a rule in a `requires` is not defined

### ISSUE THREAD

**Issue by iFrostizz** [runtimeverification/k#3585]
### What component is the issue in?

llvm-backend

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v6.0.58

### Operating System

Linux

### K Definitions (If Possible)

```k
module SIGNED-INT
    imports INT
    imports BOOL

    syntax Int ::= "minSInt8"       [macro]
                 | "maxSInt8"       [alias]
                 | "minSInt16"      [macro]
                 | "maxSInt16"      [alias]

    syntax TypedArg ::= #int8  ( Int )   [symbol]
                      | #int16 ( Int )   [symbol]

    syntax Int ::= #getValue ( TypedArg ) [function]

    syntax Bool ::= #rangeSInt ( Int, Int ) [alias]

    rule #int8  ( X ) => X
    rule #int16 ( X ) => X

    rule minSInt8  => 0
    rule maxSInt8  => 1
    rule minSInt16 => 2
    rule maxSInt16 => 3

    rule #rangeSInt ( 8 , X ) => minSInt8  <=Int X andBool X  <Int maxSInt8 
    // rule #rangeSInt ( 16, X ) => minSInt16 <=Int X andBool X  <Int maxSInt16 // NOTE I should be defined !!

    rule #getValue(   #int8 ( X )) => X       requires #rangeSInt(8 ,   X)
    rule #getValue(   #int16( X )) => X       requires #rangeSInt(16,   X)
endmodule
```

### Input

`kompile sint.k --main-module SIGNED-INT --backend llvm`

### Output

```sh
Function return type does not match operand type of return inst!
  ret %block* %4
 i1llc: error: 'tmp.OdhC0jH8Xr': input module cannot be verified
[Error] Critical: llvm-kompile returned nonzero exit code: 1
Examine output to see errors.
[Warning] Compiler: Could not find main syntax module with name
SIGNED-INT-SYNTAX in definition.  Use --syntax-module to specify one. Using
SIGNED-INT as default.
```

### Input

`cd sint-kompiled`
`llvm-kompile-codegen definition.kore dt/dt.yaml dt --no-optimize -o definition.ll`
`opt -verify definition.ll -o /dev/null`

### Output

```sh
opt: definition.ll:540:7: error: value doesn't match function result type 'i1'
  ret %block* %4
      ^
```

### Expected Results

A more helpful error message, showing that the rule that is in the `requires` clause called `#rangeSInt(16,   X)` should be defined.

**Comment by dwightguth** [comment]
We already perform some semantic checks after the macro expansion pass runs to ensure that the expanded forms of rules don't break any of the invariants we expect for rules. What we need to do is run one additional check at this time that checks that no symbols for which there are macros or aliases defined appear in any rule that is not a macro or an alias.

**Comment by gtrepta** [comment]
It looks like there's a check here that's supposed to handle the case @dwightguth mentioned. Is this what it's supposed to do or does it need to be expanded?

https://github.com/runtimeverification/k/blob/6cbfd9428c8de76e0fc69461ef089aeadf30ce00/kernel/src/main/java/org/kframework/compile/ExpandMacros.java#L185-L190

**Comment by Robertorosmaninho** [comment]
The problem here seems to be that we only check this for the body of the rule: https://github.com/runtimeverification/k/blob/6cbfd9428c8de76e0fc69461ef089aeadf30ce00/kernel/src/main/java/org/kframework/compile/ExpandMacros.java#L200

And we don't check it for `requires` or `ensures`!

**Comment by Robertorosmaninho** [comment]
A related issue is that if the rule is an identity rule, the error is the same. Ex.:

```k
module SIGNED-INT
    imports INT
    imports BOOL

    syntax Int  ::= #foo ( Int ) [function]
    syntax Bool ::= #bar ( Int ) [alias]

    rule #bar( X ) => X
    rule #foo( X ) => X       requires #bar( X )
endmodule

```
