### ISSUE TITLE
Investigate bumping JVM to v17

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3591]
We could use the features of the newer Java, but we need to make sure it works on older platforms that we are still supporting.
Particularly Ubuntu 20 may not build correctly yet. But that needs to be investigated.

**Comment by ehildenb** [comment]
Semantics still using Ubuntu focal:

- Priavte semantics: https://github.com/runtimeverification/algorand-sc-semantics. No longer in maintenance.
- Private semantics: https://github.com/runtimeverification/c-semantics/blob/master/.github/workflows/test.yml. Can be upgraded.

I think we can safely delete our Focal packaging.

**Comment by ehildenb** [comment]
Next issue we can move on to is minimizing scala code in the codebase. Java17 has record types, which is one of th emain features missing from earlier versions which caused us to use Scala.

We can make an issue about it once

**Comment by Baltoli** [comment]
Is it worth reconsidering our previously-stated position on long-term support for Ubuntu distributions? Previously, we've agreed internally that we should support 2 LTS releases (currently, that's 20.04 and 22.04, and under this scheme we'd swap 20.04 for 24.04 in April). However, if supporting a now 3-year old OS is going to cause us pain, then perhaps we want to relax that stance and only support a single LTS. I think, off the top of my head, that dropping Focal would also allow us to rationalise the number of LLVM versions we support, and therefore clean up some code in the backend.

**Comment by Baltoli** [comment]
@Scott-Guest notes that pattern matching support in 17 is limited; we might need to wait for 21

**Comment by ehildenb** [comment]
We'll try just updating the Java version in the pom.xml, and see if anything breaks!

If we can bump to 17, we can update the documentation/dockerfiles etc..., and then we can start taking advantage of new features.

Would be useful for someone to list the new features we'd like to take advantage of, so we can have targeted refactors.

**Comment by ehildenb** [comment]
Features to take advantage of:

- Record types.
