### ISSUE TITLE
Change to emitted no junk rules with nested `\or` to `\left-assoc{\or}` is breaking integration test in haskell-backend

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/k#3599]
All path reachability test is failing with:

```
diff -u all-path-total-spec.k.out.golden all-path-total-spec.k.out || ( mv all-path-total-spec.k.out all-path-total-spec.k.out.fail && false )
--- all-path-total-spec.k.out.golden	2023-08-24 10:12:45.724066576 +0000
+++ all-path-total-spec.k.out	2023-08-24 10:17:53.008350178 +0000
@@ -1 +1,21 @@
-#Top
+  #Not ( {
+    X
+  #Equals
+    a
+  } )
+#And
+  #Not ( {
+    X
+  #Equals
+    b
+  } )
+#And
+  #Not ( {
+    X
+  #Equals
+    c
+  } )
+#And
+  <k>
+    total ( X ) ~> .
+  </k>
```

The cause is the change to the format of the no-junk rule (intorduced in  #3588) from:

```
axiom{} \or{SortS{}} (Lbla'Unds'PATH'Unds'S{}(), \or{SortS{}} (Lblb'Unds'PATH'Unds'S{}(), \or{SortS{}} (Lblc'Unds'PATH'Unds'S{}(), \bottom{SortS{}}()))) [constructor{}()] // no junk
```

to

```
axiom{} \left-assoc{}(\or{SortS{}} (Lbla'Unds'PATH'Unds'S{}(), Lblb'Unds'PATH'Unds'S{}(), Lblc'Unds'PATH'Unds'S{}(), \bottom{SortS{}}())) [constructor{}()] // no junk
```

where the new format internally expands to:

```
axiom{} \or{SortS{}} (\or{SortS{}} (\or{SortS{}} (Lbla'Unds'PATH'Unds'S{}(), Lblb'Unds'PATH'Unds'S{}()), Lblc'Unds'PATH'Unds'S{}()), \bottom{SortS{}}()) [constructor{}()] // no junk
```

This in turn fails to be internalized, because the function which recognizes no junk axioms expects the rule to be right-assoc, i.e. it recurses on the right child of \or:

https://github.com/runtimeverification/haskell-backend/blob/1da6c43b8bb74a231b58978b1964a45d7ca753e4/kore/src/Kore/Attribute/Sort/ConstructorsBuilder.hs#L119

This was confirmed by changing the axiom to

```
axiom{} \right-assoc{}(\or{SortS{}} (Lbla'Unds'PATH'Unds'S{}(), Lblb'Unds'PATH'Unds'S{}(), Lblc'Unds'PATH'Unds'S{}(), \bottom{SortS{}}())) [constructor{}()] // no junk
```

and re-running the proof, which resulted in the expected `#Top`.

Unless there is a blocking reason, the front-end should probably emit 

```
axiom{} \right-assoc{}(\or{SortS{}} (Lbla'Unds'PATH'Unds'S{}(), Lblb'Unds'PATH'Unds'S{}(), Lblc'Unds'PATH'Unds'S{}(), \bottom{SortS{}}())) [constructor{}()] // no junk
```

to be consistent with the previous version?

**Comment by ehildenb** [comment]
Change is here: https://github.com/runtimeverification/k/blob/645ffc4d6e3c34de3d85574a93604c9507af222e/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L716
