### ISSUE TITLE
Missing `gdate` as MacOS dependence 

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/k#3610]
### What component is the issue in?

None

### Which command

- [ ] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v6.0.75

### Operating System

MacOS (Apple Silicon/AMD)

### Steps to Reproduce

`gdate` is used in a few scripts to get the build version, for example, but it is mainly by the `llvm-backend`, as we can see if we grep it:
```
grep -Iir "gdate" .
./llvm-backend/target/build/install/lib/scripts/utils.sh:  DATE_CMD="gdate"
./llvm-backend/target/build/bin/utils.sh:  DATE_CMD="gdate"
./llvm-backend/src/main/native/llvm-backend/nix/llvm-backend.nix:      --replace 'gdate' 'date'
./llvm-backend/src/main/native/llvm-backend/bin/utils.sh:  DATE_CMD="gdate"
./k-distribution/src/main/scripts/lib/k:            versionDate=$(gdate -d "@${versionTimestampInMilliseconds}" "+%a %b %d %H:%M:%S %Z %Y")
```

### Expected Results

On README.md we should have:

"On macOS using [Homebrew](https://brew.sh/):

```shell
git submodule update --init --recursive
brew install bison boost cmake flex fmt gcc gdate gmp openjdk jemalloc libyaml llvm@15 make maven mpfr pkg-config python stack zlib z3
```

**Note**: in this case llvm@15 is required."

**Comment by Robertorosmaninho** [comment]
We probably want to add this as a dependence on our Homebrew formula and for `kup`

**Comment by Baltoli** [comment]
There's an OS check around usages of gdate that I'd expect to set the command to just "date". I think you actually want to work out why that isn't firing somewhere

**Comment by radumereuta** [comment]
```
if [[ "$OSTYPE" == "darwin"* ]]; then
  DATE_CMD="gdate"
else
  DATE_CMD="date"
fi
```
@Baltoli this makes it look like we're explicitly looking for `gdate` on macos. Which way is it?

**Comment by Baltoli** [comment]
Oh yeah you're right, ignore my prior comment! I forgot the exact details when I was skimming this issue

**Comment by radumereuta** [comment]
Modify the script to use the correct date tool found on the system.
Maybe we can pass some arguments to the date util. If not, we could modify the output with some script.

**Comment by Robertorosmaninho** [comment]
`gdate` is necessary on llvm-backend for macOS as we need milliseconds precision for `--profile` (see https://github.com/runtimeverification/llvm-backend/pull/793). 

Unfortunately, MacOS uses FreeBSD date instead of Unix date, which is very limited in features and doesn't have support for getting the timestamp with milliseconds precision.

If eliminating `gdate` dependence is still pertinent, a workaround can be done using Python's time (see [this](https://apple.stackexchange.com/a/314573)) and an alias for `date`.

**Comment by Robertorosmaninho** [comment]
Perhaps `perl` or `time`

**Comment by Robertorosmaninho** [comment]
On `Bash>=5` we have the options of: `${$(( EPOCHREALTIME * 1000 ))/.*/}`

**Comment by Robertorosmaninho** [comment]
With `perl` we have: `perl -MTime::HiRes=time -e 'printf "%d\n", time*1000'`
