### ISSUE TITLE
[K-Bug] krun currently doesn't show the order where to put the options

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/k#3620]
### What component is the issue in?

Front-End

### Which command

- [ ] kompile
- [ ] kast
- [X] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

 v6.0.83-0-gc2ad66e022

### Operating System

MacOS (Apple Silicon/AMD)

### Steps to Reproduce

Currently `krun` accepts 2 types of options: `General options` and `krun options`, but none of these are mentioned in the order of a krun call:

```
krun --help
Usage: krun [PROGRAM] [-cNAME=VALUE] [-d DIR]
```

### Expected Results

Something like we have for kompile's help message:
```
kompile --help
Usage: kompile [options] <file>
```

This is a very common pattern in compilers: kompile, java, clang, gcc, etc...
But also in interpreters like Python and GHCi!

**Comment by radumereuta** [comment]
Please provide some before and after with the changes you want to add. We can discuss further on concrete improvements.
