### ISSUE TITLE
[K-Bug] `kompile` throw a raw llvm error message when a rule in a invalid `requires` and doesn't throw any in a invalid `ensures`

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/k#3661]
### What component is the issue in?

Front-End

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v6.0.113-0-gcb848f3950 Build date:   Mon Sep 25 14:32:32 -03 2023

### Operating System

MacOS (Apple Silicon/AMD)

### K Definitions (If Possible)

```
module TEST
    imports INT
    imports BOOL

    syntax Int  ::= #foo ( Int ) [function]
    syntax Bool ::= #bar ( Int ) [alias]

    rule #bar ( X ) => X // This should fail with type error: Int != Bool

    rule #foo( X ) => X       ensures  #bar( X ) // This passes, but it should?
    rule #foo( X ) => X       requires  #bar( X ) // This produces the llvm error
endmodule
```

### Steps to Reproduce

```
kompile test.k --main-module TEST --syntax-module TEST --backend llvm  --no-exc-wrap
```

### Expected Results

The front end should print an error in both cases saying that the ` rule #bar ( X ) => X` is returning an `Int` instead of a `Bool`.

**Comment by Robertorosmaninho** [comment]
#3585 may be related

**Comment by radumereuta** [comment]
There should be a check for LHS and RHS for macros/alias.
This may have been broken when we changed the label from rule to syntax.
We do something similar for function rules.

https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/parser/inner/disambiguation/TypeInferencer.java#L388
We may need to modify this to include macros as well.
