### ISSUE TITLE
Option to provide partial parse tree in parse error message

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#3672]
This idea for an improvement to K came out of https://github.com/runtimeverification/k/issues/3647.

The idea essentially is to provide an option to `kompile` or `kast` that provides a more detailed error message when a parsing error occurs in the inner parser. Particularly, the idea is to provide information about the partial parse forest that was constructed by parsing the sentence up to the point of the error. This term would not be able to be pretty printed because it will not actually type, but it could be printed in abstract syntax in order to provide insight into the current state of the parser.

The idea essentially would be to print an AST in the error message with the following properties:

1. Its leaves will be the tokens in the sentence that were scanned.
2. Each parent node will contain one child per production item in the production it corresponds to
3. Ambiguities will be represented using a localized `amb` node.

This should be relatively straightforward to obtain from the internal state of the parser, with a bit of tweaking in order to render it the way we want to. It will, however, be quite verbose in many cases and should not be enabled by default.

**Comment by radumereuta** [comment]
We need to reconstruct the partial AST and pretty print it.
We should hide this behavior under a new option since it could produce large output.
