### ISSUE TITLE
[K-Bug] v6.0.129 not version and so prints as "v"

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/k#3690]
### What component is the issue in?

Front-End

### Which command

- [X] kompile
- [X] kast
- [X] krun
- [X] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

v6.0.129

### Operating System

Linux

### Steps to Reproduce

daniel@daniel-MS-7E06 ~$ kup install k
removing 'github:runtimeverification/k/v6.0.128#packages.x86_64-linux.k'
 ✅ Successfully updated 'k' to version k (master).
daniel@daniel-MS-7E06 ~$ krun --version
cat: /nix/store/9swhc7ywxifkg5x05s65wzpf81i5vygr-k-6.0.129-e30530e4e57a860b57d66f366c8192f9b37a2657-maven/lib/version: No such file or directory
K version:    v
Build date:   Wed Oct 04 06:08:27 AEST 2023
daniel@daniel-MS-7E06 ~$ 

### Expected Results

daniel@daniel-MS-7E06 ~$ krun --version
K version:    v6.0.129
Build date:   Wed Oct 04 01:49:55 AEST 2023

**Comment by tothtamas28** [comment]
This bug is also present in the Debian package: https://github.com/runtimeverification/pyk/actions/runs/6399807070/job/17372506101?pr=675

**Comment by Robertorosmaninho** [comment]
Fixed with https://github.com/runtimeverification/k/pull/3691
