### ISSUE TITLE
Module imports broken for files named `README.md`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3695]
[A user on Discord reports](https://discord.com/channels/824582698147905556/824596103311786034/1160178825129377862) that they cannot import a module directly from a `README.md` in the tutorial.

The following code is a minimal reproduction:

`README.md`
````markdown
```k
module A
endmodule
```
````

`a.md`
````markdown
```k
module A
endmodule
```
````

`test.k`
```k
require "README.md"

module TEST
  imports A
endmodule
```

```console
$ kompile --version
K version:    v6.0.134
Build date:   Thu Oct 05 19:09:38 BST 2023
$ kompile test.k
[Error] Compiler: Could not find module: A
	Source(/home/bruce/code/scratch/test.k)
	Location(4,3,4,12)
	4 |	  imports A
	  .	  ^~~~~~~~~
```

If the `require` line in `test.k` is pointed at `a.md` instead, we see:
```console
$ kompile --version
K version:    v6.0.134
Build date:   Thu Oct 05 19:09:38 BST 2023
$ kompile test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
```
as expected.

**Comment by radumereuta** [comment]
This fails because it finds this file first: https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/README.md
from the builtin directory and ignores the one on the current path.
The local file should always be prioritized. I'm investigating further. Should be an easy fix.

**Comment by radumereuta** [comment]
Move the readme.md into the parent directory and make sure the links from the file still work and that all the other links pointing to that file still work.
Check with @yiyi-wang-rv that we don't break anything on the website.
Once it's deployed, double check that everything on the website still works.
