### ISSUE TITLE
Update, remove or document `pl-tutorial`

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3704]
The PL tutorial is leading to confusion from external users who are unable to complete the lessons as written with modern K: https://github.com/runtimeverification/k/issues/3698

We should do one of the following things:
* Update the lessons to reflect the current set of features supported by modern K
* Remove the broken code (rather than just [dropping it silently from CI](https://github.com/runtimeverification/k/commit/6c122465e238d5df71a8b4c2fe71d79ab2089216))
* Document externally that this tutorial is out of date and should not be relied on

**Comment by Baltoli** [comment]
Worth noting that we link to this content _directly_ from the https://kframework.org/ landing page, so we really ought to resolve this one way or another.

**Comment by Baltoli** [comment]
@dwightguth favours the documentation option; we should also update the website homepage to reflect that. Best option as a stopgap

**Comment by Baltoli** [comment]
Is @grosu still using this code for anything teaching-related?

**Comment by QWYNG** [comment]
@Baltoli 
Thank you for opening this issue!
Currently, is there any other documentation you would recommend for a beginning student to learn k?

**Comment by Baltoli** [comment]
https://kframework.org/k-distribution/k-tutorial/ The K tutorial is the best place to learn K as a programming language; the PL tutorial that you had the issue with is more of a reference for "how can I implement language X in K?

If you've finished the K tutorial, and would like some advice on using K in practice for a project, come and find us on Discord: https://discord.com/invite/CurfmXNtbN
