### ISSUE TITLE
`#let` desugaring into `#lambda` should be total (sometimes)

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/k#3715]
Currently the front-end turns `#let <X> = <Y> in ... <X>...` into `#lambda__` expressions in kore, e.g:

```
rule [range-memUpdate-before]:
      #range(B1:Bytes [ S1:Int := B2:Bytes ], S2:Int, W2:Int) =>
        #let W = minInt(W2, S1 -Int S2) #in
          #range(B1, S2, W) +Bytes #range(B1 [ S1 := B2 ], S1, W2 -Int W)
      requires 0 <=Int S2 andBool S2 <Int S1
      [simplification]
```
gets turned into:

```
rule
  #range(B1:Bytes [ S1:Int := B2:Bytes ], S2:Int, W2:Int) =>
    #lambda__3(minInt(W2, S1 -Int S2),B1,S2,B1,S1,B2,S1,W2) 
  requires 0 <=Int S2 andBool S2 <Int S1

rule 
  #lambda__3(W,B1,S2,B1,S1,B2,S1,W2) =>
    #range(B1,S2,W) +Bytes #range(B1 [ S1 := B2 ], S1, W2 -Int W)
```

In the case above where the LHS of a let is a variable, the corresponding `#lambda__3` should be marked as a total function, to allow simplification in the booster back-end.

**Comment by Robertorosmaninho** [comment]
@dwightguth [resolveFun.java](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/compile/ResolveFun.java) The modification should be in this file. The modification should be simple.

**Comment by Baltoli** [comment]
@goodlyrottenapple how important is this for you to have implemented?

**Comment by goodlyrottenapple** [comment]
Not super high priority as rules using `#let` can be re-written without it to work with booster

**Comment by Baltoli** [comment]
Ah, this looks like it shouldn't be a huge change and it would be nice to avoid having to rewrite semantics code to deal with it. Will take a look at implementing it just now
