### ISSUE TITLE
Arch packaging step fails when setting up Docker

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3723]
### Symptoms

The Arch packaging step in the release CI job fails intermittently with an error like:
```
failed to prepare mspe7tld30tquuk7bg91h3uuw: invalid argument
```
when running the user and group creation step.

### Investigation

Maybe related?
* https://github.com/docker/buildx/issues/2021

Example runs:
* https://github.com/runtimeverification/k/actions/runs/6548843829/job/17784426991
* https://github.com/runtimeverification/k/actions/runs/6589987603/job/17905643103
* https://github.com/runtimeverification/k/actions/runs/6615629899/job/17968450307

### Fix

**Comment by F-WRunTime** [comment]
Dropped Arch Linux No longer need this issue
