### ISSUE TITLE
Resource exhaustion in CI can break release builds

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3729]
### Symptoms

The K test suite can fail with what appears to be a resource exhaustion issue when cutting a release; we see errors like:
```
kore-exec: [41516716] Error (ErrorException):
    user error (Unexpected result from the SMT solver:
      Command: (push 1 )
      Expected: success
      Result: (error "line 178 column 8: push canceled" )
    )
Created bug report: kore-exec.tar.gz
Error:  Critical: Haskell Backend execution failed with code 1 and produced no output.
```
indicating that Z3 is timing out, along with other warnings like:
```
kore-exec: [177385677] Warning (WarnIfLowProductivity):
    Productivity dropped to: 49%
    Relevant K files include:
        /root/pl-tutorial/1_k/5_types/lesson_5.5/lambda.k
    Poor productivity may indicate a performance bug.
    Please file a bug report: https://github.com/runtimeverification/haskell-backend/issues
```

### Investigation

Example runs:
* https://github.com/runtimeverification/k/actions/runs/6564746927/job/17832190102
* https://github.com/runtimeverification/k/actions/runs/6588479144/job/17900818309

### Fix

**Comment by ehildenb** [comment]
We may want to just increase the overall Z3 timeout. Options are:

- `--smt-timeout NNN`, kill Z3 queries after `NNN` ms.
- `--smt-retry-limit M`, retry Z3 queries `M` times, each time adding another `NNN` ms to the timeout.

We should consider setting these defaults higher in the haskell backend directly. Good defaults would be 300ms and 2, and we need to do this for both `kore-exec` and `kore-rpc`.

We also need to check that this exception is one that the code will actually catch and retry on:

![Image](https://github.com/runtimeverification/k/assets/12721972/7b7fd824-3075-4f36-85d3-bfa49d747132)

**Comment by Baltoli** [comment]
@goodlyrottenapple still investigating whether we do the retry logic here properly - not obvious whether we are or aren't given how difficult this is to reproduce locally. Needs some more logging / introspection.

@ehildenb suggests calling `false` rather that `z3` - easy way to produce a consistent crash?
