### ISSUE TITLE
Haskell backend exception breaks release build on Arch Linux

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#3731]
The most recent K release build has failed: https://github.com/runtimeverification/k/actions/runs/6573891973/job/17858853532

### Symptoms

The "Build and Test Package" step of the K release on Arch Linux failed with the following error:

```
kore-exec: [800979013] Error (ErrorException):
    arithmetic underflow
Created bug report: kore-exec.tar.gz
Error:  krun: kore-exec ./lambda-kompiled/haskellDefinition.bin --module LAMBDA --pattern /tmp/.krun-2023-10-19-13-05-57-aaq4ojhJqy/tmp.in.oOrNWXIbzg --output /tmp/.krun-2023-10-19-13-05-57-aaq4ojhJqy/result.kore --searchType FINAL --search /tmp/.krun-2023-10-19-13-05-57-aaq4ojhJqy/tmp.pattern.YheUC7bp6U --smt none
Error:  krun: Backend crashed during rewriting with exit code 1
0a1,5
> {
>   T:Type
> #Equals
>   bool -> bool
> }
make[3]: *** [/usr/include/kframework/ktest.mak:103: tests/nested-lets.lambda] Error 1
```

This is in `k-distribution/pl-tutorial/1_k/5_types/lesson_5.5`.

### Investigation

Still digging into whether this issue can reproduce consistently, but the error in question might relate to the Data.Compact package, which we have had problems with before on certain platforms.

**Comment by dwightguth** [comment]
This is evidently an intermittent issue, which might make it difficult to track down. Let's leave it until we at least can identify how frequently it occurs.

**Comment by Baltoli** [comment]
We no longer support Arch Linux explicitly.
