### ISSUE TITLE
Automatically add dependencies updates to the project board

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#3740]
Currently, we automatically open PRs to update dependencies like the llvm-backend, haskell-backend, and the booster-backend.
We should add those PRs to the K board automatically so we can better keep track of them in our planning meetings. Otherwise, it's easy to overlook and we have long-standing PRs that can get out of date, start failing, and make them more of a handful.
I took this idea from the kontrol meeting.

Example PR: https://github.com/runtimeverification/k/pull/3739

**Comment by radumereuta** [comment]
~~Probably, this is where we need to add something: https://github.com/runtimeverification/devops/blob/master/update-deps.sh#L55~~
We may be able to use this: https://cli.github.com/manual/gh_project

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/devops/blob/dd5bdc4467467ea3b3551f5d3e54ecf28592ae3d/.github/workflows/update-deps.yml#L83-L91

The correct code is here ^

Steps:
- Add a parameter to the yaml for the project ID to use
- Need a separate file mapping project -> boards to use? or just to the K board?
- Update the script to use `gh project` to add the newly created PR to the board
