### ISSUE TITLE
Adopt Scala auto-formatter

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#3827]
Similarly to #3757, we should consider adopting a Scala auto-formatter.

[scalafmt](https://github.com/scalameta/scalafmt) seems to be a popular choice and is easily integrated with IntelliJ. The default settings look fine for me, perhaps setting `maxColumn = 100` to align with the Java formatter.

**Comment by Baltoli** [comment]
@radumereuta queries whether there are any semantic aspects to the formatting introduced here, or if it's purely stylistic. It might also be worth taking a look at what we get from IntelliJ. Any low-hanging fixes are probably worth doing.

**Comment by Baltoli** [comment]
@Scott-Guest suggests that it might also be worth looking at what bits of Scala we could port to Java?
