### ISSUE TITLE
Consider enabling Java 17 preview features

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#3836]
If we build with `--enable-preview`, Java 17 supports a limited form of pattern matching in the style of 
```
int perimeter(Shape shape) {
   return switch (shape) {
       case Circle c -> 2 * Math.PI * c.getRadius();
       case Rectangle r -> 2 * r.getWidth() + 2 * r.getLength();
   };
}
```
with optional guards on patterns as well. This is a very nice addition, and in combination with sealed class hierarchies allows for somewhat useable sum types.

However, this is only a preview feature, so some details change between Java 17 and the final implementation in Java 21.

Specifically, reading through the relevant JEPs ([406](https://openjdk.org/jeps/406), [420](https://openjdk.org/jeps/420), [427](https://openjdk.org/jeps/427), [433](https://openjdk.org/jeps/433), [441](https://openjdk.org/jeps/441)), the full-fledged feature in Java 21 breaks syntactic compatibility with the preview in Java 17 in that:
- Pattern guard syntax changes from `pattern && guard` to `pattern when guard`
- Adding parenthesis around patterns is no longer permitted (it was permitted before, but semantically meaningless).
- For readability, it is enforced that constant case labels must appear before more general patterns of the same type.

Additionally, it breaks semantic compatibility in that

- `null` only matches explicit `case null` labels, while previously it would also match any total type pattern (i.e. a pattern subsuming the type of the scrutinee). For example, given `Animal x` where `Dog extends Animal`, in Java 17 we have
```
switch (x) {
case Dog d -> ... // d is non-null
case Animal a -> ... // a could be null or non-null because Animal subsumes the type of the scrutinee
case null -> ... // unreachable and subsumed by the Animal a case
}
```
but in Java 21 the behavior is
```
switch (x) {
case Dog d -> ... // d is non-null
case Animal a -> ... // a is non-null
case null -> ... // reachable if x is null
}
```
- Exhaustive matches now throw `MatchException` rather than `IncompatibleClassChangeError` if they end up not being exhaustive at runtime. This can only occur if the underlying class was re-compiled but the match was not, so it is not a real concern for us.

If we enable the Java 17 preview, the additional pain points when we later migrate to Java 21 will then be
- Manually making the syntax changes. These are mechanical changes, and IntelliJ correctly identifies all the issues, however, neither IntelliJ nor any other tool seem to offer an automatic migration, so we need to do it by hand.
- The semantic change regarding `null` could potentially cause bugs, but it would only be triggered in very rare edge cases which seem unlikely to occur in practice, namely when
   - we are matching on `null`, and
   - we use a total type pattern rather than just the equivalent `default` case label

In my opinion, these downsides are fairly minor and the feature improves development experience enough that it's worth putting up with a bit more pain when later updating to Java 21.

**Comment by dwightguth** [comment]
I'm not sure I agree this is worth it. A preview is not going to be maintained if it has bugs the way an actual java release would be. We could put ourselves into a situation that proves very tedious to get out of by making the production release of k rely on pre release features. These previews are really not meant to be used in production by deployed applications like ours.

**Comment by Scott-Guest** [comment]
That's a fair point I hadn't considered. Closing this as not planned.
