### ISSUE TITLE
Homogenise PL Tutorial into regression tests

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3892]
We identified in our [year-end review](https://github.com/runtimeverification/k/issues/3871) that the PL Tutorial being a separate test suite _directly within K_ is not desirable. It would be better to extract the most important definitions from the tutorial as regression tests in their own right, then to split the tutorial itself out into a separate repository.[^1]

The benefits of doing this are:
* Faster CI for the core K repo; we will no longer have to run a big pile of very similar definitions on every run.
* Simpler CI setup; we won't have two different systems of makefiles and run scripts that need to be maintained independently.
* Easier audit of features & simpler updates to the tutorial code; we'll be better able to update the PL languages and definitions if we can do so as a dependent of K rather than a core part of the repository.

Related:
* https://github.com/runtimeverification/k/issues/1936

[^1]: We might want to maintain this at RV, or we might want to try and put it under the supervision of FSL.

**Comment by gtrepta** [comment]
I opened a PR for #1936: #3897

**Comment by Baltoli** [comment]
@gtrepta has opened a new repo with a copy of the PL tutorial (link?)

Also has moved a selection of the finished languages into the regression test suite.

Next step is to audit for dead / poorly supported language features.

**Comment by gtrepta** [comment]
PL Tutorial repo: https://github.com/runtimeverification/pl-tutorial
