### ISSUE TITLE
Review `--output latex` options

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3909]
Take a look at how well supported the LaTeX output of the compiler is - does it work in practice?

We don't have the _prelude_ that provides meaning to `--output latex`; you can easily emit the latex that corresponds to terms but users need to actually supply the formatting.

**Comment by Baltoli** [comment]
Issue about latex prelude exists already? Low priority - is anyone using it?

**Comment by ehildenb** [comment]
https://github.com/runtimeverification/k/issues/1560

**Comment by Baltoli** [comment]
We might just want to drop the frontend implementation of this for now; if there's an appetite to do similar in the future then we can reimplement in Pyk.
