### ISSUE TITLE
Inconsistent symbol names between KAST and KORE for syntactic list

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3940]
K version: `v6.1.105-0-gd4cb1a0100`

Consider the following definition.

```k
module INTS
  imports INT-SYNTAX
  syntax Ints ::= List{Int, ","} [klabel(ints), symbol]
endmodule
```

`kompile` generates the following productions in `compiled.txt`:

```k
syntax Ints ::= Int "," Ints [klabel(ints),          symbol, userList(*)]
syntax Ints ::= ".Ints"      [klabel(.List{"ints"}), symbol, userList(*)]
```

However, in `definition.kore`, the corresponding symbols are as follows:

```
symbol Lblints{}(SortInt{}, SortInts{}) : SortInts{} [...]
symbol Lbl'Stop'List'LBraQuot'ints'QuotRBraUnds'Ints{}() : SortInts{} [...]
```

Here, the expected symbol name for the empty list would be
```
Lbl'Stop'List'LBraQuot'ints'QuotRBra'
```

as the `symbol` attribute is present on the corresponding production.

This discrepancy is also present in `compiled.json`, where the `klabel` field (not the attribute) of the object is

```json
{"node":"KLabel","name":".List{\"ints\"}_Ints","params":[]}
```

As a side remark, right now it seems impossible to generate a human-readable KORE symbol name for the empty list. We should consider generating a simpler label (e.g. `.ints` for this example), and also provide an attribute to specify the `klabel` explicitly.

**Comment by Baltoli** [comment]
Not clear whether the problem is when we desugar the list, or later in a subsequent step. We should try to figure out why this happens to keep the attribute behaviour consistent.
