### ISSUE TITLE
Audit the backends for relevant KORE attributes

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3946]
Related: https://github.com/runtimeverification/k/issues/3500
Related: https://github.com/runtimeverification/k/issues/3540

Currently, when generating `compiled.json` and `definition.kore`, the Frontend emits a lot of attributes, many of which are probably not needed by the backends. Ideally, only those attributes should be generated that are used by at least one backend (except perhaps for `source` and `location` which are always useful for debugging and traceability).

Compile the list of attributes used by each backend, grouped by the syntactic element they are attached to.

- [x] LLVM backend - @Baltoli 
  - String lookups when attributes are required; grep for `.attributes()`, `getStringAttribute()`
- [x] Haskell backend - @goodlyrottenapple 
  - Supports cases not supported by the booster; will need some more auditing.
- [x] Booster backend - @goodlyrottenapple 
  - Relatively easy to check for attribute usage.
- [ ] Maude backend - @dwightguth / @sskeirik 

---

For guiding search in the backend code, a simple script that exports the list of KAST / KORE attributes for a kompiled definition:

[export_atts.py](https://github.com/runtimeverification/k/files/14126043/export_atts.py.txt)

Copy into `pyk` root, then

```
$ kompile imp.k --emit-json
$ poetry run python3 export_atts imp-kompiled
KORE attributes exported: imp-kompiled/atts.kore.csv
KAST attributes exported: imp-kompiled/atts.kast.csv
```

Generated artifacts: [atts.kore.csv](https://github.com/runtimeverification/k/files/14126077/atts.kore.csv), [atts.kast.csv](https://github.com/runtimeverification/k/files/14126076/atts.kast.csv)

---

Results: https://docs.google.com/spreadsheets/d/1_lX1NqjphKBdTtWwiOQC8Xt7yY565xlgS9iGy1JkR6A

**Comment by Baltoli** [comment]
@Scott-Guest collected a whitelist of attributes in the static code (complete) to correspond to these dynamic lists (maybe incomplete, but a useful starting point).

**Comment by goodlyrottenapple** [comment]
Here is the list of attributes being used in the haskell backends. The ones in **bold** appear to be unused/deprecated:

| Attribute                                         | Haskell Backend | Booster Backend | Attribute Type |
|---------------------------------------------------|:---------------:|:---------------:|:--------------:|
| priority                                          |        ✅        |        ✅        |      Axiom     |
| assoc                                             |        ✅        |                 |      Axiom     |
| comm                                              |        ✅        |                 |      Axiom     |
| unit                                              |        ✅        |                 |      Axiom     |
| idem                                              |        ✅        |                 |      Axiom     |
| non-executable                                    |        ✅        |                 |      Axiom     |
| trusted                                           |        ✅        |                 |      Axiom     |
| simplification                                    |        ✅        |        ✅        |      Axiom     |
| overload                                          |        ✅        |                 |      Axiom     |
| smt-lemma                                         |        ✅        |        ✅        |      Axiom     |
| label                                             |        ✅        |        ✅        |      Axiom     |
| org'Stop'kframework'Stop'attributes'Stop'Location |        ✅        |        ✅        |      Axiom     |
| constructor                                       |        ✅        |                 |      Axiom     |
| total                                             |        ✅        |                 |      Axiom     |
| subsort                                           |        ✅        |                 |      Axiom     |
| UNIQUE'Unds'ID                                    |        ✅        |        ✅        |      Axiom     |
| non-executable                                    |        ✅        |                 |      Axiom     |
| owise                                             |        ✅        |                 |      Axiom     |
| concrete                                          |        ✅        |        ✅        |      Axiom     |
| symbolic                                          |        ✅        |        ✅        |      Axiom     |
| preserves-definedness                             |                 |        ✅        |      Axiom     |
| total                                             |        ✅        |        ✅        |     Symbol     |
| **functional**                                    |      **✅**      |      **✅**      |   **Symbol**   |
| constructor                                       |        ✅        |        ✅        |     Symbol     |
| sortInjection                                     |        ✅        |        ✅        |     Symbol     |
| injective                                         |        ✅        |                 |     Symbol     |
| anywhere                                          |        ✅        |                 |     Symbol     |
| hook                                              |        ✅        |        ✅        |     Symbol     |
| smtlib                                            |        ✅        |        ✅        |     Symbol     |
| smt-hook                                          |        ✅        |        ✅        |     Symbol     |
| memo                                              |        ✅        |                 |     Symbol     |
| klabel                                            |        ✅        |                 |     Symbol     |
| **symbol'Kywd'**                                  |      **✅**      |                 |   **Symbol**   |
| no-evaluators                                     |        ✅        |        ✅        |     Symbol     |
| org'Stop'kframework'Stop'attributes'Stop'Location |        ✅        |                 |     Symbol     |
| macro                                             |        ✅        |        ✅        |     Symbol     |
| alias'Kywd'                                       |        ✅        |        ✅        |     Symbol     |
| idem                                              |                 |        ✅        |     Symbol     |
| smtlib                                            |        ✅        |                 |      Sort      |
| unit                                              |        ✅        |        ✅        |      Sort      |
| element                                           |        ✅        |        ✅        |      Sort      |
| concat                                            |        ✅        |        ✅        |      Sort      |
| hasDomainValues                                   |        ✅        |                 |      Sort      |
| hook                                              |        ✅        |        ✅        |      Sort      |

**Comment by Baltoli** [comment]
# LLVM Backend

| Attribute                                         | LLVM Backend | Comment                                                   |
|---------------------------------------------------|:------------:|-----------------------------------------------------------|
| priority                                          |       ✅      | Used only in the decision tree compiler to sort axioms    |
| owise                                             |       ✅      | `priority(200)`                                           |
| cool                                              |       ✅      | `priority(100)`                                           |
| cool-like                                         |       ✅      | `priority(150)`                                           |
| assoc                                             |       ✅      | Affects pretty-printing; axioms dropped for codegen       |
| comm                                              |       ✅      | Affects pretty-printing; axioms dropped for codegen       |
| idem                                              |       ✅      | Axioms dropped for codegen                                |
| non-executable                                    |       ✅      | Axioms dropped for codegen                                |
| trusted                                           |              |                                                           |
| simplification                                    |       ✅      | Axioms dropped for codegen                                |
| overload                                          |       ✅      | Affects syntactic pattern matching and macro expansion    |
| smt-lemma                                         |              |                                                           |
| label                                             |       ✅      | Identification of rules in the debugger (GDB / LLDB)      |
| org'Stop'kframework'Stop'attributes'Stop'Location |       ✅      |                                                           |
| constructor                                       |       ✅      | Axioms dropped for codegen                                |
| total                                             |       ✅      | Axioms dropped for codegen                                |
| subsort                                           |       ✅      | Affects syntactic pattern matching and macro expansion    |
| UNIQUE'Unds'ID                                    |              |                                                           |
| concrete                                          |              |                                                           |
| symbolic                                          |              |                                                           |
| preserves-definedness                             |              |                                                           |
| total                                             |       ✅      | Axioms dropped for codegen                                |
| functional                                        |       ✅      | Axioms dropped for codegen                                |
| constructor                                       |       ✅      | Axioms dropped for codegen                                |
| ceil                                              |       ✅      | Axioms dropped for codegen                                |
| sortInjection                                     |       ✅      | Code generation + general handling of triangle injections |
| injective                                         |              |                                                           |
| anywhere                                          |       ✅      | Codegen                                                   |
| hook                                              |       ✅      | Many places                                               |
| smtlib                                            |              |                                                           |
| smt-hook                                          |              |                                                           |
| memo                                              |              |                                                           |
| klabel                                            |              | What's the relationship to `label`?                       |
| symbol'Kywd'                                      |              |                                                           |
| no-evaluators                                     |              |                                                           |
| org'Stop'kframework'Stop'attributes'Stop'Location |       ✅      |                                                           |
| macro                                             |       ✅      | Macro expander, along with `alias` and `-rec` analogues   |
| alias'Kywd'                                       |              |                                                           |
| smtlib                                            |              |                                                           |
| unit                                              |       ✅      | Correct iteration over collection terms                   |
| element                                           |       ✅      | Correct iteration over collection terms                   |
| concat                                            |       ✅      | Correct iteration over collection terms                   |
| hasDomainValues                                   |       ✅      | Sort category identification in pattern-matching compiler |
| token                                             |       ✅      | Sort category identification in pattern-matching compiler |
| freshGenerator                                    |       ✅      | Hooking correct fresh function                            |
| binder                                            |       ✅      | Substitution module                                       |
| nat                                               |       ✅      | `MInt{...}` bitwidth                                      |
| colors                                            |       ✅      | Pretty-printing                                           |
| bracket                                           |       ✅      | Pretty-printing                                           |

**Comment by Baltoli** [comment]
@tothtamas28 Is going to collate these tables + Scott's static analysis of the attributes in the frontend to see if there is any low hanging fruit.

https://github.com/runtimeverification/k/blob/master/docs/user_manual.md#attribute-index - static analysis

**Comment by tothtamas28** [comment]
> @tothtamas28 Is going to collate these tables + Scott's static analysis of the attributes in the frontend to see if there is any low hanging fruit.

Spreadsheet: https://docs.google.com/spreadsheets/d/1_lX1NqjphKBdTtWwiOQC8Xt7yY565xlgS9iGy1JkR6A

**Comment by Scott-Guest** [comment]
@Baltoli @goodlyrottenapple From the attributes you listed, I noticed that `sortInjection`, `overload`, and `subsort` are not in the attribute whitelist. ~~Do the backends add these somehow, or are they just dead code? If not, something must be awry with the attribute whitelist infrastructure.~~

EDIT: Ah never mind, they're added as raw text in `ModuleToKORE` and `prelude.kore`, so are just never checked against the whitelist.

**Comment by Baltoli** [comment]
Attribute usages in the Maude backend: https://github.com/search?q=repo%3Aruntimeverification%2Fmaude-backend%20%2FAtt%5C.%2F&type=code

I see the following attributes being used from the frontend:
```
Att.UNIT()
Att.ASSOC()
Att.HOOK()
Att.ELEMENT()
Att.CONCRETE()
Att.HASKELL()
Att.ANONYMOUS()
```

And in KORE:
```
subsort
concrete
symbolic
```

**Comment by Baltoli** [comment]
I think we can consider this complete for the time being; if we want to revisit it in the future then we can reopen.
