### ISSUE TITLE
Drop support for the `macro` attribute on rules

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3947]
Having the `macro` attribute on rules has been deprecated for over two years (https://github.com/runtimeverification/k/pull/2272), consider dropping support.

This would save an implicit compiler pass in `ModuleToKORE` that checks each label production for the `macro` attribute on its function rules: https://github.com/runtimeverification/k/blob/50b6d0a969eee48834a3581ef70c812d55d8ff45/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L1694

**Comment by Baltoli** [comment]
This is just a question of dropping the loop over rules - because the frontend has accepted the rule, the production must necessarily have the `macro` attribute. We should **prohibit** macro[-rec] / alias[-rec] on rules rather than just warning for them.
