### ISSUE TITLE
[K-Improvement] Implicit identifiers to remove user burden

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/k#3958]
### Problem
In the kmir project there is a need to list out every identifier explicitly so that the symbolic parser successfully parsers. This will present a significant overhead to any user who is trying to use kmir for any sizeable program. This issue is a continuation of an old one but is explained again in [kmir #320](https://github.com/runtimeverification/mir-semantics/issues/320).

This problem may not be a problem with K necessarily, but could be a problem with the way KMIR defines it's syntax in K. But if it is the later, we will still need input from K team to correct the mistake.

### Reproducer
To reproduce the error clone kmir or update kmir to latest and navigate inside `mir-semantics`:

```
git switch more-proofs-2
cd kmir
make build
source set_env.sh
poetry run kmir prove src/tests/integration/test-data/prove.rs/assert.k
```
Notice the proof is parsing and passing then from `kmir/src/tests/integration/test-data/prove.rs/verify.k` remove lines:

```
syntax IdentifierToken ::= "core" [token]
syntax IdentifierToken ::= "panicking" [token]
syntax IdentifierToken ::= "panic" [token]
syntax IdentifierToken ::= "\"assertion failed: num == 42\"" [token]
```
and run
```
poetry run kmir prove src/tests/integration/test-data/prove.rs/assert.k
```
and notice the claim cannot parse.

**Comment by Baltoli** [comment]
@dkcumming I suggest talking to the Kontrol team (@palinatolmach @anvacaru) about how they go about generating specifications from a Foundry property test (which will be analogous to what you want to do eventually, but for Rust). If you're writing K claims by hand over a program that does indeed mention all these identifiers, its verification module will need to declare the appropriate tokens. There's not really a way to change that without a big breaking change to the way the K rule parser works.

Aside - I'm suspicious of this line:
```k
syntax IdentifierToken ::= "\"assertion failed: num == 42\"" [token]
```

This looks like it should be a string; why is the assertion message an identifier?

**Comment by Baltoli** [comment]
Closing for now as there's not much to be done K-side; happy to revisit in the future @dkcumming

**Comment by dkcumming** [comment]
@Baltoli Okay that's a good direction to start with. Yes I think there is a lot of muddling of `String` and `Identifier` currently that needs to be cleaned up. I'll continue the conversation with `Kontrol` team for their advice.
