### ISSUE TITLE
Unique rule IDs do not consider attributes with semantic impact

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/k#3984]
I noticed that different rewrite rules and equations sometimes get the same `UNIQUE_ID` if they only differ in their attributes, such as `concrete()` or `symbolic()`.

To demonstrate this:

File `test.k`
```
module TEST
  imports INT

  syntax Foo ::= foo(Int, Int) | bar(Int)

  rule [rule1]:
      foo(X, Y) => bar(X +Int Y) [concrete(X)]
  rule [rule2]:
      foo(X, Y) => bar(X +Int Y) [concrete(Y)]

endmodule
```

```shell
jost@freshcode-1:same-unique-id$ kompile test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
jost@freshcode-1:same-unique-id$ grep "rule[12]" test-kompiled/definition.kore  | grep -e "UNIQUE'Unds'ID{}([^)]*)"
  [UNIQUE'Unds'ID{}("47a45c5c997535c369cb063e28057d89a0eeacf3c14936fedd9927b91ba75caf"), concrete{}(VarX:SortInt{}), label{}("TEST.rule1"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(7,7,7,33)"), org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/home/jost/work/RV/code/hs-backend-booster/scratch/same-unique-id/test.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol]")]
  [UNIQUE'Unds'ID{}("47a45c5c997535c369cb063e28057d89a0eeacf3c14936fedd9927b91ba75caf"), concrete{}(VarY:SortInt{}), label{}("TEST.rule2"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(9,7,9,33)"), org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/home/jost/work/RV/code/hs-backend-booster/scratch/same-unique-id/test.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol]")]
```
The two rules labelled `rule1` and `rule2` differ in their attributes (and rule label) but have the same `UNIQUE_ID` value.

Obviously not all attributes should be considered when computing the unique ID, but those which have an effect on how the rule is applied should IMHO have an influence on the ID.

**Comment by tothtamas28** [comment]
ID duplication also happens a lot in `kontrol`. There, the same rule might be present in multiple modules of the input K file:

```
module S2KlibZModforgeZSubstdZModsrcZModVm-CONTRACT
    ...
    rule  ( selector ( "stopBroadcast()" ) => 1995103542 )
    ...
endmodule

...

module S2KlibZModforgeZSubstdZModsrcZModVmSafe-CONTRACT
    ...
    rule  ( selector ( "stopBroadcast()" ) => 1995103542 )
    ...
endmodule
```

In the output, the corresponding rules only differ in the `Location` attribute.

Input: [contracts.k](https://github.com/runtimeverification/k/files/14260183/contracts.k.txt)
Output: [compiled.txt](https://github.com/runtimeverification/k/files/14260184/compiled.txt)
Duplicate IDs: [duplicate-ids.txt](https://github.com/runtimeverification/k/files/14260182/duplicate-ids.txt)



Related: https://github.com/runtimeverification/k/issues/3906

**Comment by Baltoli** [comment]
@jberthold what is the booster actually doing with these IDs?

**Comment by jberthold** [comment]
> @jberthold what is the booster actually doing with these IDs?

Booster does not use them at all in its own functionality, but these `UNIQUE_ID`s will be used for traces to identify the rules used (a trace is a sequence of IDs of the rules used during rewriting and simplification).

**Comment by Baltoli** [comment]
The numbersentences pass should just take all the attributes of the rule into account, although maybe we want to preserve some of the non-unique quality as it's helped us find duplicated rules in compiled definitions.

**Comment by gtrepta** [comment]
A list of user supplied attributes that can be on rules/claims:

```
ALL_PATH
ANYWHERE
CIRCULARITY
COMM
CONCRETE
COOL
DEPENDS
HEAT
INITIALIZER
NON_EXECUTABLE
ONE_PATH
OWISE
PRESERVES_DEFINEDNESS
PRIORITY
RESULT
SIMPLIFICATION
SMT_LEMMA
STREAM
SYMBOLIC
TAG
TRUSTED
UNBOUND_VARIABLES
```

`concrete`, `symbolic`, `owise`, `priority`, `simplification`, `anywhere`, and `non-executable` are the attributes that immediately jump out at me as impacting semantics. Are there any I missed? Do the internal attributes need to be checked as well?

**Comment by Baltoli** [comment]
I think I agree with your list @gtrepta; I don't think I see any others that are going to produce the same issue here where you can have two rules with identical bodies but different attributes such that they have different behaviour. Go ahead and merge those attributes into the sentence hash, and if we see something like this crop up again we can revisit it.
