### ISSUE TITLE
Make `Att.Key` generic

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#3993]
Currently, for each entry `Att` stores its value type explicitly (the name of the class) along with the key, perhaps in an attempt to work around type erasure. Compared to a solution without stored class names, this results in additional noise in the interface, complexity of implementation, and also some memory overhead.

Consider the following design instead (sketch).

```scala
trait AttValue

class Att(val att: Map[Att.Key, Any]) {
    // no need to store valueType, just pass in to fix T
    class Key[T <: AttValue](key: String, valueType: Type[T], ...) { ... }

    def add[T <: AttValue](key: Att.Key[T], value: T): Att = ...
    def get[T <: AttValue](key: Att.Key[T]): T = ...
    ...
}
```

The somewhat nasty part of the implementation is an unchecked cast in `get`, but that warning can be safely suppressed (as long as the object is only constructed through its safe interface, e.g. not serialized and tampered with).

Also note the inconsistency between `AttValue` and `Att.Key`. Maybe `AttValue` can be renamed to `Value` and moved into `Att`.

**Comment by Baltoli** [comment]
Superseded by #4003
