### ISSUE TITLE
Debugging with krun

### ISSUE THREAD

**Issue by saikatG** [runtimeverification/k#40]
Is there a way to step through each rule application procedure or something of similar granularity? I tried using `--debug` and `-v` flags, but i don't get enough info to understand what is wrong with my semantics

**Comment by ehildenb** [comment]
You can use `--state-log` options when running with the Java backend to get a dump of all visited states and then use KLab to traversed the dumped output.

For an example, look at the script `kevm` in https://github.com/kframework/evm-semantics. If you have KLab installed, you can do `./kevm klab-run SOME_PROGRAM` to get the dump of visited states, and then do `./kevm klab-view SOME_PROGRAM` to interactively explore the dump.

I'm closing this for now, feel free to re-open if you have more questions about how to use this.
