### ISSUE TITLE
Deprecate one of `syntax priority` and `syntax priorities`

### ISSUE THREAD

**Issue by Scott-Guest** [runtimeverification/k#4009]
Currently, the outer parser accepts both 
```
syntax priority foo > bar
```
and
```
syntax priorities foo > bar
```
In the interest of cleaning up unneeded complexity in the language, we should pick one of these and deprecate the other.

Personally, I have a weak preference for the singular `priority`.

**Comment by Baltoli** [comment]
Do the same for `import[s]` and `require[s]` as appropriate.

Keep:
* `priority`
* `imports`
* `requires`

**Comment by Baltoli** [comment]
@tothtamas28 will update Pyk when the K change has been merged.

**Comment by Baltoli** [comment]
This will be a breaking downstream change in semantics; we will need to do some cleanup.

**Comment by Scott-Guest** [comment]
Searches for usage:
- `syntax priorities` [/(?-i)^[\t ]\*syntax[\t ]+priorities[\t ].\*$/](https://github.com/search?q=org%3Aruntimeverification+%2F%28%3F-i%29%5E%5B%5Ct+%5D*syntax%5B%5Ct+%5D%2Bpriorities%5B%5Ct+%5D.*%24%2F&type=code)
- `require` [/(?-i)^[\t ]\*require[\t ]+"[^"]\*"[\t ]\*$/](https://github.com/search?q=org%3Aruntimeverification+%2F%28%3F-i%29%5E%5B%5Ct+%5D*require%5B%5Ct+%5D%2B%22%5B%5E%22%5D*%22%5B%5Ct+%5D*%24%2F&type=code)
- `import` [/(?-i)^[\t ]\*import[\t ]+[A-Z][A-Z-]\*[\t ]\*$/](https://github.com/search?q=org%3Aruntimeverification+%2F%28%3F-i%29%5E%5B%5Ct+%5D*import%5B%5Ct+%5D%2B%5BA-Z%5D%5BA-Z-%5D*%5B%5Ct+%5D*%24%2F&type=code)
