### ISSUE TITLE
Feature request: stop KProve execution when a branch terminates without matching target

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#401]
Currently KProve executes until all branches terminate. I think it would be great to add the option of stopping the execution prematurely as soon as one branch terminates without matching the target.

**Comment by ehildenb** [comment]
Currently the Java backend supports `--boundary-cells ...` to make this happen, and teh Haskell backend automatically will halt execution if the term matches but the side-condition is not met. Feel free to re-open if this is still an issue.
