### ISSUE TITLE
Consolidate source code

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4022]
Merge

```
kernel
├── pom.xml
└── src
    ├── main
    │   ├── java
    │   ├── javacc
    │   ├── jjtree
    │   └── resources
    └── test
        ├── java
        └── resources
```

and

```
kore
├── build.sbt
├── pom.xml
├── project
│   └── build.sbt
└── src
    ├── main
    │   ├── java
    │   └── scala
    └── test
        ├── java
        └── scala
```

into

```
k-frontend
├── build.sbt
├── pom.xml
└── src
    ├── main
    │   ├── java
    │   ├── javacc
    │   ├── jjtree
    │   ├── resources
    │   └── scala
    └── test
        ├── java
        ├── resources
        └── scala
```

**Comment by Baltoli** [comment]
After we discussed this, I remembered that one reason for the split is that the `kore` part is somehow published and consumed by the LLVM backend: https://github.com/runtimeverification/llvm-backend/blob/d3c1ee78a4235661c5e00f29fe89e1ec5f632afb/matching/pom.xml#L35-L39

**Comment by Baltoli** [comment]
* When building the K frontend, the LLVM backend's POM will point upwards in the tree to get the KORE dependency.
* When building the LLVM backend independently:
  * Will pull first from your local maven repository
  * Otherwise we push in the K release job

**Comment by Baltoli** [comment]
We can also remove the SBT files; we no longer use those.

**Comment by Baltoli** [comment]
I think this is blocked on #4041 - @Scott-Guest when we get the Java 17 support merged across the Scala-using modules, is there anything else blocking us from merging these packages?
