### ISSUE TITLE
Emit warning on non-unique `overload` value

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4034]
Consider

```k
module FOO
    syntax Foo1 ::= Foo2

    syntax Foo1 ::= "foo" Foo1 [overload(foo)]
    syntax Foo2 ::= "foo" Foo2 [overload(foo)]

    syntax Foo1 ::= "foo" Foo1 Foo1 [overload(foo)]
    syntax Foo2 ::= "foo" Foo2 Foo2 [overload(foo)]
endmodule
```

Here, the overload induces disjoint partial orders as the arity of the symbols in the respective groups differs. In such a case, a warning (or even error) should be emitted that prompts the user to rename one of the overloads.

**Comment by Baltoli** [comment]
Yeah, this is something that I missed out in the initial PR. Previously this wasn't possible with the `klabel(_)` partial order because of the overlapping use cases, but we can indeed warn about this unambiguously with the new syntax.
