### ISSUE TITLE
Deprecate `klabel(_)` and `symbol`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4035]
Related:
* #3985
* #4034

`klabel(_)` and `symbol` should be deprecated, and warnings should be emitted to users that prompt them to switch to `symbol(_)`, `overload(_)`, or no attribute as appropriate.

Setting this up correctly is important, as it will ensure that migration to the new attributes goes without friction and with as little support from the K Team as possible.

The following is an analysis of the potential warnings that can be emitted.

### E1: `klabel(_)` + `symbol(_)`

```
[Error] The 1-argument form of the `symbol(_)` attribute cannot be combined with `klabel(_)`.
```

### E2: `klabel(_)` + `overload(_)`

```
[Error] The attributes `klabel(_)` and `overload(_)` may not occur together.
```

### E3: `symbol` not unique

```
[Error] Symbol X is not unique. Previously defined as: ...
```

This considers occurrences of both `klabel(_), symbol` and `symbol(_)`, as it should.

### W1: non-overloading `overload`

```
[Warning] Production has an `overload(_)` attribute but is not an overload of any other production.
```

### PW1: `klabel(_)` + `symbol`

```k
module PW1
    Foo ::= "foo" [klabel(foo), symbol]
endmodule
```

This is the simplest case, we can just ask the user to switch to `symbol(_)`.

```
[Warning] The no-argument form of `symbol` is deprecated. Replace `klabel(foo), symbol` by `symbol(foo)`.
```

### PW2: Non-overloading `klabel(_)` without `symbol`

```k
module PW2
    Foo ::= "foo" [klabel(foo)]
endmodule
```

```
[Warning] Attribute `klabel(_)` is deprecated. Either remove `klabel(foo)`, or replace it by `symbol(foo)`.
```

This then potentially triggers `E3`, which prompts the user the resolve symbol collisions.

### PW3: Overloading `klabel(_)`

```k
module PW3:
    Foo ::= Bar
    Foo ::= "foo" Foo [klabel(foo)]
    Bar ::= "foo" Bar [klabel(foo)]
endmodule
```

```
[Warning] Attribute `klabel(foo)` marks an overload. Add `overload(foo)` to the following productions: ...
```

This is a simple and safe modification as it preserves the overload lattice. Moreover, it simplifies the situation to something similar to `PW2` by triggering `E2`. The error message there should be modified to prompt the user to perform a specific action (same as in `PW2`):

```
[Error] The attributes `klabel(foo)` and `overload(foo)` may not occur together. Either remove `klabel(foo)`, or replace it by `symbol(foo)`
```

which then in turn might trigger `E3`, etc.

**Comment by Baltoli** [comment]
For PW1 I think the warning should fire if the production has a zero-argument symbol, regardless of whether `klabel(_)` was present; we caught a lot of them but there may well be code that was relying on the old behaviour where the outer parser would add `klabel(_)` automatically.

**Comment by tothtamas28** [comment]
Good point, but that should be a separate warning I think, since the required user action is different. So perhaps something like

```
[Warning] Attribute `klabel(_)` is missing on production with `symbol`. Either remove `symbol`, or add and argument to it.
```

Also, this warning can be added separately as this is already considered an issue (i.e. regardless of whether `symbol` and `klabel(_)` are deprecated or not). If you like this approach I'll open an issue.

**Comment by Baltoli** [comment]
https://github.com/runtimeverification/k/issues/4043

**Comment by Baltoli** [comment]
Blocked on https://github.com/runtimeverification/haskell-backend/issues/3742
