### ISSUE TITLE
Move `checkJava` logic into Java code

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4061]
When running `kompile` (and potentially other tools of the K toolkit), a script [`checkJava`](https://github.com/runtimeverification/k/blob/0179b261340c73decda52ce8971942ea6a69b4da/k-distribution/src/main/scripts/lib/checkJava#L4) is run to check version compatibility of the installed JRE with K.

If possible (i.e. if each tool that runs `checkJava` eventually ends up running Java code), consider moving this logic into the Java code base, as introspecting the running JVM for its version is simpler and less error-prone than parsing version strings from diverse sources.

Related: #4059

**Comment by Baltoli** [comment]
The main reason that this logic lives in the Bash script is to avoid spinning up a JVM if Nailgun is running; we should perhaps just fix the string processing as a first pass at the issue.

This is pretty old code, and we should also take the opportunity to refactor the script if there are opportunities to do so.

**Comment by Baltoli** [comment]
We should make an effort to give a good message for Java >= 11; older versions we can just bail out. The reason for this is that from 8 -> 11 the version numbering scheme changed, and so our logic can be more consistent by only supporting one format.
