### ISSUE TITLE
[K-installation-Bug] <TITLE>

### ISSUE THREAD

**Issue by Fanhy123** [runtimeverification/k#4072]
### What component is the issue in?

None

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K-6.2.2

### Operating System

Linux

### K Definitions (If Possible)

How to install K on centOS

### Steps to Reproduce

Installing secp256k1 on a centOS system always fails

### Expected Results

Installing secp256k1 on a centOS system always fails

**Comment by Baltoli** [comment]
Hi @Fanhy123; thanks so much for your interest in using K. We don't support CentOS when building K from source, but do offer a platform-independent installer (`kup`) for end users. You can find the instructions for using `kup` [here](https://github.com/runtimeverification/k?tab=readme-ov-file#quick-start); it should work on any platform that supports Nix. Please come back to us if you have any difficulty with `kup`.

If you'd like to work on the K internals, we support Ubuntu 22.04 and macOS for developers.

**Comment by Fanhy123** [comment]
Thank you for the information! I appreciate the guidance on using K software. I will make sure to refer to the instructions for using kup. If I encounter any difficulties, I hope you can help me again











------------------ 原始邮件 ------------------


    


        发件人: Bruce Collie  ***@***.***>    






    


        发送时间: 2024-03-04 18:41:43    






    


        收件人: runtimeverification/k  ***@***.***>     






    


        抄送: Fanhy123  ***@***.***>,Mention  ***@***.***>     






    


        主题: Re: [runtimeverification/k] [K-installation-Bug] <TITLE> (Issue#4072)    

 

Hi @Fanhy123 thanks so much for your interest in using K. We don't support CentOS when building K from source, but do offer a platform-independent installer (kup) for end users. You can find the instructions for using kup here it should work on any platform that supports Nix. Please come back to us if you have any difficulty with kup.




 

If you'd like to work on the K internals, we support Ubuntu 22.04 and macOS for developers.
