### ISSUE TITLE
Remove references to kdoc and --pdf

### ISSUE THREAD

**Issue by dplyukhin** [runtimeverification/k#41]
This is [already an issue on the legacy repo](https://github.com/kframework/k-legacy/issues/2310), but are there any plans to get KDoc working in K5, or at least to print out rules in that nice lego-block format, used e.g. on page 13 in the [SIMPLE paper](http://fsl.cs.illinois.edu/images/4/47/CS422-K-Overview.pdf)?

**Comment by tim0s** [comment]
Is there a way to get the documentation mentioned in the k tutorial? The --pdf option seems not working, kdoc does not produce any output. What is the right way to produce the pdf files shown in the tutorial with this K version:

RV-K version 1.0-SNAPSHOT
Git revision: 605c1e5
Git branch: master

**Comment by DustinWehr** [comment]
If it really doesn't work right now, the tutorial should say that. That'd mean I wasted time unnecessarily trying to get it to work.

**Comment by DustinWehr** [comment]
Even better: temporarily modify kdoc to give a warning about whatever the problem is. I couldn't get it to say anything with any of the debug and warning options.

**Comment by ehildenb** [comment]
We will comb through the tutorial and remove references to KDoc and `--pdf` option.
