### ISSUE TITLE
Make overloading more strict

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4114]
Currently the sort of the overloading production is not required to be a strict subsort of the sort of the overloaded production:

https://github.com/runtimeverification/k/blob/ef56dd96a6715cf8c3a5f172302e7550fff784fc/kore/src/main/scala/org/kframework/definition/outer.scala#L75

However, `ModuleToKORE` assumes it is, as it generates an injection between the sorts for overload axioms:

https://github.com/runtimeverification/k/blob/ef56dd96a6715cf8c3a5f172302e7550fff784fc/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L901

## How to fix it

~~Make the overload ordering more strict by changing the following disjunction into a conjunction:~~

https://github.com/runtimeverification/k/blob/ef56dd96a6715cf8c3a5f172302e7550fff784fc/kore/src/main/scala/org/kframework/definition/outer.scala#L81

~~Implementing #4034 will ensure that there's a warning / error if a given overload group splits into multiple disjoint parts because of the stronger ordering.~~

We actually want to just prevent an injection `inj{SortX{}, SortX{}}` from being generated in ModuleToKore; it's valid for two symbols to have the same sort and to be overloads of one another.

**Comment by Baltoli** [comment]
@tothtamas28 I don't think we actually want to do this, as it breaks a common pattern present in the C Semantics where overloading is used to select a _more specific function implementation_ rather than to make the sort of a term more specific. For example:
https://github.com/runtimeverification/c-semantics/blob/cc48e6e3fb726a81237e782e3701d2dea2f218a4/core/semantics/language/concepts/types.k#L290-L292

**Comment by tothtamas28** [comment]
> I don't think we actually want to do this, as it breaks a common pattern

Makes sense. Shouldn't we still fix injection generation in `ModuleToKORE` though?

**Comment by Baltoli** [comment]
> Shouldn't we still fix injection generation in ModuleToKORE though?

Yep, I think so
