### ISSUE TITLE
Non-exhaustive match warning on `total` `function` with `no-evaluators`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4148]
```
module TEST
    imports INT-SYNTAX
    syntax Int ::= foo ( Int ) [function, total, no-evaluators]
endmodule
```

```
$ kompile test.k --syntax-module TEST
[Warning] Compiler: Non exhaustive match detected: `foo(_)_TEST_Int_Int`(_)
        Source(/home/ttoth/git/pyk/test.k)
        Location(3,20,3,64)
        3 |         syntax Int ::= foo ( Int ) [function, total, no-evaluators]
          .
```

## Possible solutions

Simplest to hardest:

1. Do not allow `total` and `no-evaluators` to appear together on a given production.
2. Do not emit the warning if `no-evaluators` is present.
3. Add a fine-grained mechanism to K that enables the user to manually suppress certain warnings.
   1. Assign a unique identifier to each type of warning.
   2. Introduce a user attribute that can be attached to any element. E.g. `suppress(W101, W204)`.

**Comment by gtrepta** [comment]
Probably we should just not emit the warning.
