### ISSUE TITLE
Question - Is there a more flexible way to control the execution order of multiple K cells in K?

### ISSUE THREAD

**Issue by ppooii12009** [runtimeverification/k#4293]
Multithreading is one of the common features of high-level programming languages. In the K tutorial, a typical implementation approach is to use `spawn` to create a new `<thread>` cell containing a `<k>` cell. In this case, the execution order of multiple `<k>` cells is random (although I have found that the result is unchanged each time the program is executed without modification). When I want to manually control the execution order of these threads, an easy way to think of is to use the thread ID for control. For example:

```k
rule <k> // some operation here </k>
     <id> TID </id>
     <permission> PID </permission>
    requires TID ==Int PID
```
In this way, the rule will only be executed when the thread ID `TID` matches the permission ID `PID`. However, this approach seems a bit cumbersome(you have to add this side condition to all the rules), and it may not be suitable for scenarios where the number of threads changes dynamically. Although we can maintain the `PID` properly, is there a more flexible way to control the execution order of multiple K cells in K?

**Comment by Baltoli** [comment]
There isn't a built-in way to do this, no. You will need to explicitly encode whatever fairness / scheduling semantics you want into your code (as I think you're suggesting in your example).

Generally speaking, while there is some special treatment of the K cell by the compiler, we want the language to remain as general as possible and so we avoid doing special-casing like defining the order of execution between multiple K cells. For example, you can imagine a semantics that wants to identify in symbolic execution when there's a race between two threads.

Will close this issue for now, but please do come back to me if that's unclear or I can help with your specific code any further!

**Comment by ppooii12009** [comment]
I got it. Thanks!
