### ISSUE TITLE
Generated cell initialisation functions should be (checked &) marked as total

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/k#4301]
As the title suggests: 
The K compiler generates initialiser functions for all cells of the configuration.  In kore, these functions are called `Lblinit%NAME%Cell` (where `%NAME%` is the cell name).

Since many of these initialisers take no arguments at all, so they are actually constants. 
They should be marked as _total_ functions.
For the initialisers which do take arguments, they always take a `Map` (which will contain variables passed in by the user via `-cVARIABLE=VALUE`), passed from the `initGeneratedTopCell` function  down to the cell initialisers where those variables, such as `PGM`, are inserted into the configuration.  These functions are not necessarily total, but it could be checked (recursively through the initialisers) whether the RHS uses a partial function.
This check would also catch the pathological case where a constant cell (init function without arguments) is declared to contain an undefined value.

Background:

I am working with a semantics where some rules have the shape (paraphrased)
```
rule <k> Command => .K ... </k>
     _:StateCell => <state> <thing> .K </thing> ... <'state>
```
The `...` ellipsis in the `state` cell in this rule implicitly calls all `init*Cell` functions  for each inner cell inside the `state` cell (except `thing`, obviously). This rule could be marked as preserving definedness, but the compiler should mark its generated functions to avoid having to do so.

**Comment by ehildenb** [comment]
I think any that take a `Map` are likely to not be total, as it results in a map lookup at the leaf of the configuration.
