### ISSUE TITLE
Roll out `Simple-sub` based type inference

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4315]
The new algorithm has been available in K for a while now, let's discuss steps necessary to make it the default type inference mode on the Frontend.

**Comment by Baltoli** [comment]
This should be a one-line fix.

**Comment by Scott-Guest** [comment]
SimpleSub is currently turned on for the C and MIR semantics. I'll enable it for EVM semantics as well, and if there are no issues we should be good to enable it by default.
