### ISSUE TITLE
Ensure that pyk/K API documentation is deployed

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/k#4379]
Related: https://github.com/runtimeverification/k/issues/4183

As mentioned by @tothtamas28, the code responsible for generating [public API documentation](https://runtimeverification.github.io/pyk/) for pyk got migrated to the K repository, but it is unclear whether the changes are actually getting deployed at https://runtimeverification.github.io/pyk/.

**Comment by Baltoli** [comment]
We were previously using the default Github pages environment on the Pyk repo; we are _building_ the documentation on every PR but are never actually publishing it. We should figure out how to do this in the K context and reinstate the publishing.

**Comment by tothtamas28** [comment]
Old deployment job: https://github.com/runtimeverification/pyk/blob/68bffc5ed0994d2c462d91fa3415f170cb0ec91f/.github/workflows/master.yml#L44-L73
