### ISSUE TITLE
Migrate `ubuntu-20.04` jobs to a more recent image

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4390]
There are a few jobs that still run on `ubuntu-20.04`. We should migrate them to `ubuntu-22.04` or `ubuntu-24.04` before support for the image ends.

**Comment by Baltoli** [comment]
Will be closed when:
- https://github.com/runtimeverification/llvm-backend/pull/1091
- https://github.com/runtimeverification/k/pull/4429
are both merged.
