### ISSUE TITLE
Make an option to `krun` like `--suppress-cells` which suppresses outputting certain cells

### ISSUE THREAD

**Issue by yzhang90** [runtimeverification/k#44]
If in the configuration, a cell contains large data, it would take long time to print the whole configuration. Especially when debugging the kprover in intellij, nearly in each step, the intellij will print the whole configuration. It would be great if there is an option to `krun` and `kprove` to suppress printing certain cells in the configuration.

**Comment by dwightguth** [comment]
This has very little to do with K and a lot to do with your intellij debugger settings... I'm not sure there's anything I can reasonably be expected to change here.

**Comment by yzhang90** [comment]
Here is a hack to the `toString` function in the `KItem.java`:
```
    public String toString() {
        String label = kLabel.toString();
        if(label.equals("<program>") || label.equals("<programBytes>") || label.equals("<code>")
           || label.equals("<callStack>")){
            return kLabel + "(" + ((KList)kList).getContents().size() + ")";
        }
        else {
            return kLabel + "(" + kList.toString() + ")";
        }
    }
```
 `program`, `programBytes`, `code` and `calllStack` cells will not be printed in the configuration.
It also can be viewed as an improvement to the pretty printing, which suppress printing the cells that the users don't care about.

**Comment by dwightguth** [comment]
I'm going to close this because I can't actually make a code change like you're asking, nor would it be appropriate. If this is still blocking you let's discuss on slack how you can change your intellij settings.

**Comment by darko-marinov** [comment]
@bmmoore has also encountered problems at DENSO when printing large configurations (from RV-Match crashes). It may be worthwhile to add some "lightweight" printing that prints less (implemented in a proper way so one can configure what to print).

**Comment by ehildenb** [comment]
I think this is worth re-opening so we can discuss a way to suppress output of specific cells in all modes of operation (eg. `krun --search`, `krun --debugger`, and just `krun`). In particular, this would be useful for the `--debugger` option.

I also don't think we should modify the `toString` function, as that does not seem appropriate.
