### ISSUE TITLE
Are heating and cooling rules part of the syntax?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#440]
In the IMP tutorials, we can see the keywords `heat` and `cool` being used. I haven't been able to get K to compile rules in this form, however. Particularly, the example uses `[]` to denote the holes in the evaluation context. Are these labels present in K?

For instance:

    rule T:Term + T2:Term => T ~> [] + T2 [heat]

Fails to compile, highlighting the first `[`. In the tutorial we see something similar given as an example.

**Comment by dwightguth** [comment]
Rules with the `heat` and `cool` attributes are generated automatically from context declarations, which are in turn generated automatically from strict attributes. If you simply want something like you mention in your example, you can use:

```
syntax KItem ::= #freezerPlus(Term)
rule T:Term + T2:Term => T ~> #freezerPlus(T2) [heat]
```

If you also want something like 

```
rule V:Val ~> #freezerPlus(T2:Term) => V + T2 [cool]
```

You may want to consider writing either 
`context HOLE + _` or `syntax Term ::= Term "+" Term [strict(1)]` instead, however.

**Comment by LaifsV1** [comment]
Ah. To check if I understood, with `syntax Term ::= Term "+" Term [strict(1)]`, we wouldn't need the rule `rule T:Term + T2:Term => T ~> #freezerPlus(T2) [heat]`. The rule `rule I1:Int + I2:Int => I1 +Int I2` would be enough. Is this correct?
edit: I forgot to ask. What does `context HOLE + _` do?

**Comment by dwightguth** [comment]
putting the `strict(1)` attribute on that production is equivalent to writing:

```
context HOLE + _
```

which is in turn equivalent to writing

```
syntax KItem ::= #freezerPlus(Term)
rule HOLE:Term + T:Term => HOLE ~> #freezerPlus(T) [heat]
rule HOLE:Term ~> #freezerPlus(T:Term) => HOLE + T [cool]
```

which in turn is roughly equivalent (at least with respect to concrete execution) to writing:

```
syntax KItem ::= #freezerPlus(Term)
rule HOLE:Term + T:Term => HOLE ~> #freezerPlus(T) requires notBool isKResult(HOLE)
rule HOLE:Term ~> #freezerPlus(T:Term) => HOLE + T requires isKResult(HOLE)
```

You should definitely not write this last, however. I include it merely as illustration of the intended semantics.

So no, if you put strict(1) on the first argument, you don't need the explicit heating and cooling rules.

Note by the way that what you probably intend for addition is that both arguments be evaluated to integers, in which case you likely want either `strict(1, 2)` in which case both arguments are evaluated nondeterministically in either order, or `seqstrict(1, 2)` in which case arguments are evaluated from left to right. Of course, you could also write `seqstrict(2, 1)` in which case you would get right-to-left evaluation.

Given the strictness attributes on the production, you do not really need to worry about writing heating and cooling explicitly in your semantics, though. So you are correct that a rule like `rule I1:Int + I2:Int => I1 +Int I2` would be all you would need to implement the semantics of addition.

To answer your other question, generally speaking, `context Ctx[HOLE]` where Ctx is some arbitrary term containing a HOLE, means that if the top of the k cell matches Ctx[HOLE] (where HOLE is just a variable with a special name), and HOLE hasn't been evaluated yet, then heat whatever HOLE is bound to, and cool it when evaluation finishes.

**Comment by dwightguth** [comment]
Also, not sure if you are still interested to know, but ?A tells the semantics to introduce an unbound variable into the configuration being rewritten. This is a feature that can be taken advantage of in symbolic K backends (--backend java and --backend haskell) in order to perform unification between the subject and the pattern of the rule. If you want examples of how this can be used, I would suggest reading the 5_types section of the K tutorial, which makes use of such features in order to implement type inferencers, among other things.

**Comment by LaifsV1** [comment]
Thank you for the replies. That was incredibly helpful. For ?A, is the variable introduced fresh then? How is this different from !N used in the tutorial files?

**Comment by dwightguth** [comment]
!A introduces a fresh /constant/. this is a fully concrete term which unifies only with itself, but which is distinct from any previous fresh constant generated by the definition.

?A introduces a fresh /variable/. This will unify with anything of the same sort, provided no other constraints exist on its value. As an example, if the top of the K cell is foo(X) ~> X, where X is a fresh variable, and a rule exists in the semantics like `rule <k> foo(0) => 1 ... </k>`, then this rule will rewrite the top of the k cell to `1 ~> 0`. Why? Well, X unifies with 0, generating a substitution which is then applied to each instance of X in the subject, regardless of whether that instance matched against anything in the rule.

Once again, note that this only works on backends which support unification. Namely, java and haskell.

**Comment by LaifsV1** [comment]
Thanks for your replies. They have been extremely helpful. I have some questions less related to this issue, and was hoping I could ask here instead of opening new issues.
1) Is there documentation somewhere on the built-in parser and it's capabilities? For instance, to parse Python or Haskell, I would need to parse newlines.
2) Is there some syntactic shorthand to update maps where values may or may not be present in the domain? e.g. `M[X |-> A]` adds `X` to the domain if it's present and maps it to `A`, or updates the current value or `X` to point at `A` if `X` is already in the domain.

**Comment by dwightguth** [comment]
There is not a lot of documentation about the parser, no. In response to your specific question, K is capable of parsing newline-sensitive languages, but not indentation-sensitive languages. So you wouldn't be able to parse Python or Haskell, but you might be able to parse scala, javascript, or visual basic.

In response to your second question, I believe the syntax you are looking for is `M [ Key <- Value ]`. This will either insert or update the map by setting the binding of Key to Value.

**Comment by LaifsV1** [comment]
Thanks for all the answers. On the topic of ?A, I looked at the tutorial files and tried it out. What does ?A do exactly when running on a symbolic backend? I tested it, and it seems to assign some compatible value to ?A and executes the term using it. Is that right?

Is there any built-in symbolic execution in K? If not, is there a way to tell it to explore all paths involving these symbolic variables? for instance, `if ?A then 1 else 0` would have two possible branches, `1` and `0`. Is there a way to list all possible leaf nodes produced from exploring this term?

**Comment by dwightguth** [comment]
The java and haskell backends definitely contain built-in symbolic execution. If you write rules like:

```
rule if true then A else B => A [transition]
rule if false then A else B => B [transition]
```

and you `krun --search` the term `if ?A then 1 else 0`, it should generate two output configurations, 1 and 0. It doesn't generate a compatible value for ?A, it actually stores it in the term being rewritten as a symbolic value and unifies it with the rules being executed while tracking the symbolic constraints.

Does that answer your question?

**Comment by LaifsV1** [comment]
Yes! Thank you! That is extremely helpful. What does the [transition] tag do?

**Comment by LaifsV1** [comment]
Ah, if I have the rules `if 0 then A else B => B` and `if I:Int then A else B => A requires I =/=Int 0`, then K doesn't do a zero and non-zero branch, but appears to attempt to generate a branch for every integer. Is this correct?

**Comment by dwightguth** [comment]
It's going to branch based on which rules apply, so it should only need to do two branches.

The transition attribute tells the java backend that this rule is considered a transition in the state graph of the semantics and thus it should try to apply every single rule and generate the complete list of successor states instead of simply choosing the first rule that applies as an optimization. Ultimately we decided that this makes things confusing for users and thus removed the need to do this in the haskell backend, but the haskell backend is still under active development and cannot run every definition that the java backend supports yet. I would advise you to use the java backend for the time being unless you want to try the haskell backend and it works for you out of the box with no errors or bugs. Hence my suggestion to use the attribute on critical pairs in the semantics.

**Comment by LaifsV1** [comment]
Ah I see. I'm currently using the java backend. I have a lambda calculus with two if rules with the [transition] attributes, and an extra rule `sym X:KVar in T:Term => T[?A/X]`, which just introduces a symbolic variable `?A` in T.

However, when testing this, `krun` appears to get stuck in a loop, which is why I assumed it was generating a branch for each value rather than for each transition. Am I misunderstanding the use of `?A` in the substitution?

edit: letting it run long enough, it outputs an out of memory exception.
here is the trace:
```
java.lang.OutOfMemoryError: Java heap space
	at org.pcollections.HashPMap.plus(HashPMap.java:116)
	at org.pcollections.HashPMap.plus(HashPMap.java:29)
	at org.pcollections.MapPSet.plusAll(MapPSet.java:88)
	at org.pcollections.MapPSet.plusAll(MapPSet.java:20)
	at org.kframework.backend.java.kil.VariableSetFieldInitializer.visitNode(VariableSetFieldInitializer.java:27)
	at org.kframework.backend.java.symbolic.BasicVisitor$$Lambda$200/0x00000008402a1040.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:178)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:192)
	at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:21)
	at org.kframework.backend.java.kil.VariableSetFieldInitializer.visitNode(VariableSetFieldInitializer.java:24)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:151)
	at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:17)
	at org.kframework.backend.java.kil.VariableSetFieldInitializer.visitNode(VariableSetFieldInitializer.java:24)
	at org.kframework.backend.java.symbolic.BasicVisitor$$Lambda$200/0x00000008402a1040.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:178)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:192)
	at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:21)
	at org.kframework.backend.java.kil.VariableSetFieldInitializer.visitNode(VariableSetFieldInitializer.java:24)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:151)
	at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:17)
	at org.kframework.backend.java.kil.VariableSetFieldInitializer.visitNode(VariableSetFieldInitializer.java:24)
	at org.kframework.backend.java.symbolic.BasicVisitor$$Lambda$200/0x00000008402a1040.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:178)
	at org.kframework.backend.java.symbolic.BasicVisitor.visit(BasicVisitor.java:192)
	at org.kframework.backend.java.symbolic.BasicVisitor.visitNode(BasicVisitor.java:21)
	at org.kframework.backend.java.kil.VariableSetFieldInitializer.visitNode(VariableSetFieldInitializer.java:24)
[Error] Internal: Uncaught exception thrown of type OutOfMemoryError (Java heap
space)
```

**Comment by LaifsV1** [comment]
I'm closing this since I decided not to use `A?` and the original question was answered.
