### ISSUE TITLE
[PyK Docs] Some pages on PyK documentation don't have the expected content of modules/functions

### ISSUE THREAD

**Issue by Robertorosmaninho** [runtimeverification/k#4413]
### What K Version?

7.0.108

### Operating System

Linux

### Issue Description

https://kframework.org/pyk/api/pyk.kllvm.hints.prooftrace.html, among other modules that depend on LLVM Python bindings, doesn't have content generated by Sphinx doc. The issue seems to be that they can't find the library as they don't have access to `llvm-kompile` to find it (in the case of files that import `load_static.py`) or to compile the lib (in the case of files that depend on `load.py`), for the first case we still have the problem that we should have it compiled already. 

 We can see the errors and traces in this execution: https://github.com/runtimeverification/k/actions/runs/9353842357/job/25748732638 at the Build Webpage step.

### Steps to Reproduce

Execute `make docs` in the PyK directory without any K/LLVM Backend tools in your `$PATH` as the CI workflow that executes the docs generation doesn't have any of them installed.

### Expected Results

We expect that all modules which depend on LLVM Python Bindings can have their appropriate documentation deployed to https://kframework.org/pyk.

**Comment by tothtamas28** [comment]
A possible fix is to copy the bindings `.so` module into `site-packages` before running Sphinx. The `pyk.kllvm` modules will then be able to import `_kllvm` without `load` or `load_static`.

We have two ways of getting the bindings module. We can either get it from the K distribution, or compile it dynamically. I suggest the latter approach as it is agnostic to Python version.
