### ISSUE TITLE
pyk docstring style

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4435]
Python has multiple docstring formats:
1. Sphinx style: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html
2. Google style: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
3. NumPy style: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html
4. ...

Sphinx by default supports (1), but there's a standard extension, [napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/), that adds support for (2) and (3).

Most public functions in pyk have no docstring attached. Most of what we have is written in (1), but there's also  some docstring code written in (2).

Let's discuss which style to adapt, then start documenting the public API.

**Comment by Baltoli** [comment]
@tothtamas28 to evaluate the Napoleon plugin and make a decision on this; weak consensus for the Google style if the plugin works well.

**Comment by tothtamas28** [comment]
The plugin works well, I opened a PR to adapt existing docstring code to Google style: #4450.
