### ISSUE TITLE
Make use of parsing caches in kdist

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#4481]
One thing I noticed recently while working on making modifications to the WASM semantics is that kdist appears to be doing something that effectively clobbers `kompile`'s parsing cache each time a rule is changed. compilation times via `kdist build` might be improved rather dramatically if the code were tweaked so that incremental parsing was enabled.

**Comment by gtrepta** [comment]
https://github.com/runtimeverification/k/blob/7485b9660c628041680e012d38dba3fdeca2ec90/pyk/src/pyk/kdist/_kdist.py#L148-L150

This "cleanup" of the directory when the target is built should probably just be removed and then `kdist clean` can be relied on when a clean build is needed.

**Comment by gtrepta** [comment]
I tested out just removing the `shutil.rmtree` call and it looks like it will break the wasm semantics which does a `shutil.copytree` in one of its build targets and relies on the destination folder not being there. So, I will need to go through everything downstream to make sure this change can be made.
