### ISSUE TITLE
Syntax to extract the evaluation context?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#459]
Say we have a cell `<k> T:Term ~> K1:KItem ~> K2:KItem  ... </k>`. My understanding is that `K1 ~> K2 ~> ...` is the "context" in which `T` is being evaluated. Is there a way to extract this whole context `K1 ~> K2 ~> ...`?

e.g. if we have a context `E` in `E[T]`, I would like to extract `E`. Something with the intention of the following: 
`<k>T ~> K1 ~> K2 ~> ... ~> Kn</k><context> _ => K1 ~> K2 ~> ... ~> Kn</context>`

**Comment by dwightguth** [comment]
`rule <k> T:Term ~> E:K </k>`

Equivalently, in your example with a K1 and K2, you can write:
`rule <k> T:Term ~> (K1:KItem ~> K2:KItem ~> K:K </k>` and refer to `K1 ~> K2 ~> K`

**Comment by dwightguth** [comment]
Remember that `<k> foo ... </k>` is just syntactic sugar for `<k> (foo) ~> _ </k>`

**Comment by LaifsV1** [comment]
Thank you! I didn't realize the dots were notation for `~> _`. That makes sense.
