### ISSUE TITLE
bad links in K Tutorial

### ISSUE THREAD

**Issue by smalltalker55** [runtimeverification/k#46]
The README file for the K Tutorial says "Some of the languages defined so far using the K framework can be found in the tutorial/2_languages directory, and many others in the samples directory."    When I clink on the links for these two directories, I get a "file not found" error.

**Comment by JoshOrndorff** [comment]
This is the directory you're looking for https://github.com/kframework/k5/tree/master/k-distribution/tutorial/2_languages

**Comment by JoshOrndorff** [comment]
Looks like the link to tutorial/1_k is also broken

**Comment by ehildenb** [comment]
The K tutorial has been revamped at https://kframework.org. If there are broken links there, please open a new issue pointing them out.
