### ISSUE TITLE
Potential bug in how integer division/modulus are encoded to SMT

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#4606]
See Slack discussion: https://runtimeverification.slack.com/archives/C03NP1UP2KZ/p1724335226574649

We have two different forms of division/modulus available to users: https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#integer-arithmetic

One is Euclidian division, which rounds towards nearest. The other is t-division ("truncated division"), which rounds towards zero.

In particular:

```
 syntax Int ::= ...
               /* /Int and %Int implement t-division, which rounds towards 0 */
               | Int "/Int" Int                 [function, symbol(_/Int_), left, smt-hook(div), hook(INT.tdiv)]
               | Int "%Int" Int                 [function, symbol(_%Int_), left, smt-hook(mod), hook(INT.tmod)]
               /* divInt and modInt implement e-division according to the Euclidean division theorem, therefore the remainder is always positive */
               | Int "divInt" Int               [function, symbol(_divInt_), left, smt-hook(div), hook(INT.ediv)]
               | Int "modInt" Int               [function, symbol(_modInt_), left, smt-hook(mod), hook(INT.emod)]
```

The issue is that we're giving the same `smt-hook(...)` to both types of division and modulus, even though they behave differently below zero.

Looking at smt-lib, it seems that it implements Euclidian division: https://smt-lib.org/theories-Ints.shtml. So we have the correct implmeentation for `divInt` and `modInt`, but not `/Int` and `%Int`.

Here is a random gist I found that implements functions for `truncated` variants: https://gist.github.com/Rufflewind/a880e03fb0d13644a1e8.

Perhaps we could add these truncated variants to our SMT prelude that the backend uses, and hook those methods instead?

**Comment by virgil-serbanuta** [comment]
Also see this: https://runtimeverification.slack.com/archives/C7E701MFG/p1693948658347829

**Comment by jberthold** [comment]
FWIW see this interesting write-up about different integer divisions https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/divmodnote-letter.pdf (Daan Leijen, extract from his LVM work in the early 2000s).
He expresses Euclidean division/modulus by T-division/modulus. We would of course want the inverse of that...
