### ISSUE TITLE
A sort including contexts while avoiding circularity?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#462]
I'm trying to define an evaluation stack as a list of evaluation contexts:

    Stack ::= List{KItem,"::"}

My reasoning was that evaluation contexts `E` in `A ~> E` can be anything in the `KItem` sort. This throws a circularity exception: `KItem < Stack < KItem`.

Is there be a way to define a sort for these evaluation contexts `E`? Is there a more precise sort for `E` that isn't the whole of `KItem`?

**Comment by dwightguth** [comment]
Your best bet is just to use the K sort, which is already a cons list of KItem.

**Comment by LaifsV1** [comment]
So instead of creating a new `Stack` sort, just use `K` sort for the stack?
Is there a way I could set a cons operation like `::` to separate the items?

**Comment by LaifsV1** [comment]
I ended up using `K` for the sort, with an initial value `.K`, and the rule:
```
  rule <k> M:KVar V:Val ~> E => OP </k>
       <evalstack> ES => ListItem(E) ES </evalstack>
```
to add the evaluation context into the stack.

**Comment by dwightguth** [comment]
You can simply use `~>` as the cons operation of the `K` list.
