### ISSUE TITLE
Pattern matching lists?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#466]
Is there a way to pattern match elements of a list like you would in OCaml or Hakell?
e.g. a list `x1::x2::xs` would have elements `x1`, `x2` followed by a list `xs`. I tried `ListItem(X1) ListItem(X2) XS` but this does not seem to work. 

Additionally, how does one build a list in a similar way. 
e.g. something like `XS => ListItem(X1) ListItem(X2) XS`.

**Comment by LaifsV1** [comment]
Ah, I just realised from another issue answer just now that `~>` is the cons operator for `K`, so I could write `XS => ListItem(X1)~> ListItem(X2) ~> XS`. Is this the right idea?

**Comment by dwightguth** [comment]
it depends on the sort of your list. If the sort is List, then `ListItem(X1) ListItem(X2) XS` should work. If the sort is K, then `X1 ~> X2 ~> XS` should work. The term you wrote is actually going to rewrite to a `K` list whose elements are `List`s with a single element, which is almost certainly not what you intend.

**Comment by LaifsV1** [comment]
Thanks! `X1 ~> X2 ~> XS` is what I intended to do.
