### ISSUE TITLE
Refactor `module_to_kore`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/k#4707]
* Extract submodules: https://github.com/runtimeverification/k/pull/4704#discussion_r1876874097
* Group symbol productions by attributes before axiom generation: https://github.com/runtimeverification/k/pull/4704#discussion_r1876845326

**Comment by ehildenb** [comment]
I think these can be added to the list here: https://github.com/runtimeverification/k/issues/4690

**Comment by tothtamas28** [comment]
Subsumed by #4690.
