### ISSUE TITLE
Interface to call Z3 (or others) within K?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#478]
Is there a way to call solvers for `SMTLib` formulas within `K`?
Something with the intuition of the following rule:
```
rule <k> M => M' </k><pc> PC </pc> requires Sat(PC)
```
The idea is that a transition is taken only if the path condition `PC` is satisfiable.

**Comment by dwightguth** [comment]
Not currently, no.

**Comment by nishantjr** [comment]
I have worked on an interface for calling Z3 via the calls to `#system`. https://github.com/kframework/k/pull/350 
I have not had the time to fix errors in the CI yet, though. @LaifsV1

**Comment by LaifsV1** [comment]
@nishantjr what is the state of this? are there any working examples I could try?

**Comment by nishantjr** [comment]
There are examples in `k-distribution/tests/regression-new/smtlib2/`

run `make` after building K

**Comment by nishantjr** [comment]
Tests were passing locally on my machine, but not on the CI server. You need Z3/CVC4 in your system PATH

**Comment by ehildenb** [comment]
@nishantjr what's the status here?

**Comment by nishantjr** [comment]
We've got a working implementation being used for the matching logic prover. I have not had time to upstream it.

**Comment by nishantjr** [comment]
I'm not sure when I will be able to.

**Comment by LaifsV1** [comment]
Is this done as a K module with system calls? Or does it use internal bindings (like the OCaml bindings for Z3)?

**Comment by nishantjr** [comment]
System calls still

**Comment by ehildenb** [comment]
This can be achieved using the system calls in K, and I think @nishantjr can post his example of the wrapper library he used for making this work here. Closing for now.
