### ISSUE TITLE
Cannot run program "ocamlfind" (in directory "."): error=2, No such file or directory

### ISSUE THREAD

**Issue by MrChico** [runtimeverification/k#48]
I'm getting this message about ocamlfind when trying to run K through intelliJ. In the terminal it all seems to work fine. Any idea what causes this?

**Comment by ehildenb** [comment]
Can you try adding `--backend java` to the IntelliJ invocation of `kompile` and see if the problem persists?

**Comment by MrChico** [comment]
Yeah, that seems to work! Thank you!

**Comment by ehildenb** [comment]
Just FYI on what's happenning. When you have no `--backend` option, it defaults to `--backend ocaml`. The OCaml backend is the fast interpreter we generate which *cannot* do any symbolic reasoning.

Adding `--backend java` instead generates files consumable by the Java interpreter, which *can* do symbolic reasoning. I think we should be able to call the OCaml backend from IntelliJ, but seeing as how you want to do symbolic reasoning will not work to fix this now.
