### ISSUE TITLE
Expanding a single transition with all items of a set

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#485]
When using the `[transition]` keyword, `--search` will expand all `[transition]` labelled transitions that can be applied. However, if a single transition can be applied in multiple ways, it appears to expand only one instance.

Here's the K-file for a minimal example:
```
module TEST
  imports DOMAINS
  imports SET
  syntax Lib   ::= "end" | "import" Id Lib
  configuration <T>
                  <k> $PGM:Lib </k>
		  <methods> .Set </methods>
	        </T>
		
  rule <k> import M L => L ... </k>
       <methods> ... .Set => SetItem(M) ... </methods>
       [structural]
  rule <k> end => M </k>
       <methods> ... SetItem(M) ... </methods>
       [transition]
endmodule
```
When running the following program with `--search`:
```
import m1
import m2
import m3
import m4
end
```
we deterministically get:
```
Result ==K <T>
  <k>
    m4
  </k>
  <methods>
    SetItem ( m1 )
    SetItem ( m2 )
    SetItem ( m3 )
    SetItem ( m4 )
  </methods>
</T>
```
My question is then whether there's some built-in way to expand `rule <k> end => M : TYPE </k>` with all items `m1` to `m4` without having to alter the semantics too much.

**Comment by dwightguth** [comment]
I believe this is a limitation that the Set/Map implementation has in the Java backend. I doubt you will be able to make it so that a Set has all of its elements nondeterministically chosen for transitions.

**Comment by LaifsV1** [comment]
Is there some kind of iterator to deterministically go through all items in a Set then?
Is there a built-in way to convert Sets to Lists?

**Comment by dwightguth** [comment]
Yes to both. You can deterministically choose some element of a Set by writing a pattern like `SetItem(E) S:Set`. This can be used to iterate by means of progressively removing elements from the set until none are left, as in the following function:
```
syntax Int ::= bar(Element) [function]
rule foo(SetItem(E) S:Set) => bar(E) +Int foo(S)
rule foo(.Set) => 0
```

You can also transform a set into a list with the `Set2List` function in the `COLLECTIONS` module. Note that this does not guarantee any particular ordering for a collection; you will get some order, but different backends may choose different orders. You should only do this if you intend to process the resulting list in some fashion which is irrespective of its ordering.

**Comment by LaifsV1** [comment]
Is there an equivalent to `SetItem(E)` for Maps? 
Say I have a map `M : KVar -> Int`, can I iterate through `M` similarly by removing items in the Map?

**Comment by dwightguth** [comment]
Yes, you can do the same thing with maps: `K |-> V`

**Comment by LaifsV1** [comment]
Is the syntax something like `(K |-> V) M` as in Sets? Or does this need to be done via pattern matching the cells? e.g. `<map> ... (K |-> V) ...</map>`

**Comment by dwightguth** [comment]
Yes, the syntax is the same. If you are matching inside a cell, you can do something like `<map> ... K |-> V ...</k>` and that will be equivalent to `<map> _:Map (K |-> V) </map>`, but this is also true of sets.

**Comment by LaifsV1** [comment]
Somewhat unrelated to the topic, is there any syntax to prune a current configuration? i.e. if I want to drop a configuration and not have it appear as a final configuration, rather, have it eliminated completely.

**Comment by dwightguth** [comment]
not really, because once a configuration has been reached, there is no way to "unreach" it in the context of reachability logic. However, you can definitely express a search pattern on concrete or symbolic execution describing what states you are looking for and discard final configurations that do not match that pattern. this is what the --pattern flag to krun does.

**Comment by LaifsV1** [comment]
Ah. So the only way to achieve this effect in the semantics would be to prune possible transitions (via requires for instance) rather than the configurations that have already been reached.

**Comment by dwightguth** [comment]
Correct.
