### ISSUE TITLE
Show progress of symbolic execution

### ISSUE THREAD

**Issue by jiahao42** [runtimeverification/k#494]
Hello, I am trying to run symbolic execution on a program, but it seems that it takes forever. Is there a way to show the progress of symbolic execution? Like show the # of paths K is going to explore right now or something similar? 

My command is `krun --verbose -cPC="true" -cIN="ListItem(#symString(x))" --search example.php`

Thanks a lot.

**Comment by ehildenb** [comment]
Using the Haskell or Java backends (Haskell recommended), you can pass `--debugger` option to have it start the proof repl instead of just attempting the proof. To use this with `krun --search`, you may need ot instead do `--haskell-backend-command kore-repl`.

Re-open if this does not work.
