### ISSUE TITLE
K Parser/Matching engine expects spaces between a cell and its content

### ISSUE THREAD

**Issue by saikatG** [runtimeverification/k#50]
The following code does not give me any errors on compiling but fails to match when run:

```
 rule <thread>...  <k> test E => !T:Int ... </k> <env>Env</env> ...</thread>
        (.Bag => <thread>... <k>E</k> <env>Env</env> <id>!T</id>  ...</thread>)              
```

But this works (Note the spaces):
```
 rule <thread>...  <k> test E => !T:Int ... </k> <env> Env </env> ...</thread>
        (.Bag => <thread>... <k> E </k> <env> Env </env> <id> !T </id>  ...</thread>)    

```

Is that expected? This makes it very difficult to debug.

**Comment by ehildenb** [comment]
The K frontend has changed significantly since this issue was opened. If this is still an issue, please open a new bug report with reproduction steps following the bug report template.
