### ISSUE TITLE
feature request: a new kompile flag `--add-attribute`

### ISSUE THREAD

**Issue by daejunpark** [runtimeverification/k#502]
A new kompile flag that adds an attribute to a rule at the kompile time.

Example:

```
$ cat a.k
rule [lookup]: foo(x) => bar(y)
$ kompile --add-attribute lookup,concrete a.k
```

The above will be essentially equivalent to the following:
```
$ cat a.k
rule [lookup]: foo(x) => bar(y) [concrete]
$ kompile a.k
```

**Comment by daejunpark** [comment]
It can have multiple flags, e.g.,
```
$ kompile --add-attribute rule1,att1 --add-attribute rule1,att2 --add-attribute rule2,att3
```

**Comment by dwightguth** [comment]
Essentially the task is to pass an instance of KompileOptions to the constructor of KILtoKORE. Then when you call convertAttributes, you check the rule label and if it matches, add the attribute you pass.

In terms of KompileOptions, you just need to add a flag you can pass more than once. Take a look at LLVMKompileOptions.java and specifically the -ccopt flag for how to do it.

**Comment by radumereuta** [comment]
Using the `--post-process <json-script>` should be able to give you way more possibilities.
