### ISSUE TITLE
java backend not mentioned in help

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#51]
kompile --help

Result:

    ...
    --backend
       Choose a backend. <backend> is one of [ocaml|coq]. Each creates the
    ...

**Comment by ehildenb** [comment]
Hmmm, I thought this was already fixed in https://github.com/runtimeverification/k. @dwightguth is this an issue with how development is spread across K5 and RV/K? Perhaps we need to look into fixing the dev stream soon.

**Comment by denis-bogdanas** [comment]
Nope it's not:
https://github.com/kframework/k5/blob/525a4d38c8ddf0064bbb3eea1fede4fe7868718f/kernel/src/main/java/org/kframework/kompile/KompileOptions.java#L31

**Comment by ehildenb** [comment]
Hmmm, I remember this being fixed and merged into some K floating around somewhere. But it's also not here: https://github.com/runtimeverification/rv-match/blob/master/k/kernel/src/main/java/org/kframework/kompile/KompileOptions.java.

I think we need to reduce the number of Ks floating around.
