### ISSUE TITLE
LHS consisting of untyped variable should not be allowed

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#518]
If the LHS of the rule consists only of a variable name, it is accepted by the front-end. Example:
```
module UNDEFINED-TERM-TEST
  rule TERM_UNDEFINED => 1
endmodule
```
When rule is `[macro]`, ClassCastException is thrown.

In fact this is almost certainly a typo and LHS is intended to be some syntactically defined symbol.

**Comment by dwightguth** [comment]
Unfortunately this cannot be an error as it is a valid rule that rewrites a variable on the top of the K cell to the integer 1. If you have another example that you think should report an error, I can investigate that instead. I can give a better error message in the macro case if you'd like, but I'm not sure if that would help you?

**Comment by denis-bogdanas** [comment]
I see. In these cases it's much more likely to have an error than an intended rule with a variable in the LHS. Can we add a restriction, if the LHS of a regular rule is just a variable, then this variable must be explicitly typed?

**Comment by denis-bogdanas** [comment]
More recently, since we introduced warnings for unused variables, user will get a meaningful warning. So this is no longer an issue.
