### ISSUE TITLE
JavaCC error

### ISSUE THREAD

**Issue by charala1** [runtimeverification/k#539]
Java Compiler Compiler Version 5.0 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file /home/user/k-build/kernel/src/main/javacc/Outer.jj . . .
Note: UNICODE_INPUT option is specified. Please make sure you create the parser/lexer using a Reader with the correct character encoding.
Warning: Line 709, Column 3: Regular expression for GROUP can be matched by the empty string ("") in lexical state GROUP_STATE. This can result in an endless loop of empty string matches.

**Comment by ehildenb** [comment]
If this is still an issue, please open a new bug report with exact reproduction steps.
