### ISSUE TITLE
Is parsing affected by module name?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/k#565]
I have a file with a modules  `HOLIB-SYNTAX`. If I change the module name to `HOLI-SYNTAX`, parsing changes. I have defined order of precedence in the grammar, but it appears to be affected by the module name.

It is a bit difficult to provide a minimal example, since I'm not sure what causes it.

I'm not sure if this is related, but parsing also appears to change if I swap platform. On Ubuntu 18.10, I have consistently gotten the same terms back on different machine. But when booting Ubuntu 16.04, the terms parsed change. I'm using the latest version of Java on each platform.

**Comment by nishantjr** [comment]
If the main module is named `HOLIB`, K first looks for `HOLIB-SYNTAX` to use for parsing. Otherwise if falls back to the `HOLIB` module.

**Comment by LaifsV1** [comment]
Sorry, I wasn't clear. In my `HOLIB` file, I have a module `HOLIB` and `HOLIB-SYNTAX`. I tested this out in the following ways:

1. change filename to `holi.k`, module from `HOLIB` to `HOLI` and `HOLIB-SYNTAX` to `HOLI-SYNTAX`.
2. only change `HOLIB-SYNTAX` to `HOLI`, and inside `HOLIB`, import `HOLI-SYNTAX`.

The module `HOLIB` wouldn't have any syntax definitions inside. Just the rewrite rules. Both changes resulted in the same effect. The `HOLI` versions of the syntax consistently parsed one way, while `HOLIB` syntax parsed another way. The grammar productions remained the same. I haven't been able to come up with a minimal example, so it might be due to a bug in my semantics.

**Comment by dwightguth** [comment]
Can you try deleting the -kompiled directory and recompiling and seeing if that resolves the issue? if it does, it is likely an issue with our parse cache.

**Comment by ehildenb** [comment]
Please re-open if this is still an issue, with exact reproduction steps.
