### ISSUE TITLE
Unhelpful error message when trying to do function call in pattern match

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/k#566]
I get error messages about unmatched/incorrect parentheses in `realdef.ml` when I do what I'll describe below. Those are usually not very helpful, and perhaps there is a better way to report this error to the user?

# Description
I ran into this while refactoring from a `Map` to a configuration style, `multiplicity=` style map.

It is valid to match on functions in the key of a `Map`, which is often useful.

Example:
```k
    syntax Int  ::= #double(Int) [function]
    syntax Stmt ::= "get2" Int
 // --------------------------
    rule #double(I) => I *Int 2
    rule <k> get2 I => V ... </k>
         <aMap> ... #double(I) |-> V ... </aMap> // This matching compiles fine.
```

The same thing is not valid when matching on the key in a configuration style map:

```k
    syntax Stmt  ::= "access" Int
 // -----------------------------
    rule <k> access IDX => VAL ... </k>
         <item>
           <idx> #double(IDX) </idx> // Causes `realdef.ml` error.
           <val> VAL </val>
         </item>
```
`kompile`ing produces something like:
```
File "realdef.ml", line 2735, characters 77-78:
Error: Syntax error: ')' expected
File "realdef.ml", line 2735, characters 60-61:
Error: This '(' might be unmatched
[Error] Critical: ocamlopt returned nonzero exit code: 2
Examine output to see errors
```

The same happens when using functions from `DOMAINS` like `-Int` and `andBool`, and doesn't even need to be when accessing maps, but in any left-hand side expression, as far as I can see.

```k
    syntax Stmt ::= "silly_inc" Int
 // -------------------------------
    rule <k> silly_inc (I -Int 1 ) => I ... </k> // Causes `realdef.ml` error.
```
So this crashes the OCaml backend at kompile-time. But kompiling with Java instead, the error seems to get pushed to runtime. Executing the following file with `krun`
```
silly_inc 2
```
terminates with the following:
```
<k>
    V0
  </k>
```
which is also a unhelpful.

Is there a way this programmer mistake can be detected and reported before getting propagated through the backend? Once it reaches the backend, it causes these less related failures and misbehaviors.

# Full working example

Here's a module for seeing these behaviors. As it is, it compiles correctly. But it contains some commented out fragments. Each, when uncommented, causes the `realdef.ml` error in the OCaml backend.

```k
module BAD_MATCH
  imports DOMAINS

  configuration
    <k> $PGM:Stmt </k>
    <aMap> .Map </aMap>
    <store>
      <item multiplicity="*" type="Map">
        <idx> 0 </idx>
        <val> "hello" </val>
      </item>
    </store>
    <store2>
      <item2 multiplicity="*" type="Map">
        <idx2> false </idx2>
        <val2> "there" </val2>
      </item2>
    </store2>

    syntax Stmt ::= "get" Int
 // -------------------------
    rule <k> get I => V ... </k>
         <aMap> ... I -Int 1 |-> V ... </aMap> // This matching compiles fine.

    syntax Int  ::= #double(Int) [function]
    syntax Stmt ::= "get2" Int
 // --------------------------
    rule #double(I) => I *Int 2
    rule <k> get2 I => V ... </k>
         <aMap> ... #double(I) |-> V ... </aMap> // This matching compiles fine.

    syntax Stmt  ::= "access" Int
 // -----------------------------
    rule <k> access IDX => VAL ... </k>
         <item>
           <idx> IDX /* -Int 1 */ </idx> // Uncomment for `realdef.ml` error.
           <val> VAL </val>
         </item>

    syntax Stmt  ::= "access2" Bool
 // -------------------------------
    rule <k> access2 IDX => VAL ... </k>
         <item2>
           <idx2> IDX /* andBool true */ </idx2> // Uncomment for `realdef.ml` error.
           <val2> VAL </val2>
         </item2>

    syntax Stmt ::= "silly_inc" Int
 // -------------------------------
    rule <k> silly_inc (I /* -Int 1 */) => I ... </k> // Uncomment for `realdef.ml` error.

endmodule
```

**Comment by ehildenb** [comment]
Using function patterns in LHS of rules which are not evaluating that function is (reasonably) not allowed.

The only reason you can use it in the Key of a Map pattern match is because it actually gets compiled to be on the RHS of the map, see https://github.com/kframework/k/blob/master/pending-documentation.md#collection-patterns

I agree that we should investigate why for `Map` style cell-collections, this isn't being compiled to the RHS correctly.

Can you update your minimized example to be two separate minimized examples? One which demonstrates the bad error message (for function patterns on LHS), and one which demonstrates the compile error (for function patterns in map keys on "lhs" of rule)?

**Comment by hjorthjort** [comment]
`realdef.ml` error when trying to match a function pattern in the LHS of a regular rewrite.

```k
module BAD_MATCH
  imports DOMAINS

  configuration
    <k> $PGM:Stmt </k>

    syntax Stmt ::= "silly_inc" Int
 // -------------------------------
    rule <k> silly_inc (I -Int 1 ) => I ... </k> // Uncomment for `realdef.ml` error.

endmodule
```

Here's a version with a working map `get` for `Map` and a failing map `access` for cell maps (again with `realdef.ml` error message).

```
module BAD_MATCH_MAP
  imports DOMAINS

  configuration
    <k> $PGM:Stmt </k>
    <aMap> .Map </aMap>
    <store>
      <item multiplicity="*" type="Map">
        <idx> 0 </idx>
        <val> "hello" </val>
      </item>
    </store>

    syntax Stmt ::= "get" Int
 // -------------------------
    rule <k> get I => V ... </k>
         <aMap> ... I -Int 1 |-> V ... </aMap> // This matching compiles fine.

    syntax Stmt  ::= "access" Int
 // -----------------------------
    rule <k> access IDX => VAL ... </k>
         <item>
           <idx> IDX  -Int 1 </idx> // Uncomment for `realdef.ml` error.
           <val> VAL </val>
         </item>
```

**Comment by ehildenb** [comment]
We're deprecating the OCaml backend within the next couple months. Please switch to LLVM.
