### ISSUE TITLE
Exception: "Attempting to split non-cell term" when trying to kompile IELE

### ISSUE THREAD

**Issue by andrei-marinica** [runtimeverification/k#567]
Hi!

I have been working on IELE VM for quite some time now. I am building a Go backend inspired by the OCaml one.

Today I decided to try to merge my work the latest version from K Framework master, and I noticed that it doesn't kompile anymore. This exception is not related to the backend, I could reproduce it on the OCaml backend, and occurs before any backend code gets called.

It doesn't seem to be a problem in IELE, since nothing changed on that project since my last merge 2-3 months ago. From what I was able to debug, it seems to be a bug when cells are being sorted, during kompile.

The error is as follows:

```
Compiler: Attempting to split non-cell term
isKResult(`_=shift_,__IELE-COMMON`(K0,K1,K2))
  while executing phase "concretizing configuration" on sentence at
	<none>
	<none>
```

it occurs in SortCells.java, line 444

**Comment by dwightguth** [comment]
This particular issue should be fixed. If you have others, feel free to open a new issue.
