### ISSUE TITLE
Float multiplication error under Ocaml Backend

### ISSUE THREAD

**Issue by QianyangPeng** [runtimeverification/k#598]
The Ocaml Backend seems to give wrong result on float number multiplication.

I have definition:
```
module FLOAT-MUL-SYNTAX
    imports FLOAT
    syntax Pgm ::= f32mul ( Float, Float )
endmodule

module FLOAT-MUL
    imports FLOAT-MUL-SYNTAX

    configuration <k> $PGM:Pgm </k>

    rule <k> f32mul ( F1, F2 ) => roundFloat(F1, 24, 8) *Float roundFloat(F2, 24, 8) ... </k>
endmodule
```
and program:
```
f32mul ( -6.2831854820251465 , 1.401298464324817e-45 )
```
This should return
```
<k>
  -8.40779079e-45p24x8
</k>
```
And it returns the correct value under the Java backend.

When executing with Ocaml backend, however, it returns:
```
<k>
  -8.80461817E-45p24x8
</k>
```
This should be the result of a higher precision multiplication, but it should be wrong here.

Also, I found the result of `roundFloat` on the Ocaml and Java backend are the same, so is there any problem with `*Float` for Ocaml backend?

**Comment by ehildenb** [comment]
The OCAML backend is being deprecated. If you notice the same problem on eth LLVM backend, please open new bug report issue with reproduction steps for that backend.
