### ISSUE TITLE
Add NixOS pkg expressions

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#631]
@ttuegel has a repo of nix expressions for K that he uses locally, we should add these to the `package` files here too.

https://github.com/ttuegel/nixpkgs-kframework

**Comment by ttuegel** [comment]
As of a few days ago, I also have an automatically-updated cache of binaries, generated from the Nix expressions by a GitHub action.

**Comment by ehildenb** [comment]
Subsumed by #1595
