### ISSUE TITLE
how can i run use the symbolic way

### ISSUE THREAD

**Issue by lionheartStark** [runtimeverification/k#67]
I see, in the  old version 3.4.we can symbolic  a variate use the backend "symbolic" and run it with cIN="ListItem(#symInt(n))" but there is no  backend "symbolic" in k5,does it mean that   backend "java" already do this work?and how can i run just use the symbolic way now to symbolic a "int n"?

**Comment by ehildenb** [comment]
If you `kompile` with either the Java or Haskell backend, it will be able to do symbolic execution. `kompile --backend java` or `kompile --backend haskell` will do it.

Closing this as answered, feel free to re-open if you have more questions.
