### ISSUE TITLE
CMake error when compiling

### ISSUE THREAD

**Issue by Demi-Marie** [runtimeverification/k#681]
On a Fedora 30 machine, I get

     [exec] -- Found LLVM 8.0.0
     [exec] -- Found GMP: /usr/lib64/libgmp.so
     [exec] -- Boost version: 1.69.0
     [exec] -- Found the following Boost libraries:
     [exec] --   unit_test_framework
     [exec] -- Configuring incomplete, errors occurred!
     [exec] See also "/home/user/k/llvm-backend/target/build/CMakeFiles/CMakeOutput.log".
     [exec] CMake Error at /usr/lib64/cmake/llvm/LLVM-Config.cmake:175 (message):
     [exec]   Target AArch64 is not in the set of libraries.
     [exec] Call Stack (most recent call first):
     [exec]   /usr/lib64/cmake/llvm/LLVM-Config.cmake:100 (llvm_map_components_to_libnames)
     [exec]   /usr/lib64/cmake/llvm/LLVM-Config.cmake:93 (explicit_llvm_config)
     [exec]   tools/hello/CMakeLists.txt:7 (llvm_config)

**Comment by dwightguth** [comment]
Please install the llvm-static package. It would seem that the llvm package has a bug in its CMake scripts when linking against the shared library.

**Comment by Demi-Marie** [comment]
I now get errors from the C++ compiler, probably because I do not have the correct Rust version installed, but that is probably not a bug.
