### ISSUE TITLE
Feature request: Local binding fresh variables in the RHS of rules 

### ISSUE THREAD

**Issue by malturki** [runtimeverification/k#702]
A mechanism for local binding fresh variables in the RHS of rules, or even better, matching on patterns with fresh variables. 

For example,

```
rule <k> foo(X) => bar(Y) ... </k>
  where Y := baz(X)
```

Or matching

```
rule <k> foo(X) => bar(Y) ... </k>
  where abc(Y) := baz(X)
```

Grigore adds: mathematically, `where` has the same meaning as `requires` or `ensures` or `when` or `if` (we played with all these notations), and they are all equivalent to (conjunction at the top and equality `=` instead of `:=`):
```
axiom <k> foo(X) => bar(Y) ... </k> /\ abc(Y) = baz(X)
```
In KORE, it is OK to add annotations/attributes to axioms like above, but we should make sure we keep them mathematically correct and simple in notation, as axioms.  We'll have to generate proof objects eventually, and we need to know what the proof objects are for.

In the front end, we are more flexible in notations.  Ideally, it would be nice to allow all of `where`, `requires`, `ensures`, `if`, `when` (or pick one)

**Comment by denis-bogdanas** [comment]
It's not only for RHS. As I proposed this binding should have the semantics of substitution and be usable both in LHS and RHS.

**Comment by yzhang90** [comment]
The semantics of `requires` conjuncts the the substitutions to the LHS of the implication ( => is desugard into  -> ⋅ ), this substitution should bind the substitutions to the variables appear only in LHS or both sides ( e.g., (f(x) /\  x = 10 ) -> g(x) is basically equivalent to  f(10) -> g(10)). The substitutions in the `ensures` conjuncts with the RHS of the implication. This usually adds constraints to the fresh variables in the RHS (and they are existential quantified.)

**Comment by yzhang90** [comment]
If you have substitution in the `requires/ensures` clause of a rule, the haskell backend will not use it to simplify the rule itself (by applying the substitution). However, when you apply the rule to the current configuration, the unification algorithm will apply the substitution to the result configuration. 
That being said, if you have a rule
```
rule f(X) /\ X= h(Y) => g(X)
```
and the current configuration is f(A), after applying the rule, the result would be `g(h(Y)) /\ A = h(Y)` or g(A) /\ A = h(Y), depending on internal details.
I'm not sure about behavior of the llvm backend.

**Comment by ehildenb** [comment]
Related to #1685 , let's move discussion there.
