### ISSUE TITLE
Checks: map access in a complex context should need cast, but doesn't

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#733]
A subtle bug involving map, subscript overloading, with-config functions and other. 
Expected: Map access returns KItem thus should lead to kompile error.
Actual: No kompile error, LLVM backend crashes.

File `regression-new/checks/mapAccessWantsCast.k`
```
module MAPACCESSWANTSCAST
  imports DOMAINS

configuration <k> $PGM:K </k> <map> .Map </map>

  syntax Bytes   ::= String | Bytes32
  syntax Bytes32 ::= String | Hash
  syntax Hash    ::= String
  syntax BytesList ::= List{Bytes, ""}

  syntax Bytes ::= BytesList "[" Int "]"                              [function]

  syntax Hash ::= mapGet ( Int ) [function]
  rule [[ mapGet( I ) => MAP[ I ] ]]
    <map> MAP </map>

endmodule
```

**Comment by ehildenb** [comment]
@denis-bogdanas is this still an issue?

**Comment by ehildenb** [comment]
This is definitely a bug in the type-system if it reproduces (should be a parse error, because the return sort on the RHS of the rule is not correct).

**Comment by radumereuta** [comment]
Apparently, this has been fixed since it's been reported (probably with the SMT type inferencer).
You now get this error message:
```
[Error] Inner Parser: Unexpected sort String for variable MAP. Expected: Map
	Source(/home/radu/work/test/./test.k)
	Location(15,11,15,14)
```
Not the most intuitive, but it points you in the right direction.
