### ISSUE TITLE
front-end check: Tricky case when #as is used in RHS doesn't trigger Compile error

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/k#753]
File `regression-new/checks/trickyAsInRHS.k`
```
module TRICKYASINRHS
  imports INT
  imports MAP

configuration <k> $PGM:K </k> <map> .Map </map>

syntax KItem ::= foo(Int)
               | bar(Int)

rule <k> foo(I) => bar((I +Int 1) #as INDEX) ...</k>
     <map>... INDEX |-> _ ...</map>

endmodule
```
Expected: comile error, because `#as` can only be used in LHS. Actual: kompile passes.

Case encountered in Beacon Chain (more complex obviously). Spent several hours debugging it.

**Comment by ehildenb** [comment]
Report an error if `#as` appears on the RHS of a rewrite, or if a rewrite appears on the LHS of an `#as`

**Comment by ehildenb** [comment]
If you want this RHS `#as` in a claim, you can just as well use `#And`, so we should also restrict this for claims if it's not too much trouble.
