### ISSUE TITLE
kast: cannot unparse output from `kprove -m LEMMAS`

### ISSUE THREAD

**Issue by traiansf** [runtimeverification/k#773]
`kast` currently uses the `kompiled` definition; however, for `kprove` we essentially recompile the definition to take into account a `LEMMAS` module.  This makes it hard (impossible) to convert the output back to `k` if the output contains symbols defined in the `LEMMAS` module.

`kprove` gets around this by using the kompiled definition associated to the `LEMMAS` module to unparse the output.

Possible resolution: save the  kompiled definition associated to the `LEMMAS` module to disk (maybe somewhere in the `.kprove...` directory) and allow `kast` to choose it as the definition to use for unparsing.

**Comment by ehildenb** [comment]
This will be addressed by dis-allowing syntax declared between th edef module and the spec module, which is here: #1681
