### ISSUE TITLE
Direct support for `pandoc-tangle` process in `kompile` pipeline, to reduce the complexity of semantics build process

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#775]

**Comment by nishantjr** [comment]
We may also consider moving to [commonmark.py] since it has support for source locations in the AST

[commonmark.py]: https://github.com/readthedocs/commonmark.py

**Comment by ehildenb** [comment]
We now can directly read markdown files, rather than relying on an external tool.
