### ISSUE TITLE
`krun` completely ignores the `--coverage-file` option

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#790]
Currently `krun` seems to do nothing with the `--coverage-file` option, which makes it hard to control where the coverage report is dumped to.

This is blocking the Polkadot project (at least, it's making us use hacky work-arounds), so I'm adding it to the current K Frontend board.

**Comment by dwightguth** [comment]
Coverage doesn't generate a single file, it generates a set of files. So it would probably have to be renamed to --coverage-dir. But it should be doable. Make sure to make the path absolute before it gets baked into the interpreter though.

**Comment by ehildenb** [comment]
Currently the path to dump the coverage data at is hardcoded in `kernel/src/main/java/org/kframework/compile/GenerateCoverage.java` as an addition to each rule which logs the unique identifier using `#logToFile` hook. The way it's done makes it hard to change the directory it's logged to each time, because it's baked into the interpreter.

One way I can think to do it is:

-   Add a cell called `<coverageDir>` which has a variable `$COVERAGE_DIR:String`.
-   If `kompile` was called with `--coverage`, then `krun` looks to see if `--coverage-dir` is supplied. If not, it sets it to the default, otherwise it uses the user-supplied value to populate `$COVERAGE_DIR` in the initial configuration map.
-   The `#logToFile` now call a with-config function `coverageDir()` which grabs the contents of the cell `<coverageDir>` 

eg.:

```
    rule <k> blah => bar ... </k> [UNIQUE_ID(baz)]
```

becomes:

```
    rule [[ coverageDir() => COVERAGE_DIR ]] <coverageDir> COVERAGE_DIR </coverageDir>

    rule <k> blah => #logToFile(coverageDir(), "baz") ~> bar ... </k> [UNIQUE_ID(baz)]
```

This allows us to change `--coverage-dir` with every run of `krun`.

**Comment by ehildenb** [comment]
Of course, another way would be to dump the coverage at the hard-coded path, and then just `mv` the file to the user-specified path after running ,which requires no changes. The one downside I can think of for this approach is (1) partial results won't be at the correct place if the backend crashes partway through execution, and (2) user can't start polling the file for changes before execution finishes (esp. for long-running executions).

**Comment by dwightguth** [comment]
I would really rather we not change the configuration for this. It would probably be better if we passed a relative path to the #logToFile hook and then the #logToFile hook computed that path relative to an environment variable if one is set, otherwise it would be relative to the current working directory.

**Comment by gtrepta** [comment]
Just merged. https://github.com/kframework/llvm-backend/pull/250

You can now set `K_COVERAGEDIR` to a relative/absolute path to an existing directory when you run `krun`.

**Comment by ehildenb** [comment]
I'm re-opening this because the issue wasn't actually addressed.

This PR: https://github.com/kframework/llvm-backend/pull/250 allows us to set `K_COVERAGEDIR`, and that controls the directory where the coverage file goes. But actually:

-   It should probably be called `K_LOG_DIR` instead, since it's for all invocations of `#logToFile`, and
-   We are still ignoring the `--coverage-file` passed to `krun`, and instead logging to a randomly generated file inside `K_COVERAGEDIR`.

This allows us at least to fully parallelize the generation of coverage reports, but in a rather hacky way. Would be better to also support deciding the filename to log to. Propose just supporting one environment variable:

-   `K_LOG_FILE`: if supplied log to this file, otherwise log to randomly generated file in `*-kompiled` directory. If `--coverage-file` is passed to `krun`, it can just set this environment variable.

Not sure why we do the whole split the path at `dirname` and allow overriding the coverage directory, instead of directly allow specifying the coverage file. But if we need to keep doing that, then let's at least allow controlling the name of the file.
