### ISSUE TITLE
`imports MODULE renaming ...` construct

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#837]
In support of the KEQ tool for @mrchico's efforts on doing KYul equivalence checking, we need to be able to import modules with renamed bits. Specifically, we want to be able to prove that compiler optimizations of `KYul -> KYul` are correct, so we need to:

-   Rename all modules `MODULE` to `MODULE-A`
-   Rename all cells `<k>` to `<k-a>`.
-   Rename `$VAR` variables in configuration to `$VAR-A`?
-   Rename strategy rule tags. (or perhaps just annotate rule tags with module name, and give option to use un-annotated names when it's unambiguous)
-   Resolve `context alias` _before_ renaming, meaning it must be done separately for each renamed module.

Example:

```
module YUL
   configuration
     <T> <k> $PGM:Pgm </k> </T>

  syntax BExp ::= Bool | BExp "||" BExp [strict]
  syntax KResult ::= Bool
endmodule

module YUL-KEQ
  imports-renaming YUL{A}
  imports-renaming YUL{B}
  imports STRATEGY

  configuration
    <k> $PGM:Pgm </k>
    </T-A>
    </T-B>
    </s>
endmodule
```

Should become (using simplified notation for `strict`, but really should use `context alias`, and annotated with auto-inserted rule-tags to emphasize rename):

```
module YUL{A}
   configuration
     <T-A> <k-A> $PGM_A:Pgm </k-A> </T-A>

  syntax BExp ::= Bool | BExp "||" BExp [strict]
  syntax KResult ::= Bool

  rule <k-A> BE1:BExp || BE2:BExp => BE1 ~> [] || BE2 ... </k-A> requires notBool isKResult(BE1) [tag(regular-A)]
  rule <k-A> BE1:BExp || BE2:BExp => BE2 ~> BE1 || [] ... </k-A> requires notBool isKResult(BE2) [tag(regular-A)]

  rule <k-A> BE1:Bool ~> [] || BE2 => BE1 || BE2 ... </k-A> [tag(regular-A)]
  rule <k-A> BE2:Bool ~> BE1 || [] => BE1 || BE2 ... </k-A> [tag(regular-A)]
endmodule

module YUL{B}
   configuration
     <T-B> <k-B> $PGM_B:Pgm </k-B> </T-B>

  syntax BExp ::= Bool | BExp "||" BExp [strict]
  syntax KResult ::= Bool

  rule <k-A> BE1:BExp || BE2:BExp => BE1 ~> [] || BE2 ... </k-A> requires notBool isKResult(BE1) [tag(regular-B)]
  rule <k-A> BE1:BExp || BE2:BExp => BE2 ~> BE1 || [] ... </k-A> requires notBool isKResult(BE2) [tag(regular-B)]

  rule <k-A> BE1:Bool ~> [] || BE2 => BE1 || BE2 ... </k-A> [tag(regular-B)]
  rule <k-A> BE2:Bool ~> BE1 || [] => BE1 || BE2 ... </k-A> [tag(regular-B)]
endmodule

module YUL-KEQ
  imports YUL{A}
  imports YUL{B}
  imports STRATEGY

  configuration
    <k> $PGM:Pgm </k>
    </T-A>
    </T-B>
    </s>
endmodule
```

**Comment by dwightguth** [comment]
At a glance, this looks like quite a complex task. Let's make sure to iron out the exact behavior of the feature and make a list of what needs to be done in the implementation to make it work, before we begin writing any code.

**Comment by ehildenb** [comment]
I agree.

**Comment by ehildenb** [comment]
This is subsumed by the larger #1658  task, closing for now.
