### ISSUE TITLE
Investigate why the kprove frontend is so slow

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/k#840]
kprove's frontend which parses the spec and the updated definition and emits the KORE seems to be quite slow compared to what I would expect based on the fact that it is supposed to cache the parses. We should investigate and make sure that caching is working correctly and see if a profile of the time spent in java code reveals any obvious deficiencies.

**Comment by ehildenb** [comment]
Closing as there have been many changes since to the cacheing. If we have a specific example where it is slow, please open a bug report detailing that.
