### ISSUE TITLE
Make list of allowed attributes currently supported

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/k#843]
Currently the frontend doesn't reject definitions which use invalid or deprecated attributes. We don't necessarily need to reject definitions, but we should collect a list of existing attributes and break them into categories:

-   Attributes which are white-listable (they are directly some string or a key/value pair),
-   Attributes which are not white-listable (eg. `syntax priorities` groups), and
-   Attributes which are user-defined?

To get the list, let's look through the frontend and the major semantics (C, KEVM, KWasm).

**Comment by ehildenb** [comment]
Solutions we can think of:

-   When an attribute is not recognized as a built-in, check the edit distance with builtins and emit a warning for any it's similar to.
-   Have a whitelist of attributes which are checked against, any existing user-defined attributes would have to wrapped in a new whitelisted attribute.

At least a K 5.3 feature, or later.

**Comment by radumereuta** [comment]
Add a warning in the front-end.
We should clean the front-end code a bit to make sure we have a complete list of all the supported attributes in one place.

**Comment by radumereuta** [comment]
This check should be somewhere in the outer parser.
Should concern only the attributes a user might write.
Probably we will have to change some definitions, and make sure we declare all attributes in Att.scala.

**Comment by radumereuta** [comment]
@Scott-Guest is this a duplicate of: https://github.com/runtimeverification/k/issues/2625 ?

**Comment by Scott-Guest** [comment]
@radumereuta Yes, this is all covered under #2625. Closing as duplicate.
