### ISSUE TITLE
Generated Kore contains illegal sort injections of `#KVariable`

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#934]
The Kore generated by the frontend contains illegal sort injections such as (from `evm-semantics`):

```
// rule `is#KVariable`(inj{#KVariable,KItem}(#KVariable))=>#token("true","Bool") requires #token("true","Bool") ensures #token("true","Bool") []
  axiom{R} \implies{R} (
    \top{R}(),
    \and{R} (
      \equals{SortBool{},R} (
        Lblis'Hash'KVariable{}(kseq{}(inj{Sort'Hash'KVariable{}, SortKItem{}}(Var'Hash'KVariable:Sort'Hash'KVariable{}),dotk{}())),
        \dv{SortBool{}}("true")),
      \top{R}()))
  []
```

This sort injection is illegal because there is no subsort relation defined on `Sort'Hash'KVariable`.

**Comment by dwightguth** [comment]
This sort should probably not exist in this definition and I'm not sure where it's coming from. If you track it down, let me know and I'll give a more specific opinion; if not, I'll look into it myself when I have some time. I would expect to see this particular problem occurring if you imported one of the modules from kast.k other than BASIC-K or ML-SYNTAX, but that doesn't seem to be happening.
