### ISSUE TITLE
Consider converting the codebase to Kotlin

### ISSUE THREAD

**Issue by XVilka** [runtimeverification/k#936]
Advantages of [Kotlin](https://kotlinlang.org/)
- Conciseness
- Interoperability
- Functional programming support
- Fail-fast system
- Null-safety through nullable and non-nullable types, safe calls and safe casts
- Extension functions
- Higher-order functions
- Data classes
- Immutability
- Type aliases
- [Kotlin Native](https://kotlinlang.org/docs/reference/native-overview.html) can be compiled into the native code, yay, no more JVM!

The porting process can be done in steps, since both Kotlin and Java are interoperable with no effort. And the automated conversion can be performed easily.

**Comment by XVilka** [comment]
Another possible alternative is [Rust](https://www.rust-lang.org/), providing the reach feature set for high level programming. There is even an semi-automated [converter from Java to Rust](https://github.com/aschoerk/converter-page). It will remove the need for JVM as well, along with reducing the memory consumption.

**Comment by ehildenb** [comment]
Re-engineering either the backends or the frontend in a new language is not really a priority. We already are in the (quite lengthy) process of migrating the Java backend to Haskell, and the OCaml backend to LLVM.

The frontend will remain implemented in Java until there is a good reason not to, which given how little it does at runtime will probably not be for a long time. We are offering scripting capabilities in Python via the `pyk` library (at `k-distribution/src/main/scripts/lib/pyk`). This still uses the Java frontend, as there is a lot of code/logic there which converts from the surface K language to the backend languages Kore (Haskell and LLVM backends), and KAST (OCaml backend).

A rewrite of the frontend is a very large task. Alternative implementations welcome, but it's not something we'll tackle ourselves without (1) a clear need, (2) a lengthy design process, and (3) funding.

**Comment by ehildenb** [comment]
We (most engineers at Runtime Verification) agree that avoiding the JVM would be great, to be clear. But there is no pressing need to replace the frontend (written in Java), and the Java backend code is rapidly being deprecated. So we're already reducing our JVM dependence significantly.

**Comment by XVilka** [comment]
Good to hear, thanks for the explanation!

**Comment by ehildenb** [comment]
Going to close this for now, since it's not immediately actionable.
