### ISSUE TITLE
Failed to run test case (locales and unicode)

### ISSUE THREAD

**Issue by dongbiao830415** [runtimeverification/k#941]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kframework.compile.GenerateSentencesFromConfigDeclTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.775 sec - in org.kframework.compile.GenerateSentencesFromConfigDeclTest
Running org.kframework.compile.AddParentsCellsTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.042 sec - in org.kframework.compile.AddParentsCellsTest
Running org.kframework.compile.CloseCellsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in org.kframework.compile.CloseCellsTest
Running org.kframework.compile.SortCellsTest
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec - in org.kframework.compile.SortCellsTest
Running org.kframework.kast.KastModuleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.161 sec - in org.kframework.kast.KastModuleTest
Running org.kframework.utils.ColorUtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.156 sec - in org.kframework.utils.ColorUtilTest
Running org.kframework.utils.StringUtilTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in org.kframework.utils.StringUtilTest
Running org.kframework.utils.PosetTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in org.kframework.utils.PosetTest
Running org.kframework.utils.inject.DefinitionLoadingModuleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.kframework.utils.inject.DefinitionLoadingModuleTest
Running org.kframework.parser.concrete2kore.disambiguation.TreeCleanerVisitorTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec - in org.kframework.parser.concrete2kore.disambiguation.TreeCleanerVisitorTest
Running org.kframework.parser.concrete2kore.disambiguation.AddEmptyListsTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 3.915 sec - in org.kframework.parser.concrete2kore.disambiguation.AddEmptyListsTest
Running org.kframework.parser.concrete2kore.RuleGrammarTest
Tests run: 25, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.163 sec <<< FAILURE! - in org.kframework.parser.concrete2kore.RuleGrammarTest
test18(org.kframework.parser.concrete2kore.RuleGrammarTest)  Time elapsed: 0.163 sec  <<< FAILURE!
### java.lang.AssertionError: Expected no errors here:
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.kframework.parser.concrete2kore.RuleGrammarTest.printout(RuleGrammarTest.java:116)
	at org.kframework.parser.concrete2kore.RuleGrammarTest.parseRule(RuleGrammarTest.java:64)
	at org.kframework.parser.concrete2kore.RuleGrammarTest.test18(RuleGrammarTest.java:340)

Running org.kframework.krun.KRunFrontEndTest

**Comment by dwightguth** [comment]
Do you have z3 on your path?

**Comment by dongbiao830415** [comment]
z3  is installed，all steps follow the installation documentation。
os: Ubuntu18.04

**Comment by dwightguth** [comment]
if you apply the following patch to your source, what does the error message say?
```
diff --git a/kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java b/kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java
index d54363245..2c4438efe 100644
--- a/kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java
+++ b/kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java
@@ -96,7 +96,7 @@ public class RuleGrammarTest {
     }
 
     private void printout(Tuple2<Either<Set<ParseFailedException>, K>, Set<ParseFailedException>> rule, int warnings, boolean expectedError) {
-        if (false) { // true to print detailed results
+        if (true) { // true to print detailed results
             KExceptionManager kem = new KExceptionManager(new GlobalOptions(true, Warnings.ALL, true));
             if (rule._1().isLeft()) {
                 for (ParseFailedException x : rule._1().left().get()) {
```

**Comment by dongbiao830415** [comment]
Test failure is caused by test18 case in RuleGrammarTest.java file.
If i delete the test18 case, other cases execute successfully。
If I apply the above patch , it will print more error messages

**Comment by dwightguth** [comment]
Yeah but I actually need to see the error message it prints, because I can't reproduce this behavior locally.

**Comment by dwightguth** [comment]
Oh I think I see what this is. Test18 is the test for unicode and most likely it is failing because you are on a different locale with a different default charset, and K has not really been fully tested on other locales with regards to its unicode support. For now, I would suggest running `mvn package -DskipTests` instead of `mvn package`, and simply ignoring this error and not using unicode characters in your K definition. I will keep this issue open as a reminder that we don't have localization support working correctly yet though.

**Comment by dwightguth** [comment]
Can you please let me know what locale your Ubuntu machine is on?

**Comment by mgudemann** [comment]
I know this is an old issue, but I just ran into the same problem.
```
~/s/g/K/k (master|✔) $ locale
LANG=C.UTF-8
LANGUAGE=en
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```
on Mint 20
```
5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by radumereuta** [comment]
To be able to run the tests, you need to have `LC_ALL` set to the English format.
But you can always skip the unit tests with `mvn package -DskipTests`.
