### ISSUE TITLE
#parseKORE doesn't take into consideration sort annotation

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#945]
Version K-master, backend: LLVM
```
module TEST
  imports K-REFLECTION
  imports INT
  configuration <k> #parseKORE("\\dv{Int{}}(\"1\")"):Int </k>
endmodule
```
I would expect the output to be an Int, instead I get:
```
radu@ubuntu:~/work/test$ krun --output kast 
`<generatedTop>`(`<k>`(#token("1","K")),`<generatedCounter>`(#token("0","Int")))
```
parsed.txt has:
```
rule initKCell(.KList)=>`<k>`(#noDots(.KList),#SemanticCastToInt(`#parseKORE(_)_K-REFLECTION_Sort_String`(#token("\"\\\\dv{Int{}}(\\\"1\\\")\"","String"))),#noDots(.KList)) requires #token("true","Bool") ensures #token("true","Bool")
```
compiled.txt has this:
```
 rule `<generatedTop>`(`<k>`(`` `start_TEST_KItem`(.KList)=>`#parseKORE(_)_K-REFLECTION_Sort_String`(#token("\"\\\\dv{Int{}}(\\\"1\\\")\"","String"))``~>DotVar1),DotVar0) requires #token("true","Bool") ensures #token("true","Bool")
```
Somewhere along the way, the sort annotation is getting lost.
P.S. This is blocking me from progressing with the K-in-K definition.

**Comment by radumereuta** [comment]
This isn't fixed. You need to test with `-output kast`.
The sort of the term from `parseKORE` is still `K`:
```
`<generatedTop>`(`<k>`(#token("1","K")),`<generatedCounter>`(#token("0","Int")))
```

**Comment by radumereuta** [comment]
It would be nice to have `#parseKORE` insert an injection between the cast sort and the actual sort found inside. Right now it just crashes.
```
module TEST
  imports INT
  imports K-REFLECTION

  syntax Exp ::= Int
  configuration <k> #parseKORE("\\dv{SortInt{}}(\"1\")"):Exp </k>
endmodule
```

**Comment by radumereuta** [comment]
An extension for this issue is in runtimeverification/k#966

**Comment by dwightguth** [comment]
hooks do not know their return sort in the llvm backend, so this is impossible without a substantial refactoring of the structure of the backend, which is not really a priority for such a minor feature with such a clear workaround. I would recommend that you instead simply make sure that the term you are parsing and the inferred term of the hook are the same.

**Comment by ehildenb** [comment]
Duplicate of runtimeverification/llvm-backend#579
