### ISSUE TITLE
#parseKORE should return an error message

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#966]
If I'm missing a label in my term or I have a malformed term, `#parseKORE` right now just crashes.
In domains.k we have this production:
```
syntax IOError ::= "#noParse" "(" String ")" [klabel(#noParse), symbol]
```
which isn't used.
I think it should look something like:
```
syntax {S} Error{S} ::= "#error" "(" String ")" [klabel(#error), symbol]
                      | S // or "#success" "(" S ")" [klabel(#success), symbol]
syntax {Sort} Error{Sort} ::= #parseKORE(String) [function, hook(KREFLECTION.parseKORE)]
```

But I'm happy with any solution that returns a better error message.

**Comment by ehildenb** [comment]
Duplicate of runtimeverification/llvm-backend#579
