### ISSUE TITLE
Odd error produced from typo in syntax declaration

### ISSUE THREAD

**Issue by lucaspena** [runtimeverification/k#970]
In the K file, we had the syntax declaration `syntax DeclarationCelLSet` (erroneous capital L) with no productions for that declaration. kompiling the K file with this declaration failed, producing the error message
```
FAILED: .build/defn/test-driver/unit-tests-kompiled/interpreter
 "ext/k/k-distribution/target/release/k/bin/kompile" --backend "llvm" -I .build/defn/test-driver -ccopt -g --directory ".build/defn/test-driver" .build/defn/test-driver/drivers/unit-tests.k
%set* (%block*)* bitcast (%block* (%block*)* @apply_rule_7856 to %set* (%block*)*)/Users/lpena/kframework/matching-logic-prover/prover/ext/k/k-distribution/target/release/k/lib/../bin/llvm-kompile: line 27: 60092 Abort trap: 6           "$(dirname "$0")"/llvm-kompile-codegen "$definition" "$dt_dir"/dt.yaml "$dt_dir" $debug > "$mod"
[Error] Critical: llvm-kompile returned nonzero exit code: 134
```
Removing that line or fixing the typo fixes this error.

**Comment by dwightguth** [comment]
I would appreciate more detailed reproduction instructions as I cannot reproduce this from my most basic attempts.

**Comment by dwightguth** [comment]
Closing from lack of response. If you are able to reproduce this behavior in the future, please make sure to provide reproduction instructions.
