### ISSUE TITLE
Unsound encoding of #as patterns in Kore

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/k#975]
The encoding of `#as` patterns in Kore equations (for function rules) is unsound. For example,

```
rule f(φ #as X) => ψ(X)
```

is translated as

```
axiom f(φ ∧ X) = ψ(X)
```

which can be instantiated to give

```
axiom ⊥ = ψ(X)
```

The translation should instead be

```
axiom f(φ) = ψ(X) ∧ ⌈φ ∧ X⌉
```

See also: https://github.com/kframework/kore/issues/1324#issuecomment-565439313

**Comment by traiansf** [comment]
I'm also encountering a strange KORE encoding generated by `#as` patterns, in which the equation corresponding to the `#as` condition is added both to the precondition and the postcondition of an equation.

For example, one of the rules for `orElse`, 
```
rule _ orElseBool true => true
```

is translated to
```
    \implies{R}(
        \equals{SortBool{}, R}(
            Var'Unds'2:SortBool{},
            /* builtin: */ \dv{SortBool{}}("true")
        ),
        \and{R}(
            \equals{SortBool{}, R}(
                Lbl'Unds'orElseBool'Unds'{}(
                    Var'Unds'0:SortBool{},
                    \and{SortBool{}}(
                        /* builtin: */ \dv{SortBool{}}("true"),
                        Var'Unds'2:SortBool{}
                    )
                ),
                Var'Unds'2:SortBool{}
            ),
            \equals{SortBool{}, R}(
                Var'Unds'2:SortBool{},
                /* builtin: */ \dv{SortBool{}}("true")
            )
        )
    )
```

Which reads something like
```
  V_2 = true -> (_ orElseBool (V_2 /\ true) = V_2) /\ V_2 = true
```

What I particularly don't like about this encoding is that the substitution also appears in the ensures clause, which is not useful. I discovered this as part of a refactoring process in which we were trying to make sure function definitions don't ensure anything.

**Comment by ehildenb** [comment]
Hmmm, the translation is made more difficult when the `#as` pattern does not appear at the top of the rule, because we don't necessarily have access to the RHS of the rewrite at the point where we are supposed to translate the `#as` pattern: https://github.com/kframework/k/blob/1ac32f2abf2df78253b4385d8ed42ef2a7714e46/kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java#L1450

```
    rule <k> foo ( 1 ) #as FOO => bar(FOO) ... </k>
```

I guess you'd like:

```
    rule <k> foo(1) ~> REST </k> => (<k> bar(FOO) ~> REST </k> #And #Ceil(FOO #And foo(1)))
```

Is this example correct?

**Comment by traiansf** [comment]
yes, me and Virgil were looking on that code the other day; what I would do (based on the examples that @xc93 and @virgil-serbanuta  gave) would be to run another collector and get the as patterns as equalities and add them all to the requires clause. So, in your example,
```
 rule <k> foo ( 1 ) #as FOO => bar(FOO) ... </k>
```
would turn into 
```
rule <k> FOO => bar(FOO) ... </k>
  requires FOO = foo(1)
```

Then it would be the backend's responsibility to decide whether to apply the substitution and instantiate FOO or not.  @ttuegel @dwightguth what do you think about this?

What I'm a little concerned about is that we do this `#as` thing as a compression technique, and we should be careful that if at any point we decide to support non-functional patterns, then, at least for them, we need to use set variables in the `#as` declaration.

**Comment by dwightguth** [comment]
In general I'm not opposed to removing the as patterns from places where they cause problems. It's intended as an optimization to reduce time spent constructing terms, but if there are issues, it is fine to locally disable it.

**Comment by ttuegel** [comment]
> Then it would be the backend's responsibility to decide whether to apply the substitution and instantiate FOO or not.

So, just user-specified common subexpression elimination? I think that's fine. The Haskell backend will have no problem with it.

**Comment by ehildenb** [comment]
This is likely still a problem for `#as` patterns in simplification rules (though the function encoding changes probably fixed it for semantic rules).
