### ISSUE TITLE
K should infer sorts when using abstract syntax

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/k#985]
```
module TEST
  syntax E ::= "a"         [klabel(elma), symbol]
  syntax Lst ::= E "," Lst [klabel(constr), symbol]
               | ".Lst"    [klabel(emptyLst), symbol]
  configuration <k> constr(a, emptyLst(.KList)) </k>
  rule constr(I, L) => L
endmodule
```
This rule should apply, but right now, the sorts for `I` and `L` are being inferred as sort `K`. It used to work in the ocaml backend because we didn't have such strict sort checks and injections.

This is blocking the K-in-K definition. Since we're defining K, we have to avoid using the concrete syntax so we don't get parsing errors. The alternatives would be to either type all variables in every rule or have duplicate productions with syntax only for rules. Both of these solutions are error-prone.

**Comment by dwightguth** [comment]
I would recommend creating macros instead of using abstract syntax.
